### ISSUE TITLE
Theme toggling 

### ISSUE THREAD

**Issue by vivek286** [smaranjitghose/awesome-portfolio-websites#1003]
Once the viewer toggles the theme it only changes for that page and as he moves to another section it changes back to the light theme I   think if once the theme is toggled it should be the same for all sections.
@smaranjitghose  If it is a bug please assign it to me.

**Comment by anushbhatia** [comment]
Assigned for 3 days. Give the PR as soon as possible

**Comment by deeqakkk** [comment]
any updates @vivek286 ?

**Comment by vivek286** [comment]
@deeqakkk  working on it
