### ISSUE TITLE
Update GitHub icon's color in dark mode 

### ISSUE THREAD

**Issue by aashimawadhwa** [smaranjitghose/awesome-portfolio-websites#1005]
change the GitHub icon color to white in dark mode .

![Screenshot from 2021-07-25 02-52-11](https://user-images.githubusercontent.com/73706697/126881363-f260f072-dd7d-4e4b-a13d-4c5568fddfcd.png)

assign it to me please.

**Comment by anushbhatia** [comment]
do follow the assest guidelines of github

**Comment by aashimawadhwa** [comment]
I referred  to the code and documentation online I got to know that we  cannot change the color of a svg icon with the help of variables defined in the dark mode theme and the light mode theme .
The color remains fixed by the css property of "fill" in home.css can i change the svg to normal icon and change the arm animations to normal animation as of medium and kaggle if you allow?

**Comment by aashimawadhwa** [comment]
or if you can please guide me if I am in wrong directions , I will be very grateful ! @anushbhatia

**Comment by aashimawadhwa** [comment]
can you elaborate a bit? you mean i can change SVG to icon and change the github's icon present animation to somewhat familiar to medium and kaggle? @anushbhatia

**Comment by anushbhatia** [comment]
you can use the white bordered logo which is present in the dark mode.
let the arm animation be the same just modify the fill of the github logo according to this colour scheme rest i think it would be fine.
![f0j086weald41](https://user-images.githubusercontent.com/40017559/127828823-85c61a3b-10c7-416a-b06c-b6e23273e1db.png)

**Comment by aashimawadhwa** [comment]
will fix it in 2 days was not well .

**Comment by RituSingh2002** [comment]
hii I would like to work on this
