### ISSUE TITLE
want to add the hover effect on the profile image in homepage

### ISSUE THREAD

**Issue by SayantaniDeb** [smaranjitghose/awesome-portfolio-websites#1009]
https://user-images.githubusercontent.com/74983536/127128696-52671908-4069-4a13-b6af-a40c158f4b0e.mp4

**Comment by SayantaniDeb** [comment]
assign it to me please.

**Comment by smaranjitghose** [comment]
In laptop screens, this might be a good idea but for small screens like tablets or mobile phones it will not be feasible
