### ISSUE TITLE
Unable to view the title or hover line properly in dark mode

### ISSUE THREAD

**Issue by senyee18** [smaranjitghose/awesome-portfolio-websites#1016]
Hi, I am Sen Yee. I discover that in dark mode, the dark purple colour is too dark which is hardly able to be view. I believe simple changes in the colour for the dark mode will improve the design. 
![image](https://user-images.githubusercontent.com/86588857/127760593-0a66c567-8818-4ace-8df0-5811739cda53.png)
![image](https://user-images.githubusercontent.com/86588857/127760606-2a2904cc-700e-47b6-a829-dd0d88d3fe64.png)

**Comment by smaranjitghose** [comment]
Sure. You can raise a PR for this

**Comment by deeqakkk** [comment]
any updates @senyee18

**Comment by Saiteja-goud** [comment]
Could you please assign this issue to me, I would like to work on it?

**Comment by Saiteja-goud** [comment]
@smaranjitghose @deeqakkk Could you please assign this issue to me, I'd like to work on it?

**Comment by Saiteja-goud** [comment]
@anushbhatia @smaranjitghose @deeqakkk  

Could you please assign this issue to me, I'd like to work on it?
