### ISSUE TITLE
Education Page Mobile Responsiveness Bug(s)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1020]
![Education_Page](https://user-images.githubusercontent.com/46641503/127788794-e8661ed6-7e95-44b1-9947-e788720a80c1.png)

In small screen sizes:
- The heading almost sticks to the navbar (which does not follow the UI for the rest of the website)
- There is an unusual horizontal stretching of the page [Use chrome dev tools]

**Comment by aasthasaxena217** [comment]
@smaranjitghose , Can I work on this issue

**Comment by smaranjitghose** [comment]
Sure. @aasthasaxena217

**Comment by abhaygoel14** [comment]
@smaranjitghose I can still find the bug in the mobile responsive view. Can I work on this issue?
![image](https://user-images.githubusercontent.com/78078088/131250318-522394bb-a32e-4fbd-84fc-a4488cdc3071.png)
