### ISSUE TITLE
Redesign Education Page's Formal Education Section

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1021]
## Sample Reference

[Only for the responsiveness and overall timeline but not the cards itself](https://codepen.io/paulhbarker/pen/apvGdv)

## Instructions

- The card should have a small school image on the left  and content on the right
     - The content part should include Name of School, Location, Program Pursued, Duration, Synopsis of activities
- Make sure the cards are mobile responsive

![Colu](https://user-images.githubusercontent.com/46641503/127789199-d465775b-fc64-4fec-9896-a846045811d7.png)
-  Do not put the present dummy logos. Make use of actual university logos (to be present in the assets folder)
- The data should be dynamically added using a variable as done through the current education.js
- Images/illustrations should be placed inside assets/images/school/

**Comment by Dhruv-194** [comment]
Hey @smaranjitghose can I work on this issue?

**Comment by deeqakkk** [comment]
@Dhruv-194 sure!

**Comment by deeqakkk** [comment]
@Dhruv-194 sure.

**Comment by deeqakkk** [comment]
any updates @Dhruv-194

**Comment by Dhruv-194** [comment]
@deeqakkk I will be completing this by tomorrow :)
