### ISSUE TITLE
Fix Website Font Consistency

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1024]
- All the text used in the website should have the same font
- New Font: [Frank Ruhl Libre](https://fonts.google.com/specimen/Frank+Ruhl+Libre?query=Frank+Ruhl+Libre)
- Remove the import of any other fonts from html or css files that would not be required anymore

**Comment by ArihantJain123** [comment]
please assign me this issue it will be helpful for me and I am LGMSOC participant

**Comment by ArihantJain123** [comment]
Ok , Thanks for assign me this issue.

**Comment by AnirudhPanda** [comment]
I can do this if nobody else is assigned!

**Comment by imjonsnow362** [comment]
Is the issue fixed ?

**Comment by smaranjitghose** [comment]
Not yet~

**Comment by AnirudhPanda** [comment]
#1032

**Comment by shreyas1925** [comment]
If at all the issue is not fixed please assign it to me.

**Comment by harshil202** [comment]
You can assign me for this work I can do this.

**Comment by shreya-gb** [comment]
@smaranjitghose You want all the font to be from Poppins to Frank Ruhl Libre?

**Comment by FidalMathew** [comment]
I would like to work on the issue if available, please assign it to me.

**Comment by riyajha2305** [comment]
Can I be assigned this issue?
