### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Aksheet10** [smaranjitghose/awesome-portfolio-websites#1027]
Is there any way to pre set the theme as dark instead of light theme first and toggle for dark?

like right now it is light <toggle> dark. but could there be dark <toggle> light?

if yes please let me know how to.

thanks :)

**Comment by smaranjitghose** [comment]
Ya definitely, you can omit to take the local settings of the user into consideration when loading the page and set the default to dark.

[Reference article](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/)

File to be changed: app.js ( Scroll down after the header and footer code)

**Comment by anushbhatia** [comment]
Keep toggle button to dark on default and that will make it by default.

**Comment by Aksheet10** [comment]
oh thanks a lot for the reply, can u please tell me the area to edit for that? i tried a ton of stuff but ended up not getting anything done

**Comment by anushbhatia** [comment]
https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/assets/js/app.js
Here from line number 352 there are thses two functions which aare primarily responsible for dark mode. Play along the conditions of if else and then u will be able to do it. If not just droo your query here.

**Comment by Aksheet10** [comment]
Hi, i think there is an issue with the app.js

when forked and using it...it tens to reduce itself and it automatically gets shortened to 330 lines.. i have tried the same things 5 times atleast and everytime it changes to 330 lines.

_for the dark theme_
i tred a lot messing with the if else. but everytime i tried nothin worked. the page wouldnt load dark mode sometimes.. or only white theme would be it

**Comment by anushbhatia** [comment]
Before
`   <input type="checkbox" class="dark_toggler" aria-label="Toggle Light Mode" onclick="toggle_light_mode()"> `
After
`   <input type="checkbox" class="dark_toggler" aria-label="Toggle Light Mode" onclick="toggle_light_mode()" checked> `

try modifying this in app.js to

**Comment by Aksheet10** [comment]
hey, thanks for the reply, but this time the checkbox is checked but it doesnt change to darkmode.

i recopied the app.js from the original repo but that still defaults to the light theme. :(

**Comment by Aksheet10** [comment]
also i the github icon for dark theme (below the "I am into {}" part) remains dark. It may happen that somepeople may not be able to see tht

**Comment by anushbhatia** [comment]
> hey, thanks for the reply, but this time the checkbox is checked but it doesnt change to darkmode.
> 
> i recopied the app.js from the original repo but that still defaults to the light theme. :(

the code for dark mode is having some issues i will try rebuiding it and fixing that complete section

**Comment by anushbhatia** [comment]
> also i the github icon for dark theme (below the "I am into {}" part) remains dark. It may happen that somepeople may not be able to see tht

We had assigned someone this issue but there's no update on it regarding that

**Comment by Aksheet10** [comment]
Hey, hope that gets updated :D

Also for the badges in experience page - is it limited to only 5?

**Comment by anushbhatia** [comment]
> Hey, hope that gets updated :D
> 
> Also for the badges in the experience page - is it limited to only 5?

no, they can be extended to more.

**Comment by Aksheet10** [comment]
not working for mr weird, after i add the 6th one, the site doesnt show any of the badges
