### ISSUE TITLE
There is a problem with the contact form js ,can anyone help please

### ISSUE THREAD

**Issue by AlsaidAbdu** [smaranjitghose/awesome-portfolio-websites#1030]

**Comment by smaranjitghose** [comment]
Could you please elaborate on the issue?

**Comment by AlsaidAbdu** [comment]
This is the code in apps.js, but when using the contact form on the page, it doesn't send anything.


<div class="col-lg-6 col-md-12 mb-4 mb-md-0 form-comtainer">
          <div class="form-style-6">
             <div class="form-header">
                <h6 class="display">Get In Touch</h6>
              </div>
                <form>
                <form action="https://formcarry.com/s/G0OIb3Yx3o1" method="POST" accept-charset="UTF-8" >
                <input type="text" name="field1" placeholder="Your Name" required/>
                  <input type="email" name="field2" placeholder="Email Address"  required/>
                  <textarea name="field3" placeholder="Type your Message" required></textarea>
                  <input type="submit" value="Send" />
                </form>
             </div>
          </div>
        </div>
    </div>

**Comment by prakharsan** [comment]
Hey AlsaidAbdu,
Remove the first form tag. 
` <form action="form-carry-link-here" method="POST" accept-charset="UTF-8" >
                  <input type="text" name="field1" placeholder="Your Name" required/>
                  <input type="email" name="field2" placeholder="Email Address"  required/>
                  <textarea name="field3" placeholder="Type your Message" required></textarea>
                  <input type="submit" value="Send" />
                </form>`

**Comment by prakharsan** [comment]
Hey AlsaidAbdu,
Remove the first <form> tag
` <form action="your-form-carry-link-here" method="POST" accept-charset="UTF-8" >
                  <input type="text" name="field1" placeholder="Your Name" required/>
                  <input type="email" name="field2" placeholder="Email Address"  required/>
                  <textarea name="field3" placeholder="Type your Message" required></textarea>
                  <input type="submit" value="Send" />
                </form>`
