### ISSUE TITLE
"Resume" link color issue on click

### ISSUE THREAD

**Issue by deeqakkk** [smaranjitghose/awesome-portfolio-websites#1033]
Once we click on the resume to get redirect for new tab(john_doe.pdf) 
even after returning resume remains black in color making it almost invisible.
![image](https://user-images.githubusercontent.com/78724676/128421459-a65ea382-6192-427d-bef3-ddffa4e0117a.png)

**Comment by NumanAnees** [comment]
**not only with Resume it is happening with all the anchor tags if someone opens them in new Tab.**


![image](https://user-images.githubusercontent.com/67089723/128439109-59061343-4eef-4d6c-9855-edfa140f328e.png)

**Comment by RituSingh2002** [comment]
please assign this issue I have to fix it
