### ISSUE TITLE
Dark mode toggle defaults back to light state when refreshed

### ISSUE THREAD

**Issue by adithyasunil26** [smaranjitghose/awesome-portfolio-websites#1036]
This is a continuation to #942 . 

Problem:
The fix there does not seem to have solved the bug as it simple defaulted every page to light mode. In the current version also if we switch to dark mode and then refresh the page, the toggle defaults back to the light state even though the page is still in dark mode which is not the ideal behaviour.

Fix:
Simply checking the checkbox if the local storage has the lightMode set to dark.

**Comment by nishant3721** [comment]
@adithyasunil26 Can I work on it!?

**Comment by adithyasunil26** [comment]
@nishant3721 I have already PRed a fix in #1037 but if u have a better idea then sure go ahead

**Comment by nishant3721** [comment]
@adithyasunil26 Ok, no problem!
