### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by purohitmansi** [smaranjitghose/awesome-portfolio-websites#1041]
It will be great if all the contact information is included on the contact page like education, research which have different pages. And the homepage contains the basic information with a picture and a short summary of your work.

**Comment by purohitmansi** [comment]
Please do assign this to me to add about page instead of home.

**Comment by anushbhatia** [comment]
We have all our contact information on the footer and home pages I don't think we will need a separate contact page.
@smaranjitghose what are your views.
