### ISSUE TITLE
Reference Page Bug and Updates

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1059]
# Requirements

- Fix Responsiveness of Reference Page for mobile screen sizes 

![Reference_Page](https://user-images.githubusercontent.com/46641503/135471826-237af5fa-7d2b-44f7-bf8b-940f59966ebe.png)

- Update the default text with real recommendations that could be given by peers and managers to one for one's work in software engineering or data science. 
- Update the pictures with different open source place holder images
- Improve the code quality in the reference.js (Use better variable names, etc)
![code_quality](https://user-images.githubusercontent.com/46641503/135472472-79ca6431-8084-46c4-bb23-bab96abbc649.png)

**Comment by sanjanarp** [comment]
I'm interested, @smaranjitghose could you assign it to me?
