### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#106]
# Suggestions:

- Illustration on the left
- Form on the right 
           |--First Name**
           |--Last Name**
           |--Phone Number*
           |--Email**
           |--Message**
           |--Captcha
- Use formspree for now
- Also, put the social icons on the left
- Work on the dark mode
- Make this mobile responsive
- Update the navbar only when complete and approved

**Comment by shreyakapoor08** [comment]
Go ahead @avinashkranjan

**Comment by avinashkranjan** [comment]
@smaranjitghose You'll give link to form action for formspree..or should I use my account and after approval of design you'll give the link??

**Comment by anushbhatia** [comment]
for now, use your account the basic change is the name of the email only

**Comment by avinashkranjan** [comment]
> for now, use your account the basic change is the name of the email only

@anushbhatia Sure..

**Comment by smaranjitghose** [comment]
@avinashkranjan Any updates?

**Comment by avinashkranjan** [comment]
> @avinashkranjan Any updates?

Will push the Contact Page Today

**Comment by avinashkranjan** [comment]
@smaranjitghose Have a look

**Comment by akshita2903** [comment]
I had like to work on it.
Please assign it to me

**Comment by mharshita** [comment]
@smaranjitghose  @anushbhatia  I want to work on contact page. Please assign this to me.

**Comment by shreyakapoor08** [comment]
> I had like to work on it.
> Please assign it to me

You can go ahead

**Comment by akshita2903** [comment]
> > I had like to work on it.
> > Please assign it to me
> 
> You can go ahead

Thankyou @shreyakapoor08  Maa'm. I wanna ask can I make  this contact page  in a different file with same look as other files have?

**Comment by shreyakapoor08** [comment]
> > > I had like to work on it.
> > > Please assign it to me
> > 
> > 
> > You can go ahead
> 
> Thankyou @shreyakapoor08 Maa'm. I wanna ask can I make this contact page in a different file with same look as other files have?

Yes akshita, make a separate file try to follow the theme as other pages so that everything blends together but you can definitely add your own creativity. Also make sure to work on all the points which is mentioned in the issue. 
Hoping for a PR on this within 7 days :)

**Comment by akshita2903** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/68686051/92730150-fcc79580-f390-11ea-9906-7fe759ec9669.png)
@smaranjitghose  Sir and @shreyakapoor08  Maa'm
Please have a look into my contact page template.And Please Suggest any kind of improvement needed.
And tell can I add navigation  bar to it.

**Comment by shreyakapoor08** [comment]
> ![Screenshot (3)](https://user-images.githubusercontent.com/68686051/92730150-fcc79580-f390-11ea-9906-7fe759ec9669.png)
> @smaranjitghose Sir and @shreyakapoor08 Maa'm
> Please have a look into my contact page template.And Please Suggest any kind of improvement needed.
> And tell can I add navigation bar to it.

Looks good to me. 
Just few things -
1. Is this responsive? 
2. This seems to be the dark mode, what about the normal mode? 
3. Make the "Get in touch" heading in the centre

**Comment by smaranjitghose** [comment]
> > ![Screenshot (3)](https://user-images.githubusercontent.com/68686051/92730150-fcc79580-f390-11ea-9906-7fe759ec9669.png)
> > @smaranjitghose Sir and @shreyakapoor08 Maa'm
> > Please have a look into my contact page template.And Please Suggest any kind of improvement needed.
> > And tell can I add navigation bar to it.
> 
> Looks good to me.
> Just few things -
> 
> 1. Is this responsive?
> 2. This seems to be the dark mode, what about the normal mode?
> 3. Make the "Get in touch" heading in the centre

The Picture and "Hi, I am xyz" is not required as it will anyways be present on the home page.

**Comment by akshita2903** [comment]
> > > ![Screenshot (3)](https://user-images.githubusercontent.com/68686051/92730150-fcc79580-f390-11ea-9906-7fe759ec9669.png)
> > > @smaranjitghose Sir and @shreyakapoor08 Maa'm
> > > Please have a look into my contact page template.And Please Suggest any kind of improvement needed.
> > > And tell can I add navigation bar to it.
> > 
> > 
> > Looks good to me.
> > Just few things -
> > 
> > 1. Is this responsive?
> > 2. This seems to be the dark mode, what about the normal mode?
> > 3. Make the "Get in touch" heading in the centre
> 
> The Picture and "Hi, I am xyz" is not required as it will anyways be present on the home page.

OK Sir

**Comment by akshita2903** [comment]
> > ![Screenshot (3)](https://user-images.githubusercontent.com/68686051/92730150-fcc79580-f390-11ea-9906-7fe759ec9669.png)
> > @smaranjitghose Sir and @shreyakapoor08 Maa'm
> > Please have a look into my contact page template.And Please Suggest any kind of improvement needed.
> > And tell can I add navigation bar to it.
> 
> Looks good to me.
> Just few things -
> 
> 1. Is this responsive?
> 2. This seems to be the dark mode, what about the normal mode?
> 3. Make the "Get in touch" heading in the centre

1-It is responsive in local host 
2-Actually Maa'm I added the dark theme initially, so for light theme I am working in it. Can Give you in PR in a day or two
3-Yes ma'am I am also working on text aligning part. 
Thank you for the suggestions 😊
