### ISSUE TITLE
New Page for Semester Recap/Year Recap

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1060]
[Reference](https://codepen.io/nathantaylor/pen/PJGqdE)

## Core Idea

This page (or similar copies of this page) would be helpful for having easter eggs on one's portfolio for peers and colleagues regarding an academic or professional journey taken together. Basically, it's a slideshow of images to serve as cherishable momemts.

## Instructions

- All the images should be placed inside `./assets/images/sem/sem1/`
- Take the images from Unsplash.
- Name the images properly
- Do not add a tab in the Nav Bar. The page would be accessed directly with ``./sem_temp.html``
- The CSS file should be `./assets/css/sem_temp.css` and the Js should be ``./assets/js/sem_temp.js``
- To add or remove data for the images, it should be done from a JSON variable inside conf_temp.js. Check out research.js for reference.
- Avoid using buttons as done in the above reference

**Comment by kanchi2438** [comment]
@smaranjitghose sir, Could you please assign it to me? I'd like to work on it

**Comment by Swatilekha-Roy** [comment]
Hi @anushbhatia @smaranjitghose since this issue is presently unassigned, could you kindly assign this issue to me as a part of Open Source Day vGHC? I would love to try it out and add this feature! Thanks in advance.

**Comment by smaranjitghose** [comment]
Sure. @Swatilekha-Roy feel free to give it a try

**Comment by anushbhatia** [comment]
Looks great to me. You can go ahead and create a PR

**Comment by Swatilekha-Roy** [comment]
@anushbhatia thank you! Done.
