### ISSUE TITLE
Education Page: Eliminate Additional Space

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1062]
![Education_Page_Respon_1](https://user-images.githubusercontent.com/46641503/135474015-f6e9b026-f6bd-44cf-b59c-93ba8056651d.png)

Remove the additional space as observed in smaller screen sizes for the education page

**Comment by antonio-b** [comment]
@smaranjitghose can you assign this to me?
