### ISSUE TITLE
Favicon Bug: Education Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1063]
![Education_Page_fav](https://user-images.githubusercontent.com/46641503/135474790-84e523f0-3fd6-4fd5-b569-ad15b823a41e.png)

Similar to other pages, the favicon should change dynamically along with the page title when the user is away from the website

**Comment by sanjanarp** [comment]
I would like to work on this issue, @smaranjitghose could you assign it to me?
