### ISSUE TITLE
Add Microanimation to Footer Send Button

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1064]
[Reference](https://codepen.io/nuski/details/ExPEBgw)

- The footer code should be loaded exclusively from app.js and style.css
- Modify the color according to the theme of the website

**Comment by PuneetDabral** [comment]
sir can you please can me to do my first contribution here i am new in git hub ?!! also to help me to resolve this issue

**Comment by javi-saavedra** [comment]
Hi! Can I take on this issue?

**Comment by PuneetDabral** [comment]
can any one help me to resolve this issue?

**Comment by anushbhatia** [comment]
explain you doubt here.

**Comment by PuneetDabral** [comment]
explain in step by stem i am also new in react

**Comment by anushbhatia** [comment]
Code is present there  in reference above, just have to integrate it with footer that's present in `assets/js/app.js`

**Comment by Nzamuyejoram** [comment]
@PuneetDabral  yeah true mine too i would prefer that coz am as well new in react
