### ISSUE TITLE
Skeleton Loading

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1075]
https://codepen.io/havardob/pen/dyGGGzq 
Implement this until the CSS files and Js are loading for the pages.

**Comment by abhishekchauhan15** [comment]
I can do that. Can you please assign me this?

**Comment by abhishekchauhan15** [comment]
So basically I have to make Skeleton Loading for 4 pages only i.e: Experience, Project, Research, and Education page, right?

**Comment by anushbhatia** [comment]
@rhona3 do you want to work on this

**Comment by anushbhatia** [comment]
https://www.youtube.com/watch?v=ZVug65gW-fc follow this

**Comment by Nzamuyejoram** [comment]
@anushhatia. could you please assign me this issue and i give it a trial

**Comment by Nzamuyejoram** [comment]
@anushbhatia . Its cool thanks. let me try it
