### ISSUE TITLE
Realistic Details to reference Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1081]
Currently, the page has a fake review if you could add some reviews which have relevant data and images.
![image](https://user-images.githubusercontent.com/40017559/135674931-0383136b-87a5-49a4-973e-bbf39a53a715.png)

**Comment by astraljdc** [comment]
Hi, I'd like to do this!

**Comment by smaranjitghose** [comment]
Any updates @astraljdc ?

**Comment by astraljdc** [comment]
Yup! I submitted a contribution commit here https://github.com/smaranjitghose/awesome-portfolio-websites/pull/1087
and it looks like it got approved.
