### ISSUE TITLE
Make the footer font same as the Navbar(Poppins)

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1083]
![image](https://user-images.githubusercontent.com/40017559/135681913-636b058b-6b9e-40d6-bcbb-661b3b61efee.png)
Change this font to Poppins for the same font throughout the project.

**Comment by jennjwang** [comment]
Could I work on this? Thank you!

**Comment by smaranjitghose** [comment]
@jennjwang You can do the follow up changes w.r.t font size if you wish

**Comment by rhona3** [comment]
@anushbhatia  i think th fort is okay no need to be changed
