### ISSUE TITLE
Navbar Logo Change

### ISSUE THREAD

**Issue by turhancan97** [smaranjitghose/awesome-portfolio-websites#1093]
In documentation , it says that Open main.js and Under Footer and Navbar heading change the path inside img src="" to your image path to change your logo. But I couldn't find main.js document. 

![image](https://user-images.githubusercontent.com/22428774/135773570-695e196d-18e5-41de-bb16-cd395e365489.png)

**Comment by smaranjitghose** [comment]
We have shifted the code to app.js and replaced it with a text
