### ISSUE TITLE
Documentation Website Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1096]
- We have a documentation website built using mkdocs 
- The source code is present on the `documentation` branch while the code for the hosted part is on the `gh-pages` branch
- It basically deals with helping out non-programmers set up this project and use it for their own purpose
- We need your assistance to update the material ( some of the files have been changed: main.js -> app.js, pages have been modified, new pages are added)
- This can be done in a single PR or in a series of PRs
- **NOTE:** The PRs should not be made to the master branch and only to the concerned branches

**Comment by smaranjitghose** [comment]
@sanjanarp Yes

**Comment by rhona3** [comment]
@sanjanarp i think in future it updates it'self

**Comment by smaranjitghose** [comment]
Yes

**Comment by smaranjitghose** [comment]
> @smaranjitghose Do I remove the "Badges" section or will future updates require it? Because there's nothing on the website regarding badges in Education Page as of now.

Yes
