### ISSUE TITLE
Get in touch functionality not working

### ISSUE THREAD

**Issue by kamalkraj** [smaranjitghose/awesome-portfolio-websites#1126]
I have already replaced the link with my formcarry link. 

Is there anything else I should change ?

**Comment by panjwaniranjitsingh** [comment]
> I have already replaced the link with my formcarry link.
> 
> Is there anything else I should change ?

Just remove "<form>" written a line before "<form action=" and then formcarry link will get data.

**Comment by panjwaniranjitsingh** [comment]
> No its meant to be blank as of now cause we are not providing any backend as of now.

@anushbhatia formcarry website is giving backend you don't need to provide any backend for Get In Touch form.
