### ISSUE TITLE
Set Default to Dark Mode

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1148]

**Comment by RishiKumarRay** [comment]
how to do this, can you guide?

**Comment by gourangi-taware** [comment]
I want to resolve this issue. Can you please assign me this issue?

**Comment by arindamkeswani** [comment]
I am willing to work on this!

**Comment by smaranjitghose** [comment]
> how to do this, can you guide?

Check the discussions section please, @anushbhatia has given some pointers

**Comment by gourangi-taware** [comment]
Can you please assign me this issue? I can resolve this issue.
