### ISSUE TITLE
Microanimation for Footer Send Button

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1149]
[Reference](https://codepen.io/nuski/details/ExPEBgw)

- The footer code should be loaded exclusively from app.js and style.css
- Modify the color according to the theme of the website

**Comment by soujo** [comment]
Hi there, I want to contribute to this issue. I am registered under JWOC. Can I be assigned to contribute after 1st Feb?

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by anushbhatia** [comment]
Sure @KushalGhosh9899

**Comment by KushalGhosh9899** [comment]
Hey @anushbhatia Thanks for assigning me this issue but I have already got assigned with 2 issues so wouldn't be able to take us this for now.

**Comment by KushalGhosh9899** [comment]
Hey @anushbhatia Thanks for assigning me this issue but I have already got assigned with 2 issues so wouldn't be able to take us this for now.
Please kindly unassign and assign to some one other potential candidate.

**Comment by anushbhatia** [comment]
Okay sure

**Comment by Priiyaa** [comment]
May I work on this issue?

**Comment by anushbhatia** [comment]
Yes @Priiyaa go ahead

**Comment by Priiyaa** [comment]
**_Hi! I made this. Please review it_**<br>
![send button](https://user-images.githubusercontent.com/76914418/152596220-03805d00-97bf-496b-9d47-eec7ea1c9ead.png)<br>
Send button
![send zoom](https://user-images.githubusercontent.com/76914418/152596256-97562545-60dd-4055-9961-6236020d7ee6.jpg)
### Video of the animation

https://user-images.githubusercontent.com/76914418/152596294-041a21a2-26b5-4502-9b8a-eb2b8e49b296.mp4

**Comment by anushbhatia** [comment]
Validate it with the form elements and reduce the size of the button as it looks bigger as compared to rest of the design.

**Comment by Priiyaa** [comment]
Got it!

**Comment by Priiyaa** [comment]
@anushbhatia  I did what you asked but the problem that I am facing is that if I validate the textarea element then the animation doesn't work BUT if I validate the other two input fields except the texarea then it works perfectly

**Comment by Priiyaa** [comment]
https://user-images.githubusercontent.com/76914418/152681399-8cca930b-5577-4cf8-a645-b53a31d2578b.mp4
Is this size ok?
![button](https://user-images.githubusercontent.com/76914418/152681423-fdc57051-440d-49de-9823-12130c1fca37.png)

**Comment by smaranjitghose** [comment]
## Feedback:

- The spaceship/aeroplane's relative size should be much smaller than the button (Closely observe the reference given above)
- Could you reduce the box-shadow as well? It is too much

**Comment by Priiyaa** [comment]
@anushbhatia I did attach the video but somehow it got converted into a link. I will try to attach a proper video this time.
Feedback noted! ^-^

**Comment by smaranjitghose** [comment]
Just checked out the link, yes the animation is working fine! Make sure it is mobile responsive as well. Just one fix: the animation should only be triggered when all the fields are filled correctly and the send button is pressed instead of just pressing the send button

**Comment by Priiyaa** [comment]
Its mobile responsive. 
The problem that I am facing is that if I validate the textarea element then the animation doesn't work BUT if I validate the other two input fields except the texarea then it works perfectly.
ALSO if all the three fields are filled and we click on submit button then the animation does not work and the page reloads.

**Comment by Priiyaa** [comment]
**Fixed the icon and reduced box-shadow**
![Mobile](https://user-images.githubusercontent.com/76914418/152686566-708b5cee-6b66-4acf-a541-fa6f161773a0.jpg)

**Comment by anushbhatia** [comment]
> Its mobile responsive. 
> The problem that I am facing is that if I validate the textarea element then the animation doesn't work BUT if I validate the other two input fields except the texarea then it works perfectly.
> ALSO if all the three fields are filled and we click on submit button then the animation does not work and the page reloads.
> 
> 

Could you connect with me on discord so that i can help you.
