### ISSUE TITLE
Add Work Experience Section for the React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1150]
## Instructions:

- The page should be available at `/experience`. Handle the routing accordingly
- All the src code would be in the reactjs branch
- The UI should be exactly the same as the [hosted version](https://portfolio.smaranjitghose.com/experience.html)
- Don't forget to add the illustration and title at the top
- The data should be defined in a variable and dynamically inserted as done in the current experience.js
- Images/illustrations should be placed inside `assets/images/work/`

**Comment by hppranaav** [comment]
Hello, I would like to have a go at this, 
I have started learning React and I feel could help out
Thanks.

**Comment by smaranjitghose** [comment]
@hppranaav Sure. Feel free to give it a shot and request a PR for review on the same

**Comment by hppranaav** [comment]
Had a general observation about the application. There are high and critical vulnerabilities which can be fixed through` npm audit fix`. 
However the some of the changes are breaking changes, and are mostly related to the `react-scripts` package

**Comment by anushbhatia** [comment]
Try upgrading the package to see if they go away.

**Comment by lavakush07** [comment]
"I want to work on this issue under JWOC"

**Comment by smaranjitghose** [comment]
@lavakush07 Updates?

**Comment by Srijita-Mandal** [comment]
Hi @smaranjitghose , I want to work in this issue under JWoC.

**Comment by Srijita-Mandal** [comment]
I can't work on this issue currently for some problems. Can you please unassign me?
