### ISSUE TITLE
Add Hackathon Section for React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1152]
## Instructions:

- The page should be available at `/experience`. Handle the routing accordingly
- All the src code would be in the reactjs branch
- The UI should be exactly the same as the [hosted version](https://portfolio.smaranjitghose.com/experience.html)
- Don't forget to add the illustration and title at the top
- The data should be defined in a variable and dynamically inserted as done in the current experience.js
- Images/illustrations should be placed inside `assets/images/opensource/`

**Comment by Mainakroy050** [comment]
👋I want to work on this issue under JWOC
