### ISSUE TITLE
Add Project Page to the React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1153]
## Instructions:

- The page should be available at `/projects`. Handle the routing accordingly
- All the src code would be in the reactjs branch
- The UI should be exactly the same as the [hosted version](https://portfolio.smaranjitghose.com/projects.html)
- Don't forget to add the illustration and title at the top
- The data should be defined in a variable and dynamically inserted as done in the current project.js
- Images/illustrations should be placed inside `assets/images/projects/`

## Optional:

- Cards should have a 3D effect. [Reference Video](https://www.youtube.com/watch?v=cPKiilXlHAQ)

**Comment by tusharjain365** [comment]
Hey, I want to work on this issue under JWOC.

**Comment by smaranjitghose** [comment]
@tusharjain365 updates?

**Comment by tusharjain365** [comment]
@smaranjitghose sorry, was busy these days, will be available now onwards.
Can I work on this ?
