### ISSUE TITLE
[React Version] Update Navbar

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1154]
## Instructions:

- This should be exactly same as the hosted version
-  All the src code would be in the `reactjs` branch
- Add the toggle button and corresponding code for switching colors
- Change Resume -> Blog
- Notice that in the hosted version, the current page has a permanent underscore. In the react version, we can instead make sure that the current page(name in the navbar) is bold instead of the underscore

**Comment by Shruti025** [comment]
hey, can I take up this issue?

**Comment by KushalGhosh9899** [comment]
@Shruti025 are you still working on it? Can i take it if you aren't?

**Comment by Shruti025** [comment]
hey @smaranjitghose can I get 2-3 days starting today to work on this issue, or will it be assigned to someone else?

**Comment by anushbhatia** [comment]
No issues @Shruti025 just share the screenshot of progress 😅

**Comment by Shruti025** [comment]
hey @anushbhatia I had some doubts regarding this issue. I have conveyed them in the discord channel

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by Devmindtk** [comment]
I would like to work on this issue under JWOC plz assign it to me

**Comment by Devmindtk** [comment]
> I would like to work on this issue under JWOC plz assign it to me

@smaranjitghose  the issue that you maintained is already solved i think because resume nav menu is changed to blogs and toggle switch is fine so what i have to change in it please explain.

**Comment by Faraaz2633** [comment]
Hey there, 
I would like to work on this issue under JWOC.
could you please assign it to me?

**Comment by anushbhatia** [comment]
@Shruti025 is currenly working on this if she is unable to do it then you can take it up.
