### ISSUE TITLE
[React Version] Home Page Minor Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1157]
## Instructions:

- Remove all code for the Medium Icon
- The changes should be mobile responsive
- Refer to the hosted version
-  All the src code would be in the `reactjs` branch

**Comment by M0i9** [comment]
can i work on this ! assign this to me!!

**Comment by smaranjitghose** [comment]
Sure!

**Comment by raxvab** [comment]
I want to work on this issue under JWOC it's gonna be one of the first opportunities for me to start with open source can i get this issue assigned.

**Comment by Anadee11** [comment]
I would like to work on this under JWoC. Please assign.

**Comment by Faraaz2633** [comment]
Can I work on this under JWOC?

**Comment by Faraaz2633** [comment]
@smaranjitghose Removed Medium Icon in the reactjs branch
