### ISSUE TITLE
Improve loading time from 2.4 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1164]
Multiple files are having unused or commented code to remove so that it loads up faster
https://gtmetrix.com/reports/portfolio.smaranjitghose.com/OqEgNL8U/ 
look through the analysis and fix up the mid-low issues at least.
So that website has loading time below 1<ms  if possible.

**Comment by Atif0604** [comment]
Please assign me under JWOC
