### ISSUE TITLE
Bug in Experience Cards

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1165]
In this section the cards look transparent which makes it look weird
![image](https://user-images.githubusercontent.com/40017559/152652801-1a3e5920-054f-4bb8-b7ab-6c2f28f92d48.png)

Fix would be increase the opacity or try different combination to make it look decent

**Comment by Devmindtk** [comment]
I would like to work on this issue .please assign it to me.

**Comment by Devmindtk** [comment]
@anushbhatia  check these following color is looking fine or not?
![Screenshot (468)](https://user-images.githubusercontent.com/91221069/152937516-d7fc140a-a372-4dc3-a459-f8e674697f13.png)
![Screenshot (470)](https://user-images.githubusercontent.com/91221069/152937527-513920c3-0a98-4d15-8198-89030694e331.png)
![Screenshot (469)](https://user-images.githubusercontent.com/91221069/152937530-421c02a9-22fd-467a-866d-7a55746d8845.png)

**Comment by Devmindtk** [comment]
@anushbhatia  let me know whatever changes is required?

**Comment by anushbhatia** [comment]
Try the gradient in read more button with a darker shade on that end

**Comment by Devmindtk** [comment]
> 
you are telling about card color black and grey?

**Comment by Devmindtk** [comment]
@anushbhatia  check all these button gradients color

![Screenshot (476)](https://user-images.githubusercontent.com/91221069/153045913-df8ea072-9f6c-4822-95a8-a07db46a383a.png)
![Screenshot (479)](https://user-images.githubusercontent.com/91221069/153045926-7c6b3110-1ae5-42bb-af15-c46804019ca7.png)
![Screenshot (478)](https://user-images.githubusercontent.com/91221069/153045928-82fd8f6f-daff-456f-a650-751de63548c3.png)
![Screenshot (477)](https://user-images.githubusercontent.com/91221069/153045930-f4953d38-9c4a-4c65-8a9f-9c4fd3b9bd9f.png)

**Comment by anushbhatia** [comment]
> > 
> 
> you are telling about card color black and grey?
Try these as background for cards

1. linear-gradient(147deg, #bb86fc 0%, #940eb5 74%)  [A little darker shade for this]
2. black and grey combo

No need to change gradient for the button

**Comment by Devmindtk** [comment]
> > > 
> > 
> > 
> > you are telling about card color black and grey?
> > Try these as background for cards
> 
> 1. linear-gradient(147deg, #bb86fc 0%, #940eb5 74%)  [A little darker shade for this]
> 2. black and grey combo
> 
> No need to change gradient for the button

okay yeah I got it now.

**Comment by Devmindtk** [comment]
![Screenshot (483)](https://user-images.githubusercontent.com/91221069/153051168-2ef52a32-748f-4b08-8d96-9fdc94bfef7c.png)
![Screenshot (482)](https://user-images.githubusercontent.com/91221069/153051176-fc7fffe3-3d9c-43c7-979f-81225884cf9d.png)

**Comment by Devmindtk** [comment]
![Screenshot (481)](https://user-images.githubusercontent.com/91221069/153051239-92c08cd8-208e-4853-9f5c-df0e00a09fa9.png)

**Comment by Devmindtk** [comment]
> > ![Screenshot (483)](https://user-images.githubusercontent.com/91221069/153051168-2ef52a32-748f-4b08-8d96-9fdc94bfef7c.png) ![Screenshot (482)](https://user-images.githubusercontent.com/91221069/153051176-fc7fffe3-3d9c-43c7-979f-81225884cf9d.png)
> 
> this looks great I think

last one right?

**Comment by Devmindtk** [comment]
> > ![Screenshot (483)](https://user-images.githubusercontent.com/91221069/153051168-2ef52a32-748f-4b08-8d96-9fdc94bfef7c.png) ![Screenshot (482)](https://user-images.githubusercontent.com/91221069/153051176-fc7fffe3-3d9c-43c7-979f-81225884cf9d.png)
> 
> this looks great I think

should I create PR ?

**Comment by smaranjitghose** [comment]
yes

**Comment by Devmindtk** [comment]
> yes

which color black grey or button color shade?

**Comment by anushbhatia** [comment]
black and grey shade
