### ISSUE TITLE
Reference Page Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1168]
# Directions:
- Available [here](https://portfolio.smaranjitghose.com/reference.html)
- While transitioning between the light and dark modes, temporarily there is a card background formed which needs to be removed
- Replace the names with Smaranjit Ghose, Anush Bhatia, Santosh Kumar, Arnab Dutta Purkayastha
- Replace the default pictures @anushbhatia, @arnab1406 and my pictures instead of the default ones

**Comment by Shruti025** [comment]
Can I work on this issue under JWOC?

**Comment by Shruti025** [comment]
Hey @smaranjitghose should I leave the designation and message part empty?

**Comment by Shruti025** [comment]
Hey @smaranjitghose should I leave the designation and message part empty or should I keep them the same?

**Comment by smaranjitghose** [comment]
Just use random text for those.
