### ISSUE TITLE
Reference Page [React Version]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1169]
# Directions:
- Should be available at `\reference`
- Reference: [Master Branch ](https://portfolio.smaranjitghose.com/reference.html)
- While transitioning between the light and dark modes, temporarily there is a card background formed which needs to be removed
- Replace the names with Smaranjit Ghose, Anush Bhatia, Santosh Kumar, Arnab Dutta Purkayastha
- Replace the default pictures @anushbhatia, @arnab1406, and my pictures instead of the default ones

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by Shruti025** [comment]
Can I work on this under JWOC?

**Comment by Shruti025** [comment]
@smaranjitghose Can I work on this under JWOC?

**Comment by KushalGhosh9899** [comment]
Hey @Shruti025 I have opened a PR for the same issue

**Comment by anushbhatia** [comment]
Any one want to work on responsiveness of this page?

**Comment by KushalGhosh9899** [comment]
Yes Please assign it to me

**Comment by KushalGhosh9899** [comment]
Yes please assign it to me but what will be the label of this issue?

**Comment by Shruti025** [comment]
> Any one want to work on responsiveness of this page?

Is the responsiveness issue resolved?

**Comment by anushbhatia** [comment]
Medium
