### ISSUE TITLE
Nav bar on hover

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1174]
![new image](https://user-images.githubusercontent.com/46641503/152683956-12a6eb83-7d6a-45be-8148-9c6f709f4523.png)

On hovering in light mode the nav links colour change to white. please change it bold when hovered upon

**Comment by AtriSukul1508** [comment]
I would like to contribute to this issue

**Comment by anushbhatia** [comment]
any updates @AtriSukul1508 ?

**Comment by AtriSukul1508** [comment]
Updates about what?
