### ISSUE TITLE
[React] Footer Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1180]
![Social_med](https://user-images.githubusercontent.com/46641503/153262565-57151866-84a5-41f1-b2ab-2f40fcd25df8.png)

**Comment by Aniket-508** [comment]
@smaranjitghose Can you share the file name exactly where this bug is happening?

**Comment by Devmindtk** [comment]
I want to work on this issue please assign to me @smaranjitghose
