### ISSUE TITLE
Reference Page Bug

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1187]
Image alignment on the mobile interface is facing some issues. Below is the screenshot for reference. Frames in the image are misaligned to it.
![image](https://user-images.githubusercontent.com/40017559/153375027-85160b06-7beb-447c-a523-94e4d30c1eb7.png)

**Comment by Shruti025** [comment]
hey, can I work on this issue under JWOC?
