### ISSUE TITLE
index page: navbar links are invisible on hover

### ISSUE THREAD

**Issue by MoofyWoofy** [smaranjitghose/awesome-portfolio-websites#1198]
![image](https://user-images.githubusercontent.com/59331821/155465942-594e5de4-10d3-46a1-9d13-db3a351c4e8f.png)

navbar links are transparent when cursor hovers over them with light theme

**Comment by anushbhatia** [comment]
Do you want to work on this?

**Comment by MoofyWoofy** [comment]
Yes please

**Comment by MoofyWoofy** [comment]
for the navbar brand, do I display black colour on hover as well?

**Comment by anushbhatia** [comment]
yes you can
