### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#12]
- Preference 1 : Sphinx
- Preference 2: Docusaurus

**Comment by siddhiisonii** [comment]
@smaranjitghose sir please assign me this

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir please assign me this

Try experimenting with Docusarus or Sphinx and let me know which is more easier for you

**Comment by siddhiisonii** [comment]
@smaranjitghose okay sure sir

**Comment by SKV-programmer** [comment]
Hi Smaranjit , could you please assigned me this section

**Comment by smaranjitghose** [comment]
@SKV-programmer @siddhiisonii 

# My Suggestions: 
- Collaborate on Slack
- Learn Sphinx
- One of you give a pr to a docs branch ( Let me know before you do I'll create it) with only the basic documentation files and other necessary stuff from the master branch ( LICENSE, README, Code of Conduct)
- The other one give a PR with an MD file on how to set up documentation ( sort of a mini-blog post)
- Divide the 6 pages we have among yourself
- For each of the page, write an elaborate description of the sections and what lines to change in what files so that anyone with zero knowledge of web dev can read the docs, clone this repo, do the changes and setup their own portfolio within 30 min or less

Does this sound good?

Let me know when should I expect both of your first PR on this issue

**Comment by anushbhatia** [comment]
Did u guys start any progress?

**Comment by SKV-programmer** [comment]
Ya we are working on it

**Comment by siddhiisonii** [comment]
@KanhaMishra25 connect with me on slack and linkedin

**Comment by SKV-programmer** [comment]
I am sorry , I try to worked on Sphinx but faced some issues in that although I spend a lot of time in this section

**Comment by smaranjitghose** [comment]
@siddhiisonii @KanhaMishra25 Any updates?

**Comment by KanhaMishra25** [comment]
I am watching some youtube tutorials regarding this as READ THE DOCS
documentation is getting difficult for me to understand.

**Comment by anushbhatia** [comment]
If you face issues ask @smaranjitghose he will try to resolve your problems
