### ISSUE TITLE
Hackathon - Experience.js

### ISSUE THREAD

**Issue by Axelgoris99** [smaranjitghose/awesome-portfolio-websites#1200]
When using the current Main branch, the experience.js does not show the two first mentors correctly, there are 13 dots and 15 entries. And depending on which way you're scrolling through, you might not have access to the first two.

**Comment by anushbhatia** [comment]
Can you share a video for better understanding?

**Comment by Axelgoris99** [comment]
Wait, take a look at this and if you don't find it clear enough, I'll make a video! 
Thank you :)
In the code, you have 15 hackathon experience :)
On the website, you only have 13 showing and the two other ones need you to be at the first or the last dot and scroll one more dot where there is not supposed to be one using your mouse wheel :)
I've tried looking at the code but I could not find it! 
![15](https://user-images.githubusercontent.com/20966554/155958639-e72b88e1-eb1f-45db-955a-dfed025794af.png)
![13](https://user-images.githubusercontent.com/20966554/155958643-163cff12-64f5-4e36-b54e-65902e8ed6d1.png)

**Comment by anushbhatia** [comment]
Got it. we can add an endless carousel for this. Would you want on this?

**Comment by Axelgoris99** [comment]
? The issue is that there are possibly 2 of them that you CAN'T access.
If you only put two for example :
![image](https://user-images.githubusercontent.com/20966554/156535683-20a155dd-c4c0-4f27-b76d-24d3e738ad19.png)
There are no buttons in the carrousel. Meaning that people can't know that there is something else to see ! :)

**Comment by anushbhatia** [comment]
> ? The issue is that there are possibly 2 of them that you CAN'T access. If you only put two for example : ![image](https://user-images.githubusercontent.com/20966554/156535683-20a155dd-c4c0-4f27-b76d-24d3e738ad19.png) There are no buttons in the carrousel. Meaning that people can't know that there is something else to see ! :)

you can never access the top two experiences you mean?
