### ISSUE TITLE
Navbar Color Fix

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1201]
- In light mode: Color should be black and on hover violet
- Dark: Should not be changed
![navvar_color](https://user-images.githubusercontent.com/46641503/155875339-79ad013c-ff3a-42b5-9e80-14ca17ebb5e0.png)

Test thoroughly for all the pages and for mobile devices

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by smaranjitghose** [comment]
> I want to work on this issue under JWOC.

Assigned for 1-2 day(s)

**Comment by tanya-gupta25** [comment]
fixes#1201
