### ISSUE TITLE
Hackathon Section Button Hover

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1202]
![Hackathon_pg](https://user-images.githubusercontent.com/46641503/155876008-ca36dcc9-c590-4e01-8ce1-ff3919b33d5c.png)

**TASK**:  Remove the text color change effect on hover (For both light and dark modes)

Make sure your changes do not disturb the responsiveness or the overall UI

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by smaranjitghose** [comment]
> I want to work on this issue under JWOC.

Assigned for 1-3 days. An extension may be provided if required.
