### ISSUE TITLE
Research Page Button Fix

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1203]
![research_page_buttos](https://user-images.githubusercontent.com/46641503/155876146-37a2a855-eb9a-417e-b271-6b9980905e42.png)

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by smaranjitghose** [comment]
> I want to work on this issue under JWOC

Assigned for 1-3 days. An extension may be provided if required.
