### ISSUE TITLE
[React Version] Fix Work Ex Section

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1206]
# Current UI
![work_Ex_a](https://user-images.githubusercontent.com/46641503/155876575-0268b596-77dd-4f4b-bea6-8f6f6a0e7ea2.png)

# Expected UI
![work_Ex_b](https://user-images.githubusercontent.com/46641503/155876627-31156a9e-0468-4e08-8724-ea79b4dc7e17.png)

[Reference](https://portfolio.smaranjitghose.com/experience.html)

- The color scheme should be the same (text color, background color of cards, etc)
- The relative size of the cards
- Animation on scroll effect

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by smaranjitghose** [comment]
> I want to work on this issue under JWOC

Assigned for 1-3 days. An extension may be provided if required.
