### ISSUE TITLE
Reference Page Mobile Version Bugs

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1211]
# Current UI:
![ref_1_1](https://user-images.githubusercontent.com/46641503/155877078-c28d9915-7f0f-423c-aec4-41aaef271927.png)
![ref_1_2](https://user-images.githubusercontent.com/46641503/155877080-11fbef19-fbc7-43ad-bc3f-722c6e0f0822.png)

# Expected:
![expe_ref](https://user-images.githubusercontent.com/46641503/155877090-bb737ee9-40ef-4208-a0e0-ef465e6bec28.png)

# Task:
- **This issue is exclusively concerned with the images in the mobile versions (smaller screen sizes) for the website**
- Make sure your changes do not disturb the UI in the web version

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by smaranjitghose** [comment]
> I want to work on this under JWOC

Assigned for 2-4 days. Extension available if required.
