### ISSUE TITLE
Update Reference Page Data

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1212]
# Task

- Replace the Lorem Ipsum with actual recommendations. Use "john doe" as the name who is receiving the recommendation
- Add Imaginary Designations. For example Product Manager, Microsoft
- Replace Santosh Kumar Image with Aditya Jyoti Paul. Take image from [here](https://media-exp1.licdn.com/dms/image/C5603AQGEV-kzawPxjw/profile-displayphoto-shrink_800_800/0/1588602102622?e=1651708800&v=beta&t=8nxhFoR-WB4OKVltyYaVjmRpig_kQcvFsoa-eLjJPBQ)

# Reference

For inspiration check out the recommendation sections in the following LinkedIn profiles:
- [Example 1](https://www.linkedin.com/in/smaranjitghose/)
- [Example 2](https://www.linkedin.com/in/phreakyphoenix/)

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by smaranjitghose** [comment]
> I want to work on this issue under JWOC

Assigned for 2-4 days. An extension may be provided if required
