### ISSUE TITLE
[React Version] Fix Responsive Page UI and Responsiveness

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1213]
# Current UI

**Web Version**

![ref_page_1](https://user-images.githubusercontent.com/46641503/155877424-476561fb-ecff-4b55-bcfd-660f79d8eb76.png)
 
**Mobile Version**

![ref_page_2](https://user-images.githubusercontent.com/46641503/155877449-5ffe4cab-e542-49b3-bd72-60fda5b28d34.png)

# Expected UI

![ref_page_2_f](https://user-images.githubusercontent.com/46641503/155877491-2844a387-41c4-4917-aa95-cf25b7e32db6.png)

# Reference

[Main Branch Version](https://portfolio.smaranjitghose.com/reference.html)

# Task

- Fix Mobile Responsiveness of the page
- Adjust the cards (size + position according to that in the reference)
- Update the lorem ipsum with actual data. See [this](https://github.com/smaranjitghose/awesome-portfolio-websites/issues/1212)

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by smaranjitghose** [comment]
> I want to work on this under JWOC

Assigned for 2-4 days. An extension may be provided if required

**Comment by Shruti025** [comment]
hey, I'll need a little more time for this one. Is that alright? I have made a PR for all the other issues I was assigned.

**Comment by smaranjitghose** [comment]
Sure!
