### ISSUE TITLE
FormCarry Integration for Forms

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1214]
# Task
- Integrate `FormCarry` in the contact us forms in the footer. This would enable us to collect the feedback of the visitors on the page without having to create a dedicated backend.
- Check out the [documentation](https://formcarry.com/documentation/getting-started ) for the same.
- Do maintain the animation you can delay refreshing on a new page using a timeout or something.
- Provided the link for integration of the Form in the Project.

_Please feel free to reach out to me over discord in case you encounter any issues._

**Comment by MoofyWoofy** [comment]
Can I be assigned to this issue

**Comment by smaranjitghose** [comment]
> Can I be assigned to this issue

Assigned for 1-3 days. An extension may be provided if required.

**Comment by MoofyWoofy** [comment]
For the form action attribute, do I set it as an empty URL or leave it as it is?
Because the button doesn't trigger the form validation can I create one for name & email using regex and alert?

**Comment by anushbhatia** [comment]
> For the form action attribute, do I set it as an empty URL or leave it as it is



```
<form action="https://formcarry.com/s/BywEPAJNb" method="POST">
--
  | <label for="email">What is your Email Address?</label>
  | <input type="email" name="email" id="email">
  | <button type="submit">Subscribe</button>
  | </form>
```

use this
