### ISSUE TITLE
Add FormCarry Usage in Documentation

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#1216]
![doc_update](https://user-images.githubusercontent.com/46641503/155878232-0830f30c-b7f8-4fca-877b-3ea86e4efebb.png)

# Task:
- We wish to make it easy for the end-users of the project to update the details for the contact form as per their personal use
- The code related to documentation is available at [Head over https://github.com/smaranjitghose/awesome-portfolio-websites/tree/documentation]
- This is built using [mkdocs](https://www.mkdocs.org/)
- Add a section for the Contact Form and provide the information on how 
       - FormCarry is used
       - And the user can update the demo link to their personal link
 - Add a video if possible
 - Check the format of how the rest of the documentation is written and follow accordingly
 - The pr should be given only for the expected documentation branch

**Comment by MoofyWoofy** [comment]
Can I be assigned to this issue

**Comment by MoofyWoofy** [comment]
![image](https://user-images.githubusercontent.com/59331821/156435644-9f9b3cb5-935c-4e3e-869f-57e3c9ca9b26.png)
![image](https://user-images.githubusercontent.com/59331821/156434551-1b740273-3e08-4997-ac69-360aa3fa7c70.png)

The create form image is a gif from FormCarry documentations and the last image is a gif testing the form

Is this okay, the content and format?

**Comment by smaranjitghose** [comment]
Perfect @MoofyWoofy !
We look forward to your PR!
