### ISSUE TITLE
Restructure Image subdirectory

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1218]
## Current Structure:
![structure](https://user-images.githubusercontent.com/46641503/155878370-e2b77053-7fa0-42da-b114-7c8558ba7bd1.png)

## Expected Structure:

```
|-assets
    |- images
          |- home # Images related to the Home Page
          |- project # Images related to the Projects Page
          |- research # Images related to the Research Page
          |- work # Images related to work experience section in the Experience Page
          |- hackathon  # Images related to hackathon section in the Experience Page
          |- open_source # Images related to open source section in the Experience Page
          |- school # Images related to Formal Education Section in Education Page 
          |- mooc # Images related to Accreditation Section in Education Page
          |- reference # Images related to the Reference Page
          |- event # Images related to event page
          |- design # Images related to Design page
          |- travel # Images related to travel_temp page       
          |- skills # Images related to Tech Stack page   
          |- travel # Images related to travel_temp page       
          |- sem   # Images related to sem page       
```

# Task:

- This is a straightforward issue. You have to shift the images into new subdirectories or rename the ones in which they are already present according to the above structure.
- *The name of the directories should be exactly the same as stated above*
- Simultaneously the file paths should be updated in the corresponding html/js files
- We would expect you to split the work in 14-15 PRs so that in each PR, you do it for a particular page. This way it reduces the chances of error.

Multiple people can work on this simultaneously provided you collaborate over discord and make sure not to conflict with each other's work

**Comment by r3yc0n1c** [comment]
I want to work on this under JWoC'22

**Comment by phattymcfee** [comment]
I reviewed this issue and believe it has already been fixed.
