### ISSUE TITLE
[React Version] Design Page UI Fix

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1219]
# Task:

- Update the top section to exactly how it is in the main version of the project [here](https://portfolio.smaranjitghose.com/design.html)

![des_head](https://user-images.githubusercontent.com/46641503/155878767-470d20af-f1e7-47dd-8733-4a9e1201c14b.png)

- Remove this section. *Do not comment the code. Delete it*

![desi_](https://user-images.githubusercontent.com/46641503/155878720-e9d342cf-cf73-41bd-b6b4-b0ee35ac37dc.png)

- Update the last two sections exactly as done in the main version. 

![des_cards](https://user-images.githubusercontent.com/46641503/155878854-13ab9eaa-df79-4659-9e4a-a5603cc51a37.png)

- Keep in mind that on clicking the cards in the main version, the original file gets loaded in a new tab
- Instead of the text "Description" popping up on hover over the cards, change it to "Show Design"
![des_head_card](https://user-images.githubusercontent.com/46641503/155878844-fec26b45-266d-45a1-b64d-b41b90a62508.png)

**Comment by Tess-Vanta** [comment]
I want to work on this under JWOC
