### ISSUE TITLE
[React Version] Update Home Page Animation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1220]
# Task:

- Update the animation for `I am into ..` to the `animation in/animation out` shown [here]
- Keep in mind that only the words like "Machine Learning", "Web Development", etc should have the animation while the text I am into should not. [Similar to how it is given in reference]

**Comment by r3yc0n1c** [comment]
I want to work on this under JWoC'22
