### ISSUE TITLE
[React Version] Home Page Picture Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1221]
# Expected Behaviour:
![shad](https://user-images.githubusercontent.com/46641503/155879115-821d57e0-b2f2-4c91-addf-6e4d342d7e9c.png)

# Current State:
![shad_x](https://user-images.githubusercontent.com/46641503/155879138-fbba8567-3197-4719-a24a-a62cb3a3d5ba.png)

# Task:

- Update the shadow of the image

# Reference

[Main Version](https://portfolio.smaranjitghose.com/index.html)

**Comment by Shruti025** [comment]
I want to work on this under JWOC
