### ISSUE TITLE
[React Version] Add Dark Mode Toggle Switch

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1223]
![toggler](https://user-images.githubusercontent.com/46641503/155879434-8bc1d138-4be6-417c-bcb8-11cc87eb3a5d.png)

Try to make it as close as possible to the one in the main version

**Comment by Devmindtk** [comment]
I would like to work on this issue .please assign it to me @smaranjitghose

**Comment by anushbhatia** [comment]
> I would like to work on this issue .please assign it to me @smaranjitghose

Assigned for 3 days. Extension may be provided if required

**Comment by Devmindtk** [comment]
> 

Can you please explain exactly what i have to do like toggling switch in dark mode is already working fine so what i have to do?

**Comment by smaranjitghose** [comment]
> > 
> 
> Can you please explain exactly what i have to do like toggling switch in dark mode is already working fine so what i have to do?

Yes, but the dark mode is not implemented in the react version yet

**Comment by Devmindtk** [comment]
please check is is it fine
![Screenshot (508)](https://user-images.githubusercontent.com/91221069/156755102-087ae9d9-28eb-4176-8668-b94083855605.png)
?

**Comment by anushbhatia** [comment]
> please check is is it fine ![Screenshot (508)](https://user-images.githubusercontent.com/91221069/156755102-087ae9d9-28eb-4176-8668-b94083855605.png) ?

this is the `main` branch i think for the react version there's none on `reactjs` branch for the deployed version
https://awesome-portfolio-websites-git-fork-tanya-81e057-smaranjitghose.vercel.app/ check this here

**Comment by Devmindtk** [comment]
> > please check is is it fine ![Screenshot (508)](https://user-images.githubusercontent.com/91221069/156755102-087ae9d9-28eb-4176-8668-b94083855605.png) ?
> 
> this is the `main` branch i think for the react version there's none on `reactjs` branch for the deployed version https://awesome-portfolio-websites-git-fork-tanya-81e057-smaranjitghose.vercel.app/ check this here

I have created this one in react version.

**Comment by Devmindtk** [comment]
> > > please check is is it fine ![Screenshot (508)](https://user-images.githubusercontent.com/91221069/156755102-087ae9d9-28eb-4176-8668-b94083855605.png) ?
> > 
> > 
> > this is the `main` branch i think for the react version there's none on `reactjs` branch for the deployed version https://awesome-portfolio-websites-git-fork-tanya-81e057-smaranjitghose.vercel.app/ check this here
> 
> I have created this one in react version.

Not created a PR for this issue yet.

**Comment by anushbhatia** [comment]
You can go ahead doing that

**Comment by Devmindtk** [comment]
> You can go ahead doing that

Should I have to add the theme property Also of changing all the styling on the basis of light and dark theme or simply just i have to add a toggler button that i already done?

**Comment by anushbhatia** [comment]
Just add toggle button as of now

**Comment by Devmindtk** [comment]
> Just add toggle button as of now

created a PR please check

**Comment by Devmindtk** [comment]
> > Just add toggle button as of now
> 
> created a PR please check

https://user-images.githubusercontent.com/91221069/156899470-788d8cd2-46f5-461d-86ca-631b90ea49f8.mp4
