### ISSUE TITLE
NavBar Missing in SemTemp Page [Mobile Version]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1225]
![sem_temp](https://user-images.githubusercontent.com/46641503/155880104-ef92233d-d5a5-4abf-8106-e60dab6e1035.png)

**Comment by Devmindtk** [comment]
I would like to work on this issue. assign it to me

**Comment by Devmindtk** [comment]
> Assigned for 3 days

In mobile version in every page there is navbar present can you please share the screenshot of the page

**Comment by smaranjitghose** [comment]
> > Assigned for 3 days
> 
> In mobile version in every page there is navbar present can you please share the screenshot of the page

Actually the issue is with the width of the page in mobile mode which does not display the hamburger icon unless one scrolls left which is not an expected UX response for a small screen size (as you can see from the image above)

**Comment by Devmindtk** [comment]
> > > Assigned for 3 days
> > 
> > 
> > In mobile version in every page there is navbar present can you please share the screenshot of the page
> 
> Actually the issue is with the width of the page in mobile mode which does not display the hamburger icon unless one scrolls left which is not an expected UX response for a small screen size (as you can see from the image above)

please check i have created PR also

https://user-images.githubusercontent.com/91221069/156716942-c94b84b1-1edf-44c8-b108-4fe62cd0b8a5.mp4
