### ISSUE TITLE
Mobile Responsiveness Issue in Research Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1226]
# Current Status
![ed_s](https://user-images.githubusercontent.com/46641503/155880241-87f7e12d-fc32-4237-b9b6-d01ce6f307c3.jpeg)
![ed_sa](https://user-images.githubusercontent.com/46641503/155880242-42c74237-bf2c-439d-a2c3-d06f12af49d9.jpeg)

- The page does not adopt the dimensions of mobile devices (especially the width) appropriately

**Comment by Shruti025** [comment]
I want to work on this under JWOC
