### ISSUE TITLE
Mobile Responsiveness Issue in Education Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#1227]
# Current Status
![ed_sa-2](https://user-images.githubusercontent.com/46641503/155880397-dfd2df01-6843-4b62-9099-46c62ce5f892.jpeg)
![ed_sa](https://user-images.githubusercontent.com/46641503/155880242-42c74237-bf2c-439d-a2c3-d06f12af49d9.jpeg)

- The page does not adopt the dimensions of mobile devices (especially the width) appropriately

**Comment by 03amir** [comment]
i want to work on this issue under jwoc

**Comment by Shivam-Katare** [comment]
Hey @smaranjitghose , I want to work on this issue So, can I start to work?

**Comment by smaranjitghose** [comment]
> Hey @smaranjitghose , I want to work on this issue So, can I start to work?

Assigned for 1-3 days. An extension may be provided if required.

**Comment by Shivam-Katare** [comment]
@smaranjitghose Thanks for assigning this issue to me. I am working on it and, half work is already done. I will try to make it on time.
