### ISSUE TITLE
[REACT VERSION] Fix Open Source Section

### ISSUE THREAD

**Issue by tanya-gupta25** [smaranjitghose/awesome-portfolio-websites#1257]
### **Current UI**
![image](https://user-images.githubusercontent.com/82203261/156875285-853d0bd6-171f-4195-8db2-b6d24ae5c00e.png)

### **Expected UI**

![image](https://user-images.githubusercontent.com/82203261/156875302-4b26518e-48c5-4a6e-9086-03057ebf83fa.png)

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC

**Comment by destrex271** [comment]
I want to work on this issue
