### ISSUE TITLE
Enhancment : Validation of "Get in Touch" using pop-up msg

### ISSUE THREAD

**Issue by soujo** [smaranjitghose/awesome-portfolio-websites#1276]
The validation for the `Get in Touch` form is done using alert, which is a basic alert method. We can customize the alert message box using `sweet alert` which would better sync with the website.
If this idea looks appropriate to you then I want to work on this issue under JWOC. 
@smaranjitghose

**Comment by anushbhatia** [comment]
Great Go ahead with this

**Comment by soujo** [comment]
Kindly add the JWOC label and difficulty level @anushbhatia
