### ISSUE TITLE
Link Not Submitted

### ISSUE THREAD

**Issue by maligaurav947** [smaranjitghose/awesome-portfolio-websites#1296]
Hey There Love Your Work 
when I watching The Website got Chance to Go  through the project Section
When I am clicking the project **GitHub or link it reloading the same page** 
try to fix that

**Comment by anushbhatia** [comment]
![image](https://user-images.githubusercontent.com/40017559/162567443-d42c73fa-4640-488b-b6b4-b19a272c0fb2.png)
have you added the GitHub link there in the particular field?

**Comment by anushbhatia** [comment]
> https://portfolio.smaranjitghose.com/projects.html
> 
> seen on web page on project the project link it not working

because we have kept the link in the code blank as of now if u use the template u can replace it with the desired links
