### ISSUE TITLE
Experience Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#13]
# Experience Page
 ( Try to have cards depicting a picture or graphics related to the workplace + Role Name + Role Time + Bullet points about the work done + A micro-animation for an icon redirecting to any letter if available)
- [x] Internships/Jobs
- [x] Mentorship
- [x] Freelance/Volunteering

**Comment by divyakelaskar** [comment]
Would like to work on the issue
