### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by datasith** [smaranjitghose/awesome-portfolio-websites#1301]
Thanks for the awesome (literally) template. Can the main branch be renamed pls? Shouldn't take more than 5 mins, here's a great guide: https://www.git-tower.com/learn/git/faq/git-rename-master-to-main

Thanks again!

**Comment by anushbhatia** [comment]
Naming branch won't make a significant difference. So we would prefer it to be same

**Comment by datasith** [comment]
Hey, @anushbhatia. Respectfully, I understand the main issue is "U.S.-centric", but please be mindful and educate yourself about why it does make a difference in some parts of the world:

* [reference](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main#:~:text=GitHub%20took%20action%20based%20on,a%20different%20default%20for%20new) (out of many examples)

**Comment by datasith** [comment]
It does affect the support for social injustice around the world, and particularly in the U.S. I understand if this isn't something you feel the project needs to get involved with, but I want to bring it to your attention nonetheless.
