### ISSUE TITLE
"Hackathon Participation" text on experience page overlaps with "Get in Touch" section

### ISSUE THREAD

**Issue by moritz-gerster** [smaranjitghose/awesome-portfolio-websites#1329]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/45031224/216805920-df56a18a-3237-489d-bbc6-7b8342c0a3c7.png">

This bug seems to be very new, I just noticed it both on my personal website on the [exemplary project website](https://portfolio.smaranjitghose.com/experience.html).

**Comment by MoofyWoofy** [comment]
This is because of the new version of Swiper, to fix it, use Swiper version 8.4.6

**Comment by moritz-gerster** [comment]
> This is because of the new version of Swiper, to fix it, use Swiper version 8.4.6

Thank you @MoofyWoofy! Sorry for this naive question, but how do I install Swiper 8.4.6? I am not running this code in my own virtual environment as I do for my python files where I can install packages using pip.

**Comment by MoofyWoofy** [comment]
Inside experience.html

You will find this a link similar to this `https://unpkg.com/swiper/swiper-bundle.css`
Replace it with this, `https://unpkg.com/swiper@8.4.6/swiper-bundle.css`
You can do this for the 2 CSS and 1 JS file.

**Comment by moritz-gerster** [comment]
Thank you @MoofyWoofy. I changed it in experience.html however not in the other 2 CSS and 1 JS files as I did not find a proper place to do it there.

However, now loading my experience page takes very very long and the hackathon figure completely disappeared: https://moritz-gerster.github.io/experience.html

**Comment by MoofyWoofy** [comment]
Sorry I meant, inside `experience.html`, there should be these lines

```html
<link rel="stylesheet" href=" https://unpkg.com/swiper/swiper-bundle.css" />
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
```

Replace them with this respectively
```html
<link rel="stylesheet" href=" https://unpkg.com/swiper@8.4.6/swiper-bundle.css" />
<link rel="stylesheet" href="https://unpkg.com/swiper@8.4.6/swiper-bundle.min.css" />
<script src="https://unpkg.com/swiper@8.4.6/swiper-bundle.min.js"></script>
```

**Comment by moritz-gerster** [comment]
Thank you!
