### ISSUE TITLE
Misalignment between the windows cursor and the website's cursor

### ISSUE THREAD

**Issue by wiizzl** [smaranjitghose/awesome-portfolio-websites#1338]
I encountered a bug when attempting to reuse the website's cursor, where a misalignment was created between the actual cursor and the website's cursor when scrolling the page while moving my cursor. I managed to fix the issue by modifying the 'mousemove' event in the assets/js/cursor.js code.

```
document.addEventListener("mousemove", function (e) {
        // Show the cursor
        self.cursorVisible = true;
        self.toggleCursorVisibility();
      
        // Position the dot
        self.endX = e.pageX - window.scrollX; // I edit this line
        self.endY = e.pageY - window.scrollY; // this line too
        self.$dot.style.top = self.endY + "px";
        self.$dot.style.left = self.endX + "px";
});
```

I'm not sure if this will be useful for other people, but I hope to be able to help.

**Comment by anushbhatia** [comment]
Can you create a PR and we can have a quick look over how does it look.
