### ISSUE TITLE
Education Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#14]
# Suggestions:

- [x] Formal Education: A card with the name of the College, Degree, A picture or Illustration relevant to it,Activities
- [x] MOOCs
- [x] Badges

**Comment by shubhkhanna** [comment]
@smaranjitghose Sir, I'm working on this page.

**Comment by shubhkhanna** [comment]
> # Suggestions:
> * [x]  Formal Education: A card with the name of the College, Degree, A picture or Illustration relevant to it,Activities
> * [ ]  MOOCs
> * [ ]  Badges

#31

**Comment by Adyasha8105** [comment]
@smaranjitghose I want to do some enhancements on this page. Can I?

**Comment by smaranjitghose** [comment]
> @smaranjitghose I want to do some enhancements on this page. Can I?

Can you please elaborate more?

**Comment by Adyasha8105** [comment]
@smaranjitghose  
- I want to change all the images.
- I want to put padding everywhere as it looks clumsy.

**Comment by smaranjitghose** [comment]
> @smaranjitghose
> 
> * I want to change all the images.
> * I want to put padding everywhere as it looks clumsy.

Cool, Please give a PR. Additionaly change the hover effect that shows certificate. It's unrequired

**Comment by shubhkhanna** [comment]
> # Suggestions:
> * [x]  Formal Education: A card with the name of the College, Degree, A picture or Illustration relevant to it,Activities
> * [x]  MOOCs
> * [ ]  Badges

#54
