### ISSUE TITLE
Adding a Favicon

### ISSUE THREAD

**Issue by AshutoshDash1999** [smaranjitghose/awesome-portfolio-websites#146]
I want to add a favicon to the site. Let me know do you have any logo designed already or shall I give some suggestions?!

**Comment by AshutoshDash1999** [comment]
@smaranjitghose Do you have any logo already designed  or should I suggest one?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Do you have any logo already designed or should I suggest one?

Anythning works that does not give us a copyright issue

**Comment by AshutoshDash1999** [comment]
I was thinking, since its a professional website, a suitcase/tie will look good. also if I add text to the logo, it won't be visible in the favicon. What do you think?

**Comment by smaranjitghose** [comment]
> I was thinking, since its a professional website, a suitcase/tie will look good. also if I add text to the logo, it won't be visible in the favicon. What do you think?

Ya that works fine!

**Comment by AshutoshDash1999** [comment]
what about black icon with white background?
Like [this](https://w7.pngwing.com/pngs/890/625/png-transparent-black-suitcase-briefcase-computer-icons-suitcase-baggage-simple-briefcase-icon-bag-baggage-breafcase-brief-miscellaneous-rectangle-business.png)
*Only for representation

**Comment by waterupto** [comment]
Interested @smaranjitghose sir!

**Comment by AshutoshDash1999** [comment]
@waterupto I'm already working on this!

**Comment by waterupto** [comment]
So, am I not allowed to do it? As in they'll see which is the best one and get it merged.

**Comment by smaranjitghose** [comment]
> So, am I not allowed to do it? As in they'll see which is the best one and get it merged.

There is nothing like not allowed to in open source 😅. @AshutoshDash1999 had raised this issue and he is assigned it for 10 days ( @AshutoshDash1999 you have a few more days remaining😉 ).  @waterupto You can raise an issue and suggest an improvement/alternative after he gets his PR merged within the deadline. In order to avoid conflicts, you are suggested not to work in parallel on a task already assigned to someone😇. Please have a look at the recent message on our project's slack channel. There's a lot to be done. If you want to claim any one of those do raise an issue or comment in the thread there

**Comment by AshutoshDash1999** [comment]
@smaranjitghose I really apologise for being delayed. I didn't saw you have liked my message.
Do you like this one?
![favicon-awesome-portfolio](https://user-images.githubusercontent.com/46455250/93663497-20bc6280-fa86-11ea-925b-c9f36eb7dc27.png)

**Comment by smaranjitghose** [comment]
> @smaranjitghose I really apologise for being delayed. I didn't saw you have liked my message.
> Do you like this one?
> I kept the black-white combination to match with the color theme of the site
> ![favicon-awesome-portfolio](https://user-images.githubusercontent.com/46455250/93663497-20bc6280-fa86-11ea-925b-c9f36eb7dc27.png)

@anushbhatia would give better feedback than me on this

**Comment by AshutoshDash1999** [comment]
@anushbhatia any views on favicon?

**Comment by smaranjitghose** [comment]
> @anushbhatia any views on favicon?

@anushbhatia is occupied due to some personal as well as professional commitments. You can go ahead and give a PR for the favicon

**Comment by AshutoshDash1999** [comment]
@smaranjitghose submitted a PR #175
