### ISSUE TITLE
GraphQL script

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#154]
Create a script that uses GitHub's GraphQLv4 api to fetch the details of the PRs for this project with particular labels and/or by particular usernames

**Comment by ritvij14** [comment]
@smaranjitghose sir, I have some intro to GraphQL APIs. But I have very little knowledge about scripting. But I am interested in trying this out.
Is the script you said something like how the Bash Scripts work? Entering a command and getting the PRs for this repository?

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir, I have some intro to GraphQL APIs. But I have very little knowledge about scripting. But I am interested in trying this out.
> Is the script you said something like how the Bash Scripts work? I have played around with Bash scripts. Entering a command and getting the PRs for this repository?

We can go definitely for a bash script but I would suggest going for a python script (or JS based) as it would be easier for others to use,debig and modify

Basically the query should be: 

For this repo
        |
        |----Find Pull Requests
                              |------ with labels{label1,label2}
                                                    |---------- Name of PR
                                                    |----------All Labels
                                                    |-----------Username

**Comment by smaranjitghose** [comment]
@ritvij14 I have done a bare bones implementation [here](https://github.com/smaranjitghose/GitKundli). Perhaps you can update the script to remove further unnecessary data and leave us only with the github username of participant, labels given to a pr

**Comment by ritvij14** [comment]
Ok, sir. I don't know much of Python so I won't be working on this for now. :sweat_smile:
