### ISSUE TITLE
Detailed Contribution Guidelines

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#156]
Rewrite the Contribution.MD for helping any beginner to contribute to this project.

# Key Features:

- Some GIFs
- How to install Git, setup GitHub, etc
- How to fork this repo, create feature branch, pull changes from upstream,etc
- Giving a PR

** Majority of the above should be written in terms of CLI
** Any screenshots you used must be of this repo, pushed inside assets folder and fetched from here. It is expected that you spend time on using a software like AdobeXD,Photoshop etc to make them custom, highlight features etc

**Comment by shraddhavp** [comment]
interested @smaranjitghose  sir

**Comment by waterupto** [comment]
Interested @smaranjitghose sir!

**Comment by shraddhavp** [comment]
@waterupto  the issue is already taken

**Comment by smaranjitghose** [comment]
> Interested @smaranjitghose sir!

This is a relatively easy task. I believe @shraddhavp can do it alone. Once her PR is merged for this, @waterupto you are welcome to work on any improvements

**Comment by smaranjitghose** [comment]
> @waterupto the issue is already taken

Can I expect a PR for this by the next 3 days?

**Comment by shraddhavp** [comment]
> > @waterupto the issue is already taken
> 
> Can I expect a PR for this by the next 3 days?

yes sir by tommorow I will submit the PR
