### ISSUE TITLE
"to Top Button" design

### ISSUE THREAD

**Issue by nikita-1801** [smaranjitghose/awesome-portfolio-websites#166]
As mentioned on the channel by @smaranjitghose I'd like to work on improving the "to top button" design and position.

**Comment by nikita-1801** [comment]
Is there any design you'd like for me to implement here? Also, where do you want it to be positioned?

**Comment by smaranjitghose** [comment]
> Is there any design you'd like for me to implement here? Also, where do you want it to be positioned?

Sure you can try a new design. Well, the issue is not with the horizontal position on the webpage but with the vertical position on the web page till which it appears. For example for the Home Page, we actually do not require it
