### ISSUE TITLE
Updates to ReadMe

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#173]
## Requirements:
- [X] Remove the listed tasks
- [ ] In the beginning put a custom logo for awesome-developer-portfolio
- [X] The section following that should be a crisp ( max 100 words description of the project)
- [X] Put a subheading for ```A sneak peek```
- [x] Replace the screenshots with gifs of how each page looks when scrolled down
- [X] For each page put a sub sub heading 
- [ ] Write some points about the features of each page
- [X] Sub Section on ```How to use this?```
- [X] ```The geeks🤓 behind this initiative!:```
- [ ] Sub Section on Contribution Guidelines. Copy the content from ```Contributing.MD``` and place it here appropriately. 
- [X] Sub Heading  ```Open Source Programs we have been a part of:```
- [ ] Specify name(sub sub headings), followed by a logo and a short description of the program for : 
      - SCI 
      - HackInCodes CH-20
      - HactoberFest 2020
      - SLOP 2020
- [ ] Sub Subsections on License and Code of Conduct. Be creative here

**Comment by ritvij14** [comment]
Sir is this issue up for CH20? I would like to work on this.

**Comment by smaranjitghose** [comment]
> Sir is this issue up for CH20? I would like to work on this.

Yes

**Comment by ritvij14** [comment]
@smaranjitghose sir I have some minor doubts regarding a couple of tasks,
1. In the initial section below the main heading, should I change the whole content itself or shorten it more? It's already less than 100 words.
2. What should I write for the description of the project maintainers?

**Comment by shraddhavp** [comment]
@smaranjitghose  sir would like to work on the issue if the issue is still open

**Comment by Akansha-Bhandari** [comment]
sir can i work on this issue if it is still open ..

**Comment by anushbhatia** [comment]
> @smaranjitghose sir I have some minor doubts regarding a couple of tasks,
> 
> 1. In the initial section below the main heading, should I change the whole content itself or shorten it more? It's already less than 100 words.
> 2. What should I write for the description of the project maintainers?
> 
> I have done all the other tasks except these 2 and the logo one.

1.Paraphrasing in some other way.
2. For project maintainer section add the images of @smaranjitghose and me. Also, add links to GitHub and LinkedIn

**Comment by anushbhatia** [comment]
@shraddhavp @Akansha-Bhandari you can take up project guide and if you want and tell us about it?

**Comment by Aniruddhmuley2001** [comment]
@smaranjitghose Can I update the file in an attempt to convince developers the importance of a portfolio and to encourage the use of the template.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Can I update the file in an attempt to convince developers the importance of a portfolio and to encourage the use of the template.

Sure!

**Comment by Dhiraj3118** [comment]
I would like to do this. Tell me what custom logo I are you talking about in 2nd point.

**Comment by manasisaiba** [comment]
sir I would like to work on adding short description of the program followed by logo .

**Comment by Kerveyfelix** [comment]
Can I add the picture of NWOC logo under the programs this project is part of?
