### ISSUE TITLE
Add Favicon to Documenation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#188]
- Please push the changes only to the ```documentation branch```
- Do not push any build files
- However, you are expected to share a link of the deploy of your changes. To do this, after doing the changes locally please do:
``mkdocs gh-deploy``.

**Comment by shagun25** [comment]
can i work on this?

**Comment by shagun25** [comment]
Any deadline for submission?

**Comment by smaranjitghose** [comment]
> Any deadline for submission?

Before 2nd Oct

**Comment by sanchibansal340** [comment]
Hello @smaranjitghose. I am interested in working on this issue. 
https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/assets/images/favicon.png
Does this image needs to be added to README.md?

And where does it need to be added in the README?

Thanks!

**Comment by smaranjitghose** [comment]
> Hello @smaranjitghose. I am interested in working on this issue.
> https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/assets/images/favicon.png
> Does this image needs to be added to README.md?
> 
> And where does it need to be added in the README?
> 
> Thanks!

No you are expected to make a custom favicon for the documentation.
This is required for the documentation code generated from the ``documentation`` branch and hosted at ``gh-pages`` branch
