### ISSUE TITLE
Home Page of the Documentation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#189]
# Expected Contents:

- [ ]  Same as README

# Common Instructions

- Please push the changes only to the ```documentation branch```
- Do not push any build files
- However, you are expected to share a link of the deploy of your changes. To do this, after doing the changes locally please do:
``mkdocs gh-deploy``.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?
