### ISSUE TITLE
Getting Started for the documentation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#190]
# Expected Contents:

- Detailed Walkthrough about how to use this repository as a template, clone it, make changes, push them back and host it
- Sub Sections ( Nested Pages):
     - [ ] First Steps: Navigating to this repo on GitHub, Using this as a template, Installing and setting up Git, Cloning the repo
     - [ ] Education Page
     - [ ] Experience Page
     - [ ] Projects Page
     - [ ] Research Page
     - [ ] Home Page
     - [ ] Navbar and Footer
     - [ ] SEO and Miscellaneous 
     - [ ] Final Steps
     - [ ] Hosting: GitHub Pages, Netlify, surge.sh, Amazon Amplify

# Common Instructions

- Please push the changes only to the ```documentation branch```
- Do not push any build files
- However, you are expected to share a link of the deploy of your changes. To do this, after doing the changes locally please do:
``mkdocs gh-deploy``.

**Comment by smaranjitghose** [comment]
The beginning of the guide is abrupt. Come up with something creative for that

**Comment by smaranjitghose** [comment]
The steps should be under:

1. [SECTION A] Getting our template
         |-- [Pre-req] Configuring Git, Creating a GitHub Account
         |-- Going to our template and forking the repo
         |-- Cloning it
         |-- Navigating to it
         |--Open the terminal and ensure remote it set up
2. Making Changes
       * For each of the pages, a small description of what one can put there and a gif that shows a scroll down of the page
       * Instructions can be made more elaborate
       * SEO subsection should be more descriptive to help users understand why and how to do it
3. Hosting 
        |--The subsections on adding custom domains can be elaborated further

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @smaranjitghose
