### ISSUE TITLE
Team Page for Documentation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#191]
# Expected Contents:

- [ ]  Illustration
- [ ] A quote about teamwork
- [ ] Project Maintainer's Section
- [ ] Contributors Section

# Common Instructions

- Please push the changes only to the ```documentation branch```
- Do not push any build files
- However, you are expected to share a link of the deploy of your changes. To do this, after doing the changes locally please do:
``mkdocs gh-deploy``.

**Comment by shagun25** [comment]
can i work on this?

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by srishtij2000** [comment]
Should I share a screenshot before issuing a PR?

**Comment by smaranjitghose** [comment]
> Should I share a screenshot before issuing a PR?

You can attach it in the PR description

**Comment by srishtij2000** [comment]
Okay

**Comment by srishtij2000** [comment]
I am a bit confused that where should I attach this?

**Comment by srishtij2000** [comment]
Kindly guide me

**Comment by smaranjitghose** [comment]
> I am a bit confused that where should I attach this like where this team page is there on the website?

OH! Simple. Just take a screenshot, save it on your desktop. Forget about it for a while. Go the directory for this project. Change to the mkdocs branch. Once the changes are staged and committed, push it your forked repo, raise a pr. Edit the PR description.  Drag and drop the screenshot

**Comment by prabhat04011998** [comment]
Hey is this issue is available?

**Comment by prabhat04011998** [comment]
Hey @smaranjitghose  can you explain the issue a bit,

what i understand is that "I need to design a template for a page which will be inlcuded as team page on the website right?"
