### ISSUE TITLE
Optimization and Miscellaneous

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#20]
- [x]   Search Engine Optimization - Currently taken care by @shubhkhanna 
- [ ]   Optimize Assets
- [ ]   Faster Loading of Page
 - [x]  Dynamic Loading of content using JSON Injection
 - [x]  robot.txt
 - [ ]  Google Analytics Integration

**Comment by aashimgarg** [comment]
Add .htaccess file for browser caching too.
