### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by arghac14** [smaranjitghose/awesome-portfolio-websites#21]
Description of the enhancement:
1. Create a blog page using fastpages.
2. Integrate the existing navbar.
3. Use dark theme.
4. Use fixed colour scheme.
5. Use animation and transition effect.

**Comment by rewa15** [comment]
Sir,I want to take up the issue.

**Comment by arghac14** [comment]
@Adyasha8105 you may work on this. For now, continue with the light theme only.
