### ISSUE TITLE
Social Media Icon Links in the website are not directed to the linked webpage 

### ISSUE THREAD

**Issue by Apollo9999** [smaranjitghose/awesome-portfolio-websites#249]
In the Website https://portfolio.smaranjitghose.codes/  .The following issues are notified 

1).Consider Social Media Icon Links like Twitter, Github of the website https://portfolio.smaranjitghose.codes/ are not to directed to the concerned webpage  account of https://portfolio.smaranjitghose.codes/ in Twitter and Github

**Comment by smaranjitghose** [comment]
> In the Website https://portfolio.smaranjitghose.codes/ .The following issues are notified
> 
> 1).Consider Social Media Icon Links like Twitter, Github of the website https://portfolio.smaranjitghose.codes/ are not to directed to the concerned webpage account of https://portfolio.smaranjitghose.codes/ in Twitter and Github

This a template meant for people to use for their own portfolio so we have left them empty for putting in their own social media links as and when required
