### ISSUE TITLE
Resume Link

### ISSUE THREAD

**Issue by capturemathan** [smaranjitghose/awesome-portfolio-websites#259]
Kudos to a wonderful website 🎉 , the `Resume` section in the `navbar` doesn't redirect to your resume rather provides a general `resume-format`.

**Comment by smaranjitghose** [comment]
> Kudos to a wonderful website 🎉 , the `Resume` section in the `navbar` doesn't redirect to your resume rather provides a general `resume-format`.

Yes, that's been pending for quite some time
