### ISSUE TITLE
Add easy to modify (add content) react templates which can be hosted on static website  

### ISSUE THREAD

**Issue by hi-18-K** [smaranjitghose/awesome-portfolio-websites#260]
Could I add an react project (as templates for portfolio). That could be deployed using github pages simply or heroku or other deploying website. I will also add clear instructions for modifying, deploying and using the project.

I would also like to add simple templates for html pages that can be hosted publishing research online.(this as seprate work from above one.)

**Comment by smaranjitghose** [comment]
> Could I add an react project (as templates for portfolio). That could be deployed using github pages simply or heroku or other deploying website. I will also add clear instructions for modifying, deploying and using the project.
> 
> I would also like to add simple templates for html pages that can be hosted publishing research online.(this as seprate work from above one.)

Sure. I would create a separate branch for you

**Comment by smaranjitghose** [comment]
@anushbhatia

**Comment by smaranjitghose** [comment]
> Could I add an react project (as templates for portfolio). That could be deployed using github pages simply or heroku or other deploying website. I will also add clear instructions for modifying, deploying and using the project.
> 
> I would also like to add simple templates for html pages that can be hosted publishing research online.(this as seprate work from above one.)

Any updates?
