### ISSUE TITLE
Modify the social media icons on Home Page [ Dark mode] so that they blend with the design more effectively

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#261]

**Comment by AggiSahithi** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?

**Comment by chehak123** [comment]
Can you assign it to me?

**Comment by snehaM2210** [comment]
Hello @smaranjitghose , since no-one has done the task yet, can you please re-assign it to me? I would like to work on this issue.

**Comment by snehaM2210** [comment]
Hai @smaranjitghose, I've made these icon changes in dark mode, Is this okay or if you need any further modifications, please convey.
<img width="948" alt="Portfo" src="https://user-images.githubusercontent.com/68493940/102057401-ddb72480-3e13-11eb-8a97-fd28a9385968.PNG">
