### ISSUE TITLE
Replace the timeline in the education page with something more mobile friendly

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#263]

**Comment by shikharcodes** [comment]
Hey! I would like to work on this issue. Can you assign this to me?

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by Pranav016** [comment]
The timeline on the education page is responsive. Do you still want me to replace it? I can think of something to replace it with, some suggestions would be great. @smaranjitghose

**Comment by smaranjitghose** [comment]
> The timeline on the education page is responsive. Do you still want me to replace it? I can think of something to replace it with, some suggestions for what you would like to see would be great. @smaranjitghose

Yes the timeline is mobile responsive and we are aware of it. The area of improvement from a design point of view is it should be more aesthetically pleasing on the mobile view unlike the current version which stacks all the cards over one another at one side of the phone screen

**Comment by Pranav016** [comment]
@smaranjitghose Got you, I have a nice UI design in mind and will start working on it.

**Comment by Pranav016** [comment]
@smaranjitghose I was working on this issue and after a lot of hours of trying to add the section, that was working perfectly in a blank html file but not in this, I realized that the code base is really bad. Someone has generalized the height, width of very common bootstrap classes like row, card etc. I can add the section without the classes but it just won't be that great. So its your call of what should be done. I don't want to disrupt the code that is working, I'll try to add the section as best as I can.

**Comment by anushbhatia** [comment]
You can fix it from the scratch form if you want or else comment on the previous code and start working on it. If you wan to can go ahead with a new HTML page too.

**Comment by Pranav016** [comment]
> You can fix it from the scratch form if you want or else comment the previous code and start working on it. If you want to can go ahead with a new HTML page too.

Sure, I'll make a new branch and comment the code and start working on the page👍

**Comment by umbridge** [comment]
@smaranjitghose the text of education timeline in dark mode is not visible. Can i fix it, if you assign me this task?

![Screenshot (175)](https://user-images.githubusercontent.com/44002678/102711880-e1025280-42e2-11eb-9a9c-f7bdc98d2302.png)

**Comment by Pranav016** [comment]
> @smaranjitghose the text of education timeline in dark mode is not visible. Can i fix it, if you assign me this task?
> 
> ![Screenshot (175)](https://user-images.githubusercontent.com/44002678/102711880-e1025280-42e2-11eb-9a9c-f7bdc98d2302.png)

I was already working on the education cards, will fix this! Refer to issue #333 🙂
