### ISSUE TITLE
Toggle Button Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#264]
Whenever one switches to dark mode for a page say 'x' and we move to another page say 'y' the page loads up back in light mode instead of being continued to be displayed in 'dark mode'

**Comment by kunaljain0212** [comment]
Can I work on this issue, please? @smaranjitghose

**Comment by Vishal-raj-1** [comment]
I would like to work on this issue. 

Thanks 😃

**Comment by Vishal-raj-1** [comment]
@kunaljain0212 are you working on this issue ? If not kindly reply me, I would go for it. If you are doing take your time no problem.

**Comment by kunaljain0212** [comment]
@smaranjitghose I have created a pull request for this issue. It is ready for review -> #272

**Comment by Vishal-raj-1** [comment]
Great Brother @kunaljain0212
