### ISSUE TITLE
Improve Footer Design

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#265]

**Comment by shikharcodes** [comment]
Hey! I would like to work on this issue as a part of Nwoc. Can you assign this to me please?

**Comment by chehak123** [comment]
Can i work on it as a part of nwoc?

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @smaranjitghose

**Comment by chehak123** [comment]
Thanks for assigning it to me. Can you please brief out about what all to be added in footer?

**Comment by Vishal-raj-1** [comment]
Hello @chehak123, You have to improve footer. Some Issues I get in footer is :


![fo](https://user-images.githubusercontent.com/59874304/101236040-b5cd1000-36f3-11eb-80aa-083872044ede.JPG)

I think it should be like :

![fo2](https://user-images.githubusercontent.com/59874304/101236064-f62c8e00-36f3-11eb-860e-b7bc5c00e3fb.JPG)

 One More Thing you can do is Improve Icons in Dark theme .

![fo3](https://user-images.githubusercontent.com/59874304/101236126-794de400-36f4-11eb-9ab4-3536333e2212.JPG)

@smaranjitghose @anushbhatia I think You should assign this issue to multiple people.

**Comment by Nishant2907** [comment]
Hello can i work on this issue?

**Comment by smaranjitghose** [comment]
> Hello @chehak123, You have to improve footer. Some Issues I get in footer is :
> 
> ![fo](https://user-images.githubusercontent.com/59874304/101236040-b5cd1000-36f3-11eb-80aa-083872044ede.JPG)
> 
> I think it should be like :
> 
> ![fo2](https://user-images.githubusercontent.com/59874304/101236064-f62c8e00-36f3-11eb-860e-b7bc5c00e3fb.JPG)
> 
> One More Thing you can do is Improve Icons in Dark theme .
> 
> ![fo3](https://user-images.githubusercontent.com/59874304/101236126-794de400-36f4-11eb-9ab4-3536333e2212.JPG)
> 
> @smaranjitghose @anushbhatia I think You should assign this issue to multiple people.

Would you like to work on the responsiveness bug

**Comment by Nishant2907** [comment]
Hi @smaranjitghose  i did some changes in the footer design, kindly look at the screenshots i am attaching and give your reviews.
on max width
![image](https://user-images.githubusercontent.com/59792198/101453873-05ab1180-3956-11eb-88ca-fca57867a1de.png)

on reducing the width f the screen
![image](https://user-images.githubusercontent.com/59792198/101453982-3db25480-3956-11eb-8098-2e19988f71fd.png)

kindly have a look and give ur reviews.

**Comment by Nishant2907** [comment]
Hi @smaranjitghose, I have updated all the changes you asked for. I am making a PR kindly review it.

**Comment by Vishal-raj-1** [comment]
.> on max width
> ![image](https://user-images.githubusercontent.com/59792198/101453873-05ab1180-3956-11eb-88ca-fca57867a1de.png)

Logo should be in center.

**Comment by Vishal-raj-1** [comment]
Okay I am going to work on this issue. Will send the PR shortly.

**Comment by Nishant2907** [comment]
Hey buddy, i am still working on the PR. Just hold on for a sec...

**Comment by Vishal-raj-1** [comment]
> Hey buddy, i am still working on the PR. Just hold on for a sec...

Sure buddy, I have no problem you can continue !! and take your time, I will solve another issue!!

Don't Hurry, Do it nicely. All the best @Nishant2907  🔥

**Comment by Nishant2907** [comment]
Actually i had completed the issue previous night, just forgot to commit it. Will commit it within minutes. You can have a look at the commits. Also do tell if you find any loose ends in the code :)

**Comment by Vishal-raj-1** [comment]
@Nishant2907 I love to do reviewing peers code. But because of guideline of NWOC, I can't review. So let wait @smaranjitghose Sir will review and merge and I will do the rest( I have seen it need lot more to do). 

Keep Coding and Learning!!

**Comment by Nishant2907** [comment]
Yep Sure,

**Comment by Vishal-raj-1** [comment]
@Nishant2907 Hey Brother You have done awesome work 👏🏻 . Now logo and quotes are perfectly fine. I think there is something that I can work upon the icon part.

**Comment by smaranjitghose** [comment]
> @Nishant2907 Hey Brother You have done awesome work 👏🏻 . Now logo and quotes are perfectly fine. I think there is something that I can work upon the icon part.

Sure. Go ahead
