### ISSUE TITLE
Improve Nav Bar design for Mobile View

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#266]

**Comment by shikharcodes** [comment]
Hey! I would like to work on this issue as a part of Nwoc. Can you assign this to me?

**Comment by chehak123** [comment]
Can i work on it as a part of nwoc?

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @smaranjitghose

**Comment by anushbhatia** [comment]
Any update?

**Comment by Vishal-raj-1** [comment]
@shikharcodes Brother if you working on this issue so please reply otherwise there are many who loves to work right now.

**Comment by smaranjitghose** [comment]
> @shikharcodes Brother if you working on this issue so please reply otherwise there are many who loves to work right now.

You can go ahead
