### ISSUE TITLE
Light and dark mode slider in not sliding at mobile view  

### ISSUE THREAD

**Issue by An-prog-hub** [smaranjitghose/awesome-portfolio-websites#274]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/67872399/100992738-8cd53f80-357a-11eb-8621-9371986523e7.gif)

**Comment by Vishal-raj-1** [comment]
@smaranjitghose @anushbhatia Sir I want to work on this issue. Should I start ?

**Comment by anushbhatia** [comment]
Use a fresh toggle button code and you can change the template for the navbar if necessary in that.

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia Sir I want to work on this issue. Should I start ?

Let's give @An-prog-hub 3 days for this. If he is unable to do it or if there are improvements left out, you can take over

**Comment by Vishal-raj-1** [comment]
> Let's give @An-prog-hub 3 days for this. If he is unable to do it or if there are improvements left out, you can take over

Sure Sir, @An-prog-hub Take your time. All the best!!

**Comment by smaranjitghose** [comment]
By the way, a small design improvement to the slider would be "the sun" . The two concentric circles make it a bit weird. We can go for something that resembles it more closely
