### ISSUE TITLE
CSS Problem on Research Page.

### ISSUE THREAD

**Issue by Vishal-raj-1** [smaranjitghose/awesome-portfolio-websites#277]
Because of this button, research page is not responsive.
![John Doe _ Research - Google Chrome 04-12-2020 14_39_33](https://user-images.githubusercontent.com/59874304/101144833-ed2db500-363e-11eb-9e44-6493a55de9de.png)

Page looks like..
![xcv](https://user-images.githubusercontent.com/59874304/101144871-fb7bd100-363e-11eb-83d2-3405a7d6b4c5.JPG)

**Comment by Vishal-raj-1** [comment]
Sir there is no problem with button the problem is with table. can i change table with container? @smaranjitghose @anushbhatia

**Comment by smaranjitghose** [comment]
> Sir there is no problem with button. The problem is with table. can I change table with container? @smaranjitghose @anushbhatia
> 
> ![research](https://user-images.githubusercontent.com/59874304/101501318-99e89900-3995-11eb-9bb9-73a8863c4406.JPG)

Sure

**Comment by smaranjitghose** [comment]
> > Sir there is no problem with button. The problem is with table. can I change table with container? @smaranjitghose @anushbhatia
> > ![research](https://user-images.githubusercontent.com/59874304/101501318-99e89900-3995-11eb-9bb9-73a8863c4406.JPG)
> 
> Sure

Continued [here](https://github.com/smaranjitghose/awesome-portfolio-websites/issues/292) for tracking all the changes done to the page
