### ISSUE TITLE
Carousel of Certificate in Education section

### ISSUE THREAD

**Issue by Tejas1510** [smaranjitghose/awesome-portfolio-websites#278]
A carousel of the certificate to showcase all your certificates
![image](https://user-images.githubusercontent.com/64543913/101178858-7c52c100-366f-11eb-957f-8107951b1a33.png)

We can swap right or left using the two buttons provided

**Comment by Tejas1510** [comment]
@smaranjitghose, @anushbhatia can i work on this issue

**Comment by anushbhatia** [comment]
go ahead with the carousel but it should automatically move after an adequate interval.

**Comment by Tejas1510** [comment]
@anushbhatia yes it would automatically move after a interval of 3 sec
