### ISSUE TITLE
Place the Cite button on the card and add an extra abstract button

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#283]
In the Research, page add these changes accordingly

**Comment by sayna3311** [comment]
Please assign this to me. I would like to contribute.

**Comment by anushbhatia** [comment]
If you face any issues message any mentor on slack

**Comment by smaranjitghose** [comment]
> Please assign this to me. I would like to contribute.

Continued [here](https://github.com/smaranjitghose/awesome-portfolio-websites/issues/292)
