### ISSUE TITLE
Add about block on homepage.

### ISSUE THREAD

**Issue by Vishal-raj-1** [smaranjitghose/awesome-portfolio-websites#289]
Home Page is very small. There is nothing in homepage except navbar, header and one block. It would be better( from my point of view) if there is small about block in homepage. 

@anushbhatia @smaranjitghose Should I work on this idea or it is not your requirement for now?

**Comment by smaranjitghose** [comment]
> Home Page is very small. There is nothing in homepage except navbar, header and one block. It would be better( from my point of view) if there is small about block in homepage.
> 
> @anushbhatia @smaranjitghose Should I work on this idea or it is not your requirement for now?

That's a fantastic idea. I can imagine that we can remove the picture from the first section and put it in the about block with a small 100 word description. 

What do you think?

@anushbhatia can help with the UI more

**Comment by Vishal-raj-1** [comment]
> That's a fantastic idea. I can imagine that we can remove the picture from the first section and put it in the about block with a small 100 word description.

Yep Sir !! I was thinking on the same way. 🔥

**Comment by Vishal-raj-1** [comment]
@smaranjitghose sir, there is commented about section in index.html file. But I am little confuse about the layout. I have two options that are running in my mind.


**FIRST: About section of two column**

In this about section I will use one image in one column and two to three small paragraph in another column. Then doing one more thing below this two column. something like this

![idea](https://user-images.githubusercontent.com/59874304/101761816-9de5f980-3b02-11eb-9e6b-7f78af827e19.JPG)

This number will be calculated dynamically. doing some styling as well.

**SECOND: Header as About**

I will make about section in which i will write heading and then using 3-4 column acc to their roles. something like this.


![idea2](https://user-images.githubusercontent.com/59874304/101762354-590e9280-3b03-11eb-9c95-cbed1c535196.JPG)

I am doing second. Please tell me which design will be awesome!!

**Comment by Vishal-raj-1** [comment]
It is fully responsive about section.

**Desktop View:** 

![about](https://user-images.githubusercontent.com/59874304/101768835-21f0af00-3b0c-11eb-95b4-ad0d8d62dcd7.JPG)

**Mobile View:**

![about 2](https://user-images.githubusercontent.com/59874304/101769155-8f9cdb00-3b0c-11eb-8601-43f9c74975ba.JPG)

Review it @smaranjitghose @anushbhatia Sir. It is fully responsive, but I can work on styling part(give me some suggestion for that)
