### ISSUE TITLE
Make the navbar fixed to the top of the page while one scrolls down

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#291]

**Comment by m-code12** [comment]
I would like to take this up @smaranjitghose, please assign it to me.

**Comment by sammy8825** [comment]
I would like to solve this issue can u assign it to me @smaranjitghose ?

**Comment by m-code12** [comment]
@smaranjitghose I have raised a pr #313, do have a look.
