### ISSUE TITLE
Code and Design Improvements to Research page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#292]
- [ ] In the reseach.js, for each entity in the JSON  we should have:
- Name of the paper
- Conference/Journal
- Authors
- Year
- Image ( path of the image)
- Citation ( just one)
- 250 words abstract 

**add the code for cite button with the same json not defining any extra variable for it.**

- [x] We need to realign the cite button and add an abstract button to the bottom right or bottom left of the cards- **Assigned to @sayna3311 for 3 days***. Continued from [here](https://github.com/smaranjitghose/awesome-portfolio-websites/issues/283)

- [x] Fix CSS related responsivness bug - **Assigned to @Vishal-raj-1 for 3 days***. Continued from [here](https://github.com/smaranjitghose/awesome-portfolio-websites/issues/277)

**Comment by sayna3311** [comment]
![image](https://user-images.githubusercontent.com/67572440/101529813-16d83a80-39b7-11eb-9828-f5b2818e259d.png)

Placed like this?

**Comment by sayna3311** [comment]
![image](https://user-images.githubusercontent.com/67572440/101531444-4daf5000-39b9-11eb-8cdf-644adb69e867.png)

Is this okay?

**Comment by sayna3311** [comment]
@anushbhatia @smaranjitghose please check. So that I can send a PR.

**Comment by smaranjitghose** [comment]
> ![image](https://user-images.githubusercontent.com/67572440/101531444-4daf5000-39b9-11eb-8cdf-644adb69e867.png)
> 
> Is this okay?

@sayna3311 Could you please place the cite button adjacent to the abstract button

**Comment by sayna3311** [comment]
> > ![image](https://user-images.githubusercontent.com/67572440/101531444-4daf5000-39b9-11eb-8cdf-644adb69e867.png)
> > Is this okay?
> 
> @sayna3311 Could you please place the cite button adjacent to the abstract button

Oh, okay sure. I have changed it as required. I am sending a PR.

**Comment by sayna3311** [comment]
![image](https://user-images.githubusercontent.com/67572440/101725816-539b5300-3ad7-11eb-8226-fe0f78779076.png)

**Comment by Vishal-raj-1** [comment]
@smaranjitghose Sir after #361 what else is needed ? I have missed to mention this issue on my PR #361.

**Comment by Vishal-raj-1** [comment]
I am also participant of **DWOC** & **SWOC**.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Sir after #361 what else is needed ? I have missed to mention this issue on my PR #361.

As per design goes,
I would like to see a 250 word text popping up when one clicks on Abstract

As far as code goes,
we can define the cite information inside the same JSON as the name, date, authors insteading of creating separate variables

**Comment by sohitdon** [comment]
I have experience in HTML,CSS JS and Reactjs , i want to contribute on this please assign me this project

**Comment by Deep2631** [comment]
sir i want to work on this issues.

**Comment by smaranjitghose** [comment]
> I have experience in HTML,CSS JS and Reactjs , i want to contribute on this please assign me this project

Assigned for 2 days

**Comment by sohitdon** [comment]
@smaranjitghose  Thanks for assigning this project for me i will start working on it from tomorrow as SWOC contribution period will start
