### ISSUE TITLE
Issue for Design/Content Suggestions

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#293]
Please feel free to use this issue to suggest any further additions/eliminations to the project in terms of usability, UI, pages, features, code quality, and optimization

**Comment by sauravvsonu** [comment]
I founded issue in the menu button in the responsive view; it is not working (trigger) issue properly. And also a problem in interface there.

**Comment by smaranjitghose** [comment]
> I founded issue in the menu button in the responsive view; it is not working (trigger) issue properly. And also a problem in interface there.

Could you raise two separate issues for them so that I can assign you points for each

**Comment by mayankkuthar** [comment]
@smaranjitghose I founded an issue on the Landing Page when we switch to Dark mode, The icons below the "A little about me"' section got vanished and the text was written under the "A little about me"' section also remains in the black color font which is not visible in Dark Mode. 
![chrome-capture](https://user-images.githubusercontent.com/39026182/102382146-1ad80e00-3ff0-11eb-94ec-672bcb3bead7.gif)
