### ISSUE TITLE
Change the contents of the documentation with the same as that of readme

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#294]
**REMINDER**: we are using mkdocs for the documentation. The deploy is on ``gh-pages`` branch while the code is on the ``documentation branch``

**Comment by Vishal-raj-1** [comment]
I will work on this issue !! Please Assign it to me 🔥

**Comment by Vishal-raj-1** [comment]
@anushbhatia @smaranjitghose It is ready !! Please Review ☺

**Comment by Vishal-raj-1** [comment]
This issue is done. You can close this issue @smaranjitghose @anushbhatia sir !!
