### ISSUE TITLE
Making the project more appealing to both women and men

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#296]
For each of the illustrations on the pages, there should be one representing a woman and an alternative for a man in the assets so that our users can choose as per their preference

**Comment by dhruvjha11** [comment]
Do you mean on the website or the documentation??

**Comment by smaranjitghose** [comment]
> Do you mean on the website or the documentation??

The website

**Comment by sayna3311** [comment]
I would like to work on this issue. Please assign this to me @smaranjitghose .

**Comment by smaranjitghose** [comment]
> I would like to work on this issue. Please assign this to me @smaranjitghose .

For the illustrations you can make use of undraw.co
