### ISSUE TITLE
Change the favicon to a circular profile picture of a person (use any free illustration for this)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#297]

**Comment by Nishant2907** [comment]
Hey, kindly assign this to me.

**Comment by anjali1102** [comment]
I taking up this issue check my pr

**Comment by sayna3311** [comment]
Can I work on this issue? Please assign this to me @smaranjitghose .

**Comment by anjali1102** [comment]
> Can I work on this issue? Please assign this to me @smaranjitghose .

The PR has been merged.May be they forgot to close the issue
