### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#300]
An admin dashboard ( Django is preferred but NodeJS+ Express is welcome too) so that users can simply update the contents of the portfolio using  a GUI.

Continue this on a separate branch please

**Comment by tirlochanarora16** [comment]
Hey, @smaranjitghose the idea sounds great, and using NodeJS + Express JS is a great way of achieving the goal. But can you tell me that alongside HTML5 and CSS3 are you using any kind of front-end frameworks like React, Angular, or Vue JS?

**Comment by smaranjitghose** [comment]
> Hey, @smaranjitghose the idea sounds great, and using NodeJS + Express JS is a great way of achieving the goal. But can you tell me that alongside HTML5 and CSS3 are you using any kind of front-end frameworks like React, Angular, or Vue JS?

Yes. Once the frontend is finalized we will shift to React

**Comment by tirlochanarora16** [comment]
@smaranjitghose, you'll also require a database to store the users, and then some kind of authentication will be necessary so one user cannot change the contents of the other user's portfolio.

**Comment by tirlochanarora16** [comment]
@shreyakapoor08

**Comment by smaranjitghose** [comment]
> @smaranjitghose, you'll also require a database to store the users, and then some kind of authentication will be necessary so one user cannot change the contents of the other user's portfolio.

Since this is portfolio website so only the user for whom the website is made will be handling the dashboard, unless specifically required, we do not give access to our personal websites to someone else

**Comment by tirlochanarora16** [comment]
@smaranjitghose, what contents of the portfolio will be managed by the dashboard?

**Comment by smaranjitghose** [comment]
> @smaranjitghose, what contents of the portfolio will be managed by the dashboard?

Basically, most of the data we are entering as a JSON in our JS files

**Comment by shambashib20** [comment]
Can I work on this issue? @smaranjitghose sir? Making this admin panel?
