### ISSUE TITLE
Live demo and GitHub icons are not fully visible

### ISSUE THREAD

**Issue by m-code12** [smaranjitghose/awesome-portfolio-websites#301]
In the projects.html page,the live demo and github icons are not fully visible for music recommendation engine and movie recommendation system in both light and dark theme.

![Screenshot (236)](https://user-images.githubusercontent.com/53649201/101514029-da024880-39a2-11eb-985f-697276c28330.png)
![Screenshot (237)](https://user-images.githubusercontent.com/53649201/101514096-e9819180-39a2-11eb-8f95-a7535af626bd.png)

**Comment by smaranjitghose** [comment]
> In the projects.html page,the live demo and github icons are not fully visible for music recommendation engine and movie recommendation system in both light and dark theme.
> 
> ![Screenshot (236)](https://user-images.githubusercontent.com/53649201/101514029-da024880-39a2-11eb-985f-697276c28330.png)
> ![Screenshot (237)](https://user-images.githubusercontent.com/53649201/101514096-e9819180-39a2-11eb-8f95-a7535af626bd.png)

Would you like to fix the bug?

**Comment by m-code12** [comment]
> > In the projects.html page,the live demo and github icons are not fully visible for music recommendation engine and movie recommendation system in both light and dark theme.
> > ![Screenshot (236)](https://user-images.githubusercontent.com/53649201/101514029-da024880-39a2-11eb-985f-697276c28330.png)
> > ![Screenshot (237)](https://user-images.githubusercontent.com/53649201/101514096-e9819180-39a2-11eb-8f95-a7535af626bd.png)
> 
> Would you like to fix the bug?

Yes,sure.
Also please could you assign for opening this issue?

**Comment by smaranjitghose** [comment]
> > > In the projects.html page,the live demo and github icons are not fully visible for music recommendation engine and movie recommendation system in both light and dark theme.
> > > ![Screenshot (236)](https://user-images.githubusercontent.com/53649201/101514029-da024880-39a2-11eb-985f-697276c28330.png)
> > > ![Screenshot (237)](https://user-images.githubusercontent.com/53649201/101514096-e9819180-39a2-11eb-8f95-a7535af626bd.png)
> > 
> > 
> > Would you like to fix the bug?
> 
> Yes,sure.
> Also please could you assign me points for opening this issue?

Sure

**Comment by ankurg132** [comment]
I would like to work on the issue.

**Comment by ankurg132** [comment]
Also, on reducing the device width, this problem occurs in other cards too. Sharing the screenshot below-

![Screenshot (522)](https://user-images.githubusercontent.com/31045221/103086144-d78e2880-4609-11eb-8529-bc47564de36d.png)

**Comment by smaranjitghose** [comment]
> Also, on reducing the device width, this problem occurs in other cards too. Sharing the screenshot below-
> 
> ![Screenshot (522)](https://user-images.githubusercontent.com/31045221/103086144-d78e2880-4609-11eb-8529-bc47564de36d.png)

Raise a separate issue for this. Make the grid size to 2. You can make the size of the card similar to [this](https://www.ishandeveloper.com/work.html)

Also, we can get rid of the project description, have related technology tags and the top of the page a search bar to sort them according to it

**Comment by smaranjitghose** [comment]
> I would like to work on the issue.

BTW you are in NWOC or DWOC or SWOC?

**Comment by ankurg132** [comment]
> > I would like to work on the issue.
> 
> BTW you are in NWOC or DWOC or SWOC?

I'm in NWOC, though I'm still waiting for my initial PR to be merged.

**Comment by ankurg132** [comment]
> > Also, on reducing the device width, this problem occurs in other cards too. Sharing the screenshot below-
> > ![Screenshot (522)](https://user-images.githubusercontent.com/31045221/103086144-d78e2880-4609-11eb-8529-bc47564de36d.png)
> 
> Raise a separate issue for this. Make the grid size to 2. You can make the size of the card similar to [this](https://www.ishandeveloper.com/work.html)
> 
> Also, we can get rid of the project description, have related technology tags and the top of the page a search bar to sort them according to it

Okay, will work on it!
