### ISSUE TITLE
Set Up discussion feature for great conversion.

### ISSUE THREAD

**Issue by Vishal-raj-1** [smaranjitghose/awesome-portfolio-websites#303]
@smaranjitghose @anushbhatia Sir, Did you see new feature on github ? We can set discussion on this repo. So what you have to do is just click this block in setting section of your repo. It's Amazing I guess. Have a try.

![discussion](https://user-images.githubusercontent.com/59874304/101589985-8c6ff500-3a0f-11eb-8756-48b53dfe1adf.JPG)

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia Sir, Did you see new feature on github ? We can set discussion on this repo. So what you have to do is just click this block in setting section of your repo. It's Amazing I guess. Have a try.
> 
> ![discussion](https://user-images.githubusercontent.com/59874304/101589985-8c6ff500-3a0f-11eb-8756-48b53dfe1adf.JPG)

Nice Suggestion @Vishal-raj-1
