### ISSUE TITLE
Modifications to social media icons

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#316]
- [ ] Add a Social Media icon (with relevant transition) for Google Scholar, Instagram, Codeforces and Leetcode
- [ ] Modify the code so that the user can display any combination of social media as per their needs.
- [ ] Input the links of the same using a JSON in main.js or home.js
- [ ] Replace the email id in the footer with a corresponding ✉ icon
- [ ] Footer Bug:
![footer_bug](https://user-images.githubusercontent.com/46641503/102020588-17e6de80-3da0-11eb-9e03-ed0f5be241f1.jpg)

**Comment by snehaM2210** [comment]
Please assign me this issue..I would like to work on this @smaranjitghose

**Comment by sauravvsonu** [comment]
@smaranjitghose  I would like to work  on this issue (1st, 2nd, and 4th point)

**Comment by Vishal-raj-1** [comment]
> @smaranjitghose, I would like to work on this issue (1st, 2nd, 4th, 5th point). And would you explain a little about 3rd point?

have a look at main.js footer section !! You will understand easily

**Comment by smaranjitghose** [comment]
@sauravvsonu I would urge you to take one task at a time so that we can give all of the participants a chance.

Would you like to go ahead with 1 and 2?

**Comment by smaranjitghose** [comment]
> Please assign me this issue..I would like to work on this @smaranjitghose

Would like to go ahead with 3 and 4?

**Comment by snehaM2210** [comment]
> > Please assign me this issue..I would like to work on this @smaranjitghose
> 
> Would like to go ahead with 3 and 4?

Yeah sure😊, but if I've got any doubts, where can I contact you?

**Comment by sauravvsonu** [comment]
> @sauravvsonu I would urge you to take one task at a time so that we can give all of the participants a chance.
> 
> Would you like to go ahead with 1 and 2?

okay I will start with it

**Comment by Vishal-raj-1** [comment]
> Yeah sure😊, but if I've got any doubts, where can I contact you?

Join slack channel (link in README)

**Comment by tejaswini22199** [comment]
can I work on the 3 and 4 issues

**Comment by snehaM2210** [comment]
> > Yeah sure😊, but if I've got any doubts, where can I contact you?
> 
> Join slack channel (link in README)

Yeah, I've joined and working on the no. 3 and 4 issues😊

**Comment by sauravvsonu** [comment]
> @sauravvsonu I would urge you to take one task at a time so that we can give all of the participants a chance.
> 
> Would you like to go ahead with 1 and 2?

hey, I had completed with adding, some required icon look at it onces.

![image](https://user-images.githubusercontent.com/54908611/102239531-f65f3180-3f1c-11eb-86ae-c524ddc34476.png)
![image](https://user-images.githubusercontent.com/54908611/102239615-0ecf4c00-3f1d-11eb-8996-41aaeb979b91.png)

**Comment by mayankkuthar** [comment]
@smaranjitghose Hi, As the issue is still open I would like to work on the 1st, 2nd, 4th, and 5th points. Please assign me this issue and will fix this ASAP. I am really curious to work on this issue. :)

**Comment by dollyjain51099** [comment]
I would like to work on 1st, 4th and 5th issue, please assign it to me!

**Comment by tirlochanarora16** [comment]
Can I cover some of the parts of the footer for fixes?

**Comment by smaranjitghose** [comment]
> Can I cover some of the parts of the footer for fixes?

Please collaborate with @dollyjain51099 for this issue

**Comment by tirlochanarora16** [comment]
@dollyjain51099, how are you planning on designing the icons?

**Comment by dollyjain51099** [comment]
> @dollyjain51099, how are you planning on designing the icons?

I'll be creating floating social media icons with some hover effects.

**Comment by tirlochanarora16** [comment]
> > @dollyjain51099, how are you planning on designing the icons?
> 
> I'll be creating floating social media icons with some hover effects.

Sounds nice. Have you started to work on it?

**Comment by dollyjain51099** [comment]
> > > @dollyjain51099, how are you planning on designing the icons?
> > 
> > 
> > I'll be creating floating social media icons with some hover effects.
> 
> Sounds nice. Have you started to work on it?

Yes!

**Comment by tirlochanarora16** [comment]
@smaranjitghose  can I redo the footer using custom CSS rather than using materialize.css?

**Comment by tirlochanarora16** [comment]
Modified footer #375

**Comment by smaranjitghose** [comment]
> @smaranjitghose can I redo the footer using custom CSS rather than using materialize.css?

That would be fantastic!

**Comment by tirlochanarora16** [comment]
> > @smaranjitghose can I redo the footer using custom CSS rather than using materialize.css?
> 
> That would be fantastic!

@smaranjitghose, can I start working on it then?

**Comment by smaranjitghose** [comment]
> > > @smaranjitghose can I redo the footer using custom CSS rather than using materialize.css?
> > 
> > 
> > That would be fantastic!
> 
> @smaranjitghose, can I start working on it then?

yes

**Comment by moritz-gerster** [comment]
> * [ ]  Add a Social Media icon (with relevant transition) for Google Scholar, Instagram, Codeforces and Leetcode

I understand this issue was closed with #388 but I still don't understand how to add the Google Scholar icon?

I also would like an icon for [Orcid ID](https://orcid.org/), [Researchgate](https://www.researchgate.net/), and YouTube!
