### ISSUE TITLE
Different color to icon in About section of Home page

### ISSUE THREAD

**Issue by Vishal-raj-1** [smaranjitghose/awesome-portfolio-websites#321]
# Description

Currently we have same color to icons in about section of home page. We can give different color to icons in both theme.

# Screenshots

## Currently in light theme 

![light](https://user-images.githubusercontent.com/59874304/102100304-4a9be000-3e4f-11eb-9a11-d89c64809c64.JPG)

## Currently in Dark theme 

![dark](https://user-images.githubusercontent.com/59874304/102100330-538cb180-3e4f-11eb-8ce7-9c7d4ba6b422.JPG)

Can use this as [Reference](https://codepen.io/jorgesanes10/pen/QdMEXr) anything else @anushbhatia you can suggest.

P.S : Currently I have issues to work with. So Its open for all.

**Comment by sayna3311** [comment]
I would like to work on it. Can you please assign this to me? @Vishal-raj-1 @smaranjitghose @anushbhatia

**Comment by Vishal-raj-1** [comment]
You can work on !!

**Comment by Ayushgup85** [comment]
is this issue still open?

**Comment by smaranjitghose** [comment]
> is this issue still open?

Yes

**Comment by aum-singhal** [comment]
Can I also work on this?? I will be happy to contribute.

**Comment by Vishal-raj-1** [comment]
Hey @sayna3311 !! are you working on this issue or not ? I am giving some microanimation to this block which handle this issue as well . Please reply as soon as possible !!

**Comment by smaranjitghose** [comment]
> Can I also work on this?? I will be happy to contribute.

Collaborate with @Vishal-raj-1 on this please

**Comment by Vishal-raj-1** [comment]
@aum-singhal you can collaborated with me on stack channel

**Comment by aum-singhal** [comment]
ohk for sure

**Comment by smaranjitghose** [comment]
If anyone of you is working on this, please do raise a new issue
