### ISSUE TITLE
Direct change in style.css affect About section of Homepage.

### ISSUE THREAD

**Issue by Vishal-raj-1** [smaranjitghose/awesome-portfolio-websites#324]
# Describe the bug

Now because of last [commit](https://github.com/smaranjitghose/awesome-portfolio-websites/commit/4d0095b62bd2dfdceb4eeddc6f0316122796276d)  by @Pranav016 home page is look like

## Home 

![home bug](https://user-images.githubusercontent.com/59874304/102330673-db89cd00-3faf-11eb-9538-6e0ad30e0f58.JPG)

## About 

![about bug](https://user-images.githubusercontent.com/59874304/102330750-f2302400-3faf-11eb-823b-3c100d39370f.JPG)

# To Reproduce 
1. Since I have given style to .card directly. I will use some class for that cards
2. @Pranav016 collaborate with me (we can talk, will use stack for that purpose) 

# Expected behavior

## Home
![home](https://user-images.githubusercontent.com/59874304/102332646-5e138c00-3fb2-11eb-9138-faf7773567e1.JPG)

## About
![about sghj](https://user-images.githubusercontent.com/59874304/102332760-89967680-3fb2-11eb-8918-aae706cb5820.JPG)

**Comment by Pranav016** [comment]
@Vishal-raj-1 it's working completely fine on my system! I'll send a video after my class gets over.

**Comment by Pranav016** [comment]
Oh I figured it out, we can work on it! Small issue, for dark mode, text is black.

**Comment by Vishal-raj-1** [comment]
> Oh I figured it out, we can work on it! Small issue, for dark mode, text is black.

Yep, I have solved it by adding a id to about section. It's my bad I shouldn't directly style the .card class.

**Comment by Pranav016** [comment]
@Vishal-raj-1 I just noticed that after your PR, the color of rthe mooc cards got affected!

Before- 
![image](https://user-images.githubusercontent.com/54665036/102717046-c42b4680-4305-11eb-87d2-003d29fc5db3.png)

After your PR-
![image](https://user-images.githubusercontent.com/54665036/102717062-e2914200-4305-11eb-8b16-bbd768aa04fc.png)

I think coz you clubbed these in css- `#about .card, #mooc .card{}`
That is why it is causing this issue. Dont't worry, We can work on this. 😄 
I'll make a PR to solve this!

**Comment by Vishal-raj-1** [comment]
> I think coz you clubbed these in css- `#about .card, #mooc .card{}`
> That is why it is causing this issue. Don't worry, We can work on this. 😄

Yep I was thinking about that But I don't want to overwrite your change. No problem go ahead !!
