### ISSUE TITLE
Fixed Navbar Problem

### ISSUE THREAD

**Issue by Vishal-raj-1** [smaranjitghose/awesome-portfolio-websites#325]
# Describe the bug

When Fixed the navbar at top. We Have to give padding to the first container. 

**To Reproduce**

1. Give padding to the containers

**Actual behavior**

![project](https://user-images.githubusercontent.com/59874304/102341655-27dc0980-3fbe-11eb-9116-1cc54ac1f335.JPG)

![resaerch](https://user-images.githubusercontent.com/59874304/102341665-2ad6fa00-3fbe-11eb-94dd-8d2195c05665.JPG)

**Comment by m-code12** [comment]
I would like to take this up @Vishal-raj-1

**Comment by Vishal-raj-1** [comment]
> I would like to take this up @Vishal-raj-1

Sure !!

**Comment by smaranjitghose** [comment]
> > I would like to take this up @Vishal-raj-1
> 
> Sure !!

Are you cool with @m-code12 taking it?

**Comment by Vishal-raj-1** [comment]
Yes
