### ISSUE TITLE
Bug report: On Landing Page, Text and Icon are not visible in Dark Mode

### ISSUE THREAD

**Issue by mayankkuthar** [smaranjitghose/awesome-portfolio-websites#327]
I founded an issue on the Landing Page when we switch to Dark mode, The icons below the "A little about me"' section got vanished and the text was written under the "A little about me"' section also remains in the black color font which is not visible in Dark Mode.

![chrome-capture](https://user-images.githubusercontent.com/39026182/102383445-8e2e4f80-3ff1-11eb-810e-ff9322d84be3.gif)

**Comment by Vishal-raj-1** [comment]
It's already #324 here.

**Comment by Swastik1710** [comment]
Hey @Vishal-raj-1 , can you please assign me this issue.

**Comment by Vishal-raj-1** [comment]
It is already solved.( Ready for merge)

**Comment by Swastik1710** [comment]
Oh okay @Vishal-raj-1 , no problem ! BTW I have done it too, so can you please review it and give some feedback . Would be quite helpful.
![1](https://user-images.githubusercontent.com/71871571/102587065-3e56a200-4131-11eb-99d6-0dce3e4710a3.png)
![2](https://user-images.githubusercontent.com/71871571/102587071-41519280-4131-11eb-86de-66a0841fd307.png)
![3](https://user-images.githubusercontent.com/71871571/102587075-4282bf80-4131-11eb-8ac7-9f3f1d8cf0d4.png)
![4](https://user-images.githubusercontent.com/71871571/102587079-444c8300-4131-11eb-867a-f4d3bd6d6231.png)
