### ISSUE TITLE
Bug report: The problem in the dark mode Mentorship cards

### ISSUE THREAD

**Issue by rajarshi-hub** [smaranjitghose/awesome-portfolio-websites#332]
**Describe the bug**
In the dark mode the dates just below the heading are not properly visible needs to b change its color to white when the dark mode is on.
![Screenshot (351)](https://user-images.githubusercontent.com/62015785/102641106-869db080-4181-11eb-95b7-3849ccad988a.png)

**To Reproduce**
1. just changing the color for the text in the date as the other text in the card.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Comment by rajarshi-hub** [comment]
Will my score be added for raising this issue @anushbhatia

**Comment by smaranjitghose** [comment]
> Will my score be added for raising this issue @anushbhatia

Yes. We update the scores every 5 days

**Comment by chinmaym07** [comment]
Hey @smaranjitghose  Can I try this issue?
