### ISSUE TITLE
Experience page not responsive for large mobile and small tablets screens.

### ISSUE THREAD

**Issue by Chaitanya31612** [smaranjitghose/awesome-portfolio-websites#337]
**Describe the bug**
Experience page header text is not responsive for large mobile screens(407px to ).
**To Reproduce**
1. Reduce the font size of the text.

**Expected behavior**
It should not break for large mobile screens and small tablet screens.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
It is not responsive for large mobile screens and small tablet screens.

**Screenshots**

![image](https://user-images.githubusercontent.com/54992097/102714376-1b282000-42f4-11eb-9ca3-b2d8ebd4f862.png)
![image](https://user-images.githubusercontent.com/54992097/102714565-60991d00-42f5-11eb-9dd3-8e7b1a0aecfc.png)

![image](https://user-images.githubusercontent.com/54992097/102714560-52e39780-42f5-11eb-9945-b7382b045b20.png)

![image](https://user-images.githubusercontent.com/54992097/102714550-46f7d580-42f5-11eb-85fc-c8f809bc4769.png)

**Comment by AdityaTeltia** [comment]
Can i work on this issue ?

**Comment by smaranjitghose** [comment]
> Can i work on this issue ?

You can take over from 26th
