### ISSUE TITLE
The project page screenshot in readme is not updated.

### ISSUE THREAD

**Issue by ankurg132** [smaranjitghose/awesome-portfolio-websites#358]
**Describe the bug**
The project page readme currently shows a grid with 2 columns while in the actual page the grid is of 4 columns.

**Comment by smaranjitghose** [comment]
> **Describe the bug**
> The project page readme currently shows a grid with 2 columns while in the actual page the grid is of 4 columns.

We plan to update the readme and the documentation in the last weel

**Comment by ankurg132** [comment]
So shall I close this issue?

**Comment by smaranjitghose** [comment]
> So shall I close this issue?

Yes
