### ISSUE TITLE
Feature request: Cursor should be pointer when hovering over the dark mode toggler

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#360]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/49204837/103148545-d5050d80-4786-11eb-800f-b512aea2b865.png)
When we hover over the dark mode toggler then the cursor remains the default one but the cursor should be a pointer as it performs some functionality.

**Describe the solution you'd like**
I would like to make the cursor pointer.

**Comment by Jatin-MaTTriX** [comment]
I want to work on this issue

**Comment by dipanshparmar** [comment]
@smaranjitghose we have a problem here, I cannot add cursor: pointer to the toggler because the sun icon wrapper is messing it up. It feels like that the cursor: pointer is overflowed but it is because of the icon wrapper and it looks bad.

https://user-images.githubusercontent.com/49204837/103155535-dce4a200-47c6-11eb-81d6-8f83995b70e1.mp4

 I tried tweaking it with javascript but couldn't achieve the desired results. Now we have two options, 1. either we can let it be like it is, or 2. we have to tweak the toggler design. Please let me know which one do you prefer.

**Comment by smaranjitghose** [comment]
> @smaranjitghose we have a problem here, I cannot add cursor: pointer to the toggler because the sun icon wrapper is messing it up. It feels like that the cursor: pointer is overflowed but it is because of the icon wrapper and it looks bad.
> 
>  compressed.mp4 
> I tried tweaking it with javascript but couldn't achieve the desired results. Now we have two options, 1. either we can let it be like it is, or 2. we have to tweak the toggler design. Please let me know which one do you prefer.

I think need to tweak the toggle design. @anushbhatia Your opinions?

Have a look at [this PR](https://github.com/smaranjitghose/awesome-portfolio-websites/pull/362)

**Comment by dipanshparmar** [comment]
> I think need to tweak the toggle design. @anushbhatia Your opinions?
> 
Looking forward to hearing from @anushbhatia

**Comment by dipanshparmar** [comment]
> Have a look at [this PR](https://github.com/smaranjitghose/awesome-portfolio-websites/pull/362)

Me?

**Comment by smaranjitghose** [comment]
> > Have a look at [this PR](https://github.com/smaranjitghose/awesome-portfolio-websites/pull/362)
> 
> Me?

Ya
