### ISSUE TITLE
Bug report: Dark mode toggler is not working on small screen sizes

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#364]
**Describe the bug**
Dark mode toggler is not working on small screen sizes.

**To Reproduce**
1. Click on Inspector
2. Choose a small screen size
3. Click on dark mode toggler
4. See, nothing changes

**Expected behavior**
Toggler should toggle between the themes

**Actual behavior**
Toggler is not toggling the themes

**Screenshots**
https://user-images.githubusercontent.com/49204837/103163780-9fb0fc00-4828-11eb-9ac9-20478f476c3b.mp4

**Comment by Utkarshn10** [comment]
This issue is only occurring in the sidebar menu and not in the navbar. I can try to fix it .  I am a Swoc participant.
