### ISSUE TITLE
Feature request: Add the color and size change in options in navbar and option on hovering and showing the current tab differently

### ISSUE THREAD

**Issue by abhijeet007rocks8** [smaranjitghose/awesome-portfolio-websites#369]
Current Issue -:
In Light mode, the navbar is elements on hovering is not visible.

Solution-:
We can add a text color change on hovering the elements and highlight the current tab as per page 
eg. when on education page the education tab should be in different color from the other tabs.

**Comment by abhijeet007rocks8** [comment]
I would like to work on it.

**Comment by rakshitnayak** [comment]
Even i would like to contribute on this issue! SWOC21 participant.!

**Comment by smaranjitghose** [comment]
We are moving to Neumorphic UI.
So this won't be necessary.
Have a look at #405

**Comment by abhijeet007rocks8** [comment]
Sir I have made the changes already and can modify it as per neuromorphic ui can you please 
assign issue #405 to me then??
