### ISSUE TITLE
Feature request : Add animation in waving hand

### ISSUE THREAD

**Issue by Surajbokde** [smaranjitghose/awesome-portfolio-websites#377]
![image](https://user-images.githubusercontent.com/66197682/103192824-1b31ac80-4900-11eb-9d7c-1d83804219f9.png)

Add animation in the above waving hand.

**Comment by Aarushi02-ab** [comment]
I want to work on this issue. Please assign me this task @Surajbokde sir.

**Comment by smaranjitghose** [comment]
> ![image](https://user-images.githubusercontent.com/66197682/103192824-1b31ac80-4900-11eb-9d7c-1d83804219f9.png)
> 
> Add animation in the above waving hand.

You are a part of DWOC right?

**Comment by Surajbokde** [comment]
@smaranjitghose change label from dwoc to swoc . I am mentor at swoc so assign this issue to any contributor .

**Comment by Aarushi02-ab** [comment]
> > ![image](https://user-images.githubusercontent.com/66197682/103192824-1b31ac80-4900-11eb-9d7c-1d83804219f9.png)
> > Add animation in the above waving hand.
> 
> You are a part of DWOC right?

Yes, I am a part of DWOC

**Comment by smaranjitghose** [comment]
> @smaranjitghose change label from dwoc to swoc . I am mentor at swoc so assign this issue to any contributor .

Sure

**Comment by smaranjitghose** [comment]
> @smaranjitghose change label from dwoc to swoc . I am mentor at swoc so assign this issue to any contributor .

SWOC and DWOC are running parallelly and we have many common participants. So as per the participants choice we can assign the label to the PRs. The issues are open to everyone

**Comment by AdityaTeltia** [comment]
Can I Work on this ?

**Comment by SwatiBhatia18** [comment]
I want to work on this issue . Please assign me this task @anushbhatia

**Comment by AdityaTeltia** [comment]
Isn't this wrong u r assigning task to someone and taking pr of other ?

**Comment by smaranjitghose** [comment]
> Isn't this wrong u r assigning task to someone and taking pr of other ?

Ya, I agree it should not be done.
Since DWOC is already going on and SWoC contributions are counted from Jan 5, so I made an exception and have informed the person in their PR as well that this would not be entertained from next time.
