### ISSUE TITLE
Skill Page Enhancement

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#380]
Improve the mobile view for site showing two illustrations together 
Skills images are not properly added they get stretched.

**Comment by tirlochanarora16** [comment]
@anushbhatia, illustrations that are on the home page right?

**Comment by smaranjitghose** [comment]
> @anushbhatia, illustrations that are on the home page right?

[Skills Page](https://portfolio.smaranjitghose.codes/skill.html)

**Comment by Harshita-Kanal** [comment]
Can I work on this? I am from SWOC

**Comment by ayushrastogi689** [comment]
I would like to work on this issue.
I am a participant of SWoC 2021.

**Comment by anushbhatia** [comment]
Sure guys work on it the PR which is best will be merged.

**Comment by sohitdon** [comment]
I have experience in HTML,CSS JS and Reactjs , i want to contribute on this please assign me this project
