### ISSUE TITLE
Feature request: instead of directly redirecting the viewer to the drive link , give  the option to download and view the resume

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/awesome-portfolio-websites#387]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

instead of directly redirecting the viewer/user to the drive link we can add the option to download and view the resume

**Describe the solution you'd like**

***demo of the implemented feature ***
![demo port](https://user-images.githubusercontent.com/64387054/103247578-58904b80-498d-11eb-971c-fae7a2db8083.gif)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

I Make a landing page for the resume and add a card that features the resume image the card also contains to buttons, one for download and the other for view

**Additional context**

**Comment by Abhijay007** [comment]
@smaranjitghose sir, can I work on this issue?

**Comment by Vishal-raj-1** [comment]
@Abhijay007 looks awesome to me !!

**Comment by smaranjitghose** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is.
> 
> instead of directly redirecting the viewer/user to the drive link we can add the option to download and view the resume
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> ***demo of the implemented feature ***
> ![demo port](https://user-images.githubusercontent.com/64387054/103247578-58904b80-498d-11eb-971c-fae7a2db8083.gif)
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Approach to be followed (optional)**
> A clear and concise description of the approach to be followed.
> 
> I Make a landing page for the resume and add a card that features the resume image the card also contains to buttons, one for download and the other for view
> 
> **Additional context**
> 
> Add any other context or screenshots about the feature request here.

w.r.t to hiring manages, no one would like to see your resume page separately once they are on your portfolio website. What you can do is put this as a subsection on one of the pages like home page

**Comment by Abhijay007** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > A clear and concise description of what the problem is.
> > instead of directly redirecting the viewer/user to the drive link we can add the option to download and view the resume
> > **Describe the solution you'd like**
> > A clear and concise description of what you want to happen.
> > ***demo of the implemented feature ***
> > ![demo port](https://user-images.githubusercontent.com/64387054/103247578-58904b80-498d-11eb-971c-fae7a2db8083.gif)
> > **Describe alternatives you've considered**
> > A clear and concise description of any alternative solutions or features you've considered.
> > **Approach to be followed (optional)**
> > A clear and concise description of the approach to be followed.
> > I Make a landing page for the resume and add a card that features the resume image the card also contains to buttons, one for download and the other for view
> > **Additional context**
> > Add any other context or screenshots about the feature request here.
> 
> w.r.t to hiring manages, no one would like to see your resume page separately once they are on your portfolio website. What you can do is put this as a subsection on one of the pages like home page

@smaranjitghose ok sir, I can make it as a  subsection on the home page.
so can i work on this?

**Comment by Abhijay007** [comment]
@smaranjitghose sir,  I am done with this sub-section part here is the demo of the implemented card

***demo***

![demo-awesome](https://user-images.githubusercontent.com/64387054/103396458-672b5e00-4b59-11eb-957e-d90c8e997b79.gif)

@smaranjitghose sir, now I have one question that can I remove this ` my resume`  section from the header or left it as it is. 

![remove](https://user-images.githubusercontent.com/64387054/103396590-22ec8d80-4b5a-11eb-9667-881030dd11f2.PNG)

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir, I am done with this sub-section part here is the demo of the implemented card
> 
> _**demo**_
> 
> ![demo-awesome](https://user-images.githubusercontent.com/64387054/103396458-672b5e00-4b59-11eb-957e-d90c8e997b79.gif)
> 
> @smaranjitghose sir, now I have one question that can I remove this ` my resume` section from the header or left it as it is.
> 
> ![remove](https://user-images.githubusercontent.com/64387054/103396590-22ec8d80-4b5a-11eb-9667-881030dd11f2.PNG)

# Feedback:
 Instead of having a section with a heading. I would suggest having a center aligned button saying "Grab my Resume" just below the about section.
 
 Don't forget to remove the "My Resume" tab from the navbar (main.js)

**Comment by Abhijay007** [comment]
> > @smaranjitghose sir, I am done with this sub-section part here is the demo of the implemented card
> > _**demo**_
> > ![demo-awesome](https://user-images.githubusercontent.com/64387054/103396458-672b5e00-4b59-11eb-957e-d90c8e997b79.gif)
> > @smaranjitghose sir, now I have one question that can I remove this ` my resume` section from the header or left it as it is.
> > ![remove](https://user-images.githubusercontent.com/64387054/103396590-22ec8d80-4b5a-11eb-9667-881030dd11f2.PNG)
> 
> # Feedback:
> Instead of having a section with a heading. I would suggest having a center aligned button saying "Grab my Resume" just below the about section.
> 
> Don't forget to remove the "My Resume" tab from the navbar (main.js)

@smaranjitghose sir , by the above feedback, did you mean something like this:

![demo-final](https://user-images.githubusercontent.com/64387054/103432488-97c8d180-4c05-11eb-9875-81d967aa47d6.gif)

**Comment by smaranjitghose** [comment]
> > > @smaranjitghose sir, I am done with this sub-section part here is the demo of the implemented card
> > > _**demo**_
> > > ![demo-awesome](https://user-images.githubusercontent.com/64387054/103396458-672b5e00-4b59-11eb-957e-d90c8e997b79.gif)
> > > @smaranjitghose sir, now I have one question that can I remove this ` my resume` section from the header or left it as it is.
> > > ![remove](https://user-images.githubusercontent.com/64387054/103396590-22ec8d80-4b5a-11eb-9667-881030dd11f2.PNG)
> > 
> > 
> > # Feedback:
> > Instead of having a section with a heading. I would suggest having a center aligned button saying "Grab my Resume" just below the about section.
> > Don't forget to remove the "My Resume" tab from the navbar (main.js)
> 
> @smaranjitghose sir , by the above feedback, did you mean something like this:
> 
> ![demo-final](https://user-images.githubusercontent.com/64387054/103432488-97c8d180-4c05-11eb-9875-81d967aa47d6.gif)

A description of "how to download the resume" is not required. Rest is fine

**Comment by Abhijay007** [comment]
Ok, @smaranjitghose sir got it 👍
