### ISSUE TITLE
Research Page UI update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#392]
# Aim:

Change the current research page into neuromorphic form

# References:

- [What is neuromorphic UI? ](https://css-tricks.com/neumorphism-and-css/)
- [ Tool for Generating CSS code for Neumorhpic UI](https://neumorphism.io/#e0e0e0)
- [Sample Cards](https://dribbble.com/shots/14376942-Neumorphism-UI-Trend-App-Screen?utm_source=Clipboard_Shot&utm_campaign=sahilbajaj&utm_content=Neumorphism%20UI%20Trend%20App%20Screen&utm_medium=Social_Share)

Please consult with @anushbhatia over this. He has a lot of experience to help out in a better way than I can in this regard

**Comment by dipanshparmar** [comment]
I would like to work on this.
