### ISSUE TITLE
Footer Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#393]
The footers is different for the home page and the other pages.

# Aim:

Rewrite the footer code in the main.js, such that it has:

- Contact Form on the right
- Social Media Icons on the left: 
        1. LinkedIn
        2. GitHub
        3. Twitter
        4. Email
        5. Kaggle
        6. Google Scholar
        7. Leetcode
        8. Codeforces
        9. Dribble
        10. Instagram
        
  [ Note at a time only 5 social media icons are to be displayed and the code for the remaining should be commented out for future use. However, you are expected to produce two screenshots/gifs with for each set of social media icons both for dark mode and light mode]
 
 Reference for footer social media icons: https://girlscriptboilerplate.netlify.app/

**Comment by Deep2631** [comment]
sir i want to work on this

**Comment by Utkarsh-Agarwal-585** [comment]
Sir I want to contribute on this.

**Comment by smaranjitghose** [comment]
> sir i want to work on this

Any updates?

**Comment by Utkarsh-Agarwal-585** [comment]
Hello Sir,
I'll update you within 2 days... I started it today itself...

**Comment by Vishal-raj-1** [comment]
@smaranjitghose Sir currently footer is seems like this 

## On Home Page  

![home](https://user-images.githubusercontent.com/59874304/103460667-2f314000-4d3e-11eb-8594-b33d4d67896c.JPG)

## On Project Page
![project](https://user-images.githubusercontent.com/59874304/103460668-30fb0380-4d3e-11eb-8863-3c8135adf8f9.JPG)


and that two type of footer bugs are available. I can make responsive footer which contain 5 social media icons on left side and form on right side.

**Comment by sj056** [comment]
Hey! Can want to work on it? (I'm a participant of SWOC'21)

**Comment by smaranjitghose** [comment]
> Hey! Can want to work on it? (I'm a participant of SWOC'21)

Sure. Go ahead

**Comment by pratiksha-pandey** [comment]
@smaranjitghose May I work on this issue?

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia May I work on this issue? I am a participant of SWoC'21.

@sj056 @pratiksha-pandey Both of you give your own designs. We'll merge the best one.

Remove the "John Doe" image from the footer, it's unnecessary as it repeats the one in the navbar for the mobile view

I am giving both of you 2 days for this. Do discuss in the channel with the mentors if you face any roadblocks.

Remember that the social media icons should be similar to that in the home page above.

**Comment by dollyjain51099** [comment]
I would like to work on this issue, please assign it to me!

**Comment by smaranjitghose** [comment]
> I would like to work on this issue, please assign it to me!

Please wait at least 2 days after the other mentees are assigned

**Comment by sj056** [comment]
@smaranjitghose  Sir I have modified the footer. I have added all 10 icons in main.js . Suggest if any modification is required.

![John Doe _ Projects - Google Chrome 2021-01-07 12-50-39 (1)](https://user-images.githubusercontent.com/56972234/103866941-94918200-50ec-11eb-8adf-79117e4d183b.gif)

![John Doe _ Projects - Google Chrome 2021-01-07 13-35-28](https://user-images.githubusercontent.com/56972234/103867897-1afa9380-50ee-11eb-8c5b-0e4475de327c.gif)

**Comment by ridsuteri** [comment]
hey @smaranjitghose can i work on this issue ..?

**Comment by smaranjitghose** [comment]
> > I would like to work on this issue, please assign it to me!
> 
> Please wait at least 2 days after the other mentees are assigned

@ridsuteri Please read this

**Comment by ridsuteri** [comment]
> > > I would like to work on this issue, please assign it to me!
> > 
> > 
> > Please wait at least 2 days after the other mentees are assigned
> 
> @ridsuteri Please read this

ok

**Comment by dollyjain51099** [comment]
can you please add the label for swoc!

**Comment by jatinjain001** [comment]
I would like to work on this , as I am participant of SWOC2021
