### ISSUE TITLE
Remove "toTop" button from all pages

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#394]

**Comment by ami-harry** [comment]
I want to contribute to this issue

**Comment by Utkarsh-Agarwal-585** [comment]
I'm ready to contribute to this issue. It will be look good after solving this issue.

**Comment by smaranjitghose** [comment]
> I want to contribute to this issue

Any updates? This is a simple task i believe

**Comment by Abhijay007** [comment]
> > I want to contribute to this issue
> 
> Any updates? This is a simple task I believe

@smaranjitghose sir, can I work on this?

**Comment by Jatin-MaTTriX** [comment]
@smaranjitghose  sir , can I work on this issue ?

**Comment by Jatin-MaTTriX** [comment]
sir i am SWOC participant can i work on this issue ?

**Comment by Abhijay007** [comment]
@smaranjitghose sir can I commit code with my existing PR which is (added resume section #406) 
or start working after that get merged?

**Comment by smaranjitghose** [comment]
> > @smaranjitghose sir can I commit code with my existing PR which is (added resume section #406)
> > or start working after that get merged?
> 
> I don't think that it makes any problem if I link this issue as well with my existing PR.

Sure
