### ISSUE TITLE
Add better animation effects on the pages

### ISSUE THREAD

**Issue by aum-singhal** [smaranjitghose/awesome-portfolio-websites#397]
I noticed that some of the animations are too slow or some of them are very abrupt. 
Even the box shadows are same on hover.
So I can help on those areas if you felt the same.

**Comment by smaranjitghose** [comment]
> I noticed that some of the animations are too slow or some of them are very abrupt.
> Even the box shadows are same on hover.
> So I can help on those areas if you felt the same.

That would be really cool!
Also, if you have time, I would urge you to try custom css animations as well!

**Comment by aum-singhal** [comment]
Thanks a lot sir 😊

**Comment by nilisha-jais** [comment]
I want to work on this isuue(Participant of SWoC2021)

**Comment by smaranjitghose** [comment]
@nilisha-jais @aum-singhal Figure out to make the animations more optimized and create custom animations as well wherever necessary

**Comment by aum-singhal** [comment]
Sure sir. I have already done some work in the experience page and have tried to optimised the animations. For now trying to work on some custom animations.

**Comment by nilisha-jais** [comment]
> @nilisha-jais @aum-singhal Figure out to make the animations more optimized and create custom animations as well wherever necessary

ok sir
