### ISSUE TITLE
UI Improvement: Project cards can be designed better

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#399]
Right now the project cards look like this: 
![image](https://user-images.githubusercontent.com/49204837/103410297-be005a00-4b90-11eb-8114-5ca626851b2b.png)

I would like to improve the look of these cards. May I get assigned?

**Comment by smaranjitghose** [comment]
> Right now the project cards look like this:
> ![image](https://user-images.githubusercontent.com/49204837/103410297-be005a00-4b90-11eb-8114-5ca626851b2b.png)
> 
> I would like to improve the look of these cards. May I get assigned?

I would definitely urge you to go ahead with this.
UI/UX is subjective as well, so if at any point the maintainers don't see eye to eye with your vision of the design, don't feel disheartened.
Looking forward to your PR 😊
