### ISSUE TITLE
UI Improvements: Skills page need some spacing and alignment

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#400]
Right now there is no divider and enough space between the skill sections.
![image](https://user-images.githubusercontent.com/49204837/103410501-729a7b80-4b91-11eb-95a8-ec45db549b17.png)

and the top section should be aligned at the center as well:
![image](https://user-images.githubusercontent.com/49204837/103410513-91990d80-4b91-11eb-8955-fdf09f402c02.png)

May I get assigned?

**Comment by smaranjitghose** [comment]
> Right now there is no divider and enough space between the skill sections.
> ![image](https://user-images.githubusercontent.com/49204837/103410501-729a7b80-4b91-11eb-95a8-ec45db549b17.png)
> 
> and the top section should be aligned at the center as well:
> ![image](https://user-images.githubusercontent.com/49204837/103410513-91990d80-4b91-11eb-8955-fdf09f402c02.png)
> 
> May I get assigned?

Some additional improvements can be:
- Entering the data of each card using a JSON from a skills.js [ This should include a heading, bullet points, the path of image/illustration]
- In mobile view, the illustrations follow each other rather than an alternating pattern of illustration followed by text.

**Comment by Jatin-MaTTriX** [comment]
can I work on this issue?

**Comment by dipanshparmar** [comment]
Yeah! @Jatin-MaTTriX  please go ahead as I'm working on some other issue right now.

**Comment by Jatin-MaTTriX** [comment]
@smaranjitghose  sir plz assign this issue to me so that i can make PR .

**Comment by Jatin-MaTTriX** [comment]
I have successfully added  proper spacing and lines 

https://user-images.githubusercontent.com/72266203/103663748-75351080-4f97-11eb-90be-1b524d8860ae.mp4

**Comment by Jatin-MaTTriX** [comment]
@smaranjitghose  Sir i updated my PR as per your suggestions . In Updated PR i removed lines and add better alignment to images
