### ISSUE TITLE
Bug: GitHub logo gets disappeared on hover

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#401]
GitHub logo gets disappeared on hover in the home page.
![image](https://user-images.githubusercontent.com/49204837/103410791-f012bb80-4b92-11eb-962e-a8cbe3c07740.png)

May I get assigned?

**Comment by khandelwal20sid** [comment]
assign me this task

**Comment by dipanshparmar** [comment]
@khandelwal20sid This issue is already solved!
