### ISSUE TITLE
Neumorphic Navigation Bar Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#405]
# Aim:

Change the current navigation bar into the neuromorphic form [Leave the awards section for now]

Start with Light mode first

# References:

- [What is neuromorphic UI? ](https://css-tricks.com/neumorphism-and-css/)
- [ Tool for Generating CSS code for Neumorhpic UI](https://neumorphism.io/#e0e0e0)
- [Sample Cards](https://dribbble.com/shots/14376942-Neumorphism-UI-Trend-App-Screen?utm_source=Clipboard_Shot&utm_campaign=sahilbajaj&utm_content=Neumorphism%20UI%20Trend%20App%20Screen&utm_medium=Social_Share)

Please consult with @anushbhatia over this. He has a lot of experience to help out in a better way than I can in this regard

**Comment by deepti23-web** [comment]
@smaranjitghose SWOC Participant. I m interested in working on this. Can you please assign this to me?

**Comment by abhijeet007rocks8** [comment]
I already resolved the issue #369, can add on the neuromorphic UI. 
Can you change my assigned issue to #405 ??

**Comment by dipanshparmar** [comment]
@smaranjitghose I would like to work on this.

**Comment by smaranjitghose** [comment]
> @smaranjitghose I would like to work on this.

Assigned for 2 days. I will reassign for an extended time if required.
