### ISSUE TITLE
Make a dynamic banner for the repo README

### ISSUE THREAD

**Issue by Pranav016** [smaranjitghose/awesome-portfolio-websites#412]
**Feature Description-**
I would like to design a banner for the repo README with dynamically generating stats of the repo. It would complement this amazing repo.

I would like to work on this under **NWoC**.

**Comment by smaranjitghose** [comment]
> **Feature Description-**
> I would like to design a banner for the repo README with dynamically generating stats of the repo. It would complement this amazing repo.
> 
> I would like to work on this under **NWoC**.

That would be really nice!

**Comment by Pranav016** [comment]
> > **Feature Description-**
> > I would like to design a banner for the repo README with dynamically generating stats of the repo. It would complement this amazing repo.
> > I would like to work on this under **NWoC**.
> 
> That would be really nice!

Can you add NWoC label? I'll  make the PR, Thanks :)

**Comment by Pranav016** [comment]
Can you update the Leaderboard please! Ty

**Comment by smaranjitghose** [comment]
> Can you update the NWoC Leaderboard please! Ty

Done
