### ISSUE TITLE
Add issue templates || Feature request

### ISSUE THREAD

**Issue by Pranav016** [smaranjitghose/awesome-portfolio-websites#417]
### Description-
I would like to add a bug report and a feature request template to maintain consistency and to make it easier for the maintainer to review issues.

I would like to work on this today and get it merged since it is the last day of **NWoC** 😄

**Comment by smaranjitghose** [comment]
> ## This issue was raised under NWoC
> ### Description-
> I would like to add a bug report and a feature request template to maintain consistency and to make it easier for the maintainer to review issues.
> 
> I would like to work on this today and get it merged since it is the last day of **NWoC** 😄

We have decided against having a common template for PRs and Issues respectively
