### ISSUE TITLE
Research Page Card Modification: Buttons🔘

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#424]
- Shift ``cite`` and ``abstract`` buttons more towards the bottom right
![button_change](https://user-images.githubusercontent.com/46641503/103943526-4023ec00-5158-11eb-9da3-58ae2325e485.jpg)

- Button position should be absolute and not relative to the content in the card

![image](https://user-images.githubusercontent.com/40017559/103941109-65166000-5154-11eb-8d76-797ab2343a05.png)

**Comment by BALARAMGHOSH** [comment]
@smaranjitghose 
I want to contribute in this issue.

**Comment by BALARAMGHOSH** [comment]
![webpage_button](https://user-images.githubusercontent.com/48158402/104083684-ae56d480-5266-11eb-82f9-c27df5415d71.png)
Are the button positions correct now, or I have to do something more?

**Comment by smaranjitghose** [comment]
> ![webpage_button](https://user-images.githubusercontent.com/48158402/104083684-ae56d480-5266-11eb-82f9-c27df5415d71.png)
> Are the button positions correct now, or I have to do something more?

The second part of the task stated in the description is not solved yet

**Comment by BALARAMGHOSH** [comment]
Ok, I will do it asap.
