### ISSUE TITLE
Research Page Code Update 🐱‍💻

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#426]
# Task 1

In the reseach.js, for each entity in the JSON  we should have:

- Name of the paper
- Conference/Journal
- Authors
- Year
- Image ( path of the image)
- Citation ( just one) content
- 250 words abstract content

**add the code for content of the cite button with the same JSON not defining any extra variable for it.**

# Task 2

On clicking the abstract, open a pop up similar to what we have for cite button

**Comment by ishubham21** [comment]
I want to work on this issue.
