### ISSUE TITLE
Code Fix: 👩‍⚕️ Find all materialize related code and convert them to bootstrap

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#427]

**Comment by vishnupsingh523** [comment]
Sir, can I try to solve this problem ?? I am new to open source and will give my best to solve this one. 😄

**Comment by smaranjitghose** [comment]
> Sir, can I try to solve this problem ?? I am new to open source and will give my best to solve this one. 😄

I assigning this to you for 2 days

**Comment by vishnupsingh523** [comment]
> > Sir, can I try to solve this problem ?? I am new to open source and will give my best to solve this one. 😄
> 
> I assigning this to you for 2 days

Sir which version I have to use for bootstrap??

**Comment by vishnupsingh523** [comment]
Sir, I have made some changes Please check... <a href="https://github.com/smaranjitghose/awesome-portfolio-websites/pull/450" >Issue:#427</a>.
And If it is not up to the mark please guide me 😄.
