### ISSUE TITLE
Adding Minimal Label:Project Page👾

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#428]
Adding Minimal Labels to the project so that they look good

**Comment by vishnupsingh523** [comment]
Mam which kind of lables you want there?

**Comment by smaranjitghose** [comment]
> Mam which kind of lables you want there?

Labels like "react" which pop up on hover for project page cards

**Comment by CharvyJain** [comment]
@smaranjitghose I believe the labels are already present.

**Comment by Chaitanya31612** [comment]
@smaranjitghose I'd like to take it up. How should I change the label's design, any suggestion?

**Comment by anushbhatia** [comment]
You can use https://tailwindcomponents.com/component/tags these and add this to the project page of the site

**Comment by Chaitanya31612** [comment]
> You can use https://tailwindcomponents.com/component/tags these and add this to the project page of the site

Sure, any background color preferences or should I send a pic for each one?

**Comment by anushbhatia** [comment]
![Screenshot_20210126_104029_com android chrome](https://user-images.githubusercontent.com/40017559/105803205-f98d1900-5fc2-11eb-8f96-50e6967a9a5e.jpg)
Currently the labels are like this

**Comment by Chaitanya31612** [comment]
Okay 👍

**Comment by Chaitanya31612** [comment]
@anushbhatia please review my pull request #508 and suggest any change if required.

**Comment by smaranjitghose** [comment]
# 2. Adding Custom labels

@Chaitanya31612 I am closing this issue. Raise a new issue for this as discussed in your PR comments. Also, let me know if I have assigned you the right tags for the open source program you are in. I am not sure whether you are in SWoC or DWoC

**Comment by Chaitanya31612** [comment]
> # 2. Adding Custom labels
> @Chaitanya31612 I am closing this issue. Raise a new issue for this as discussed in your PR comments. Also, let me know if I have assigned you the right tags for the open source program you are in. I am not sure whether you are in SWoC or DWoC

I am in SWOC, not in DWOC. Are there any criteria on how pr will be evaluated/scored?

**Comment by smaranjitghose** [comment]
> > # 2. Adding Custom labels
> > @Chaitanya31612 I am closing this issue. Raise a new issue for this as discussed in your PR comments. Also, let me know if I have assigned you the right tags for the open source program you are in. I am not sure whether you are in SWoC or DWoC
> 
> I am in SWOC, not in DWOC. Are there any criteria on how pr will be evaluated/scored?

No, I was just asking so that I can make sure that I can award you for all the programs you are in
