### ISSUE TITLE
Toggle Button UPGRADE🤘

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#431]
## Design:

[Reference](https://codepen.io/jkantner/pen/XEzWGr?editors=1100)

__NOTE: Please store all assets locally__

## UX:
Unlike the current toggle button, the transition should take place in whichever area of the toggle button the mouse is clicked rather than only on a specific side

**Comment by ishubham21** [comment]
I want to work on this issue.

**Comment by smaranjitghose** [comment]
I am closing this for now. There is a major issue with the nav bar. This can be taken over only after that
