### ISSUE TITLE
Project Page Search Bar UI🖼

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#432]
Make it neumorphic

[Reference](https://codepen.io/tdtrung17693/pen/BaozOzQ)

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by jatinjain001** [comment]
I want to work on this if it is available let me know

**Comment by sanjay270899** [comment]
@smaranjitghose You can close this issue if you wish.
