### ISSUE TITLE
Theme changer button (dark-light) not working in screens sizes < lg (i.e. 990px)

### ISSUE THREAD

**Issue by ishubham21** [smaranjitghose/awesome-portfolio-websites#433]
**Description:** Below provided are the two images which illustrate that the toggle button for dark-light mode is not functional. It can further be visualised by noticing how the toggle button in the first image is set for the light theme, but the dark theme is enabled for the webpage in the background. Same for image 2, just the conditions vice-versed.

**Image-1**
<img width="416" alt="Screenshot (59)" src="https://user-images.githubusercontent.com/34435822/103976921-0d044b80-519e-11eb-8c90-2fd297fb9678.png">

**Image-2**
<img width="343" alt="Screenshot (58)" src="https://user-images.githubusercontent.com/34435822/103976927-0ece0f00-519e-11eb-83ca-10789c9713a7.png">

I can work on resolving this issue (**under SWOC**).

**Comment by smaranjitghose** [comment]
Please address this in #431. I'll assign a HARD label for both of tasks done together (UI + Bug)
