### ISSUE TITLE
Cards under 'A little about me' aren't of the same height

### ISSUE THREAD

**Issue by ishubham21** [smaranjitghose/awesome-portfolio-websites#434]
**Description:** These 4 cards possess different heights, upsetting the overall user experience.

<img width="548" alt="Screenshot (57)" src="https://user-images.githubusercontent.com/34435822/103976705-7f286080-519d-11eb-8afb-7770d4108855.png">

I can work on this issue. Please assign **(under SWOC**)

**Comment by smaranjitghose** [comment]
Also, make sure the content in the cards is loaded from a file home.js, similar to what we have for the [project page](https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/assets/js/project.js)

**Comment by ishubham21** [comment]
Can you please explain what exactly does 'Greeting Request Failed' means?

**Comment by smaranjitghose** [comment]
> Can you please explain what exactly does 'Greeting Request Failed' means?
> <img alt="Screenshot (61)" width="579" src="https://user-images.githubusercontent.com/34435822/104084568-3e4c4c80-526e-11eb-90f4-81eb6b8b859d.png">
> Please let me know the issue.

It's a bug with the GitHub action. Nothing wrong from your end😊
