### ISSUE TITLE
Custom Illustrations [UI/UX]: Project Page🖼

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#435]
__NOTE__: __This is an issue is purely for making custom illustrations using AdobeXD, Photoshop, or Figma. There is no active coding involved whatsoever. And we require you to make the illustrations rather than editing them. Only take the issue if you are cool with this__

# Project Page Illustration Requirement:
![Illustration_Project_Page](https://user-images.githubusercontent.com/46641503/103994812-89f2ed80-51bd-11eb-9538-fe9fd97b3a38.jpg)

Make two separate Illustrations ( one for guys and the other for girls) out of this example. Feel free to add more details (Like giving the laptops a common color, the logo in the centre of the laptop being GitHub's octocat, making the shirt of the man on a brighter shade of white

# Output:

- Remember that we have to make the illustrations compatible for the current project's top section
- Please provide full resolution png as well svg images in your PRs
- Name the illustrations appropriately

**Comment by bhavesh1129** [comment]
Hey I want to work on this issue.

**Comment by smaranjitghose** [comment]
> Hey I want to work on this issue.

Use the slack channel for discussion on this before the design is finalized. That way the process is expedited!

**Comment by kanishkaa24** [comment]
Hey!
I want to work on this. Please assign me.
