### ISSUE TITLE
Custom Illustrations: Research Page 🖼 [UI/UX]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#436]
__NOTE__: __This is an issue is purely for making custom illustrations using AdobeXD, Photoshop, or Figma. There is no active coding involved whatsoever. And we require you to make the illustrations rather than editing them. Only take the issue if you are cool with this__

# Research Page Illustration:
![research](https://user-images.githubusercontent.com/46641503/103995648-c83cdc80-51be-11eb-8944-9b07acf47dea.jpg)

Make two separate Illustrations ( one for guys and the other for girls) out of this example.
 Feel free to add more details (Like giving the laptops a common color, the logo in the center of the laptop being GitHub's octocat, changing the colors of the shirt and the coat to something that shall relate to a "data scientist". The background symbols can be altered to logos of TensorFlow, PyTorch, OpenCV, the symbolization of a neural network)
 
 
# Output:

- Remember that we have to make the illustrations compatible with the current research's top section
- Please provide full resolution png as well as svg images in your PRs
- Name the illustrations appropriately

**Comment by bhoomika07** [comment]
I work on Illustrator and Photoshop, would like to solve this issue.

**Comment by smaranjitghose** [comment]
> SWOC. I work on Illustrator and Photoshop, would like to solve this issue.

For this one, it will take some time. So I urge you to use our slack channel for to-and-fro discussions regarding the illustration, feedback, and update before giving the PR. That way the process would be expedited.

**Comment by bhoomika07** [comment]
> > SWOC. I work on Illustrator and Photoshop, would like to solve this issue.
> 
> For this one, it will take some time. So I urge you to use our slack channel for to-and-fro discussions regarding the illustration, feedback, and update before giving the PR. That way the process would be expedited.

okay will keep that in mind, I'll start working!

**Comment by jatinjain001** [comment]
I would like to work on it please assign it to me

**Comment by jatinjain001** [comment]
I am working on it

**Comment by anushbhatia** [comment]
Okay great if you need any suggestion feel free to approach me
