### ISSUE TITLE
Convert home page UI to neumorphic UI

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#439]
Can we convert the home page UI to neumorphic UI?
![image](https://user-images.githubusercontent.com/49204837/104028838-3600fc80-51ef-11eb-8192-ec4ce829b6df.png)

If yes then I would like to work on this.

**Comment by smaranjitghose** [comment]
> Can we convert the home page UI to neumorphic UI?
> ![image](https://user-images.githubusercontent.com/49204837/104028838-3600fc80-51ef-11eb-8192-ec4ce829b6df.png)
> 
> If yes then I would like to work on this.

I have some plans for custom animation incorporation ( involving gamification) to the home page and education page. So meanwhile could you please raise an issue for the experience page regarding the same
