### ISSUE TITLE
Add ability to search projects by project name as well

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#440]
Currently, the projects can only be searched by the tech tag. I would like to add the functionality of searching the project by its name itself.

**Comment by AmeyaJain-25** [comment]
I'm new to SWOC. 
If this issue is not done or is if allowed, can I work on this issue to get resolved

**Comment by dipanshparmar** [comment]
@AmeyaJain-25 Yeah! please go ahead

**Comment by AmeyaJain-25** [comment]
Thanks @dipanshparmar

**Comment by AmeyaJain-25** [comment]
I have added the feature for searching through the project name too.

Search through tag
![image](https://user-images.githubusercontent.com/66305085/104492346-7f8b8600-55f9-11eb-8a69-5d703dd076f3.png)

Search through project name
![image](https://user-images.githubusercontent.com/66305085/104492366-87e3c100-55f9-11eb-9576-33e9c4527885.png)


Is it good to push and generate a PR?
Or any suggestions or changes needed?
