### ISSUE TITLE
Convert Experience page UI to neumorphic UI

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/awesome-portfolio-websites#445]
![image](https://user-images.githubusercontent.com/49204837/104048609-871dea00-5209-11eb-849f-878d266d1226.png)

**May I work on this?**

**Comment by smaranjitghose** [comment]
![expereince_nuemorphic1](https://user-images.githubusercontent.com/46641503/104091574-35766d80-52a4-11eb-9349-1b6488410852.jpg)
Some minor tweaking in the box-shadow is required to make it in parallel with the research page cards.

There is an overflow of text in some of the cards
