### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#453]
__NOTE: This is an issue that exclusively demands knowledge of Python. Please take this up only if you are comfortable beyond basics__

#### Branch for source code: [documentation](https://github.com/smaranjitghose/awesome-portfolio-websites/tree/documentation)

__Please read through the documentation carefully and dedicate some time!__

## Documentation Requirements:

1. Welcome [Refer the readme]
    - About the project
    - Why Open Source?
    - Programs we have been a part of
    - Sneak Peak (Use Gifs)
    - Team
 
 ** Please do beyond just copy-paste. Use your creative writing skills.   
 
 2.  How to start using it?
      - Install Git
      - Setup Git and GitHub Account
      - Navigate to GitHub Repository
      - Fork the repo
      - Clone the repo [ use `git clone ..... --depth 1`]
      - Access the local copy
      - Delete Additional Stuff ( Readme, Readme assets,etc)
 3. Page by Page Changes:
      - Home Page
      - Education Page
      - Project Page
      - Experience Page
      - Research Page
      - Social Media Links
      - Assets
      - SEO
      
  ^^ Detailed guide on which files to open, where to change the content and for what parts? Use screenshots of the changes!
  
  4.  Publishing the portfolio!
      - Save the changes
      - The step by step to push to Github
      - Tip: On making the repository private if desired
      - Deployment + Using Custom Domain:
               - GitHub Pages
               - Netlify
               - AWS Amplify
               
# Directions:
- Some of the content is already there. We expect you to improve it in all ways possible!
- Please take only one page at a time to update and state it clearly in the comments below
- First update the source code, check your build output, push to your own gh-pages branch
- Then in the PR, compare both the `documentation` and `gh-pages` branch (separate PRs but would be counted as a pair)
- Attach a screenshot of your changes
- Attach a link to your own deploy preview on GitHub pages
- Use proper comments in the markdown files

**Comment by HarshKhilawala** [comment]
@smaranjitghose  Please assign this to me.

**Comment by raman08** [comment]
I would like to work on it

**Comment by raman08** [comment]
The home page is kind of large and a lot to scroll.
I was thinking to make separate pages for the Code of conduct and Licence on their separate page.
Also, there should be a separate page for the deployment section.

**Comment by smaranjitghose** [comment]
> The home page is kind of large and a lot to scroll.
> I was thinking to make separate pages for the Code of conduct and Licence on their separate page.
> Also, there should be a separate page for the deployment section.

Keep the home page intact❌
Have a separate page for deployment✅

**Comment by raman08** [comment]
> > The home page is kind of large and a lot to scroll.
> > I was thinking to make separate pages for the Code of conduct and Licence on their separate page.
> > Also, there should be a separate page for the deployment section.
> 
> Keep the home page intact
> Have a separate page for deployment

Okk @smaranjitghose I will create a separate page for the deployment
