### ISSUE TITLE
User Experience (UX) enhancement for Home Page. 

### ISSUE THREAD

**Issue by ishubham21** [smaranjitghose/awesome-portfolio-websites#459]
On the home page, when the screen size is set to 768px (i.e. for mobile-landscape/iPad), the cards under 'A little about me' shrinks down to fit 4 cards which makes it look ugly. 
**Solution - ** Instead of 4 cards, we can have two cards for middle-sized screens. 
<img width="578" alt="Screenshot (76)" src="https://user-images.githubusercontent.com/34435822/104328839-43312a80-5512-11eb-9e43-9066c84dd0e9.png">

**Comment by AmeyaJain-25** [comment]
Can you assign me this issue.
I'm new to SWoC 2021, so help me to know that do I have to ask to assign or can I directly start.
 I would like to solve this issue under SWoC.

**Comment by smaranjitghose** [comment]
> On the home page, when the screen size is set to 768px (i.e. for mobile-landscape/iPad), the cards under 'A little about me' shrinks down to fit 4 cards which makes it look ugly.
> **Solution - ** Instead of 4 cards, we can have two cards for middle-sized screens.
> <img alt="Screenshot (76)" width="578" src="https://user-images.githubusercontent.com/34435822/104328839-43312a80-5512-11eb-9e43-9066c84dd0e9.png">

@ishubham21 you are still working on this right?

**Comment by ishubham21** [comment]
> > On the home page, when the screen size is set to 768px (i.e. for mobile-landscape/iPad), the cards under 'A little about me' shrinks down to fit 4 cards which makes it look ugly.
> > **Solution - ** Instead of 4 cards, we can have two cards for middle-sized screens.
> > <img alt="Screenshot (76)" width="578" src="https://user-images.githubusercontent.com/34435822/104328839-43312a80-5512-11eb-9e43-9066c84dd0e9.png">
> 
> @ishubham21 you are still working on this right?

Yes, I am. Will submit a PR in 1 hour.

**Comment by smaranjitghose** [comment]
We are moving away from neumorphism and removing this section altogether
