### ISSUE TITLE
Home Tab and Experience Tab is not visible when side navbar is opened

### ISSUE THREAD

**Issue by AmeyaJain-25** [smaranjitghose/awesome-portfolio-websites#461]
Here, when we see the application in small width screen, the Home tab and experience tab gets hidden by the top header. 
I would like to resolve this issue. Please assign me this issue
![image](https://user-images.githubusercontent.com/66305085/104346363-55689400-5525-11eb-84dc-2cc597595325.png)

I would like to work on this issue under SWoC 2021. Please assign me this issue.

**Comment by AmeyaJain-25** [comment]
Thanks @smaranjitghose

**Comment by smaranjitghose** [comment]
@AmeyaJain-25 While you work on this, please pull the recent changes incorporated

**Comment by AmeyaJain-25** [comment]
I did the pull upstream master before commiting my code.
