### ISSUE TITLE
`Check out our awesome Documentation` link in README.md is broken

### ISSUE THREAD

**Issue by vidhi-mody** [smaranjitghose/awesome-portfolio-websites#462]
On clicking `Check out our awesome Documentation` in the README
<img width="897" alt="Screenshot 2021-01-13 at 7 40 52 PM" src="https://user-images.githubusercontent.com/49282105/104463167-6ffb4580-55d7-11eb-865b-79578f9b1221.png">

The result is: 
<img width="576" alt="Screenshot 2021-01-13 at 7 41 10 PM" src="https://user-images.githubusercontent.com/49282105/104463188-77baea00-55d7-11eb-8056-036afe956d8e.png">

**Comment by smaranjitghose** [comment]
Refer #453 to understand better. Just generate the documentation  using the source code on `documentation` branch

**Comment by smaranjitghose** [comment]
Resolved via integration of new GitHub Action for mkdocs
