### ISSUE TITLE
New Navigation Bar🏗

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#469]
The current navigation bar is written using Materialize.
I expect you to replace it completely using Boostrap or Custom CSS

Follow the exact work done [here](https://girlscriptboilerplate.netlify.app/)

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by kanishkaa24** [comment]
Can I work on this ?

**Comment by jatinjain001** [comment]
Can I work on this please?

**Comment by anushbhatia** [comment]
No updates yet. The basic version is done by us. Any of you interested in this issue, contact me over slack for the design
