### ISSUE TITLE
Improve Footer Design🪓

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#470]
Make the light mode color black

Make it simple [like](https://smaranjitghose.codes/)

**Comment by Priyanshu-official** [comment]
I would like to work on that
pls Assign me

**Comment by smaranjitghose** [comment]
> I would like to work on that
> pls Assign me

Assigned for 2 days

**Comment by jatinjain001** [comment]
I would like to work on it

**Comment by jatinjain001** [comment]
I would like to work on it

**Comment by 07yuvraj** [comment]
I would like to work on it

**Comment by parthpandyappp** [comment]
@smaranjitghose Is this still open for contribution? If yes, I'm glad to be in!
And actually what part in the footer for https://portfolio.smaranjitghose.codes/ needs enhancement?

**Comment by pankajkumarbij** [comment]
I would like to work on it, please assign it t me.

**Comment by anushbhatia** [comment]
Sure go ahead @parthpandyappp  and @pankajkumarbij

**Comment by jainh6148** [comment]
Hi sir, I am a front end web developer as well as a freelancer. I have also worked in UI/UX design. I would love to improve the footer design. Kindly assign the project to me.

**Comment by smaranjitghose** [comment]
> Hi sir, I am a front end web developer as well as a freelancer. I have also worked in UI/UX design. I would love to improve the footer design. Kindly assign the project to me.

Sure, finish off the issues already assigned to you. Then you can continue with this one as well

**Comment by kumarhritik99** [comment]
Hi I would like to contribute to this issue. Please assign it to me

**Comment by nishant3721** [comment]
Hello sir, I would like to contribute in this. I have also created my portfolio website and I would love to work in the footer section as mention above. Please assign it to me!

**Comment by parthpandyappp** [comment]
@smaranjitghose What actually needs to be done? Can you please be more specific regarding this issue??

**Comment by achalesh27022003** [comment]
@smaranjitghose Sir I can improve responsive footer with input animation in contact form and also pulsating heart animation and making that quote in italic looks nice.

https://user-images.githubusercontent.com/57138750/108501299-1c1b0500-72d7-11eb-8eea-3ce0da572f60.mp4
or 
[reference](https://www.awesomescreenshot.com/video/2812993?key=9930d72e074427b4a5339878e9e5a498)


Please assign me this issue under **DWoC** sir.

**Comment by achalesh27022003** [comment]
@smaranjitghose sir is there any problem with it?
