### ISSUE TITLE
Carefully Remove all code related to Resume Section Home Page❌

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#471]

**Comment by ishubham21** [comment]
Can you please elaborate on this issue.

**Comment by smaranjitghose** [comment]
![Uploading about_me.jpg…]()

**Comment by CharvyJain** [comment]
Can I work on this issue ?

**Comment by kanishkaa24** [comment]
Can I work on this issue?

**Comment by smaranjitghose** [comment]
Too late for PR. Already handled by the maintainers. Please understand such issues are supposed to take under 10 min of time and we expect a PR accordingly
