### ISSUE TITLE
Carefully Remove all code related to About Section Home Page ❌

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#472]

**Comment by nilisha-jais** [comment]
Can you please describe this issue

**Comment by smaranjitghose** [comment]
> Can you please describe this issue

It's self-explanatory as per the title!

![about_me](https://user-images.githubusercontent.com/46641503/104697504-ddbd8380-5735-11eb-86b8-6aaf0f031dfc.jpg)

**Comment by raman08** [comment]
I would like to work on it

**Comment by nilisha-jais** [comment]
> > Can you please describe this issue
> 
> It's self-explanatory as per the title!
> 
> ![about_me](https://user-images.githubusercontent.com/46641503/104697504-ddbd8380-5735-11eb-86b8-6aaf0f031dfc.jpg)

I can work on this issue.Please assign it to me

**Comment by kanishkaa24** [comment]
Can I work on this issue ?

**Comment by nilisha-jais** [comment]
I guess the code is already manipulated as there is no such section. Please help

**Comment by smaranjitghose** [comment]
Too late for PR. Already handled by the maintainers. Please understand such issues are supposed to take under 10 min of time and we expect a PR accordingly
