### ISSUE TITLE
Fix Experience Page Colors and CARDS

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#475]
[Reference](https://smaranjitghose.codes/experience.html)

**Comment by ishubham21** [comment]
I want to do this.

**Comment by nilisha-jais** [comment]
I want to work on this issue as a part of SWoC'21

**Comment by vidhi-mody** [comment]
@nilisha-jais I'm temporarily un-assigning this issue since Shubham commented first. I've assigned the other issues you are interested in working on to you.

**Comment by nilisha-jais** [comment]
> @nilisha-jais I'm temporarily un-assigning this issue since Shubham commented first. I've assigned the other issues you are interested in working on to you.

okay np
