### ISSUE TITLE
Feat: Hover Effect on Nav Bar

### ISSUE THREAD

**Issue by im-sakshijain** [smaranjitghose/awesome-portfolio-websites#478]
![jo](https://user-images.githubusercontent.com/62291788/104833130-6b2ae000-58bc-11eb-9994-1250ba732874.jpeg)
As of now, when we go from home to experience or any other section of the nav bar there is no hover effect.
![navvv](https://user-images.githubusercontent.com/62291788/104833177-be9d2e00-58bc-11eb-96f2-b7888e313e8d.jpeg)
![m](https://user-images.githubusercontent.com/62291788/104833179-c230b500-58bc-11eb-9704-c077add820fb.jpeg)
These are some examples, I can do something like that.

I would like to work on this issue under SWoC'21. Please assign this issue to me.

**Comment by smaranjitghose** [comment]
Now onwards, we are planning to create the navbar components from scratch instead of using bootstrap. @im-sakshijain if you wish to do it, could you please DM @anushbhatia over slack. 

Remember: the navigation bar would be complete in 2-3 PRs over a week's time and requires commitment. Since we'll follow a particular color palette, use micro animations as well as transition effects each for dark and light modes

**Comment by im-sakshijain** [comment]
Okay Got it! I want to do this. I'll DM to @anushbhatia. Thank you.

**Comment by Amit366** [comment]
Sir is this issue still open??

**Comment by anushbhatia** [comment]
GO ahead with the 3rd one I would prefer that with colour palette specified in the pinned issue

**Comment by im-sakshijain** [comment]
https://user-images.githubusercontent.com/62291788/105733306-6b2f7d80-5f57-11eb-90ac-72b2b1d5058e.mp4

Is this effect fine?

**Comment by anushbhatia** [comment]
Refer #487 for the colour palette. The hove effect can be the same that you have done on the portfolio site

**Comment by smaranjitghose** [comment]
>  2021-01-25.21-50-53.mp4 
> Is this effect fine?

any updates?

**Comment by im-sakshijain** [comment]
What exactly,  I've to do with color palette, like the hover color should be #f4f4f4 ? Or should  I change  the hover effect?

**Comment by smaranjitghose** [comment]
> What exactly, I've to do with color palette, like the hover color should be #f4f4f4 ? Or should I change the hover effect?

@anushbhatia
