### ISSUE TITLE
Colour Palette🎨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#487]
![color palllete](https://user-images.githubusercontent.com/40017559/104850260-10bd6e00-5914-11eb-8c2a-b0b7e53f68ab.jpg)

**Comment by Amit366** [comment]
Can you elaborate this issue?

**Comment by anushbhatia** [comment]
It is converting the current project to this template

**Comment by Moonlightsculptor88** [comment]
Can I work on this issue?

**Comment by Rajdeep-99** [comment]
Is the issue solved? If not I would like to work on it.
