### ISSUE TITLE
Improve Education Page Alignment

### ISSUE THREAD

**Issue by Aayush-hub** [smaranjitghose/awesome-portfolio-websites#494]
Award and prizes is overlapped by get in touch in education page.

# Screenshot
![Capture11](https://user-images.githubusercontent.com/65889104/105026923-21392a00-5a75-11eb-84b3-98d48f6ffafe.PNG)

**Comment by smaranjitghose** [comment]
> Award and prizes is overlapped by get in touch in education page.
> 
> # Screenshot
> ![Capture11](https://user-images.githubusercontent.com/65889104/105026923-21392a00-5a75-11eb-84b3-98d48f6ffafe.PNG)

Give a PR and remove the carousel all together

**Comment by Aayush-hub** [comment]
@smaranjitghose Please add SWOC label.
