### ISSUE TITLE
"open-source developer" card is already bigger than other cards. 

### ISSUE THREAD

**Issue by mishrajiharsh219** [smaranjitghose/awesome-portfolio-websites#504]
In Home section, the "open-source developer" card is already bigger than other cards. All cards should be of equal size when the website is opened for the first time. Look at the height of the "open source " section, it is bigger than other cards.
Please assign me this issue.
![issue sithub](https://user-images.githubusercontent.com/50453715/105603605-b0b74380-5dbb-11eb-8649-29a85a13b65c.PNG)

**Comment by smaranjitghose** [comment]
This section has been removed long back
