### ISSUE TITLE
Design improvements in some areas.

### ISSUE THREAD

**Issue by Chaitanya31612** [smaranjitghose/awesome-portfolio-websites#506]
## Objectives:-

- Fix this search bar:

![image](https://user-images.githubusercontent.com/54992097/105698829-7325f800-5f2c-11eb-8315-c57cfe0a923c.png)

- Fix some spacing in card on experience page:

![image](https://user-images.githubusercontent.com/54992097/105698776-5d183780-5f2c-11eb-94a1-388e8e522caa.png)

- Also some ui improvement in cards:

![image](https://user-images.githubusercontent.com/54992097/105698875-88028b80-5f2c-11eb-9095-a505681c837f.png)

I'd like to work on these issues and improvements.

**Comment by Chaitanya31612** [comment]
@anushbhatia please review my pull request #507. (Just to mention I am under the SWOC program.)

**Comment by achalesh27022003** [comment]
I would work on this issue with some hover effects on cards. I would also add top to bottom button in this. Please assign me this issue. @smaranjitghose  sir.

**Comment by achalesh27022003** [comment]
And also I can do some animations and cool hover effect in nav bar and some background animation using particle.js, Please assign me @smaranjitghose  sir.

**Comment by smaranjitghose** [comment]
> I would work on this issue with some hover effects on cards. I would also add top to bottom button in this. Please assign me this issue. @smaranjitghose sir.

Please raise individual issues for your suggestions with a possible demo/reference.
Looking forward to your ideas!

Meanwhile check out the SVG animation issues and try them if you wish to
