### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#510]
[Basic Reference](https://www.hackchennai.in/)

Please do not put a comment what do you want  in this, look up the color palette, do some research on dribble and codepen and accordingly come up with something new

**Comment by ishubham21** [comment]
I want to do this.

**Comment by achalesh27022003** [comment]
I can customize this with linear gradient sir @smaranjitghose . If you allow, I can work on it. Thanks

**Comment by smaranjitghose** [comment]
> I can customize this with linear gradient sir @smaranjitghose . If you allow, I can work on it. Thanks

Give @ishubham21 1 more day. After that give the PR

**Comment by achalesh27022003** [comment]
I have sent the PR , pls review, merge and level-label it and also I don't know why it didn't passed one test case.
https://github.com/smaranjitghose/awesome-portfolio-websites/pull/544

**Comment by achalesh27022003** [comment]
I got it why it didn't passed as I guess you removed access of greeting bot so it's not able to push the message. Pls look into it and level label PR asap

**Comment by smaranjitghose** [comment]
> I got it why it didn't passed as I guess you removed access of greeting bot so it's not able to push the message. Pls look into it and level label PR asap

It's a bug in the github action

**Comment by achalesh27022003** [comment]
@smaranjitghose sir pls level label the PR and merge it under DWOC and also I'm participating in SWoC.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir pls level label the PR and merge it under DWOC and also I'm participating in SWoC.

Where is the PR? Could you please comment there. It would be way more convenient
