### ISSUE TITLE
Project Card Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#511]
![project_card_bug](https://user-images.githubusercontent.com/46641503/106368966-b987b680-6373-11eb-8cec-2b5be29262a5.jpg)

**Comment by Chaitanya31612** [comment]
@smaranjitghose I'd like to work on this.

**Comment by jatinjain001** [comment]
I would like to work on it please assign it to me

**Comment by jatinjain001** [comment]
![Uploading Screenshot (223).png…]()

I resolved the bug, I just need to align the skill tags so that it should not be shown in a half way

**Comment by smaranjitghose** [comment]
> ![Screenshot (223)](https://user-images.githubusercontent.com/46483236/107320980-c5881c80-6ac7-11eb-9e09-e2f3be03adf7.png)
> 
> I resolved the bug, I just need to align the skill tags so that it should not be shown in a half way

If you observe properly, your change has messed up the search bar icon

**Comment by jatinjain001** [comment]
I got it i just make a pr now wait only 30 mins only

**Comment by jatinjain001** [comment]
I am confused a little my task is to solve the issue for skills tag which is showing half away
am i correct?

**Comment by smaranjitghose** [comment]
> I am confused a little my task is to solve the issue for skills tag which is showing half away
> am i correct?
> But there is already this issue is solved . Can you please explain me ?

It's the entire project card

**Comment by jatinjain001** [comment]
Okay what should i do on the project card? its looking perfect

**Comment by smaranjitghose** [comment]
> Okay what should i do on the project card? its looking perfect

😅
See the screenshot I gave in your last PR. It has to work for all screen sizes

**Comment by jatinjain001** [comment]
okay so its make to responsive only? is this my task?

**Comment by smaranjitghose** [comment]
> okay so its make to responsive only? is this my task?

Yes.
And without hover, only the name should be visible. On Hover, transition + Visibility of Tags + Github and Preview Icons

**Comment by jatinjain001** [comment]
okay
