### ISSUE TITLE
Project Page Search Bar Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#512]
![Search_Bar_Project_page](https://user-images.githubusercontent.com/46641503/106368997-010e4280-6374-11eb-8810-f53210169295.jpg)

**Comment by Chaitanya31612** [comment]
@smaranjitghose I can fix this as I've also fixed the search icon for the component. So if you wish I can fix this.

**Comment by achalesh27022003** [comment]
If you want then I can make search bar expanded animations. For that you can assign me @smaranjitghose sir.

**Comment by smaranjitghose** [comment]
> If you want then I can make search bar expanded animations. For that you can assign me @smaranjitghose sir.

Sure, raise a separate issue for this so that it is convenient to keep track.

Also, elaborate in the description of the issue "Search Bar Expanded Animations" Or give some reference
