### ISSUE TITLE
Project_Card_Tag_Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#513]
![Project_Card_tag_bug](https://user-images.githubusercontent.com/46641503/106369038-3fa3fd00-6374-11eb-90a3-f1a530a9c547.jpg)

**Comment by Chaitanya31612** [comment]
@smaranjitghose I'd like to fix this. You are talking about space within and between elements, right?

**Comment by smaranjitghose** [comment]
> @smaranjitghose I'd like to fix this. You are talking about space within and between elements, right?

Assigned for 2 days.

**Comment by Chaitanya31612** [comment]
> > @smaranjitghose I'd like to fix this. You are talking about space within and between elements, right?
> 
> Assigned for 2 days.

![image](https://user-images.githubusercontent.com/54992097/106383720-7ec26480-63ed-11eb-9d97-68d09bfba601.png)

**Comment by smaranjitghose** [comment]
> > > @smaranjitghose I'd like to fix this. You are talking about space within and between elements, right?
> > 
> > 
> > Assigned for 2 days.
> 
> ![image](https://user-images.githubusercontent.com/54992097/106383720-7ec26480-63ed-11eb-9d97-68d09bfba601.png)

The small comma
