### ISSUE TITLE
Pre-Loader using SVG Animation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#517]
Combine the following 

- [Reference 1](https://codepen.io/arkwis/pen/chnop)
- [Reference 2](https://codepen.io/Maskedman99/pen/YzPvrgN)

^^ For reference 2, instead of the nucleus at the center, try to have a brain outline so that we can make the animation depict a neural network [OPTIONAL}

- Follow the color palette
- The text should be "John Doe" 
- Document the code clearly so that anyone can change it as per their names

**Comment by deytulsi18** [comment]
Can I take up this task @smaranjitghose ?

**Comment by deytulsi18** [comment]
Can you just tell me that where shall this animation be placed in the landing page (index.html), In place of the name **John Doe** ?

**Comment by smaranjitghose** [comment]
> Can you just tell me that where shall this animation be placed in the landing page (index.html), In place of the name **John Doe** ?

It's a preloader or let's say splash screen

**Comment by Chaitanya31612** [comment]
@smaranjitghose I'd like to work on this.

**Comment by Abhijay007** [comment]
@smaranjitghose sir with the referenced links I make this pre-loader :

![pre-loader](https://user-images.githubusercontent.com/64387054/107664367-591d4100-6cb2-11eb-9d4a-39539a2d3206.gif)

it is very easy to customize this preloader you just need to change the image and text according to your preferences. 
So if a user who is not from the coding background can change it easily.

**Comment by Abhijay007** [comment]
@smaranjitghose sir, I can change the color scheme according to you if you approve this. currently, I use purple neural-network brain SVG.

**Comment by Abhijay007** [comment]
> @smaranjitghose sir with the referenced links I make this pre-loader :
> 
> ![pre-loader](https://user-images.githubusercontent.com/64387054/107664367-591d4100-6cb2-11eb-9d4a-39539a2d3206.gif)
> 
> it is very easy to customize this preloader you just need to change the image and text according to your preferences.
> So if a user who is not from the coding background can change it easily.

@smaranjitghose sir can I open a PR for this.

**Comment by smaranjitghose** [comment]
> > @smaranjitghose sir with the referenced links I make this pre-loader :
> > ![pre-loader](https://user-images.githubusercontent.com/64387054/107664367-591d4100-6cb2-11eb-9d4a-39539a2d3206.gif)
> > it is very easy to customize this preloader you just need to change the image and text according to your preferences.
> > So if a user who is not from the coding background can change it easily.
> 
> @smaranjitghose sir can I open a PR for this.

Give a PR. I'll have a look surely

**Comment by jainh6148** [comment]
Hi Sir, I am a front end web developer and working as a freelancer. I would love to contribute to this project. I will appreciate it if you can assign me this project.

**Comment by smaranjitghose** [comment]
> Hi Sir, I am a front end web developer and working as a freelancer. I would love to contribute to this project. I will appreciate it if you can assign me this project.

Finish the two issues you are being assigned as per requirements, after that you can claim this

**Comment by Abhijay007** [comment]
> Give a PR. I'll have a look surely

ok @smaranjitghose sir

**Comment by Sloth-Panda** [comment]
Can I get to work on this?

**Comment by smaranjitghose** [comment]
> Can I get to work on this?

Assigned for 3 days
