### ISSUE TITLE
[ADVANCED] SVG Animation for Toggle Button

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#520]

**Comment by vismitap** [comment]
Hey! What exactly needs to be done here? There is already an animation for the toggle button. What changes need to be made? I would like to work on this issue.

**Comment by smaranjitghose** [comment]
> Hey! What exactly needs to be done here? There is already an animation for the toggle button. What changes need to be made? I would like to work on this issue.

There is no toggle button at all currently.

Once that is resolved. I share more details on this one

**Comment by vismitap** [comment]
> > Hey! What exactly needs to be done here? There is already an animation for the toggle button. What changes need to be made? I would like to work on this issue.
> 
> There is no toggle button at all currently.
> 
> Once that is resolved. I share more details on this one

Sure, np👍.

**Comment by SamikshaSankar** [comment]
@smaranjitghose assign me this issue under LGM-SOC'21
