### ISSUE TITLE
SVG Animation for the bottom of sidebar

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#521]
[Reference](https://codepen.io/zhoha/pen/xxZowqg)

**Comment by Chaitanya31612** [comment]
@smaranjitghose are you suggesting this for mobile view? I don't get which sidebar?

**Comment by smaranjitghose** [comment]
> @smaranjitghose are you suggesting this for mobile view? I don't get which sidebar?

Yes for mobileview

**Comment by Chaitanya31612** [comment]
@smaranjitghose do you want me to add this animation at bottom of the sidebar or somewhere else?

![image](https://user-images.githubusercontent.com/54992097/107124313-2d244900-68c9-11eb-9730-758c70e187c9.png)

**Comment by smaranjitghose** [comment]
> @smaranjitghose do you want me to add this animation at bottom of the sidebar or somewhere else?
> 
> ![image](https://user-images.githubusercontent.com/54992097/107124313-2d244900-68c9-11eb-9730-758c70e187c9.png)


Yes the bottom, leaving a few spaces after the education line

Additionally, we can reduce some of the spaces between the top "john Doe" text  and "Home" line. It's unnecessary.  Also, the color of the text looks weird, make it black

**Comment by Abhijay007** [comment]
can I work on this?

**Comment by Abhijay007** [comment]
@smaranjitghose sir do you want something like this?

![nav](https://user-images.githubusercontent.com/64387054/108715007-48858a00-7540-11eb-889c-933234adc357.PNG)

I will animate this and use any other SVG if you want.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir do you want something like this?
> 
> ![nav](https://user-images.githubusercontent.com/64387054/108715007-48858a00-7540-11eb-889c-933234adc357.PNG)
> 
> I will animate this and use any other SVG if you want.

Rotate the wheels and paddles

**Comment by Abhijay007** [comment]
> > @smaranjitghose sir do you want something like this?
> > ![nav](https://user-images.githubusercontent.com/64387054/108715007-48858a00-7540-11eb-889c-933234adc357.PNG)
> > I will animate this and use any other SVG if you want.
> 
> Rotate the wheels and paddles

yes @smaranjitghose sir will do that 👍

**Comment by Abhijay007** [comment]
> Rotate the wheels and paddles

![bike animation](https://user-images.githubusercontent.com/64387054/108913559-2418d300-7650-11eb-8fe6-de24b855a2dc.gif)

@smaranjitghose sir done with the changes have a look.

do I need to change something, can I open PR for this?

**Comment by smaranjitghose** [comment]
Give a PR

**Comment by Abhijay007** [comment]
Ok sir

**Comment by smaranjitghose** [comment]
Give a PR
