### ISSUE TITLE
SVG Animation for Research Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#522]
Try to come with something creative

[Sample](https://codepen.io/brunoalves/pen/NWGRxKR)

Do not just move random components!

**Comment by Chaitanya31612** [comment]
@smaranjitghose I would like to take it up!

**Comment by smaranjitghose** [comment]
> @smaranjitghose I would like to take it up!

Any updates on this?

**Comment by Chaitanya31612** [comment]
> > @smaranjitghose I would like to take it up!
> 
> Any updates on this?

I will try to do it by today.

**Comment by Chaitanya31612** [comment]
@smaranjitghose you want me to animate elements of current svg in research page or to replace it with one of them?

**Comment by smaranjitghose** [comment]
> @smaranjitghose you want me to animate elements of current svg in research page or to replace it with one of them?

Try animating the elements of the current SVG

**Comment by Chaitanya31612** [comment]
> > @smaranjitghose you want me to animate elements of current svg in research page or to replace it with one of them?
> 
> Try animating the elements of the current SVG

okay
