### ISSUE TITLE
Adding tilt effect for the cards 

### ISSUE THREAD

**Issue by deytulsi18** [smaranjitghose/awesome-portfolio-websites#531]
So I would like to suggest an enhancement which goes like: 
Adding tilt effect for the cards under section **A Little about me** in the home page.

**Comment by smaranjitghose** [comment]
> So I would like to suggest an enhancement which goes like:
> Adding tilt effect for the cards under section **A Little about me** in the home page.

Pull the recent version of the website. That section is no more there
