### ISSUE TITLE
UI\UX for mobile design - Project, Experience page

### ISSUE THREAD

**Issue by RutvikJ77** [smaranjitghose/awesome-portfolio-websites#533]
I was pondering through the template where I encountered a few bugs. As a UI\UX designer, the approach should be mobile-first which made me change the website size. The animations or the tabs which provided information in the experience/projects page are not visible if the screen width is reduced. Additionally, there are unnecessary "," tags in the project section of which technologies are used.

![Screenshot 2021-02-02 at 10 12 10 AM (2)](https://user-images.githubusercontent.com/45565999/106553639-c5c06f00-653f-11eb-854d-c93c18b3bd24.png)
![Screenshot 2021-02-02 at 10 12 32 AM (2)](https://user-images.githubusercontent.com/45565999/106553644-c6f19c00-653f-11eb-9efe-b8cbf044b543.png)

**Comment by smaranjitghose** [comment]
Check out #511  #513

**Comment by RutvikJ77** [comment]
Got it! I am closing this issue.
