### ISSUE TITLE
Toggle Switch for Dark/Light mode

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#535]
[Reference](https://codepen.io/ashleynolan/pen/wBppKz)

**Comment by akshay1027** [comment]
I would like to contribute to this issue @smaranjitghose sir

**Comment by jyotsana3108** [comment]
I would like to contribute and resolve this issue using CSS @smaranjitghose

**Comment by smaranjitghose** [comment]
> I would like to contribute to this issue @smaranjitghose sir

Updates?

**Comment by jainh6148** [comment]
Hi Sir, I would like to contribute to this issue.

**Comment by akshay1027** [comment]
> > I would like to contribute to this issue @smaranjitghose sir
> 
> Updates?

sorry sir, I am having exams, you can unassign me!

**Comment by Hritikkumar** [comment]
Hi, I would like to work on this issue. Kindly assign it to me as well!

**Comment by smaranjitghose** [comment]
> Hi, I would like to work on this issue. Kindly assign it to me as well!

Let @jainh6148 try this for the next 3 days. Meanwhile, you can try out #520

**Comment by smaranjitghose** [comment]
@jainh6148, since you are working on the other issue, I am extending the deadline for this one by 3 more days

**Comment by Hritikkumar** [comment]
Hi @smaranjitghose , I would like to know that what colors you want in the dark theme? Also I would like to request you to give me one or two more days as I was busy in my college work.

**Comment by smaranjitghose** [comment]
> Hi @smaranjitghose , I would like to know that what colors you want in the dark theme? Also I would like to request you to give me one or two more days as I was busy in my college work.

@anushbhatia could you provide the colour palette
