### ISSUE TITLE
Micro animations for social media icons

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#536]
[Reference](https://codepen.io/nat-davydova/pen/jOEgQwp)

Please use your creativity

For example:
- GitHub: the octocat moves the hand. A [rough example](https://codepen.io/thulioph/pen/bowmeR)✅ 
- Twitter: the tweety flaps wings ✅
- LinkedIN: the dot over I bounces like a ball
- Medium:
- Kaggle:
- Codeforces:
- Google Scholar:
- Dribble:
- Instagram:

**Comment by achalesh27022003** [comment]
@smaranjitghose sir I can do this. Please assign me this issue.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir I can do this. Please assign me this issue.

Assigned for next 4 days. If required, we can extend the deadline!

**Comment by achalesh27022003** [comment]
Sir I want to ask few questions that:
is it necessary to keep medium, kaggle icons etc? Can we change them for our conveience or not?
Secondly I think i have to use svg animation bcz throough i tag i am oly able to fly twitter bird only...github and linked in ball are through svg animations. So can I use svg for all icons?

**Comment by smaranjitghose** [comment]
> Sir I want to ask few questions that:
> is it necessary to keep medium, kaggle icons etc? Can we change them for our conveience or not?
> Secondly I think i have to use svg animation bcz throough i tag i am oly able to fly twitter bird only...github and linked in ball are through svg animations. So can I use svg for all icons?

Sure. Feel free to use SVG animations

We are adding options for Kaggle, Medium, etc because this project is meant to be a generalized template for a wide variety of audience from different backgrounds. As per one's choice, one can comment or uncomment the related code later.

Don't worry, give PRs for one social media icon microanimation at a time

**Comment by Abhijay007** [comment]
@smaranjitghose sir, I did some changes to micro animations.

![micro-animations](https://user-images.githubusercontent.com/64387054/107847030-4e77be80-6e0e-11eb-842c-4761b44fffa4.gif)

can I work on this issue?

**Comment by anushbhatia** [comment]
This looks too main stream and not minimal try keeping it minimal with micor animations

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir, I did some changes to micro animations.
> 
> ![micro-animations](https://user-images.githubusercontent.com/64387054/107847030-4e77be80-6e0e-11eb-842c-4761b44fffa4.gif)
> 
> can I work on this issue?

Have a look at what I have suggested in the issue description and what you are producing!

Don't you think this looks absolutely weird?

**Comment by sherin527** [comment]
Sir, I want to try this out, could you assign me this task also.

**Comment by Abhijay007** [comment]
> Have a look at what I have suggested in the issue description and what you are producing!
> 
> If you were an HR and wanted to visit a candidate's portfolio, don't you think this looks absolutely weird?😅

ok @smaranjitghose sir I will try to improve this and try to work on a particular icon at a time.

**Comment by smaranjitghose** [comment]
> > Have a look at what I have suggested in the issue description and what you are producing!
> > If you were an HR and wanted to visit a candidate's portfolio, don't you think this looks absolutely weird?😅
> 
> ok @smaranjitghose sir I will try to improve this and try to work on a particular icon at a time.

No offense to you @Abhijay007 brother. It was an honest suggestion w.r.t to ui/ux

**Comment by smaranjitghose** [comment]
> Sir, I want to try this out, could you assign me this task also.

Assigned for 4 days

**Comment by Abhijay007** [comment]
@smaranjitghose sir I am done with Twitter SVG it looks like this. now

![twitter](https://user-images.githubusercontent.com/64387054/107873801-433e9480-6edb-11eb-9e59-d2b5bf0e34d1.gif)

but sir I am facing a problem now, that this Twitter SVG has a very big code.

![code](https://user-images.githubusercontent.com/64387054/107873839-83057c00-6edb-11eb-82c0-fd6c632c42bc.PNG)

now the problem I am facing is that this code does not look that good in the main file it reduces code readability.
I try to link SVG to an HTML document by using an image, object, SVG tag but that doesn't work.

I read some blogs and answers related to this on StackOverflow and w3schools but not able to find any optimized solution they also suggest using SVG directly on the page if you want to edit its CSS.

Sir, can you suggest me something related to this.

**Comment by Abhijay007** [comment]
I am also done with the micro animation GitHub icon.

**Comment by Abhijay007** [comment]
github one:

![github-icon](https://user-images.githubusercontent.com/64387054/107874407-9581b480-6edf-11eb-8f5d-34772c4124bb.gif)

**Comment by anushbhatia** [comment]
Keep the wings of the twitter bird blue don't make it mix of white and blue

**Comment by Abhijay007** [comment]
Ok sir I will keep those wings blue

**Comment by Abhijay007** [comment]
> Keep the wings of the twitter bird blue don't make it mix of white and blue

![bluw-wings](https://user-images.githubusercontent.com/64387054/107903152-741bd980-6f6e-11eb-8660-8e9be077648a.gif)


done with the changes @smaranjitghose and @anushbhatia Sir.

can I  open a PR for these two now?

**Comment by smaranjitghose** [comment]
> > Keep the wings of the twitter bird blue don't make it mix of white and blue
> 
> ![bluw-wings](https://user-images.githubusercontent.com/64387054/107903152-741bd980-6f6e-11eb-8660-8e9be077648a.gif)
> 
> done with the changes @smaranjitghose and @anushbhatia Sir.
> 
> can I open a PR for these two for now?

Definitely brother! Go ahead and give a PR.

Try to incorporate it in the footer icons too

**Comment by Abhijay007** [comment]
> Try to incorporate it in the footer icons too

@smaranjitghose Sir , footer section is also done:

![footer](https://user-images.githubusercontent.com/64387054/107983519-f39bbe00-6feb-11eb-904e-c88f3aef9127.gif)

**Comment by smaranjitghose** [comment]
> > Try to incorporate it in the footer icons too
> 
> @smaranjitghose Sir , footer section is also done:
> 
> ![footer](https://user-images.githubusercontent.com/64387054/107983519-f39bbe00-6feb-11eb-904e-c88f3aef9127.gif)

Fantastic give a PR please

**Comment by smaranjitghose** [comment]
Also, I hope that this was a nice learning experience for your @Abhijay007. @anushbhatia and I can be strict at times but the main motive is to ensure that all you get to learn something more useful.😊

**Comment by smaranjitghose** [comment]
> Sir, I want to try this out, could you assign me this task also.

You can take the dribble and medium icons if you wish

**Comment by Abhijay007** [comment]
> Also, I hope that this was a nice learning experience for your @Abhijay007. @anushbhatia and I can be strict at times but the main motive is to ensure that all you get to learn something more useful.😊

No problem 😄 @smaranjitghose sir I learned a lot about SVG manipulation using CSS during this PR. And I know as a mentor you always want contributors to learn and give their best 😊. 

if you don't point out my mistakes then maybe I am not able to do this task. It was a great learning experience.

**Comment by smaranjitghose** [comment]
@Abhijay007 you can continue with the LinkedIN (and additional Instagram Icon, keep the original colors) using [this](https://useanimations.com/) reference.   Do a CTRL+F on the reference website to look for the desired animation.

@anushbhatia  could you please give some suggestions for dribble(perhaps dribbling across the horizontal plane to distinguish it from LinkedIn), google scholar(perhaps similar to the facebook microanimation given above)?

**Comment by Abhijay007** [comment]
> @Abhijay007 you can continue with the LinkedIN (and additional Instagram Icon, keep the original colors) using [this](https://useanimations.com/) reference. Do a CTRL+F on the reference website to look for the desired animation. 

ok @smaranjitghose sir

**Comment by Abhijay007** [comment]
> @Abhijay007 you can continue with the LinkedIN (and additional Instagram Icon, keep the original colors) using [this](https://useanimations.com/) reference. Do a CTRL+F on the reference website to look for the desired animation.
> 
> @anushbhatia could you please give some suggestions for dribble(perhaps dribbling across the horizontal plane to distinguish it from LinkedIn), google scholar(perhaps similar to the facebook microanimation given above)?

done with Instagram icon:

![instagram1](https://user-images.githubusercontent.com/64387054/108083192-d53fcc00-7098-11eb-9d07-5a85e1e73992.gif)

![instagram2](https://user-images.githubusercontent.com/64387054/108083222-dec93400-7098-11eb-98ca-27c669c481d6.gif)

@smaranjitghose sir out of these two which one you prefer more? should I include that outer ring?

**Comment by smaranjitghose** [comment]
The first one is a sure no!

As I had pointed out earlier, boundaries around social media icons don't look good

For the second one, make sure the motion starts with something(I mean it should not become blank on hover and then appear)

Something I can suggest is not doing much with the square(perhaps lifting it a bit) and filling the internal circle with pink to give an effect similar to the shutter closing of a dslr

**Comment by smaranjitghose** [comment]
For the LinkedIn one take direct reference


Check out the icon of Google Scholar and Kaggle (and use the Facebook reference for them)

**Comment by Abhijay007** [comment]
Ok sir

**Comment by smaranjitghose** [comment]
@Abhijay007 checkout [AnimeJS](https://animejs.com/documentation/#svgAttr) and let me know if it is relevant to your task in terms of better readability and ease of use

**Comment by Abhijay007** [comment]
> @Abhijay007 checkout [AnimeJS](https://animejs.com/documentation/#svgAttr) and let me know if it is relevant to your task in terms of better readability and ease of use

ok @smaranjitghose sir I will try to convert all SVG in this format after I am done with all the icons micro animations.

**Comment by Abhijay007** [comment]
sir @smaranjitghose sir out of these two which one you prefer more? 

![instagram1](https://user-images.githubusercontent.com/64387054/108155484-f938f700-7104-11eb-90b6-9227db69bfc4.gif)

![insta2](https://user-images.githubusercontent.com/64387054/108155533-140b6b80-7105-11eb-9ea6-5ac8e1a6fe17.gif)

do I need to change something?

**Comment by Abhijay007** [comment]
LinkedIn animation is also done, sir:

![linkedin1](https://user-images.githubusercontent.com/64387054/108186790-d114bc80-7133-11eb-9267-3f77cec36b42.gif)

![linkedin2](https://user-images.githubusercontent.com/64387054/108186809-d4a84380-7133-11eb-839e-ad43efba5aee.gif)

@smaranjitghose sir out of these two which one you want me to implement?

**Comment by achalesh27022003** [comment]
@Abhijay007  you are doing good work bro. 
I just go

**Comment by achalesh27022003** [comment]
got twitter and linked in animation though😅

**Comment by smaranjitghose** [comment]
> LinkedIn animation is also done, sir:
> 
> ![linkedin1](https://user-images.githubusercontent.com/64387054/108186790-d114bc80-7133-11eb-9267-3f77cec36b42.gif)
> 
> ![linkedin2](https://user-images.githubusercontent.com/64387054/108186809-d4a84380-7133-11eb-839e-ad43efba5aee.gif)
> 
> @smaranjitghose sir out of these two which one you want me to implement?
> 
> 

LinkedIn go for the second one

Change it in footer too

**Comment by anushbhatia** [comment]
Don't fill the internal colour for it. Keep the logo for Instagram is same. On hover make that click animation. As soon as animation is over keep the logo same.

**Comment by Abhijay007** [comment]
> Don't fill the internal colour for it. Keep the logo for Instagram is same. On hover make that click animation. As soon as animation is over keep the logo same.

internal color for Linkedin icon?

**Comment by Abhijay007** [comment]
@smaranjitghose , @anushbhatia sir done with the changes.

![animations](https://user-images.githubusercontent.com/64387054/108202663-7be2a600-7147-11eb-9353-12c575ce6c8c.gif)

**Comment by Abhijay007** [comment]
@anushbhatia @smaranjitghose sir done with all the changes take a look

![changes](https://user-images.githubusercontent.com/64387054/108206804-ecd88c80-714c-11eb-9d59-36811336429d.gif)

**Comment by smaranjitghose** [comment]
> @anushbhatia @smaranjitghose sir done with all the changes take a look
> 
> ![changes](https://user-images.githubusercontent.com/64387054/108206804-ecd88c80-714c-11eb-9d59-36811336429d.gif)

Pitch Perfect!

For the instagram, one last tweak would be if we could continuously have the shutter closing and opening with a small interval

**Comment by Abhijay007** [comment]
> For the instagram, one last tweak would be if we could continuously have the shutter closing and opening with a small interval

sir, do you mean without hover?
means automated?

**Comment by Abhijay007** [comment]
> For the instagram, one last tweak would be if we could continuously have the shutter closing and opening with a small interval

@smaranjitghose sir done with the changes take a look:

![insta](https://user-images.githubusercontent.com/64387054/108320939-78076000-71e9-11eb-8a31-6060ca52a052.gif)

sir, can I open a PR for these two now?

**Comment by smaranjitghose** [comment]
Yes, it's perfect!

Replace the medium icon in the footer with Instagram.

Comment elaborately too!

**Comment by Abhijay007** [comment]
> Yes, it's perfect!
> 
> Replace the medium icon in the footer with Instagram.
> 
> Comment elaborately too!

@smaranjitghose sir done with the changes take a look 

![icons](https://user-images.githubusercontent.com/64387054/108401426-571f2900-7242-11eb-83d0-13bcd6365eb2.gif)

can I open a PR for these two for now?

**Comment by Abhijay007** [comment]
@smaranjitghose sir can you please share some references for the Kaggle icon, I have something in mind for the dribble icon but don't know about Kaggle much.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir can you please share some references for the Kaggle icon, I have something in mind for the dribble icon but don't know about Kaggle much.

Do it similar to the Facebook micro animation reference I gave above

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir done with the dribble animation:
![dribbble](https://user-images.githubusercontent.com/64387054/108627781-52928480-747d-11eb-952a-4f93cdb13f02.gif)

do you want to me change something?

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir code forces also done:

![codeforces](https://user-images.githubusercontent.com/64387054/108639646-a4f29600-74bb-11eb-8882-56cea5954c97.gif)

can I open a PR for these two for now?

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia sir code forces also done:
> 
> ![codeforces](https://user-images.githubusercontent.com/64387054/108639646-a4f29600-74bb-11eb-8882-56cea5954c97.gif)
> 
> can I open a PR for these two for now?

Definitely brother. Please give a PR.

Proceed with medium as per their official animation. Make kaggle and google scholar as per the facebook animation in the reference.

**Comment by Abhijay007** [comment]
> > @smaranjitghose @anushbhatia sir code forces also done:
> > ![codeforces](https://user-images.githubusercontent.com/64387054/108639646-a4f29600-74bb-11eb-8882-56cea5954c97.gif)
> > can I open a PR for these two for now?
> 
> Definitely brother. Please give a PR.
> 
> Proceed with medium as per their official animation. Make kaggle and google scholar as per the facebook animation in the reference.

ok @smaranjitghose sir I will open a PR for these two now and try to complete medium, kaggel, and google scholar by tomorrow

**Comment by smaranjitghose** [comment]
> 
> 
> > > @smaranjitghose @anushbhatia sir code forces also done:
> > > ![codeforces](https://user-images.githubusercontent.com/64387054/108639646-a4f29600-74bb-11eb-8882-56cea5954c97.gif)
> > > can I open a PR for these two for now?
> > 
> > 
> > Definitely brother. Please give a PR.
> > Proceed with medium as per their official animation. Make kaggle and google scholar as per the facebook animation in the reference.
> 
> ok @smaranjitghose sir I will open a PR for these two now and try to complete medium, kaggel, and google scholar by tomorrow

Cool

**Comment by smaranjitghose** [comment]
@Abhijay007 
Since today is the last day of SWOC, try to wrap this up.

### Once more suggestion:

In a practical scenario, no one will ever use all the micronanimations, so you can keep the css intact in the home.css and style.css

and in the html file comment out the code and add additional code like

```
<!--
--------------------------------------
MICROANIMATION FOR TWITTER
--------------------------------------
-->
```

Additionally, in the footer try to keep LinkedIn, GitHub, Kaggle, Twitter

**Comment by Abhijay007** [comment]
> @Abhijay007
> Since today is the last day of SWOC, try to wrap this up.

@smaranjitghose sir I will try my best.

**Comment by Abhijay007** [comment]
> ### Once more suggestion:
> In a practical scenario, no one will ever use all the micronanimations, so you can keep the css intact in the home.css and style.css
> 
> and in the html file comment out the code and add additional code like
> 
> ```
> 
> ```

ok sir I will comment out code like this.
