### ISSUE TITLE
Active page in navbar can be in different colour

### ISSUE THREAD

**Issue by akshay1027** [smaranjitghose/awesome-portfolio-websites#539]
Active page in the navbar section can be in a different colour to differentiate the page that is currently active from the other pages that are not active.

**Comment by smaranjitghose** [comment]
> Active page in the navbar section can be in a different colour to differentiate the page that is currently active from the other pages that are not active.

Definitely!

@anushbhatia could you please discuss the color scheme for this change as you have an in-depth background in ui/ux in comparison to mine

**Comment by akshay1027** [comment]
@anushbhatia sir, let me know as well 🙌🏻

**Comment by akshay1027** [comment]
> > Active page in the navbar section can be in a different colour to differentiate the page that is currently active from the other pages that are not active.
> 
> Definitely!
> 
> @anushbhatia could you please discuss the color scheme for this change as you have an in-depth background in ui/ux in comparison to mine

Sorry I closed by mistake, @anushbhatia sir, let me know as well 🙌🏻!

**Comment by anushbhatia** [comment]
https://codepad.co/snippet/minimal-navbar
something minimal and simple like this also use the colour schemes given in the #487

**Comment by jainh6148** [comment]
Hi, I would like to contribute to this project

**Comment by smaranjitghose** [comment]
> Hi, I would like to contribute to this project

Please proceed as per @anushbhatia 's suggestions in the comment above

**Comment by jainh6148** [comment]
Hi Smaranjitghose, I have resolved the issue but while committing the changes I undo the commits and now it's showing this  (screenshot I have attached here). Can you please help me resolve this issue?
![Screenshot (227)](https://user-images.githubusercontent.com/77544921/108058058-7a4aac80-7079-11eb-97e5-d482cf1d37b5.png)

**Comment by smaranjitghose** [comment]
> Hi Smaranjitghose, I have resolved the issue but while committing the changes I undo the commits and now it's showing this (screenshot I have attached here). Can you please help me resolve this issue?
> ![Screenshot (227)](https://user-images.githubusercontent.com/77544921/108058058-7a4aac80-7079-11eb-97e5-d482cf1d37b5.png)

- Set an upstream to my repo
```
git remote add upstream https://github.com/smaranjitghose/awesome-portfolio-websites.git
```
- Pull the changes from my master
```
git pull upstream master
```
- Check out a new branch from master say x
```
git checkout -b x
```
- Now merge the x branch and the branch you have worked on
```
git checkout jainh6148
git merge x
```
- You might some conflicts on style.css or main.js files in which you have been working on. You would be aware of which change to keep. The rest of the merging would take recursively 
- push the changes to github
```
git push origin jainh6148
```
- Now, click on the pull request button, compare it with  my ``master``, give appropriate title and description (possibly an additional clip/screenshot of the output of the change too)


## Bonus:
Google how to do rebase and make a squash commit

**Comment by jatinjain001** [comment]
I want to take this issue Kindly assign it to me and please add the tag  DWOC too
