### ISSUE TITLE
"Grab My resume" section on the home page 

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/awesome-portfolio-websites#543]
feature-request: Add an interactive resume section on the home page: 

***after implementation it will look like this***

![resume section](https://user-images.githubusercontent.com/64387054/107114116-794f9900-6889-11eb-934a-348ac4a9d632.gif)

I already implemented it once but I don't know why it is not showing on the currently deployed link of the website in the main repo.

**Comment by smaranjitghose** [comment]
> feature-request: Add an interactive resume section on the home page:
> 
> _**after implementation it will look like this**_
> 
> ![resume section](https://user-images.githubusercontent.com/64387054/107114116-794f9900-6889-11eb-934a-348ac4a9d632.gif)
> 
> I already implemented it once but I don't know why it is not showing on the currently deployed link of the website in the main repo.

We are planning to put it somewhere else perhaps in a separate contact page and have hence removed it for the time being
