### ISSUE TITLE
Feature request: Add "back to top" button

### ISSUE THREAD

**Issue by Abhijay007** [smaranjitghose/awesome-portfolio-websites#545]
Add "back to top" button in the different pages of the site especially in the experience and education section because user need to scroll back a bit more in these sections.

**Comment by AmeyaJain-25** [comment]
I would like to work on this issue under SWoC.
Please assign it to me

**Comment by smaranjitghose** [comment]
We are planning to integrate a chatbot that's why the "toTop" button is scrapped from the dev cycle for now
