### ISSUE TITLE
Preloader Animation for each page

### ISSUE THREAD

**Issue by omrajsharma** [smaranjitghose/awesome-portfolio-websites#550]
Preloader for each page before any page is completely loads
![preloader](https://user-images.githubusercontent.com/60071210/107464957-4eb25880-6b87-11eb-92b6-5797f941357f.gif)

**Comment by omrajsharma** [comment]
Can I work work upon this issue. After resolving this issue the user experience will be much better.

**Comment by smaranjitghose** [comment]
Check out #517
