### ISSUE TITLE
Removing GIFs from README file

### ISSUE THREAD

**Issue by kmryashasvi** [smaranjitghose/awesome-portfolio-websites#561]
As we know that,
A readme file lets you know about the repo as well as attracting contributors to contribute in it.
But, readme file included in your repo is loosing grip in both of the roles, because of the GIFs mentioned in it,
They create an informal image of your repo, which is not good,
In order to maintain formality of your readme file,
Let me remove the gifs and insert some catching sentences instead.
Look at your repo, you will also feel, there is a need to remove them
This is regarding crosswoc,

**Comment by smaranjitghose** [comment]
The entire purpose of gifs/memes in today's presentation is to catch attention. Unless there is any swearing or inappropriate stuff, going formal with project descriptions(other than documentation itself) is a fool's array for me. Ofcourse we can go with illustrations and clips but that is too much time consuming w.r.t README.

And please refrain from words like "image of the repo",  "loosing grip on both sides" if you wish to contribute. I seriously do not care about these things. If someone can read code or the instructions to use it, that's all. I don't worry much about people-pleasing w.r.t projects. As far as contributors are concerned, the projects are open for contribution for anyone who wishes to do so. Definitely, we can have stuff like more detailed Contributing guidelines, tests, environment configs to make things easier for a great chunk of the people who identify as newbies to a stack but there is absolutely no need to attract contributors by following certain writing styles.
