### ISSUE TITLE
Animate the SVG on the top of Education Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#567]
- You are welcome to incorporate new SVGs. Feel free to check the illustrations in the custom illustrations folder

- Try to come with something creative

[Sample](https://codepen.io/brunoalves/pen/NWGRxKR)

- Do not just move random components!

- For the animation itself, either write the svg animation from scratch or use [anime.js](https://animejs.com/documentation/#svgAttr)

**Comment by Abhijay007** [comment]
I want to work on this

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir can I implement something like [this](https://codepen.io/konoanimation/pen/VRQvxP) for the education page I will change the color schema accordingly.

**Comment by Abhijay007** [comment]
> @smaranjitghose @anushbhatia sir can I implement something like [this](https://codepen.io/konoanimation/pen/VRQvxP) for the education page I will change the color schema accordingly.

checkout [this](https://codepen.io/JoseRosario/pen/wpxGeE) one also

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir can use something like [this](https://codepen.io/uiswarup/pen/MWWNOjo) in this project as we have different pages in this template projects, education, experience, etc.

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir can I implement [this](https://codepen.io/uiswarup/pen/MWWNOjo) on the education page and [this](https://codepen.io/konoanimation/pen/VRQvxP) one on the research page? I will change the color scheme accordingly

**Comment by anushbhatia** [comment]
> > @smaranjitghose @anushbhatia sir can I implement something like [this](https://codepen.io/konoanimation/pen/VRQvxP) for the education page I will change the color schema accordingly.
> 
> checkout [this](https://codepen.io/JoseRosario/pen/wpxGeE) one also

Make it look like a college student instead of a school kid

**Comment by anushbhatia** [comment]
> @smaranjitghose @anushbhatia sir can use something like [this](https://codepen.io/uiswarup/pen/MWWNOjo) in this project as we have different pages in this template like projects, education, experience, etc.

You can use this as an alternative in education page also prevent moving leaves present at the bottom that's too much.

**Comment by anushbhatia** [comment]
If you are using undraw everywhere use that in all pages don't mix and match different micro animations

**Comment by anushbhatia** [comment]
> @smaranjitghose @anushbhatia sir can I implement [this](https://codepen.io/uiswarup/pen/MWWNOjo) on the education page and [this](https://codepen.io/konoanimation/pen/VRQvxP) one on the research page? I will change the color scheme accordingly

Keep the beard black we are not that old.

**Comment by Abhijay007** [comment]
> > @smaranjitghose @anushbhatia sir can I implement [this](https://codepen.io/uiswarup/pen/MWWNOjo) on the education page and [this](https://codepen.io/konoanimation/pen/VRQvxP) one on the research page? I will change the color scheme accordingly
> 
> Keep the beard black we are not that old.

😄 ok sir

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir done with the SVG animation for the education page have a look:

![education page (2)](https://user-images.githubusercontent.com/64387054/109405011-ee4a5600-7991-11eb-90e5-30cc59c0bdee.gif)

can I open a PR for this?

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia sir done with the SVG animation for the education page have a look:
> 
> ![education page (2)](https://user-images.githubusercontent.com/64387054/109405011-ee4a5600-7991-11eb-90e5-30cc59c0bdee.gif)
> 
> can I open a PR for this?

Yes, please

**Comment by smaranjitghose** [comment]
This issue is resolved. @Abhijay007 if you are continuing with the other micronanimations (for experience, project and research) do comment on the respective issues as well before going ahead with a PR.

And nice work man!😍

**Comment by Abhijay007** [comment]
> This issue is resolved. @Abhijay007 if you are continuing with the other micronanimations (for experience, project and research) do comment on the respective issues as well before going ahead with a PR.
> 
> And nice work man!😍

ok sir I will soon present some micro animations for the research and project page and thanks a lot sir for your appreciation 😄
