### ISSUE TITLE
Animate the SVG at the top of Project Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#574]
## Sample:
![sample](https://user-images.githubusercontent.com/46641503/108130137-27064780-70d5-11eb-920b-b1d398d9cb50.gif)

*Credits lie with [original creators](https://www.hellomonday.com/about)*

## Specifications

- Please do not use the above reference directly. It is given for giving a clear idea of what can be done

- We expect you to modify some open source illustration to achieve this

- In your PR description, do not forget to add a reference to the place from where you took it

- openpeeps has some great stuff for our use case

- Another alternative is undraw.co

- For the animation itself, either write the svg animation from scratch or use [anime.js](https://animejs.com/documentation/#svgAttr)

**Comment by Abhijay007** [comment]
can I work on this?

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir can we implement something like [this](https://codepen.io/khadkamhn/pen/OVwONo). we can edit those social links to major projects.

what are your thought on this?

it is just a suggestion 😅

**Comment by anushbhatia** [comment]
This won't look good as this is not appealing and we can do a flip animation as we are going for simple and minor animation just like the one attached above. this animation will be too much

**Comment by Abhijay007** [comment]
> This won't look good as this is not appealing and we can do a flip animation as we are going for simple and minor animation just like the one attached above. this animation will be too much

ok sir I will try to implement something else. 
thanks for your review 😄

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir can implement something like [this](https://codepen.io/antipasjiajia/pen/QVQaYK). 
I will change the background and color scheme according to the current(on the website) illustration.

**Comment by anushbhatia** [comment]
Yes, go ahead remove the rating thing from it.

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir done with the SVG animation for the research page have a look:

![research-page](https://user-images.githubusercontent.com/64387054/109408417-9cb0c400-79af-11eb-822f-b3676b876224.gif)

can I open a PR for this?

**Comment by smaranjitghose** [comment]
Sure.

Put the comments too as suggested

**Comment by Abhijay007** [comment]
sir do you mean comment like this 

```
  
 /*
---------------------------
      SVG ANIMATION
---------------------------
*/
  
```

**Comment by Abhijay007** [comment]
> It would be even better if you could load this dynamically from research.js as I suggested in your last pr (if you do that, give a separate PR for that itself)

or sir I will try to shift these SVG codebases on js files for all pages but for now can I make a pr with HTML and CSS format?

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir can I implement something like [this](https://codepen.io/konoanimation/pen/GeLPwx) on the project or experience page don't worry about background and color I will change them according to the website color scheme.

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir, done with the SVG animation for the project page have a look:

![project-page](https://user-images.githubusercontent.com/64387054/109416352-afdd8700-79e3-11eb-8cc0-95ee3f58eac3.gif)

can I open a PR for this?

**Comment by smaranjitghose** [comment]
Keep the color scheme of the sign animations constant. Rest looks fine

**Comment by smaranjitghose** [comment]
> sir do you mean comment like this 
> 
> ```
>   
>  /*
> ---------------------------
>       SVG ANIMATION
> ---------------------------
> */
>   
> ```

Yes

**Comment by Abhijay007** [comment]
> Keep the color scheme of the sign animations constant. Rest looks fine

sir, can you please explain a bit in detail?

**Comment by Abhijay007** [comment]
can I change that purple floating part to green?

**Comment by Abhijay007** [comment]
![changes](https://user-images.githubusercontent.com/64387054/109417143-57f54f00-79e8-11eb-8a34-ae23f6c91cec.PNG)

like this?

**Comment by Abhijay007** [comment]
> ![changes](https://user-images.githubusercontent.com/64387054/109417143-57f54f00-79e8-11eb-8a34-ae23f6c91cec.PNG)
> 
> like this?

can I open a PR now?

**Comment by smaranjitghose** [comment]
> can I change that purple floating part to green?
> 
> 

Make it in a different shade of purple as compared to the two people sitting

**Comment by Abhijay007** [comment]
ok sir

**Comment by Abhijay007** [comment]
![changes](https://user-images.githubusercontent.com/64387054/109417372-6728cc80-79e9-11eb-86cb-6edc94496f1e.PNG)

@smaranjitghose is it looking fine now?

**Comment by smaranjitghose** [comment]
> ![changes](https://user-images.githubusercontent.com/64387054/109417372-6728cc80-79e9-11eb-86cb-6edc94496f1e.PNG)
> 
> @smaranjitghose is it looking fine now?
> 

Yup

**Comment by Abhijay007** [comment]
@smaranjitghose sir can you merge this (#616) first or I make a separate branch for it?

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir can you merge this (#616) first or I make a separate branch for it?

I will merge it in a while. Give me 5 min

**Comment by Abhijay007** [comment]
Ok sir

**Comment by smaranjitghose** [comment]
Nicely done @Abhijay007. The latest PR closes this issue. Try to wrap up the experience page SVG animation issue too

**Comment by Abhijay007** [comment]
> Nicely done @Abhijay007. The latest PR closes this issue. Try to wrap up the experience page SVG animation issue too

I will try my best sir!!

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir can I try something from these two [this](https://codepen.io/GeoffreyCrofte/pen/YzyooLw) and 
[this](https://codepen.io/CrunchySquirell/pen/KYzYKQ) for experience page?

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia sir can I try something from these two [this](https://codepen.io/GeoffreyCrofte/pen/YzyooLw) and 
> [this](https://codepen.io/CrunchySquirell/pen/KYzYKQ) for experience page?

Go for the one with the man sitting in formals

Try to alter it a little bit
