### ISSUE TITLE
Dynamic Favicon

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#576]
**Your creativity is the upper limit here**. 
- However, do not change the favicon for every mouse click 🙏. 
- 404 page can have a different favicon
- Dark mode and light mode's can have different favicons

References:

- [GeeksforGeeks article](https://www.geeksforgeeks.org/how-to-change-favicon-dynamically/)
- [Medium Blog](https://medium.com/@alperen.talaslioglu/building-dynamic-favicon-with-javascript-223ad7999661)

**Comment by himanshu007-creator** [comment]
> **Your creativity is the upper limit here**.
> 
> * However, do not change the favicon for every mouse click 🙏.
> * 404 page can have a different favicon
> * Dark mode and light mode's can have different favicons
> 
> References:
> 
> * [GeeksforGeeks article](https://www.geeksforgeeks.org/how-to-change-favicon-dynamically/)
> * [Medium Blog](https://medium.com/@alperen.talaslioglu/building-dynamic-favicon-with-javascript-223ad7999661)

sir i would love to work on this issue, But where i have to upload my code. It just have to be a page with switching button or o have to use this favicon in an existing page here?

**Comment by smaranjitghose** [comment]
> > **Your creativity is the upper limit here**.
> > 
> > * However, do not change the favicon for every mouse click 🙏.
> > * 404 page can have a different favicon
> > * Dark mode and light mode's can have different favicons
> > 
> > References:
> > 
> > * [GeeksforGeeks article](https://www.geeksforgeeks.org/how-to-change-favicon-dynamically/)
> > * [Medium Blog](https://medium.com/@alperen.talaslioglu/building-dynamic-favicon-with-javascript-223ad7999661)
> 
> sir i would love to work on this issue, But where i have to upload my code. It just have to be a page with switching button or o have to use this favicon in an existing page here?

This is for the entire website

**Comment by Harshal0902** [comment]
@anushbhatia can you please assign this issue to me?
I would like to work on this issue.

**Comment by omrajsharma** [comment]
I would like to work on this issue. @anushbhatia can you please assign this issue to me.

**Comment by Harshal0902** [comment]
There should be Dynamic Favicon for 404 page and Dark mode and light mode page right?

**Comment by dollyjain51099** [comment]
I would like to work on this issue, @smaranjitghose kindly assign it to me!

**Comment by Aniket118** [comment]
I would would like to work on this issue, @smaranjitghose  can assign this to me!
