### ISSUE TITLE
Dynamic Page Title

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#577]
[Reference](https://medium.com/@alperen.talaslioglu/changing-page-title-dynamically-when-user-changes-tab-5d372554377c)

The above reference is well detailed. Please go through it carefully if you wish to contribute to this.

**Comment by ShivangiRai1310** [comment]
Hii, would like to work on this issue under SWOC and DWOC.

**Comment by jatinjain001** [comment]
I would like to contribute in this please assign it to me

**Comment by Sloth-Panda** [comment]
Can I work on this?

**Comment by jatinjain001** [comment]
Why should dynamic change in title even it is already changing title when we navigate through different pages, and there is not any type of dynamic behaviour in this website.. Please explain it to me.

**Comment by omrajsharma** [comment]
can i work on this issue.

**Comment by jatinjain001** [comment]
Okay.
