### ISSUE TITLE
Bid Adieu Materialize 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#578]
- *Carefully* remove all materialize related code from the project (including the unused calls in the HTML files and the js and css files corresponding to the materialize)
- Double-check that you don't mess up the current working of the project before giving a PR

**Comment by souravseal99** [comment]
Hi @smaranjitghose, I want to work on this.

**Comment by smaranjitghose** [comment]
> Hi @smaranjitghose, I want to work on this.

Assigned for 2 days
