### ISSUE TITLE
Bottom to Top Button

### ISSUE THREAD

**Issue by achalesh27022003** [smaranjitghose/awesome-portfolio-websites#583]
Sometimes we got tired of scrolling up so long so there is feature I want to add @smaranjitghose  sir i.e  bottom to top button.
[Reference](https://www.awesomescreenshot.com/video/2798113?key=4ed189d87eee60c97e4614c5cc8207b6)
![iss1](https://user-images.githubusercontent.com/57138750/108351542-ab5ae680-720b-11eb-8657-e848338128aa.png)
Please assign me this issue under DWoC.

**Comment by smaranjitghose** [comment]
We would have a chatbot integration soon, hence this is not required for now
