### ISSUE TITLE
 Animation in Navigation Bar

### ISSUE THREAD

**Issue by achalesh27022003** [smaranjitghose/awesome-portfolio-websites#586]
Nav bar itself is another important segment of any website. Nav bar should have some hover animation so that it makes user attractive. I want to add this feature in this manner under **DWoC**  @smaranjitghose  sir.

https://user-images.githubusercontent.com/57138750/108500189-6602eb80-72d5-11eb-9163-b7978e1ceb31.mp4
or
[Reference](https://www.awesomescreenshot.com/video/2812993?key=9930d72e074427b4a5339878e9e5a498)
Please assign me this issue under **DWoC**.

**Comment by smaranjitghose** [comment]
We already have an on-hover animation for nav bar
