### ISSUE TITLE
Project Card bug

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#598]
Currently, the GitHub and desktop icons are hidden in this so we need to resolve this on click they should be visible.
https://user-images.githubusercontent.com/40017559/108893462-1f93f080-7637-11eb-9dca-bb2233bb66b9.png

**Comment by Abhijay007** [comment]
can I work on this ?

**Comment by omrajsharma** [comment]
I would like to work on this

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir, done with the changes.

![PR-projects icons](https://user-images.githubusercontent.com/64387054/109022322-b917dc80-76e1-11eb-9059-c1a325a057fe.gif).

works fine for all screen sizes.

can I open a PR for this? do I need to change something?

sir but can you please review these PRs (#599  & #600 ) once because if I try to open a PR now then my previous commits will also appear in that PR and I think that is not a good coding practice that may affect the commit history of the project.

**Comment by smaranjitghose** [comment]
> 
> 
> @smaranjitghose @anushbhatia sir, done with the changes.
> 
> ![PR-projects icons](https://user-images.githubusercontent.com/64387054/109022322-b917dc80-76e1-11eb-9059-c1a325a057fe.gif).
> 
> works fine for all screen sizes.
> 
> can I open a PR for this? do I need to change something?
> 
> sir but can you please review these PRs (#599 & #600 ) once because if I try to open a PR now then my previous commits will also appear in that PR and I think that is not a good coding practice that may affect the commit history of the project.

@Abhijay007  brother, the github and preview buttons should be (atleast logically a line) below the space where the tags end and not in the same line

**Comment by smaranjitghose** [comment]
> 
> 
> > @smaranjitghose @anushbhatia sir, done with the changes.
> > ![PR-projects icons](https://user-images.githubusercontent.com/64387054/109022322-b917dc80-76e1-11eb-9059-c1a325a057fe.gif).
> > works fine for all screen sizes.
> > can I open a PR for this? do I need to change something?
> > sir but can you please review these PRs (#599 & #600 ) once because if I try to open a PR now then my previous commits will also appear in that PR and I think that is not a good coding practice that may affect the commit history of the project.
> 
> @Abhijay007 brother, the github and preview buttons should be (atleast logically a line) below the space where the tags end and not in the same line

Also, in mobile view, the onhover effect is really weird.

There is too much space between the heading and the tags

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia  sir done with the changes:

***desktop-view***
![desktop-view](https://user-images.githubusercontent.com/64387054/109222940-f5c9fd80-77df-11eb-90a2-7b3cfaae98f2.gif)

***mobile-view***
![mobile-view](https://user-images.githubusercontent.com/64387054/109223494-a6380180-77e0-11eb-8035-ec4079a4db17.gif)

do I need to change something?  

can I open a PR for this?

**Comment by anushbhatia** [comment]
Move it on the bottom right near the tile and rest everything is fine. Give the PR ASAP.

**Comment by Abhijay007** [comment]
Ok sir

**Comment by Abhijay007** [comment]
> Move it on the bottom right near the tile and rest everything is fine. Give the PR ASAP.

@smaranjitghose @anushbhatia sir done with the changes:

![project-bug](https://user-images.githubusercontent.com/64387054/109399730-93e9cf00-796a-11eb-8ff1-0a4b4cd408d5.gif)

**Comment by smaranjitghose** [comment]
> > Move it on the bottom right near the tile and rest everything is fine. Give the PR ASAP.
> 
> @smaranjitghose @anushbhatia sir done with the changes:
> 
> ![project-bug](https://user-images.githubusercontent.com/64387054/109399730-93e9cf00-796a-11eb-8ff1-0a4b4cd408d5.gif)
> 
> do I need to change something?
> 
> can I open a PR now?

"Bottom-most" right

**Comment by Abhijay007** [comment]
Ok sir

**Comment by Abhijay007** [comment]
> "Bottom-most" right


@smaranjitghose @anushbhatia  sir done with the changes sir 

![project-bug-changes](https://user-images.githubusercontent.com/64387054/109401815-e29d6600-7976-11eb-9764-f4fa0ab60180.gif)

is this looks fine now? do I need to change something? 

can I open a PR now?

**Comment by smaranjitghose** [comment]
> > "Bottom-most" right
> 
> @smaranjitghose @anushbhatia sir done with the changes sir
> 
> ![project-bug-changes](https://user-images.githubusercontent.com/64387054/109401815-e29d6600-7976-11eb-9764-f4fa0ab60180.gif)
> 
> is this looks fine now? do I need to change something?
> 
> can I open a PR now?

Yes

**Comment by Abhijay007** [comment]
Ok sir
