### ISSUE TITLE
Custom Pre-Loader

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#612]
Combine the following 

- [Reference 1](https://codepen.io/arkwis/pen/chnop)
- [Reference 2](https://codepen.io/Maskedman99/pen/YzPvrgN)

^^ For reference 2, instead of the nucleus at the center, try to have a brain outline so that we can make the animation depict a neural network [OPTIONAL}

- Follow the color palette
- The text should be "John Doe" 
- Document the code clearly so that anyone can change it as per their names

**Comment by sparshsharma2510** [comment]
@smaranjitghose  can you please explain a bit more on how are you thinking to combine the two references?

**Comment by smaranjitghose** [comment]
The nucleus animation would be on the top
The text animation below it

**Comment by sparshsharma2510** [comment]
I would like to work on it. Kindly assign it to me if possible.

**Comment by sparshsharma2510** [comment]
@smaranjitghose I can't think of a way out to replace the SVG with an actual text i.e. people won't be able to change it according to their names because the animation rolls on SVG paths. Can you please help me out?
