### ISSUE TITLE
Home Page Spacing Bug (responsivness)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#615]
## Expected Behaviour for all screens

![home_movb](https://user-images.githubusercontent.com/46641503/109406936-feb6fc80-79a2-11eb-8716-25cebfa664c9.png)

## Current Behaviour in Web View

![home_web](https://user-images.githubusercontent.com/46641503/109406941-0d051880-79a3-11eb-9833-0a64d13beaf7.png)

**Comment by Abhijay007** [comment]
@smaranjitghose sir can I work on this

**Comment by smaranjitghose** [comment]
Yes

**Comment by Abhijay007** [comment]
@smaranjitghose @anushbhatia sir, done with the changes have a look:

![home-page-bug](https://user-images.githubusercontent.com/64387054/109422908-7a489600-7a03-11eb-988a-3991497bfb1e.gif).

I made it responsive (removed unnecessary space) for very possible device.

can I open a PR for this now?

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia sir, done with the changes have a look:
> 
> ![home-page-bug](https://user-images.githubusercontent.com/64387054/109422908-7a489600-7a03-11eb-988a-3991497bfb1e.gif).
> 
> I made it responsive (removed unnecessary space) for every possible device.
> 
> can I open a PR for this now?

Yes
