### ISSUE TITLE
Major Bug in  Education, Expereince, Project Pages [Mobile View]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#619]
## Expected Behaviour: ( NOTICE THE PLACEMENT OF THE SVG AND THE TEXT)

![ressreach__page](https://user-images.githubusercontent.com/46641503/109419902-cbea2400-79f5-11eb-81ad-59f543133bf4.jpeg)

## ACTUAL Behaviour:

![Project_page_bug](https://user-images.githubusercontent.com/46641503/109419904-cee51480-79f5-11eb-9177-8a3c450610e6.jpeg)

![expereince_page_bug](https://user-images.githubusercontent.com/46641503/109419905-cf7dab00-79f5-11eb-95d5-2d71b3f821a7.jpeg)

![education_page_bug](https://user-images.githubusercontent.com/46641503/109419907-cf7dab00-79f5-11eb-8a8d-7354fd8080ee.jpeg)

Please fix this for the mobile view, do not mess up the web view

**Comment by Abhijay007** [comment]
@smaranjitghose  @anushbhatia sir, can I work on this?

**Comment by Abhijay007** [comment]
@smaranjitghose sir can I implement this on the experience page?

![expreince-page](https://user-images.githubusercontent.com/64387054/109428196-0070d680-7a1c-11eb-942b-3be58f890880.gif)

I know it has minimal animation as compare to other SVGs but I will try to improve this 😅

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir can I implement this on the experience page?
> 
> ![expreince-page](https://user-images.githubusercontent.com/64387054/109428196-0070d680-7a1c-11eb-942b-3be58f890880.gif)
> 
> I know it has minimal animation as compare to other SVGs but I will try to improve this 😅 

Yes

**Comment by jatinjain001** [comment]
Can  i work on this issue? If it is available , Let me know.

**Comment by Abhijay007** [comment]
> Can i work on this issue? If it is available , Let me know.

I was working on it but  @jatinjain001 you can work on it if you want. one thing I want to mention is that edit SVG viewports for solving this issue because if you try to edit margin then the alignment of botttom icons may get affected.

**Comment by ShubhamKumar5802** [comment]
Hello sir, I want to work on this, I am in learning period of open source contribution, please give me this opportunity

**Comment by smaranjitghose** [comment]
> Hello sir, I want to work on this, I am in learning period of open source contribution, please give me this opportunity

Assigned for 3 days

**Comment by ShubhamKumar5802** [comment]
Good morning sir,

I had worked on your project and applied for pull request, but the test
hasn't passed, but sorry to say, that was not my fault, you had used class
name that starts from captial letter, and that's way code is not passing
test

Please help me out....

**Comment by Rajdeep-99** [comment]
Hello Sir can I work on this issue?
