### ISSUE TITLE
How about a JS/HTML/CSS Linter?

### ISSUE THREAD

**Issue by vybhav72954** [smaranjitghose/awesome-portfolio-websites#620]
As this website is powered by JS, HTML and CSS, how about a linter for the same?

**Comment by anushbhatia** [comment]
Sure mention the linter's used for each of them. I would prefer Prettier instead of all these.

**Comment by vybhav72954** [comment]
My suggestions:

[HTML](https://github.com/htmlhint/HTMLHint)
[CSS](https://stylelint.io/)
[JS](https://eslint.org/)

I can make actions for these in case you find them interesting.

**Comment by anushbhatia** [comment]
okay great go ahead with them
