### ISSUE TITLE
Remove label of ended programs 

### ISSUE THREAD

**Issue by anjali1102** [smaranjitghose/awesome-portfolio-websites#629]
DWOC   has been ended on January 31, 2021. check here https://dwoc.io/
MWOC  has also ended on  Feb 28 2021. check here  https://mexili.org/winter_of_code/#/winter_of_code
SWoC    has ended on March 15, 2021. Check here https://swoc.tech/

currently, CWOC, GSSOC are ONLY GOING ON
@smaranjitghose urgent work

**Comment by smaranjitghose** [comment]
I believe we need to tweak the github action or the workflow. Do you want to give a PR for it?

**Comment by anjali1102** [comment]
Yes, I will do it

**Comment by noviicee** [comment]
Can I take this up if it is till open..? @smaranjitghose
