### ISSUE TITLE
The right hand side image In About Us section is very close to the text I want to reposition it in proper position

### ISSUE THREAD

**Issue by ambivert-sam** [smaranjitghose/awesome-portfolio-websites#633]
![Screenshot (171)](https://user-images.githubusercontent.com/74984661/115851497-a2250a80-a444-11eb-96d3-4f2ed9e1c972.png)

**Comment by ambivert-sam** [comment]
@Vishal-raj-1 & @urvashi-code1255 can I work on this issue please assign it to me

**Comment by smaranjitghose** [comment]
Wrong repo.

@Vishal-raj-1
