### ISSUE TITLE
Shift Codebase to ReactJS

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#640]
- Work exclusively on the branch `reactjs`
- Convert the codebase for each page from basic html, css, js to reactjs one page at a time:
    - [ ] Home Page
    - [ ] Experience Page
    - [ ] Project Page
    - [ ] Education Page
    - [ ] Research Page

**Comment by RiyaGupta89** [comment]
Can I work on this issue?

**Comment by Devansh2000Shaw** [comment]
Can I contribute on this under LGM SOC 21. Thank you.

**Comment by AB-san** [comment]
I also would like to work on this issue under lgm-soc

**Comment by smaranjitghose** [comment]
@RiyaGupta89  @Devansh2000Shaw  Please collaborate on this issue and take up one or more pages

**Comment by pragyamittal0** [comment]
Can I contribute on this under LGMSOC 21

**Comment by smaranjitghose** [comment]
> Can I contribute on this under LGMSOC 21

Assigned for 3 days
