### ISSUE TITLE
Change UI for Headings and Subheadings

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#641]
## Requirements:

[Key Reference](https://girlscriptboilerplate.netlify.app/index.html)

- Keeping in mind the color scheme (shades of blue and black) update all the headings in the website
- **Refrain from using inline or internal CSS as much as possible**
- Smartly split the headings into an even number of words 
Some Examples:

Experience ---> My Experience
Volunteership ---> Volunteering Initiatives.

Do not just copy-paste these suggestions. Come up with something simple yet meaningful

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by itsij** [comment]
I would like to work on this as LGM-SOC'21 Participant. Plz assign this to me.

**Comment by itsij** [comment]
Hey @smaranjitghose  
Plz have a look at these heading suggestions:

1. Experience -> My Experience
2. Volunteership -> Volunteering Initiatives / Volunteering roles/ Volunteering Experience
3. Mentorship -> Mentoring Initiatives
4. Projects -> Projects Corner
5. Research -> Research Work
6. Education(main heading) -> Educational Background
7. Education(sub heading) -> Schooling and College Background
8. MOOCS -> MOOC Certifications/ MOOC Credentials / Online Courses

Are they fine? 
Let me know which heading would u like to keep for the ones where i have written multiple suggestions.
Also, do let me know if u want me to change any heading...

**Comment by smaranjitghose** [comment]
1. ✅
2. Volunteering Endeavours
3. Mentorship Initiatives
4. My Projects
5. ✅
6. ✅
7. Formal Education
8. Online Accreditations

You may proceed with the above for changing the UI of the headings and Subheadings on the different pages and raise a PR @itsij

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

**Comment by smaranjitghose** [comment]
@itsij You have 2 more days for this, else it would be assigned to @nekkantimadhu

**Comment by itsij** [comment]
Yeah, I'm working on it.
Will report back to u with a PR soon.
