### ISSUE TITLE
Project Card UI change

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#643]
[Reference](https://www.lahautesociete.com/etudes-de-cas/)

- For this project, on hover the github and the web icons pop up on the bottom right. We do not need to have separate page open as given in the above reference.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Jagannath8** [comment]
I have pulled request for this issue but it is showing this error

Add Labels / Add Labels (pull_request_target) Failing after 5s — Add Labels

Please help me out @smaranjitghose  how to solve this

**Comment by smaranjitghose** [comment]
Ignore that check

**Comment by Manas502** [comment]
Hey, @smaranjitghose I might be able to do this but I am not able to understand the issue completely. Do you mind making a small video explaining the same? Maybe a screen recording?

**Comment by AKC068** [comment]
Hey,
I got it what that what to do according to reference.
@smaranjitghose can you please assign this to me ?

**Comment by smaranjitghose** [comment]
@AKC068 Assigned for 3 days

**Comment by AKC068** [comment]
https://user-images.githubusercontent.com/59188454/121587322-480ef180-ca52-11eb-8923-dcccd8a71631.mp4


I've done this till now. Let me know @smaranjitghose if it full fill your requirements. I've shown the responsiveness in every view.

**Comment by anushbhatia** [comment]
This doesn't look good with the UI

**Comment by AKC068** [comment]
What should I change in this according to you?
