### ISSUE TITLE
Mentorship Section UI Update in Experience Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#644]
### Some Specifications:

- Make the subheading `Community Involvement` from `Mentorship`
- Do not copy-paste the Boostrap carousel directly. Make a custom carousel appropriate to the theme
- Automatically change the image after 3 seconds *unless hovered*
- Keep in mind we have to display logos or pictures which are quite different from posters. Therefore, adjust the width accordingly (and make sure in a single laptop screen of 15.6", not more than 3 full cards are visible)
- Have minimal arrows for navigation on both sides
- Use placeholder images of any technical community initiative (to be placed inside Experience Page)
- **MUST BE MOBILE RESPONSIVE**
- The current cards are dynamically loaded from `expereince.js` and should continue to do so even after this change

**Comment by RiyaGupta89** [comment]
Can I work on this issue?

**Comment by smaranjitghose** [comment]
@RiyaGupta89 Since you would be already shifting the codebase to react, I would advice working on this once it is complete

**Comment by Salonee-Jain** [comment]
Can I work on this issue under LGM SOC

**Comment by smaranjitghose** [comment]
> Can I work on this issue under LGM SOC

Assigned for 3 days

**Comment by smaranjitghose** [comment]
Closed due to inactivity. To be continued in #748
