### ISSUE TITLE
Replace any or all usage of fontawesome icons with feathericons

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#645]

**Comment by Aiswarika** [comment]
Hey @smaranjitghose can you please assign me this issue?

**Comment by janvi01** [comment]
Can I work on this issue? @smaranjitghose

**Comment by kshitija-2001** [comment]
I am a member of LGM SOC
I would like to contribute to this issue. @smaranjitghose

**Comment by smaranjitghose** [comment]
@janvi01 has 1 more day, after that @kshitija-2001 can take over

**Comment by kshitija-2001** [comment]
Ok Thank you!

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

**Comment by Deep06-11** [comment]
I want to contribute to this issue under LGM SOC 21. Please assign it to me.
