### ISSUE TITLE
Add Textanimations

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#646]
[Reference](https://codepen.io/jh3y/pen/vzqVWa)

-  Use the block style for Headings Like "Education"

-  Use the perspective style for subheadings like "MOOC"

**Comment by Aiswarika** [comment]
@smaranjitghose Can you please assign me this issue? I will be working on it after the 10th as part of the contest.

**Comment by Aiswarika** [comment]
Is this animation fine?  @smaranjitghose 

https://user-images.githubusercontent.com/72227445/121044115-e2f99880-c7d2-11eb-8333-e956493d39c5.mp4

**Comment by smaranjitghose** [comment]
No. Please have a look at the issue description for the exact requirements. Make the headings bold as well to make them distinguishable from the rest of the text in the page

**Comment by Aiswarika** [comment]
Okay I will be working on it.

**Comment by anushbhatia** [comment]
This looks animation fantastic but it would better if the only happens when we hover on it. if we leave it then it should stay same.

**Comment by Jestin1702** [comment]
> This looks animation fantastic but it would better if the only happens when we hover on it. if we leave it then it should stay same.

This is an hover effect.

**Comment by Jestin1702** [comment]
@smaranjitghose  would you like me to work on the same?

**Comment by smaranjitghose** [comment]
Sure. Feel free to give a PR.
