### ISSUE TITLE
Memory/Event Page Template

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#647]
## Idea behind this:

This page can be used for a standalone picturesque description of any conference, talk, hackathon one attends. Perhaps even some community/social initiatives or one's grad school farewell/fresher's

## Some specifications

- [Reference](https://www.stevenmengin.com/).
- Do not replicate the above reference top to bottom rather use it as an inspiration. ( For example, we don't need the `x/y` section notifications on the top right, use `Gotham` font's **BOLD** for the text, Text Animation can be tweaked,  the stylized text can be ignored)
- Most parts of this page should be loaded dynamically where we can simply specify the text and the corresponding picture to a json variable inside event.js
- Make sure the navbar and the footer of the current project is consistent

**Comment by Rutikab12** [comment]
Hey, @smaranjitghose I would like to work on this issue from June 10 as letsgrowmore SOC'21 participant. Do assign me if possible.
Thank You!

**Comment by Rutikab12** [comment]
Thank you @smaranjitghose I will start working on it as competition begin.

**Comment by Rutikab12** [comment]
Excuse me, I can't be able to complete this task because of some health reasons. Thank You. I have unassigned myself. @smaranjitghose

**Comment by prads46** [comment]
sir since i am new to open source could u please tell me in this do we have to create a seperate page where one can add images of a particular event?

**Comment by smaranjitghose** [comment]
> sir since i am new to open source could u please tell me in this do we have to create a seperate page where one can add images of a particular event?

Yes. make the page as event.html and the corresponding css as event.css

**Comment by prads46** [comment]
Sir can u assign it to me?

**Comment by anushbhatia** [comment]
assigned for 4 days. Do keep us updated with progress.

**Comment by tanzzz-tech** [comment]
@anushbhatia  can u please assign me this issue?

**Comment by anushbhatia** [comment]
I have assigned @prads46 for now as soon her time period is over. You will be assigned.

**Comment by prads46** [comment]
How much time do i have for this issue?

**Comment by smaranjitghose** [comment]
> How much time do i have for this issue?

3 days.

Meanwhile, i think @tanzzz-tech  you can work on another template page with a different theme. As in practicality we would have these pages for different purposes for example, Talks Throwbacks, College Graduation, etc
