### ISSUE TITLE
Volunteership Card UI Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#649]
## Certain Requirements

- [Reference](https://girlscriptboilerplate.netlify.app/achievements.html). Follow the bottommost cards
- Take care of the color scheme (shades of black and blue)
- **Do not** add `Read More`  or the arrow following at the bottom
- Use the already available images and text currently used for the same
- **MAKE SURE THE CARDS ARE MOBILE RESPONSIVE**
- Try to ensure that all the cards should always be of the same size irrespective of the length of the content
- The current cards are dynamically loaded from `expereince.js` and should continue to do so even after this change

**Comment by Sanika2103** [comment]
Hey @smaranjitghose  I would like to work on this issue. Will you assign it to me?

**Comment by anushbhatia** [comment]
Assigned for 3 days

**Comment by Sanika2103** [comment]
yess

**Comment by Sanika2103** [comment]
I'm done with it I'll upload it tomorrow

**Comment by smaranjitghose** [comment]
@Sanika2103 Awesome!! I look forward to review it and possibly integrate it.

**Comment by Sanika2103** [comment]
Can you please help me where and how should I upload files?
