### ISSUE TITLE
Dark Mode Toggle Switch

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#650]
[Reference](https://codepen.io/ashleynolan/pen/wBppKz)

**Comment by shvmsh20** [comment]
assign this to me

**Comment by RR-Sahoo** [comment]
hyy can I work on this

**Comment by V-Yeshwanth** [comment]
I want to work on this issue!!!

**Comment by smaranjitghose** [comment]
@shvmsh20 @V-Yeshwanth Once the toggle is over, you can work on the dark mode for the website itself

**Comment by 1anshu-56** [comment]
I want to work on this issue as i have made same thing earlier in my project please assign it to me.

**Comment by smaranjitghose** [comment]
@shvmsh20 has 1 more day, after that @1anshu-56 can take over

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

**Comment by shvmsh20** [comment]
@smaranjitghose you can unassign me this issue. I tried but couldn't able to get the desired result.

**Comment by vaishnavi1011** [comment]
I want to create this dark mode toggle switch.Please assign me the issue

**Comment by nitishapiplani** [comment]
i will make it in half an hour if you assign to me 
lgmsoc participant

**Comment by smaranjitghose** [comment]
@1anshu-56 You have two days for this, after which @nitishapiplani can take over

**Comment by varunwho** [comment]
I can work on this if it's not yet resolved

**Comment by nitishapiplani** [comment]
hey but you said yo  will assign this issue to me

**Comment by Deep06-11** [comment]
I want to contribute to this issue under LGM SOC 21. Please assign it to me.

**Comment by smaranjitghose** [comment]
> hey but you said yo will assign this issue to me

Ya, I expected you to start working as soon as the former assignee's deadlines were over.

**Comment by nitishapiplani** [comment]
> > hey but you said yo will assign this issue to me
> 
> Ya, I expected you to start working as soon as the former assignee's deadlines were over.

But it was not assigned to me that's why I didn't start

**Comment by smaranjitghose** [comment]
> > > hey but you said yo will assign this issue to me
> > 
> > 
> > Ya, I expected you to start working as soon as the former assignee's deadlines were over.
> 
> But it was not assigned to me that's why I didn't start

No worries. You can begin now.

**Comment by smaranjitghose** [comment]
Any updates @nitishapiplani @varunwho ?

**Comment by varunwho** [comment]
> Any updates @nitishapiplani @varunwho ?

I thought @nitishapiplani is doing this bcoz she claimed the issue before me (or else I am almost done with the toggle switch)

**Comment by nitishapiplani** [comment]
> Any updates @nitishapiplani @varunwho ?

in process of completion

**Comment by smaranjitghose** [comment]
@varunwho @nitishapiplani Are anyone of done with this?

**Comment by smaranjitghose** [comment]
Closed due to inactivity
