### ISSUE TITLE
size of navbar in firefox

### ISSUE THREAD

**Issue by SamikshaSankar** [smaranjitghose/awesome-portfolio-websites#664]
![2021-06-08 (8)](https://user-images.githubusercontent.com/52104082/121187687-f6197080-c885-11eb-8fdd-5b332d777420.png)

**Comment by SamikshaSankar** [comment]
@anushbhatia how I can change this..because when I checked in chrome it works perfectly

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by forkbikash** [comment]
Hey @smaranjitghose, is someone still working on this issue? If not please assign this to me.

**Comment by SamikshaSankar** [comment]
@forkbikash I am working on this issue

**Comment by anushbhatia** [comment]
Do give an update @SamikshaSankar

**Comment by smaranjitghose** [comment]
Closed due to inactivity
