### ISSUE TITLE
Bottom to top button

### ISSUE THREAD

**Issue by royalleads15** [smaranjitghose/awesome-portfolio-websites#665]
Add bottom to top button in every page so that on can easily reach on top of page when he / she is on bottom of page .

**Comment by V-Yeshwanth** [comment]
I want to work on this issue!!

**Comment by royalleads15** [comment]
I am already done with it bro 😀😀

**Comment by mehulmb1** [comment]
I would like to work on this. can you assign this to me.

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by Devansh2000Shaw** [comment]
I want to contribute on this issue under LGM SOC 21. Thank you.

**Comment by nKeiros13** [comment]
Can I contribute on this issue under LGM SOC 21?

**Comment by sejalvasan** [comment]
Please assign this issue to me under LGM SOC.

**Comment by smaranjitghose** [comment]
@sejalvasan We are on the process of shifing the codebase to React. Check out #640. Maybe you can work with folks on that issue for this same task

**Comment by AnjaniSriya** [comment]
I would like to contribute to this issue...
Please allow me..

**Comment by 1anshu-56** [comment]
I am a participant @ LGMSoC and I want to work on this issue can you please assign it to me as I have previous experience with this issue, so please assign it to me.

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21,   Could you please assign this issue to me?

**Comment by smaranjitghose** [comment]
@1anshu-56 I believe I have assigned you another issue. Could you please wrap that up?

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

**Comment by prads46** [comment]
if this issue is still not resolved could you please assign it to me under LGM-SOC 21

**Comment by varunwho** [comment]
I can work on this if it's not yet resolved!

**Comment by smaranjitghose** [comment]
> I can work on this if it's not yet resolved!

Assigned for 4 days

**Comment by varunwho** [comment]
@smaranjitghose I've added the scroll to top button and I've designed it in such a way resembling the social media icon circles. Let me know if you're expecting some other design (like color etc) and then I'll create a PR accordingly 

https://user-images.githubusercontent.com/53107832/122235443-52f6d580-cedb-11eb-96b1-2ef4845466a2.mp4

**Comment by anushbhatia** [comment]
> @smaranjitghose I've added the scroll to top button and I've designed it in such a way resembling the social media icon circles (of the home page). Let me know if you're expecting some other changes like design (like color etc) or something else and then I'll create a PR accordingly
> 
>  Portfolio.mp4
Looks good to me!

**Comment by varunwho** [comment]
> Looks good to me!
> You can make PR.

Sure! Thankyou @anushbhatia

**Comment by royalleads15** [comment]
@smaranjitghose @anushbhatia Sir I have a design , Kindly visit it and  if it suits then I can make PR .
![back to top](https://user-images.githubusercontent.com/56637948/122370242-89386180-cf7c-11eb-9706-cf80151ff4bc.jpg)

**Comment by smaranjitghose** [comment]
@anushbhatia could you please suggest to him a micro animation.

Additionally the color of the button should change when on the remainder page to suit the theme

**Comment by smaranjitghose** [comment]
The overall design and size looks cool!

**Comment by anushbhatia** [comment]
https://codepen.io/TKS31/pen/gOaKaxx @smaranjitghose something like this?

**Comment by smaranjitghose** [comment]
> https://codepen.io/TKS31/pen/gOaKaxx @smaranjitghose something like this?

The middle one, ya!  The color scheme should be consistent with the rest of the website.
