### ISSUE TITLE
Description on hover in Project and Experience Section 

### ISSUE THREAD

**Issue by V-Yeshwanth** [smaranjitghose/awesome-portfolio-websites#666]

**Comment by Manas502** [comment]
Hey! Is it possible that I work on this issue? I think it's my forte.

**Comment by V-Yeshwanth** [comment]
Sorry bro! I have Created already

**Comment by smaranjitghose** [comment]
@V-Yeshwanth Could you please elaborate on what you wish to add?

**Comment by V-Yeshwanth** [comment]
Short content related to projects and experiences displayed when Clicked on a card.
And providing buttons for GitHub and live website .
Also improving the cards UI

**Comment by supzi-del** [comment]
Can you assign this to me under LGMSOC?

**Comment by smaranjitghose** [comment]
> Short content related to projects and experiences displayed when Clicked on a card.
> And providing buttons for GitHub and live website .
> Also improving the cards UI

We previously had that option but after some thought decided to remove it since a line or two does not do justice to the project description. The buttons are already there. Do checkout the separate project card UI issue and give your suggestions w.r.t it in that issue
