### ISSUE TITLE
Footer Design

### ISSUE THREAD

**Issue by dpshikha476** [smaranjitghose/awesome-portfolio-websites#668]
I want to change the footer design which includes the social media icons and get in touch form.
Pls assign me this under LGM SOC'21.

**Comment by smaranjitghose** [comment]
Although I am not sure whether your suggestions would be in line with @anushbhatia's design suggestions, I would love to see you tryout and incorporate the changes to the greatest extent @dpshikha476.

Assigned for 3 days

**Comment by dpshikha476** [comment]
Thank You!

**Comment by aditya687** [comment]
I can improve the footer design and contribute it

**Comment by aditya687** [comment]
I can contribute social media accounts and to connect with us in the footer section. Please  assign me this issue I would like to work on this issue under LGMSOC21.

**Comment by aditya687** [comment]
Issue #676
I have given a footer design for your site. You can  see the change @smaranjitghose. You can check my pr.

**Comment by jatinjain001** [comment]
I would like to contribute in this please let me know if it is availabl
