### ISSUE TITLE
Enhancing Research and Education Page 

### ISSUE THREAD

**Issue by Rutuj-Runwal** [smaranjitghose/awesome-portfolio-websites#669]
- [ ] Adding AOS animation to card elements in Research Page
- [ ] Changing Research page elements to flex-box div for more responsiveness(The research page has elements listed out as table elements where as one on the education page are flex-box)
- [ ] (Suggestion) Changing the preloader form the current "blue-cube" to something more engaging

This Issue as a part of my contribution towards LGM-SOC'21

**Comment by smaranjitghose** [comment]
Assigned for a week for the overall issue. But I would suggest splitting the work in 3 PRs

**Comment by Salonee-Jain** [comment]
Can I work on this issue under LGM SOC

**Comment by smaranjitghose** [comment]
> Can I work on this issue under LGM SOC

No. It's by default assigned to the participant who raised the issue

**Comment by smaranjitghose** [comment]
@Salonee-Jain  In case you wish to contribute further to the above pages. Please raise a new issue with an elaborate description of your proposal
