### ISSUE TITLE
Work Experience Card UI Update for Phone View

### ISSUE THREAD

**Issue by AKC068** [smaranjitghose/awesome-portfolio-websites#670]
- [x] Current animation on work experience card is having imperfection for phone view. When we touch a 'work experience card' in phone view then its overflow animation overlaps other card which seems not be perfect. 

- [x] I'll change the overflow property for it and give perfection in phone view.

- [x] `Suggestion` - AOS animation should be there and we can also try a different animation for phone view irrespective of pc view.

@smaranjitghose can you please assign me this issue as a participant of LGM-SOC'21.

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by Salonee-Jain** [comment]
Can I work on this issue under LGM SOC
