### ISSUE TITLE
Improve the footer design

### ISSUE THREAD

**Issue by tjanhvi** [smaranjitghose/awesome-portfolio-websites#676]

**Comment by tjanhvi** [comment]
Please assign me this issue

**Comment by tjanhvi** [comment]
Please assign me this issue

**Comment by vimalprogrammer** [comment]
I would like to work on this issue under LGMSOC21, please assign me.

**Comment by asdsyd** [comment]
I would like to work on this issue under **LGMSOC21**, please assign me.

**Comment by anushbhatia** [comment]
How would you do so. Do gives us updates regarding that.

**Comment by KhushiRoy** [comment]
I want to contribute on this issue under LGMSOC.

**Comment by aditya687** [comment]
I would like to work on this issue under LGMSOC21, please assign me to contribute
.

**Comment by smaranjitghose** [comment]
Duplicate #668
