### ISSUE TITLE
Footer Copyright Claim

### ISSUE THREAD

**Issue by Shaishav0507** [smaranjitghose/awesome-portfolio-websites#680]
Hey @smaranjitghose 
I would like to add footer with Copyright Claim under your name.
If you would like to include in your project, please assign me.
Thanks

**Comment by smaranjitghose** [comment]
### Closed due to:

- This is an open source project. We want everyone to use this project without any hindrance
- Unless one sells a portfolio for purely commercial initiatives and has registered for the same, a copyright symbol is legally invalid.
