### ISSUE TITLE
Can we add copyright section in footer section of website.

### ISSUE THREAD

**Issue by starrohan999** [smaranjitghose/awesome-portfolio-websites#681]

**Comment by starrohan999** [comment]
I am LGM SOC-21 participant. Please assign it to me @smaranjitghose

**Comment by AnjaniSriya** [comment]
I am a member of LGM SOC
I would like to contribute, please allow me

**Comment by mahiwattamwar** [comment]
Hi @smaranjitghose  I am LGM SOC-21 participant. I can make this changes please assign me

**Comment by smaranjitghose** [comment]
Check #680
