### ISSUE TITLE
The titles for the respective Social Media Icons

### ISSUE THREAD

**Issue by Sudeep8708** [smaranjitghose/awesome-portfolio-websites#687]
Hey, I would like to give titles for respective social media icons, 
so it might be helpful for the users where they're being driven to when they click it! 
I'm an LGMSoC participant.
I would like to fix that drawback,  and also request you to assign it to me..so that the website gets better and clear.

**Comment by Sudeep8708** [comment]
@smaranjitghose sir can I proceed to fix this issue and make a PR?

**Comment by anushbhatia** [comment]
Before creating a PR could you share a sample or a link for it so that we can understand it better.

**Comment by Sudeep8708** [comment]
![WhatsApp Image 2021-06-12 at 19 29 03 (1)](https://user-images.githubusercontent.com/81461977/121778488-b23fa780-cbb4-11eb-911c-a70f60bfb702.jpeg)
![WhatsApp Image 2021-06-12 at 19 29 03](https://user-images.githubusercontent.com/81461977/121778494-b4a20180-cbb4-11eb-9785-da62f9824150.jpeg)


I hope the above pics depicts what I thought to add.
That is when the user is about to click any social media icons, it will be titled with its respective name.
Thanks!

**Comment by smaranjitghose** [comment]
Not required as of now
