### ISSUE TITLE
coustmize navigation bar 

### ISSUE THREAD

**Issue by nitishapiplani** [smaranjitghose/awesome-portfolio-websites#688]
when used in phone and navigation bar is open nthng else appears
![git 1](https://user-images.githubusercontent.com/83905949/121744144-149a9880-cb20-11eb-8a85-13d8e36b5562.PNG)

**Comment by smaranjitghose** [comment]
Could you please elaborate more on what you wish to add? 

The navigation bar is supposed to look like this as per the current codebase😅

**Comment by shreya-gb** [comment]
Please assign me! I can help you out with this :)

**Comment by smaranjitghose** [comment]
> Please assign me! I can help you out with this :)

Please read the guidelines posted on slack workspace

**Comment by smaranjitghose** [comment]
Closed due to inactivity
