### ISSUE TITLE
Change Cursor to pointer in Experience and Project section.

### ISSUE THREAD

**Issue by ishitakapoor26** [smaranjitghose/awesome-portfolio-websites#691]
Changed Cursor to pointer in Experience and Project section.

**Comment by ishitakapoor26** [comment]
@smaranjitghose pls assign this issue to me.

**Comment by smaranjitghose** [comment]
> @smaranjitghose pls assign this issue to me.

Please read the guidelines stated in the slack channel regarding spam comments

**Comment by 0xCipher-max** [comment]
> Changed Cursor to pointer in Experience and Project section.

I can Do this task perfectly in very less time
