### ISSUE TITLE
Add Hovering Effect to cards

### ISSUE THREAD

**Issue by ishitakapoor26** [smaranjitghose/awesome-portfolio-websites#694]
Adding hovering effects to projects, research and experience cards.
@smaranjitghose Pls assign this issue to me.

**Comment by Sumit11081996** [comment]
can you assign me this issue

**Comment by ishitakapoor26** [comment]
> can you assign me this issue

Hey I'm already working on it. Pls look for some other isssue.

**Comment by ishitakapoor26** [comment]
@smaranjitghose pls assign this issue to me.

**Comment by Parth-Shete** [comment]
@smaranjitghose Pls assign this issue to me.
