### ISSUE TITLE
Navbar not behaving properly

### ISSUE THREAD

**Issue by geek9012** [smaranjitghose/awesome-portfolio-websites#695]
Hi
I forked the repository and made the changes to my portfolio. But the navbar seems like this:
![image](https://user-images.githubusercontent.com/84989098/121775436-53befd00-cba5-11eb-8f6b-6ddd0be5860d.png)

But according to the documentation(https://smaranjitghose.github.io/awesome-portfolio-websites/gs/#seo-and-miscellaneous), it should look like this:

![image](https://user-images.githubusercontent.com/84989098/121775452-705b3500-cba5-11eb-97b3-3158c55b2a58.png)

I performed this step: **Under Footer and Navbar heading, inside a href="#!" class="brand-logo", change the path inside <img src="" to your image path**

But the navbar still looks like:
![image](https://user-images.githubusercontent.com/84989098/121775436-53befd00-cba5-11eb-8f6b-6ddd0be5860d.png)

Also, the toggle button for dark theme is missing.
I also noticed that **main.js is not called from index.html.** So, how is main.js put into use?

**Comment by smaranjitghose** [comment]
We have removed the dark mode option.
