### ISSUE TITLE
Improve Footer UI

### ISSUE THREAD

**Issue by gourav02** [smaranjitghose/awesome-portfolio-websites#696]

**Comment by smaranjitghose** [comment]
Please elaborate on your suggestions

**Comment by gourav02** [comment]
to modify the design . Instead of the email form, it can have a mail icon and it will redirect to the Gmail page for sending mail. that way it will look neater. And I also can improve the footer design bit more.

**Comment by anushbhatia** [comment]
do keep us updated with it.

**Comment by gourav02** [comment]
ok.thank you

**Comment by smaranjitghose** [comment]
Closed due to inactivity
