### ISSUE TITLE
Improving the experience section

### ISSUE THREAD

**Issue by Khushi-agarwal** [smaranjitghose/awesome-portfolio-websites#700]
In the experience section I would like to add the flip card animation so that on hovering over the cards it would display the animation.

**Comment by smaranjitghose** [comment]
Which cards, in particular, are you referring to?

**Comment by Khushi-agarwal** [comment]
@smaranjitghose over the volunteer ship one.

**Comment by anushbhatia** [comment]
Can you show a link or a video demo?

**Comment by Khushi-agarwal** [comment]
![My Movie 4](https://user-images.githubusercontent.com/76625662/121835374-c7b8ec80-ccee-11eb-9ec6-0bfe5d33ec88.gif)
You can get a reference from this @anushbhatia @smaranjitghose
