### ISSUE TITLE
Add zoom transform on hover- mentorship cards

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#701]
The mentorship cards have no scale transition on hover like that of volunteership and experience section. I would like to add this feature under LGM SOC.

**Comment by supzi-del** [comment]
This can also be added in the research section.

**Comment by smaranjitghose** [comment]
Could you raise a PR for the Research page first? Once we approve that, you can proceed with implementation on the mentorship cards as well.
