### ISSUE TITLE
add links to the gifs in README.md file

### ISSUE THREAD

**Issue by Umesh-01** [smaranjitghose/awesome-portfolio-websites#705]
## Description
I think these two gifs (see the below image) should contain a links to the related files because there are the chances that anyone can click on them and these are of no use without them.  

![image](https://user-images.githubusercontent.com/83420185/121816381-de345900-cc98-11eb-8f33-eaa7ffe14037.png)

## Solution 
I want to add links to these gifs so that if anyone click on them it will take them to the related web pages where these files are present.

**Comment by Umesh-01** [comment]
@smaranjitghose sir should I make these changes??

**Comment by smaranjitghose** [comment]
Not relevant
