### ISSUE TITLE
Dark Mode UI

### ISSUE THREAD

**Issue by tanya070820** [smaranjitghose/awesome-portfolio-websites#710]
@smaranjitghose Please try to assign me this issue

**Comment by smaranjitghose** [comment]
@tanya070820 Please be patient 😅.

I am assigning you this for 5 days.  Do have a look at the toggle switch issue too. Give separate PRs for each issue. Try to consult @anushbhatia over slack for deciding the colors.

**Comment by tanya070820** [comment]
@smaranjitghose Sorry Sir 
Surely I will look to that also.

**Comment by smaranjitghose** [comment]
No worries @tanya070820 . Do keep us updated!

**Comment by smaranjitghose** [comment]
@tanya070820 Any updates? 

Check out [this](https://github.com/smaranjitghose/awesome-portfolio-websites/pull/730) PR as it is a forerunner to your task

**Comment by anushbhatia** [comment]
https://material.io/design/color/dark-theme.html do follow these guidelines

**Comment by tanya070820** [comment]
ok Sir

**Comment by smaranjitghose** [comment]
> ok Sir

Are you still working on this?

**Comment by tanya070820** [comment]
I haven't started till yet

**Comment by smaranjitghose** [comment]
> I haven't started till yet

How many days would you need for this? At least the first PR?

**Comment by tanya070820** [comment]
around three days

**Comment by smaranjitghose** [comment]
> around three days

Cool. Then that's the deadline for you

**Comment by aliya-rahmani** [comment]
@tanya070820 updates?

**Comment by smaranjitghose** [comment]
Closed due to inactivity
