### ISSUE TITLE
Dynamic Title "Come back"

### ISSUE THREAD

**Issue by varunwho** [smaranjitghose/awesome-portfolio-websites#711]
The dynamic title is kinda disturbing and doesn't look good for a portfolio website. I meant that constant switching of "Come back" and "John Doe | Home"

![Screenshot 2021-06-14 222448](https://user-images.githubusercontent.com/53107832/121930187-b78d2580-cd5f-11eb-90f9-b71fa50adf33.png)

I feel we can remove this as it was looking a bit unprofessional (personally) and only keep "John Doe | Home".
What say, admins?

**Comment by smaranjitghose** [comment]
Touche!

@varunwho You can remove it from all the pages. Assigned for 3 days
