### ISSUE TITLE
 Creative Text Animation Effects 

### ISSUE THREAD

**Issue by Surajvatsya** [smaranjitghose/awesome-portfolio-websites#716]
Designed a linear dynamic animation for text "Experience" in experience.html.

![Screenshot (3163)](https://user-images.githubusercontent.com/68156079/122091102-1321e680-ce26-11eb-9d13-e0eb83407761.png)
![Screenshot (3165)](https://user-images.githubusercontent.com/68156079/122091114-16b56d80-ce26-11eb-96d2-de8758c62be7.png)
![Screenshot (3164)](https://user-images.githubusercontent.com/68156079/122091116-174e0400-ce26-11eb-9bfa-d571fb36fcf2.png)

 

I would kindly request @smaranjitghose to assign this issue to me.

**Comment by smaranjitghose** [comment]
We already have the svg animation beside it so it would be an overkill for the UI

**Comment by Surajvatsya** [comment]
ok sir, Thanks for guide.
