### ISSUE TITLE
Align footer text in the same line

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#720]
The quote in the footer is not aligned with the get in touch section. I would like to fix this under LGMSoC.
I will be making the below changes.
Before - see footer text
![Screenshot (193)](https://user-images.githubusercontent.com/78655439/122234952-e7ad0380-ceda-11eb-9b9d-5f6c90c132a6.png)
After
![Screenshot (194)](https://user-images.githubusercontent.com/78655439/122234979-ec71b780-ceda-11eb-9dcc-66a30f44b04c.png)

**Comment by anushbhatia** [comment]
Assigned for 2 days

**Comment by supzi-del** [comment]
> @supzi-del, Can I work on this issue?

Hey, I'm working on this issue. You can find other issues to work on.

**Comment by Parth-Shete** [comment]
> > @supzi-del, Can I work on this issue?
> 
> Hey, I'm working on this issue. You can find other issues to work on.

Okay
