### ISSUE TITLE
Create a page for gallery ( for art works of the portfolio owner )

### ISSUE THREAD

**Issue by forkbikash** [smaranjitghose/awesome-portfolio-websites#723]
A gallery section can be created in the portfolio. If you(@anushbhatia) approve and assign it to me, I can start the work.
This section can benefit ui/ux designers and other artists.

**Comment by forkbikash** [comment]
Hey @smaranjitghose ,
 Should I include the page link in the navbar (or wait for proper time) ?

The gallery page looks like this.....
![Screenshot (108)](https://user-images.githubusercontent.com/70908998/122560068-c1fc3780-d05d-11eb-9696-a9c7d211d127.png)
![Screenshot (109)](https://user-images.githubusercontent.com/70908998/122560105-cc1e3600-d05d-11eb-894f-c7ed6b51c001.png)
![Screenshot (110)](https://user-images.githubusercontent.com/70908998/122560119-d17b8080-d05d-11eb-966d-4d0a224e0ce3.png)
![Screenshot (111)](https://user-images.githubusercontent.com/70908998/122560133-d6d8cb00-d05d-11eb-91de-1c7ad315897f.png)
![Screenshot (112)](https://user-images.githubusercontent.com/70908998/122560148-dd674280-d05d-11eb-95ba-347e9db0103f.png)
![Screenshot (113)](https://user-images.githubusercontent.com/70908998/122560155-e2c48d00-d05d-11eb-9087-19198a0287e9.png)

Can I open PR now?

**Comment by smaranjitghose** [comment]
Sure. Please give a PR. Do not put the link in the Nav bar for now
