### ISSUE TITLE
Social icons merging into footer section when tested for responsive of  home section

### ISSUE THREAD

**Issue by puneetkaur2929** [smaranjitghose/awesome-portfolio-websites#727]
hey @smaranjitghose 

I have found that **social icons are merging with footer**  in **home** section as shown in screenshot attached 
I am interested to work on this issue.
Kindly assign this issue to me under LGM SOC '21 

![Screenshot (33)](https://user-images.githubusercontent.com/80326308/122282878-89e3e000-cf09-11eb-8689-79f85dadc59a.png)

**Comment by smaranjitghose** [comment]
What device?

**Comment by smaranjitghose** [comment]
There is no such config in the current chrome tools on my end. However, the issue persists for iPhone SE and Galaxy Fold devices. You can resolve it if you wish

**Comment by smaranjitghose** [comment]
Assigned for 3 days
