### ISSUE TITLE
Changing colors of some elements to match the color theme of respective pages

### ISSUE THREAD

**Issue by itsij** [smaranjitghose/awesome-portfolio-websites#731]
I would like to make color changes to the below mentioned elements according to respective page color themes, so that the pages look more uniform:

- scrollbar
- get in touch form
- cards

Would also make changes in their hover colors accordingly.

For eg:

![image](https://user-images.githubusercontent.com/72145053/122349824-3ce42600-cf6a-11eb-9acb-f7aa825df2a4.png)

![image](https://user-images.githubusercontent.com/72145053/122349948-61400280-cf6a-11eb-9715-5103347c086d.png)

![image](https://user-images.githubusercontent.com/72145053/122351721-0c04f080-cf6c-11eb-8e61-938b1bc4250e.png)

![image](https://user-images.githubusercontent.com/72145053/122350128-90567400-cf6a-11eb-9aa1-8cbdd9f6ded8.png)

@smaranjitghose I would like to work on this issue as LGMSOC Participant

**Comment by anushbhatia** [comment]
Don't modify the shadow elements of the website instead just make changes to the scrollbar and contact form. 
Try to reduce code redundancy by specifying the theme if possible.

**Comment by smaranjitghose** [comment]
@itsij One suggestion, follow the color theme of the research page for the entire website to maintain consistency. Rest looks good to me. Looking forward to your PR.

**Comment by itsij** [comment]
> @itsij One suggestion, follow the color theme of the research page for the entire website to maintain consistency. Rest looks good to me. Looking forward to your PR.

@smaranjitghose can we change the image on projects page to some image in purple-blue color bcoz that's the only one with different color...and by doing this, we can define purple-blue color for scrollbar, contact form in "style.css" only instead of individual pages, ( like u wanted for consistency ) and it will look fine on all pages....?

**Comment by itsij** [comment]
or is it fine this way itself?

![image](https://user-images.githubusercontent.com/72145053/122500071-b124d500-d00f-11eb-9b9f-d237f9dd849c.png)

**Comment by smaranjitghose** [comment]
> > @itsij One suggestion, follow the color theme of the research page for the entire website to maintain consistency. Rest looks good to me. Looking forward to your PR.
> 
> @smaranjitghose can we change the image on projects page to some image in purple-blue color bcoz that's the only one with different color...and by doing this, we can define purple-blue color for scrollbar, contact form in "style.css" only instead of individual pages, ( like u wanted for consistency ) and it will look fine on all pages....?

Sure

**Comment by itsij** [comment]
Hey @smaranjitghose!!
Instead of changing the image of projects page, I have changed the colors of that svg to suit the theme. Plz have a look:

![image](https://user-images.githubusercontent.com/72145053/122644483-11606780-d133-11eb-8434-1d861901fbc3.png)

Is it looking fine? or shall i make some changes...?

**Comment by smaranjitghose** [comment]
> Hey @smaranjitghose!!
> Instead of changing the image of projects page, I have changed the colors of that svg to suit the theme. Plz have a look:
> 
> ![image](https://user-images.githubusercontent.com/72145053/122644483-11606780-d133-11eb-8434-1d861901fbc3.png)
> 
> Is it looking fine? or shall i make some changes...?

Perfect. Do go ahead and give a PR
