### ISSUE TITLE
Adding Resume option in navigation bar

### ISSUE THREAD

**Issue by vivek286** [smaranjitghose/awesome-portfolio-websites#732]
I would like to add a resume option to the navigation bar which will redirect the user to the resume file uploaded on google drive.
@smaranjitghose @anushbhatia  If you approve the issue please assign it to me.

**Comment by divyasri77** [comment]
we can add resume button in home page itself

**Comment by anushbhatia** [comment]
@smaranjitghose what say?

**Comment by smaranjitghose** [comment]
@anushbhatia Putting it on the home page will break the essence of the particle theme. Perhaps on the footer, as a download resume button or on the nav bar.

BTW, @divyasri77 feel free to raise an issue to add a blog page to the navbar. ( We won't build it, rather open the blog hosted on another server in a new tab)

**Comment by anushbhatia** [comment]
> n or on the nav bar.

yep
