### ISSUE TITLE
Add Skill Tab to Nav Bar

### ISSUE THREAD

**Issue by divyasri77** [smaranjitghose/awesome-portfolio-websites#734]
In this page we can add the skills that we are good at.

**Comment by anushbhatia** [comment]
Could you elaborate this with an example if possible. @smaranjitghose do we want this in the project. we can just have a section of this on the home page?

**Comment by smaranjitghose** [comment]
Ya, Maybe in a section below the homepage definitely!

**Comment by smaranjitghose** [comment]
@anushbhatia I would request you to help out with the UI design in case we proceed with this to maintain the consistency of the theme

**Comment by 444-555-fatima** [comment]
please elborate me this issue

**Comment by anushbhatia** [comment]
https://dribbble.com/shots/1941601-Design-Skills

**Comment by divyasri77** [comment]
added the skill section
review by pull request👍

**Comment by 444-555-fatima** [comment]
assign me

**Comment by aliya-rahmani** [comment]
@444-555-fatima, a PR has already been raised for this issue, do find others with an "up for grab" tag.
