### ISSUE TITLE
Add Achievements Tab to Nav Bar

### ISSUE THREAD

**Issue by Pratishtha33** [smaranjitghose/awesome-portfolio-websites#735]
Here can be any type of user who will need the portfolio website. so, Adding these features would give a complete touch to their resume.

**Comment by smaranjitghose** [comment]
I can assign you the issue if you wish to create a full fledged Achievements Page. 

@anushbhatia UI suggestions and microanimations please!

**Comment by Pratishtha33** [comment]
Yes, It would be accurate. I'm ready to make full fledge Achievements page.

**Comment by 444-555-fatima** [comment]
please assign me this issue

**Comment by smaranjitghose** [comment]
@444-555-fatima  Please check out the other issues. I have clearly mentioned in the guidelines on the slack workspace that once a participant is assigned an issue, it would not be reassigned till their tenure of 2-3 days is over.

**Comment by anushbhatia** [comment]
> I can assign you the issue if you wish to create a full fledged Achievements Page.
> 
> @anushbhatia UI suggestions and microanimations please!

https://dribbble.com/shots/4048382-Achievement-illustrations
https://dribbble.com/shots/8804697-User-team-achievements-for-Skara-company-wiki
https://dribbble.com/shots/10927327-Celebration-Animation-for-30k-Followers (Particle effect in bg)
![image](https://user-images.githubusercontent.com/40017559/122601220-96457580-d08e-11eb-8bb7-813cd7413934.png)

**Comment by Pratishtha33** [comment]
should I put some random Achievements in order to show something?

**Comment by anushbhatia** [comment]
Yes, you could add random as of now or some of yours.

**Comment by aliya-rahmani** [comment]
@Pratishtha33  unassigned due to inactivity.

**Comment by 444-555-fatima** [comment]
please review my pR

**Comment by smaranjitghose** [comment]
The PR should be on this repository and not your forked one!

- Please have a look at the commits before giving a PR
- Your work just depends on an achievement.html, achievement.js, and achievement.css. However, this PR tends to change 42 files that have no relation with the work
- Demo Snapshot/Clip missing in the PR Description
- Poor Documentation of Code
- Corresponding Issue improperly linked


__Please rectify the above mistakes__
