### ISSUE TITLE
Footer Send Button UI Update

### ISSUE THREAD

**Issue by rishika789** [smaranjitghose/awesome-portfolio-websites#737]
on hovering send button of get in touch section . I would like to change the colour effects.

![Screenshot (917)](https://user-images.githubusercontent.com/78673968/122454143-ad219480-cfc8-11eb-8d78-dd1fce5c0e7c.png)

**Comment by anushbhatia** [comment]
Would you like to add a micro animation to that part it would be great like 
https://codepen.io/nuski/details/ExPEBgw
https://codepen.io/cjr85/pen/JjWKEMR

**Comment by smaranjitghose** [comment]
> Would you like to add a micro animation to that part it would be great like
> https://codepen.io/nuski/details/ExPEBgw
> https://codepen.io/cjr85/pen/JjWKEMR

The first reference seems cool! @rishika789 take 3 days to implement that and let us know

**Comment by aliya-rahmani** [comment]
@rishika789 updates?

**Comment by riya123-hub** [comment]
I am a  participant in LGMSOC. Can I take this issue ?

**Comment by riya123-hub** [comment]
I have made the changes and pulled request. plz do review

**Comment by riya123-hub** [comment]
I am really sorry I mistakenly unassigned myself. Can u plz reassign me

**Comment by smaranjitghose** [comment]
> I am really sorry I mistakenly unassigned myself. Can u plz reassign me

It is fine @riya123-hub .  Please have a look a the feedback given on your PR. Kudos for the hard work done however the requirements stated above are different
