### ISSUE TITLE
Footer Realignment Web View

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#739]
![footer_update](https://user-images.githubusercontent.com/46641503/122481417-444c1380-cfec-11eb-980c-6e2c6f87641e.png)
- Shift the Elements towards the respective corners
- The quote should be in a single line. For long quotes, it should extend to the next line

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue. I can work on it.

**Comment by aliya-rahmani** [comment]
@JahnaviKashyap19 updates?

**Comment by JahnaviKashyap19** [comment]
> @JahnaviKashyap19 update
Hello! Thank you for assigning me the issue. I have created the pull request. Kindly review it.

**Comment by smaranjitghose** [comment]
Major responsiveness issue. Check the review please and test the changes well before the PR
