### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#74]
Features:
- [ ] Try to improve the particle effect in the background
- [ ] Improve the documentation of the particle script with detailed explanations
- [x] Terminal Like effect for the professions
- [ ] About Section
- [ ] Dark mode for the section containing: particle effect, social media icons, terminal effect and the name

**Comment by N00Bmaster2810** [comment]
Does in about section we have to add content by ourselves???

**Comment by anushbhatia** [comment]
Lorem Ipsum as of now

**Comment by shudhanshu03** [comment]
Can i apply parallax scrolling effect on home page @anushbhatia @smaranjitghose . And if yes ? then suggest which type of image should i add ?

**Comment by AshutoshDash1999** [comment]
@smaranjitghose I want to work on full page parallax effect.

**Comment by the-supernova** [comment]
@smaranjitghose I can add the terminal effect

**Comment by RiyaAgrawal17** [comment]
Particle effect issue has been resolved ?

**Comment by N00Bmaster2810** [comment]
Can I work on the about section.

**Comment by salonilakhotia** [comment]
I want to work on About Section

**Comment by smaranjitghose** [comment]
> I want to work on About Section.
> @smaranjitghose Can you assign me this

I have assigned you the footer. Once you complete that, you can start with this page

**Comment by smaranjitghose** [comment]
> Particle effect issue has been resolved ?

We want to improve the visuals and the dark mode of the page is completely left out

**Comment by N00Bmaster2810** [comment]
@smaranjitghose  @anushbhatia  sir could you please provide some suggestion about the about section regarding its placement on the page and content

**Comment by the-supernova** [comment]
The Terminal Effect as asked-
![demo](https://user-images.githubusercontent.com/56555259/90319184-5d5ee080-df53-11ea-9418-67c302a0759d.gif)
Anything more to add in this? Should I add some colour to make it look different?

**Comment by the-supernova** [comment]
![demo](https://user-images.githubusercontent.com/56555259/90319215-a9118a00-df53-11ea-90f8-486ffef3bbcb.gif)
The Terminal Effect as asked
Did I miss anything? Should I add some color to it to make it look different?

**Comment by ankitapuri** [comment]
Can i work on this issue

**Comment by smaranjitghose** [comment]
> Can i work on this issue

Please specify on which thing you want to work/add/improve

**Comment by ankitapuri** [comment]
I want to work on the section

**Comment by ankitapuri** [comment]
what should appear in the background of parallax

**Comment by smaranjitghose** [comment]
@N00Bmaster2810 For the About Section Try to have an color reverse effect like this:https://www.wibe.in/

**Comment by mharshita** [comment]
@smaranjitghose  Okay!  Will try my best to submit by 28.
I need to make a toggle at the nav bar right?
And there would be no about section while viewing in the dark mode?

**Comment by nikita-1801** [comment]
@smaranjitghose I'd like to work on the color reverse effect and try to have one like it is in https://www.wibe.in/ as you said. Please assign it to me.

**Comment by khushboojoshi3** [comment]
**Dark mode for the section containing: particle effect, social media icons, terminal effect, and the name.** 
I would like to work on this issue.
Can I work on this issue?
