### ISSUE TITLE
Pre-Loader Bug in Project Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#740]
## Self Explanatory Issue

The preloader is not being delivered on the project page.

**Comment by Pallav-19** [comment]
@smaranjitghose  I have fixed this bug  already , assign me so that I will create a pull request, thank you !

**Comment by Pallav-19** [comment]
Hey!, @smaranjitghose  I have created a pull request, kindly check !

**Comment by Pallav-19** [comment]
@anushbhatia Hey, if You are free kindly review the PR, Thank You!

**Comment by smaranjitghose** [comment]
@Pallav-19 Time and again I have mentioned in the slack workspace, that both the maintainers are working full time and we would get back to review the issue within 48 hours. This is not our primary priority and we cannot always instantaneously reply due to other commitments. Please try to be patient and avoid spamming with such comments on the issue/pull request threads
