### ISSUE TITLE
Replace all instances of the word Bibtex on the buttons of the Research Page with "Cite"

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#741]
**Self Explanatory**

**Comment by Pallav-19** [comment]
@smaranjitghose  please assign this to me

**Comment by Pallav-19** [comment]
@smaranjitghose already I have resolved it . Assign me so that I will create a pull request soon

**Comment by Pallav-19** [comment]
@smaranjitghose  Thank You !
