### ISSUE TITLE
Vertical Timeline to Replace Cards for Formal Education in Education Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#745]
[Reference](https://codepen.io/savalazic/full/QKwERN)

## Modifications: (w.r.t the reference)

- The text should be similar both in terms of content and UI as present on the current cards in the education page
- Choose the card for 25th May, 2016 in the reference as the UI
- Take care of responsiveness in the mobile screens
- Do not put the present dummy logos. Make use of actual university logos (to be present in the assets folder)
- The should be injected using a json variable as done currently in the education.js

**Comment by MukulKolpe** [comment]
Hey @smaranjitghose, can you please assign this issue to me.

**Comment by anushbhatia** [comment]
Assigned for 3 days

**Comment by aliya-rahmani** [comment]
@MukulKolpe  updates?

**Comment by MukulKolpe** [comment]
Please can I get an extension of a day, I am working on it.

**Comment by smaranjitghose** [comment]
Sure

**Comment by MukulKolpe** [comment]
I had injected data in the education.js file in JSON format and changed logos. But I was not able to make a similar UI after trying for 2 days. Sorry for that.

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGM-SOC

**Comment by aliya-rahmani** [comment]
@Amrutha1101 updates?

**Comment by Amrutha1101** [comment]
I was working on the other issue assigned. I completed that. I'll start with this now, will complete in 4 days.

**Comment by smaranjitghose** [comment]
Any updates @Amrutha1101? It's been almost a week

**Comment by Amrutha1101** [comment]
I'm unable to work on this issue due to exams. So I'm unassigning :)

**Comment by Jahnavi-Jonnalagadda** [comment]
@smaranjitghose @anushbhatia Could you please assign this issue to me, I'd like to work on it.
