### ISSUE TITLE
Hackathon Section in Expereince Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#748]
[Reference](https://codepen.io/JavaScriptJunkie/details/WgRBxw)

## Requirements:

- Remove the mentorship cards (with all HTML, CSS and JS code related to them. Do not comment them out)
- The title of the section should be __Hackathon Participation__
- The UI should be the same as  given in the reference
- Do not change the background color of the page ( in the reference it is a shade of orange)
- The Color of the scrollbar of the timeline should be the same as that of the headings of the page
- Do not put Lorem Ipsum and random Images. Take the data from my [LinkedIN](https://www.linkedin.com/in/smaranjitghose/)'s volunteering section.  [Take the details of 15 Hackathons]
- Data should be input as done already using a json variable in the expreince.json
- The image should be the logo of the hackathon ( Do not take the picture from their LinkedIn page, rather from the actual website)
- The title should be name of the Hackathon
- Add a subtitle for the role (Judge/Mentor/Speaker/Winner/Runnerup)
- The remaining body should be minimum. Directly copy from my Linkedin's description

**Comment by ishitakapoor26** [comment]
pls assign me this issue.

**Comment by RituCs** [comment]
I would like to work on this issue under LGMSOC'21.Please assign it to me.

**Comment by ishitakapoor26** [comment]
> I would like to work on this issue under LGMSOC'21.Please assign it to me.

@RituCs Hey I'm already working on this issue. Look for some other issue! Good Luck!

**Comment by smaranjitghose** [comment]
@ishitakapoor26 You have 1 more day for this issue

**Comment by smaranjitghose** [comment]
> I would like to work on this issue under LGMSOC'21.Please assign it to me.

Do you wish to take this up?

**Comment by RituCs** [comment]
> > I would like to work on this issue under LGMSOC'21.Please assign it to me.
> 
> Do you wish to take this up?

Yes

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by RituCs** [comment]
I am not able to run the JS file given in the reference after adding the required library. Please help. Thank You.

**Comment by deeqakkk** [comment]
@RituCs any updates regarding progress?

**Comment by RituCs** [comment]
I have facing issue when trying  to load data from  expreince.js.

**Comment by smaranjitghose** [comment]
1 more day for your deadline

**Comment by RituCs** [comment]
![Screenshot from 2021-06-30 15-49-40](https://user-images.githubusercontent.com/60483448/123944540-d83db800-d9ba-11eb-9918-45528f7eaf42.png)

If everything is ok then I will create pr.

**Comment by padmajabhol** [comment]
Is this issue still open? I want to work on this.

**Comment by aliya-rahmani** [comment]
@padmajabhol, this issue is taken. Do find others with an "up for grab" tag.
