### ISSUE TITLE
Conference Highlight Page Template

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#749]
[Reference](https://codepen.io/dev_loop/full/MWKbJmO)

[Footer Wave Reference](https://codepen.io/goodkatz/pen/LYPGxQz)

## Instructions

- Make the cards square in shape
- The title and subtitle text should be present at the bottom of the cards rather than the center
- All the images should be placed inside `./assets/images/events/conf1/`
- Name the images properly
- The images to be used for the purpose of the demo page are to be taken from [here](https://www.instagram.com/p/B71KSgEDw7I/)
- Do not add a tab in the Nav Bar. The page would be accessed directly with ``./conf_temp.html``
- The CSS file should be `./assets/css/conf_temp.css` and the Js should be ``./assets/js/conf_temp.js``
- To add or remove cards and the details for the same, it should be done from a JSON variable inside conf_temp.js. Check out research.js for reference.

**Comment by Shaishav0507** [comment]
Can I work on this issue ?

**Comment by aliya-rahmani** [comment]
@Shaishav0507 updates?

**Comment by Shaishav0507** [comment]
Working on it

**Comment by anushbhatia** [comment]
you can just send the screenshot of progress by then.

**Comment by deeqakkk** [comment]
@Shaishav0507 any progress updates?

**Comment by Shaishav0507** [comment]
@deeqakkk 
Not yet, as recently got vaccinated.
So have been down for few days.
I don't think I would be able to finish it.

**Comment by Shaishav0507** [comment]
If possible assign to someone else

**Comment by deeqakkk** [comment]
No problem @Shaishav0507 it's fine.

**Comment by padmajabhol** [comment]
Interested. Can you assign this to me?

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by padmajabhol** [comment]
> Assigned for 3 days
![Screenshot (252)](https://user-images.githubusercontent.com/75530516/124309023-c2312280-db87-11eb-850b-01baad9263b6.png)
Is this how it should be? I haven't added the navbar as of now. Please mention the changes.

**Comment by smaranjitghose** [comment]
Ya. Looks cool. Just add the different pages and make sure we can add/remove images/heading using hackathon.js. Remove the text at the bottom for all cards.

Rest looks fine! Try to modify this for mobile view to the best of your abilities before giving a PR [Optional but would be great if you do it]

**Comment by padmajabhol** [comment]
> Ya. Looks cool. Just add the different pages and make sure we can add/remove images/heading using hackathon.js. Remove the text at the bottom for all cards.
> 
> Rest looks fine! Try to modify this for mobile view to the best of your abilities before giving a PR [Optional but would be great if you do it]

Do I need to add the default navbar and footer to this page? It does create some problems.

**Comment by padmajabhol** [comment]
And for this particular UI, you need to give a different class to each of the cards, how can the data be accessed using a JSON file?

**Comment by anushbhatia** [comment]
> > Ya. Looks cool. Just add the different pages and make sure we can add/remove images/heading using hackathon.js. Remove the text at the bottom for all cards.
> > Rest looks fine! Try to modify this for mobile view to the best of your abilities before giving a PR [Optional but would be great if you do it]
> 
> Do I need to add the default navbar and footer to this page? It does create some problems.

Do let me know the problem we will try resolving.

**Comment by anushbhatia** [comment]
> And for this particular UI, you need to give a different class to each of the cards, how can the data be accessed using a JSON file?



> And for this particular UI, you need to give a different class to each of the cards, how can the data be accessed using a JSON file?

As all cards are identical you can have a same class calling all the necessary functionality through it. Only load data through json.

**Comment by padmajabhol** [comment]
> > And for this particular UI, you need to give a different class to each of the cards, how can the data be accessed using a JSON file?
> 
> > And for this particular UI, you need to give a different class to each of the cards, how can the data be accessed using a JSON file?
> 
> As all cards are identical you can have a same class calling all the necessary functionality through it. Only load data through json.

I have texted you regarding the json data on your discord, please see the attached screenshot.

**Comment by Jahnavi-Jonnalagadda** [comment]
@anushbhatia @smaranjitghose I would like to work on this issue, please assign it to me.
