### ISSUE TITLE
Pull_Request_templates.md 

### ISSUE THREAD

**Issue by ritiksoni00** [smaranjitghose/awesome-portfolio-websites#75]
**Description of the enhancement**

There is only the Issue's template can i work on PR_template ????

**Comment by smaranjitghose** [comment]
> **Description of the enhancement**
> 
> There is only the Issue's template can i work on PR_template ????

Usually, Pull Requests are expected to be varied in the description as per the bug solved or feature added. Hence we did not keep a Pull Request Template. If you wish you can add one

**Comment by ritiksoni00** [comment]
you can give me key points so that i can manage to cover as much as i can do...
