### ISSUE TITLE
Travel Vlog Summary Template Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#750]
[Reference](https://codepen.io/suez/full/AXQaEg)

[Footer Wave Reference](https://codepen.io/goodkatz/pen/LYPGxQz)

## Instructions

- Make the cards square in shape
- Add a title like "Trip to the X" before the cards
- For the purpose of the demo, replace the "section 1", "section 2", etc texts with "Day 1", "Day 2", "Day 3", etc
- All the images should be placed inside `./assets/images/travel/trip1/`
- Take the images from unsplash. ( For example tourist spots in New Delhi)
- Name the images properly
- Do not add a tab in the Nav Bar. The page would be accessed directly with ``./travel_temp.html``
- The CSS file should be `./assets/css/travel_temp.css` and the Js should be ``./assets/js/travel_temp.js``
- To add or remove cards and the details for the same, it should be done from a JSON variable inside conf_temp.js. Check out research.js for reference.

**Comment by forkbikash** [comment]
Please assign it to me.

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by forkbikash** [comment]
Hey @smaranjitghose ,
This is how the design should look ?
![Screenshot (114)](https://user-images.githubusercontent.com/70908998/122618003-0104aa00-d0ab-11eb-8ea2-340effc72ff6.png)
![Screenshot (115)](https://user-images.githubusercontent.com/70908998/122618019-08c44e80-d0ab-11eb-9880-0cfd5eb249eb.png)
![Screenshot (116)](https://user-images.githubusercontent.com/70908998/122618042-0feb5c80-d0ab-11eb-802e-1af23a6c0e95.png)
![Screenshot (117)](https://user-images.githubusercontent.com/70908998/122618052-15e13d80-d0ab-11eb-93c5-a335ea8f3117.png)
![Screenshot (118)](https://user-images.githubusercontent.com/70908998/122618067-1b3e8800-d0ab-11eb-8caa-9cba8769b049.png)

**Comment by anushbhatia** [comment]
Increase the height of the image of whatever. So that it can be looked at carefully. Also, try adding an image in portrait mode also.
