### ISSUE TITLE
New Pre-Loader

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#752]
[Reference](https://codepen.io/alterebro/pen/abZzNRo)

__The color should be consistent with the theme of the website__

**Comment by varunwho** [comment]
Hey I can try working on this, please assign this issue to me!

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by varunwho** [comment]
https://user-images.githubusercontent.com/53107832/122638361-452a9580-d111-11eb-9542-3f6e97812d4b.mp4

Like these? (There are 2 samples in this)

**Comment by smaranjitghose** [comment]
No 😅
I specifically gave the atom pre loader reference

**Comment by varunwho** [comment]
> No 😅
> I specifically gave the atom pre loader reference

So I'll use the same without any modifications..?
Colours?

**Comment by smaranjitghose** [comment]
> > No 😅
> > I specifically gave the atom pre loader reference
> 
> So I'll use the same without any modifications..?
> Colours?

Modify the colors. Add a text like John Doe in the bottom, maybe play around with the electrons or the background or the axis. But keep the animation as an atom rotating about an axis

**Comment by varunwho** [comment]
https://user-images.githubusercontent.com/53107832/122669503-5a6bf680-d1db-11eb-9c8d-31c087a061c2.mp4

The original colors weren't visible in this light background and for light mode, we need a light bg so that's why I changed the color to purple and also added a John Doe text with the same animation as "I am a ____"

**Comment by anushbhatia** [comment]
the animation looks great . The only thing that I would want to change is increasing the width of the lines of these rather than changing the background.

**Comment by smaranjitghose** [comment]
Avoid the typewriter effect on the text. Just have it there without any animation
