### ISSUE TITLE
Repository OpenGraph Card 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#753]
- Create a promotional card with dimensions 1280×640px for the repository (This appears when the link to the repository is shared across various social media, even WhatsApp!)
- The Name of the project should be prominent.
- The background should resonate well with the goal of the project

[Sample Reference](https://github.com/smaranjitghose/AppleFoliarAI)

**Comment by varunwho** [comment]
Hey can you assign this to me

**Comment by varunwho** [comment]
How's this?
![awesome-portfolio](https://user-images.githubusercontent.com/53107832/122637084-620f9a80-d10a-11eb-81ae-2bca7bc092a3.png)

**Comment by varunwho** [comment]
### Something like this?
![portfolio](https://user-images.githubusercontent.com/53107832/122638441-b9fdcf80-d111-11eb-8e30-4f622dccc5bf.png)

**Comment by smaranjitghose** [comment]
Please have a look at the reference.

**Comment by varunwho** [comment]
> Please have a look at the reference.

This one right?
![Screenshot 2021-06-20 123719](https://user-images.githubusercontent.com/53107832/122665345-4f599c00-d1c4-11eb-8acd-e1a5594e0a3b.png)



> ### Something like this?
> ![portfolio](https://user-images.githubusercontent.com/53107832/122638441-b9fdcf80-d111-11eb-8e30-4f622dccc5bf.png)

In this, I've used the ParticlesJs background, male-female DP image and the same colour (purple) to resonate with the project.
Did you want something different? Can you tell me more specific details please

**Comment by smaranjitghose** [comment]
I don't have the time to explain this issue any further than what is present in the issue description as I would take much less time to actually finish the work myself.

**Comment by shreya0204** [comment]
Hey, as I understood, You want to say that you want a promotional card design for your projects to be published along with your GitHub repo.

So, I have designed this card attached below.

- It is simple, elegant, as your mentioned reference image.
- It is of size 1280 x 640 as mentioned.
- You can add your project image in place of the reference image along with Project Title.
- Description and link to the repo are totally optional ( can be changed )


![My Post (3)](https://user-images.githubusercontent.com/78657883/123391442-a9d66c00-d5b9-11eb-8d0d-7fe6be737615.png)

Also, let me know if you like it, then you want its code to be in vanilla HTML CSS, or use of any framework is allowed.

**Comment by smaranjitghose** [comment]
@shreya0204 Yes. 

I have put one in the README myself. 

Your suggestion seems cool too. However, avoid using any pictures that indicate a relationship with food and try to select one which is more suitable for our project.

Currenly, we are using HTML, CSS, JS along with some Bootstrap, Jquery,AOS and Particle.jS. We plan to shift to React soon!

**Comment by shreya0204** [comment]
Yes, I have seen which you have put in README.
But, that is am image. So you want an image banner or you want HTML coded banner. Please clarify.

**Comment by smaranjitghose** [comment]
> Yes, I have seen which you have put in README.
> But, that is am image. So you want an image card or you want HTML coded card. Please clarify.

Image

**Comment by shreya0204** [comment]
Okay. That's cool.
So I'll be making one card for your portfolio website. 
The content is the same as you have written in the image in the README file or the content would be different.

**Comment by smaranjitghose** [comment]
> Okay. That's cool.
> So I'll be making one card for your portfolio website.
> The content is the same as you have written in the image in the README file or the content would be different.

It can be different. Feel free to be creative. But should reflect the goal of the project

**Comment by shreya0204** [comment]
Okay thank you for giving flexibility, I'll be sending the card soon.

**Comment by shreya0204** [comment]
I have attached the image card below

![My Post (7)](https://user-images.githubusercontent.com/78657883/123457639-bed6ed80-d601-11eb-8839-4a442a91e618.png)

**Comment by anushbhatia** [comment]
Heading should a little bit more clear and bolder so that they will be able to remember the name of the project at least

**Comment by shreya0204** [comment]
Okay, I'll do that and I have to put the card in the assets --> images section, right?

**Comment by shreya0204** [comment]
Do let me know if any further changes are required

![My Post (8)](https://user-images.githubusercontent.com/78657883/123507804-23895b00-d689-11eb-81af-3c73df8748d3.png)

**Comment by smaranjitghose** [comment]
> Okay, I'll do that and I have to put the card in the assets --> images section, right?

No. Put it in readme_assets

**Comment by smaranjitghose** [comment]
> Do let me know if any further changes are required. I made the title bold so it is clearly visible and catchy.
> 
> ![My Post (8)](https://user-images.githubusercontent.com/78657883/123507804-23895b00-d689-11eb-81af-3c73df8748d3.png)

@shreya0204 Would it be possible for you to take a snapshot of our current version of the website (perhaps different pages) and put it inside the laptop, mobile, tablet and monitor screen objects in the above image?

@anushbhatia what do you think about this suggestion. Let us know

**Comment by shreya0204** [comment]
> @shreya0204
> 
> # Feedback
> * Would it be possible for you to take a snapshot of our current version of the website (perhaps different pages) and put it inside the laptop, mobile, tablet, and monitor screen objects in the above image?
> * Kindly make the text as: " We aim to make your personal website creation simple and elegant af while you can focus on your innovation and learning".
> * Kindly make the words "personal website" "innovation" and "learning" bold
> * Replace the hyphen after the word link with a colon
> * Could you provide a PDF Card for the same with the link embedded. ( Rephrase the text as Check it Out for the PDF and remove the entire text for link)
> 
> @anushbhatia do let us know if you have any further suggestions.

Thank you for your feedback.

Yes, I can change the inside screen images with your website images but it will result in a change in the layout of devices.
Images don't have links embedded in the text. For that either you need a web page function or HTML template.

**Comment by smaranjitghose** [comment]
Yes I am aware of that. I meant, convert the image into a PDF and then have a link.  (That is optional for now)

**Comment by shreya0204** [comment]
Okay, I'll do that.

**Comment by shreya0204** [comment]
I have attached the image below.

- I have put your website images on the screen of the device.
- Changed the text along with the highlighted text.
- Removed Hyphen.
- Convert the image as pdf and put up the link of the repo as Check It Out.


![Capture1](https://user-images.githubusercontent.com/78657883/123535206-09f71a80-d740-11eb-85ca-c145af645773.JPG)



Do let me know if any further changes are required.

**Comment by smaranjitghose** [comment]
Looks Awesome. Please give a PR.

So are you giving one image and one pdf:
- Image: The check it out text is replaced by the original link of the repo (text)
- PDF: Exactly the same, except that the link is embedded.

**Comment by shreya0204** [comment]
Which link should I put up in the hyperlink then?

**Comment by smaranjitghose** [comment]
- Ya both in readme assets.
- The Hyperlink (text) would be in the image

**Comment by shreya0204** [comment]
Yeah. Done!
