### ISSUE TITLE
Project Usage Documentation Website [Python + Markdown]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#754]
__NOTE: This is an issue that exclusively demands knowledge of Python. Please take this up only if you are comfortable beyond basics__

#### Branch for source code: [documentation](https://github.com/smaranjitghose/awesome-portfolio-websites/tree/documentation)

__Please read through the documentation carefully and dedicate some time!__

## Documentation Requirements:

1. Welcome [Refer the readme]
    - About the project
    - Why Open Source?
    - Programs we have been a part of
    - Sneak Peak (Use Gifs)
    - Team
 
 ** Please do beyond just copy-paste. Use your creative writing skills.   
 
 2.  How to start using it?
      - Install Git
      - Setup Git and GitHub Account
      - Navigate to GitHub Repository
      - Fork the repo
      - Clone the repo [ use `git clone ..... --depth 1`]
      - Access the local copy
      - Delete Additional Stuff ( Readme, Readme assets,etc)
 3. Page by Page Changes:
      - Home Page
      - Education Page
      - Project Page
      - Experience Page
      - Research Page
      - Social Media Links
      - Assets
      - SEO
      
  ^^ Detailed guide on which files to open, where to change the content and for what parts? Use screenshots of the changes!
  
  4.  Publishing the portfolio!
      - Save the changes
      - The step by step to push to Github
      - Tip: On making the repository private if desired
      - Deployment + Using Custom Domain:
               - GitHub Pages
               - Netlify
               - AWS Amplify
               
# Directions:
- Some of the content is already there. We expect you to improve it in any or all ways possible!
- Please take only one page at a time to update and state it clearly in the comments below
- First, update the source code, check your build output, push to your own gh-pages branch
- Then in the PR, compare both the `documentation` and `gh-pages` branch (separate PRs but would be counted as a pair)
- Attach a screenshot of your changes
- Attach a link to your own deploy preview on GitHub pages
- Use proper comments in the markdown files

**Comment by Komal-99** [comment]
I would like to put efforts on this issue . the only thing i didn't understand in discussion above is deployment  and custom domains point. and else i would like to ask like its written pages by pages changes but haven't mentioned any specific change and the last like stated above to step by step pushing changes on git hub page so is it documentation git hub page or i just need to make markdown readme 

Don't take me wrong i am really interesting and just asking doubts which confuse me.  you can even check my profile my main techtstack is python

**Comment by smaranjitghose** [comment]
Hey @Komal-99 :

The deployment guide page is meant to help out people to host the website from the code on their GitHub repository

**Comment by Komal-99** [comment]
So all this documentation part will be seperate gut hub page on website na?

**Comment by smaranjitghose** [comment]
This documentation (using mkdocs) will generate a separate website all together on the github-pages branch

**Comment by Komal-99** [comment]
Okay okay.  Haven't use mkdocs but will explore and let you know

**Comment by smaranjitghose** [comment]
Cool.
Don't worry it's fairly simple. You will be able to figure out things in 15 min.
Sure

**Comment by smaranjitghose** [comment]
Any updates @Komal-99 ?

**Comment by Komal-99** [comment]
Ya sure will give by evening actually just yesterday my exams got over

**Comment by Komal-99** [comment]
your discord id?

**Comment by anushbhatia** [comment]
Abyss#9432

**Comment by Komal-99** [comment]
unable to find uh on server and in adding friend it showing you not accepting request

**Comment by smaranjitghose** [comment]
Just post the queries here itself

**Comment by Komal-99** [comment]
sorry for delay i was lit bit busy ..but i just want to ask i have setup mkdocs on my local and it created two files so in index.md now directly i have create readme  design which we want on page

**Comment by smaranjitghose** [comment]
Please understand you are being assigned a simple markdown + python issue for 9 days which is far more than the time required for this.

**Comment by Komal-99** [comment]
ok sorry
