### ISSUE TITLE
Adding gmail icon to footer

### ISSUE THREAD

**Issue by vivek286** [smaranjitghose/awesome-portfolio-websites#757]
I would like to add a Gmail icon to the footer which will redirect the viewer to Gmail compose with already filled Gmail of portfolio user.
preview of the redirected page -

![WhatsApp Image 2021-06-18 at 8 11 07 AM](https://user-images.githubusercontent.com/68116663/122498582-38d4fa00-cfa4-11eb-92da-9338c9e92a7d.jpeg)

@smaranjitghose @anushbhatia If you approve the issue please assign it to me.

**Comment by smaranjitghose** [comment]
The purpose of the contact form is to avoid giving the email
