### ISSUE TITLE
spacing in eduction heading on different screen size

### ISSUE THREAD

**Issue by rushikadivar** [smaranjitghose/awesome-portfolio-websites#762]
heading of the education page are not responsive for different screen size and needs changes in breakpoint

**Comment by rushikadivar** [comment]
please assign me that issue

**Comment by smaranjitghose** [comment]
Assigned for 2 days

**Comment by aliya-rahmani** [comment]
@rushikadivar what's the status of your PR?

**Comment by rushikadivar** [comment]
It's already merged with different issue along with their code

**Comment by aliya-rahmani** [comment]
got it!
