### ISSUE TITLE
Shaking Hand

### ISSUE THREAD

**Issue by Pratham-Mishra178** [smaranjitghose/awesome-portfolio-websites#765]
I want to shake the hand in the hii I'm john doe line

**Comment by Pratham-Mishra178** [comment]
@smaranjitghose assign it to mee please

**Comment by smaranjitghose** [comment]
> @smaranjitghose assign it to mee please

Avoid these spam messages. Once you raise an issue, the maintainers would get back to you in 24-48 hours.

**Comment by Pratham-Mishra178** [comment]
got it
really sorry
