### ISSUE TITLE
A simple webpage using basics of HTML and CSS

### ISSUE THREAD

**Issue by bindaldhara** [smaranjitghose/awesome-portfolio-websites#769]

**Comment by smaranjitghose** [comment]
Please elaborate

**Comment by bindaldhara** [comment]
It is just a simple webpage with the help of basics of HTML and CSS filling a form for joining the gym ..

**Comment by smaranjitghose** [comment]
We do not have a relation with a gym in this project. Please have a look at the codebase and the purpose of the project
