### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/awesome-portfolio-websites#779]
[Reference of toggle button](https://henryegloff.com/how-to-code-a-simple-dark-mode-toggle/) 

### The Colour theme for the dark mode should be followed from google's [material UI](https://material.io/design/color/dark-theme.html)
![image](https://user-images.githubusercontent.com/40017559/122917400-9c33a300-d37b-11eb-9938-ed425250b1e5.png)
Here's typography and relevant background present here.

Also if you want the design link for the file it is present here and you can refer to [this](https://storage.googleapis.com/mio-assets/resources/Material%20Dark%20Theme%20Design%20Kit.fig)

**Comment by ashuydv** [comment]
Plz assign it to me...

**Comment by harshita9621** [comment]
Can I work on this issue?

**Comment by nekkantimadhu** [comment]
Could you please assign me please

**Comment by anushbhatia** [comment]
Assigned for 5 days. Do give regular updates @ashuydv
