### ISSUE TITLE
Add some shadow below profile picture for depth

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#783]
A box shadow can be added below the profile picture on landing page. The picture looks blended into the background. Adding shadow would add some depth.

**Comment by supzi-del** [comment]
![Screenshot (296)](https://user-images.githubusercontent.com/78655439/123147885-33ccea80-d47d-11eb-951d-5716a433938d.png)
It would look like this

**Comment by supzi-del** [comment]
I would like to work on this under LGMSOC.

**Comment by smaranjitghose** [comment]
Assigned for 2 days,

**Comment by harshita9621** [comment]
Can I work on this issue??

**Comment by smaranjitghose** [comment]
> Can I work on this issue??

Please read the issue threads before blindly commenting

**Comment by harshita9621** [comment]
@smaranjitghose I read the issue then only I apply for it.
