### ISSUE TITLE
Home Page for React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#784]
# Description

- Keeping the theme the same, work on converting the current home page's codebase in React
- Be cautious of the routing for the navbar
- Work on the `react` branch

**Comment by ashuydv** [comment]
I want to work on this issue,

**Comment by anushbhatia** [comment]
Assigned for 3 days.

**Comment by ashuydv** [comment]
Can I get more one day, i faced some issues

**Comment by smaranjitghose** [comment]
Sure. Take two!

**Comment by ashuydv** [comment]
On both pages

**Comment by smaranjitghose** [comment]
Cool!

**Comment by smaranjitghose** [comment]
Cool!

**Comment by ashuydv** [comment]
I'll commit the homepage today

**Comment by smaranjitghose** [comment]
Updates?

**Comment by ashuydv** [comment]
Yes, working on footer will commit  inn some time

**Comment by ashuydv** [comment]
I've made a PR, do check it !!
