### ISSUE TITLE
Education Page for React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#785]
# Description

- Keeping the theme the same, work on converting the current Education page's codebase in React
- Be cautious of the routing for the navbar
- Work on the `react` branch

**Comment by ashuydv** [comment]
I want to work on this issue

**Comment by anushbhatia** [comment]
Finish the previous 2 issues then we can assign rest of them.

**Comment by Diksha02** [comment]
I would like to work on this issue

**Comment by sheetalj2205** [comment]
I want to work on this issue in open source day

**Comment by urmi-256** [comment]
Can I work on this issue?

**Comment by deeqakkk** [comment]
Sure @sheetalj2205 , you can work on it.
Keep us updated about progress.

**Comment by deeqakkk** [comment]
@urmi-256 You can look for some another issue. @sheetalj2205 asked for it first, so i hope you understand.
or you both can collectively work on it. Just lemmie know.

**Comment by smaranjitghose** [comment]
@sheetalj2205 This has been shifted too #866
