### ISSUE TITLE
Expereince Page in React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#786]
# Description

- Keeping the theme the same, work on converting the current home page's codebase in React
- Be cautious of the routing for the navbar
- Work on the `react` branch

**Comment by ashuydv** [comment]
I want to work on this issue

**Comment by deeqakkk** [comment]
@ashuydv Assigned for 3 days but keep me updating.

**Comment by smaranjitghose** [comment]
@ashuydv You are already assigned 3 issues including the new Dark mode one. I would love to see you contribute even more. However for the fairness w.r.t. the other participants I am unassigning you from this one temporarily. Please finish at least one react issue and the dark mode one completely. After that, you can continue with this.

**Comment by ashuydv** [comment]
ok

**Comment by luucamay** [comment]
Hello! I would like to work on this issue :)

**Comment by smaranjitghose** [comment]
@luucamay Could you please wait for 1 day before starting to contribute. We have some small changes to be made to the react branch. @anushbhatia would push a couple of commits today.

[Reference for the structure of files](https://github.com/smaranjitghose/doc2pen/tree/master/src)

**Comment by luucamay** [comment]
@smaranjitghose I can wait no problem!

**Comment by smaranjitghose** [comment]
It's done you can proceed.

**Comment by smaranjitghose** [comment]
@luucamay This is being shifted to #869 . Do comment there and you can start working on this directly!
