### ISSUE TITLE
Project Page in React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#787]
# Description

- Keeping the theme the same, work on converting the current project page's codebase in React
- Be cautious of the routing for the navbar
- Work on the `react` branch

**Comment by deeqakkk** [comment]
@ashuydv You can work on it.

**Comment by smaranjitghose** [comment]
@ashuydv You are already assigned over 3 issues including the new Dark mode one. I would love to see you contribute even more. However for the fairness w.r.t. the other participants I am unassigning you from this one temporarily. Please finish at least one react issue and the dark mode one completely. After that, you can continue with this.

**Comment by ashuydv** [comment]
ok

**Comment by Srijan1878** [comment]
Can I work on this issue? @smaranjitghose

**Comment by deeqakkk** [comment]
@Srijan1878 Go ahead to resolve this issue.

**Comment by Srijan1878** [comment]
Okay!

**Comment by deeqakkk** [comment]
@Srijan1878 any update regarding progress?

**Comment by Srijan1878** [comment]
Will submit by tuesday.

**Comment by smaranjitghose** [comment]
The deadline of 3 days is over. Closed due to inactivity

**Comment by Srijan1878** [comment]
I am almost done, I can submit it by tonight.
I wasn't aware of the deadline, apologies for that.
