### ISSUE TITLE
Research Page for React Version

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#788]
# Description

- Keeping the theme the same, work on converting the current research page's codebase in React
- Be cautious of the routing for the navbar
- Work on the `react` branch

**Comment by ashuydv** [comment]
I want to work on this  issue,
My question is the repo same ??

**Comment by anushbhatia** [comment]
Yes just create it in a new branch.

**Comment by anushbhatia** [comment]
Assigned for 3 days.

**Comment by ashuydv** [comment]
I'm working on this, will commit it today

**Comment by smaranjitghose** [comment]
I guess this is still remaining to be worked upon.

BTW, @aliya-rahmani  we have this project in AnitaBorg Open Source Day. If you wish you can apply to continue as a mentor there as well.

**Comment by aliya-rahmani** [comment]
@smaranjitghose I'm sorry but I already selected as a mentor for Greenpeace Planet 4 project, it was before this project was introduced there.

**Comment by smaranjitghose** [comment]
No worries 😎💪

**Comment by aditisingh2412** [comment]
I would like to work on this issue. Can I?

**Comment by deeqakkk** [comment]
@aditisingh2412 assigned for 3 days!

**Comment by smaranjitghose** [comment]
@aditisingh2412 This is shifted to #868
