### ISSUE TITLE
Decrease height of volunteer card images

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#793]
The images of volunteer cards have 300px which is a little enlarged. It should be perfectly square.
I want to add the following changes:

Before:
![image](https://user-images.githubusercontent.com/78655439/123330523-c0e67100-d55b-11eb-84e6-cb88e5f5d61a.png)

After:
![Screenshot (304)](https://user-images.githubusercontent.com/78655439/123330560-ce036000-d55b-11eb-9f58-ebf54cce9d0f.png)

**Comment by anushbhatia** [comment]
Assigned for 2 days.

**Comment by smaranjitghose** [comment]
@supzi-del We now have a dark mode too for the website. Please ensure that your changes work well for both the modes as well as different screen sizes

**Comment by smaranjitghose** [comment]
@supzi-del 

Please change the title to "Open Source" ☺


Additionally, I am planning to change the UI of the cards to a direction aware hover effect. [Reference](https://codepen.io/noeldelgado/pen/pGwFx). If you wish you can raise this in a separate issue and continue after the PR for current issue is merged.

**Comment by supzi-del** [comment]
> @supzi-del
> 
> Please change the title to "Open Source" ☺
> 
> Additionally, I am planning to change the UI of the cards to a direction aware hover effect. [Reference](https://codepen.io/noeldelgado/pen/pGwFx). If you wish you can raise this in a separate issue and continue after the PR for current issue is merged.

Okay, sure :)
But is it right to add 30daysofFlutter and GarudaHacks under open source?

**Comment by smaranjitghose** [comment]
> > @supzi-del
> > Please change the title to "Open Source" ☺
> > Additionally, I am planning to change the UI of the cards to a direction aware hover effect. [Reference](https://codepen.io/noeldelgado/pen/pGwFx). If you wish you can raise this in a separate issue and continue after the PR for current issue is merged.
> 
> Okay, sure :)
> But is it right to add 30daysofFlutter and GarudaHacks under open source?

Nope. Remove them

**Comment by supzi-del** [comment]
![image](https://user-images.githubusercontent.com/78655439/123512049-d87c4180-d6a2-11eb-9709-2e3cd5dc084e.png)
The open source section will look like this. I will make a PR if this is okay.

**Comment by supzi-del** [comment]
![image](https://user-images.githubusercontent.com/78655439/123512141-796afc80-d6a3-11eb-817c-6e5e2472dd39.png)

Also, the extra space below the description can be removed, it will look like this ☝️
Should I make a new issue for this?

**Comment by smaranjitghose** [comment]
> ![image](https://user-images.githubusercontent.com/78655439/123512049-d87c4180-d6a2-11eb-9709-2e3cd5dc084e.png)
> The open source section will look like this. I will make a PR if this is okay.

Go ahead please!

**Comment by smaranjitghose** [comment]
> ![image](https://user-images.githubusercontent.com/78655439/123512141-796afc80-d6a3-11eb-817c-6e5e2472dd39.png)
> 
> Also, the extra space below the description can be removed, it will look like this ☝️
> Should I make a new issue for this?

Not required. Just raise another PR and refer the same issue. Keep in mind all the cards should be responsive such if one card becomes larger due the greater amount of text in it, the others should also increase in size irrespective of the amount of text being lesser

**Comment by supzi-del** [comment]
Anything else to be done before closing this issue?

**Comment by smaranjitghose** [comment]
> @supzi-del
> 
> Please change the title to "Open Source" ☺
> 
> Additionally, I am planning to change the UI of the cards to a direction aware hover effect. [Reference](https://codepen.io/noeldelgado/pen/pGwFx). If you wish you can raise this in a separate issue and continue after the PR for current issue is merged.

This one^^. If you are continuing with that effect, do raise a new issue. Else let me know, I'll raise one

**Comment by supzi-del** [comment]
> > @supzi-del
> > Please change the title to "Open Source" ☺
> > Additionally, I am planning to change the UI of the cards to a direction aware hover effect. [Reference](https://codepen.io/noeldelgado/pen/pGwFx). If you wish you can raise this in a separate issue and continue after the PR for current issue is merged.
> 
> This one^^. If you are continuing with that effect, do raise a new issue. Else let me know, I'll raise one

Okay, you can raise it and anyone could work on it as I'm not that familiar with this..
