### ISSUE TITLE
Website Links are not provided in the Footer Section

### ISSUE THREAD

**Issue by Namangujral1** [smaranjitghose/awesome-portfolio-websites#794]
I have seen the website and find an issue that in footer section, the links or buttons of your social media handles are not working. Please approve this issue and assign it to me . I want to work for this under LGM SOC'21

So please provide me your social media handles to update them

**Comment by smaranjitghose** [comment]
It's not supposed to work. This project is ought be used as a template and hence we have not provided any actual links

**Comment by Namangujral1** [comment]
> It's not supposed to work. This project is ought be used as a template and hence we have not provided any actual links

Okkk.... No issues
