### ISSUE TITLE
Footer UI Tweak

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#797]
![footer_update](https://user-images.githubusercontent.com/46641503/123427851-c2a74780-d5e2-11eb-9962-7a5903a595ba.png)

Remove the elements pointed out above including the line.

**Comment by supzi-del** [comment]
I would like to work on this.

**Comment by smaranjitghose** [comment]
Since this is a simple issue, I am giving 1 day for this. If you need more time, we can extend the deadline

**Comment by supzi-del** [comment]
![image](https://user-images.githubusercontent.com/78655439/123432199-bd98c700-d5e7-11eb-9cd0-7df802bae17a.png)

**Comment by supzi-del** [comment]
For this issue, hr tag should be removed. However there's no such tag in the repo.

**Comment by smaranjitghose** [comment]
I just noticed. Due to some prior PRs, we now have app.js and main.js which do the same thing. The <hr> tag is present in the app.js but main.js. This is a redundancy issue I believe.

Could you please safely remove the main.js insuring everything works well when we use the app.js for all the pages. I am upgrading the level of the issue.

**Comment by supzi-del** [comment]
Actually, when I open index.html in live server, it is still showing the old version (without dark mode, without new footer, without new loader).
So unless it is updated, I cannot see the changes.

**Comment by smaranjitghose** [comment]
![Live_Server](https://user-images.githubusercontent.com/46641503/123439758-ac53b880-d5ef-11eb-89bc-aa10ff819161.png)

For me, when I use the live server it does show the current codebase.

Pull the changes from upstream (this repo) to your forked repo

**Comment by supzi-del** [comment]
Oh okay, got it now. Thanks
