### ISSUE TITLE
Website Color Consistency

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#798]
![A_1](https://user-images.githubusercontent.com/46641503/123428136-1e71d080-d5e3-11eb-9124-58d8c30d6b5e.png)
![footer_update](https://user-images.githubusercontent.com/46641503/123428143-1fa2fd80-d5e3-11eb-92b8-705b3666d76c.png)

- The footer form, illustration(s), underscores, title text and the scroll bar should be of the same color. 
- Go ahead with a shade of purple or mauve
- This should be done for all the pages in the website

**Comment by Amrutha1101** [comment]
Can I get assigned for this issue under LGM-SOC?

**Comment by deeqakkk** [comment]
@Amrutha1101 Yes, you can work on it.

**Comment by Amrutha1101** [comment]
![Screenshot (113)](https://user-images.githubusercontent.com/63070698/123518142-2c4a5300-d6c2-11eb-99d4-f71d44d80e6a.png)
Should I have to change these text colors too to purple?
But I think white text color looks good.

**Comment by anushbhatia** [comment]
No text colours look great in white don't change them

**Comment by anushbhatia** [comment]
https://material.io/design/color/dark-theme.html#ui-application here's a purple what say @smaranjitghose i think this will look good

**Comment by Amrutha1101** [comment]
![IMG_20210628_160557](https://user-images.githubusercontent.com/63070698/123623203-ccbb8700-d82a-11eb-9169-58b0910b7154.jpg)
This one ?

**Comment by smaranjitghose** [comment]
> ![IMG_20210628_160557](https://user-images.githubusercontent.com/63070698/123623203-ccbb8700-d82a-11eb-9169-58b0910b7154.jpg)
> This one ?

Yep

**Comment by Amrutha1101** [comment]
![Screenshot (114)](https://user-images.githubusercontent.com/63070698/123775684-3bace480-d8ec-11eb-8049-ef9b3fb51420.png)
![Screenshot (115)](https://user-images.githubusercontent.com/63070698/123775704-40719880-d8ec-11eb-9c63-91cdcfb83397.png)
![Screenshot (116)](https://user-images.githubusercontent.com/63070698/123775721-436c8900-d8ec-11eb-9e44-f5e3e176d5c9.png)
![Screenshot (117)](https://user-images.githubusercontent.com/63070698/123775729-46677980-d8ec-11eb-9474-c72d60d5eadf.png)
![Screenshot (118)](https://user-images.githubusercontent.com/63070698/123775744-48c9d380-d8ec-11eb-86f5-7f8f442f60c2.png)
![Screenshot (120)](https://user-images.githubusercontent.com/63070698/123775759-4b2c2d80-d8ec-11eb-8a45-5760855585e1.png)
Let me know if any changes to be made..

**Comment by smaranjitghose** [comment]
Please use this color palette: https://www.color-hex.com/color-palette/10715

- Different shades for different elements
- #4e00bb for the text
- The color you have used for the illustrations is perfect.

You can make this small change and give a PR directly
