### ISSUE TITLE
Research Page Button Bug Dark Mode

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#799]
![Research_Page_color](https://user-images.githubusercontent.com/46641503/123428819-d8693c80-d5e3-11eb-8b02-b94ceddbe830.png)

For reference about the button color, have a look at the gifs of the previous version of the website given in the readme

**Comment by Sarthakjain594** [comment]
Heyy Can I work on this issue ?

**Comment by smaranjitghose** [comment]
@Sarthakjain594  Assigned for 2 days
