### ISSUE TITLE
Experience Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#80]
( Try to have cards depicting a picture or graphics related to the workplace + Role Name + Role Time + Bullet points about the work done + A micro-animation for an icon redirecting to any letter if available)
- [ ] Internships/Jobs
- [ ] Mentorship
- [ ] Freelance/Volunteering

** Please feel free to use your own academic data or use my or @anushbhatia 's.

**Comment by N00Bmaster2810** [comment]
Can I work on this

**Comment by salonilakhotia** [comment]
Please assign any part from the above to me

**Comment by smaranjitghose** [comment]
@salonilakhotia Can you please improve the Internship/Jobs Section
@N00Bmaster2810 Can you please improve the Mentorship Section.

You folks can work on the dark mode of the same.

Does this sound good?

**Comment by N00Bmaster2810** [comment]
@smaranjitghose sir, I can do the mentorship section, thanks

**Comment by raksha009** [comment]
I would like to work on the volunteering section of the project. Plz assign it to me

**Comment by salonilakhotia** [comment]
@smaranjitghose sir, I can do.Thanks

**Comment by Tejas1510** [comment]
I want to work on this issue

**Comment by smaranjitghose** [comment]
> I want to work on this issue

@Tejas1510, The above participants have 5 days after that you can take over

**Comment by smaranjitghose** [comment]
@salonilakhotia  Take two more days for this. After that may I expect a PR?
@Tejas1510 Take up the work for the dark mode of the page. For UI related doubts regarding the same contact @anushbhatia

**Comment by mharshita** [comment]
@anushbhatia  @smaranjitghose  I want to work on experience page. Please assign this to me.
