### ISSUE TITLE
Make the social media buttons on the Home Page more prominent w.r.t the background

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#800]
# Reference

#### Light Mode

![social_media_buttona](https://user-images.githubusercontent.com/46641503/123429435-955b9900-d5e4-11eb-8fa9-c0ad21e7bb7e.png)

#### Dark Mode

![social_media_button_dark](https://user-images.githubusercontent.com/46641503/123429622-c50aa100-d5e4-11eb-8312-a91d3a24c081.png)

# Note:

- The micro animations should not be messed up
- On Hover, color change and raise should remain as we have in the current version

**Comment by puneetkaur2929** [comment]
@smaranjitghose 
You want these changes in both the modes?

**Comment by aliya-rahmani** [comment]
@puneetkaur2929 these changes are only for the dark mode, but the already persisting hover effects shouldn't be affected. You need to make the according to the reference. I'm assigning you this issue for 3 days.

**Comment by Shivangi-27** [comment]
I want to try to solve this issue in light mode?

**Comment by smaranjitghose** [comment]
@Shivangi-27 Assigned for 2 days

**Comment by Shivangi-27** [comment]
![image](https://user-images.githubusercontent.com/72151453/125400081-12518580-e3cf-11eb-87db-5f224294be86.png)

I removed the background color of all the icons for both light and dark themes. Is this alright or do I have to change the background color of all the icons

**Comment by Shivangi-27** [comment]
I removed the background color of all the icons for both light and dark themes. Is this correct or do I have to change the background color of all the icons?

![image](https://user-images.githubusercontent.com/72151453/125400640-c6eba700-e3cf-11eb-8bb8-eea083df1cb3.png)

**Comment by anushbhatia** [comment]
> I removed the background color of all the icons for both light and dark themes. Is this correct or do I have to change the background color of all the icons?
> 
> ![image](https://user-images.githubusercontent.com/72151453/125400640-c6eba700-e3cf-11eb-8bb8-eea083df1cb3.png)
> 
> ![image](https://user-images.githubusercontent.com/72151453/125400744-e5ea3900-e3cf-11eb-9ace-aa5d4b8ddede.png)

Some logos like GitHub and others won't be visible in that case so we can't use this.

**Comment by Shivangi-27** [comment]
Ok i will try to set the perfect background color in both the modes

**Comment by Shivangi-27** [comment]
I changed the background color of all the icons for both light and dark themes.

![image](https://user-images.githubusercontent.com/72151453/125556209-b7e6156b-1c77-4097-882d-5923f507ebf8.png)

![image](https://user-images.githubusercontent.com/72151453/125556224-336eb243-0803-4e19-a917-3b3a6b67ecc8.png)

**Comment by smaranjitghose** [comment]
It looks absolutely weird w.r.t the UI.

Just use two different shades of black, one is already done for the background of the page, for the icon background play around with the color palette and figure it out. Perhaps something closer to that of the navbar background color. There is no need to modify the light mode icon background color.

Please understand, if we spend time and give you the exact color codes, the purpose of raising the issue is over and we can simply push a commit for the same

**Comment by purohitmansi** [comment]
Please assign this to me.
I want to give it a try.

**Comment by Shivangi-27** [comment]
.dark-theme.socialicon{
  background-color: #423F3E;
}
I am applying this in home.css but it's not working. Am I wrong somewhere??

**Comment by anushbhatia** [comment]
> .dark-theme.socialicon{
> background-color: #423F3E;
> }
> I am applying this in home.css but it's not working. Am I wrong somewhere??

there are already elements present in the dark mode for particular elements just look through them

Refer to these variables and try adding an ew variable or modifying colour here so the colours will get updated automatically.
https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/assets/css/home.css
`html[data-theme="dark"] {
  --col-icon:white;
  --col-bd-radius:black;
  --col-bd-icon:transparent;
  --col-box-shadow: 5px 5px 10px rgba(22, 21, 21, 0.7) , -5px -5px 10px rgba(255,255,255,0.1);
  --col-box-shadow-hover:inset rgba(255, 255, 255, 1) 2px 2px 4px, 
 inset rgba(255, 255, 255, 0.5) -2px -2px 4px;
  --col-icon-dribbble: #ea4c89;
  --col-icon-linkedin: #0e76a8;
  --col-icon-medium: #00ab6c;
  --col-icon-kaggle: #41aff3;
  --col-icon-instagram: rgb(201, 94, 174);
  --col-icon-mail:rgb(209, 82, 82);
  --col-icon-google-scholar:#3cba54;
  --col-icon-codeforces:rgb(19, 145, 184);
  --col-icon-leetcode:rgb(255, 181, 62);
  --col-white: #fff;
}`

How this works is according to the mode presents the CSS will automatically fetch the variable and add that particular colour to it directly.

**Comment by smaranjitghose** [comment]
Resolved
