### ISSUE TITLE
Fix the responsiveness issues for the Expereince Page in Mobile Screens

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#801]
Self Explanatory

**Comment by Abhishek-Sahoo** [comment]
Can I work on this issue?

**Comment by RiyaGupta89** [comment]
Can i work on this issue?

**Comment by smaranjitghose** [comment]
@RiyaGupta89  Assigned for 2 days.

**Comment by aliya-rahmani** [comment]
@RiyaGupta89 updates?

**Comment by Atif0604** [comment]
@aliya-rahmani @smaranjitghose can i work on this 
I'm a participant of LGMSOC-21

**Comment by aliya-rahmani** [comment]
@Atif0604 you have 3 days to work.
