### ISSUE TITLE
Research Page Mobile Screen Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#802]
There is a huge gap between the illustration and the cards in the research page for Mobile Screens. Reduce that

![Research_Page_mobile_Screen](https://user-images.githubusercontent.com/46641503/123430246-95a86400-d5e5-11eb-9d77-0bc4cf417a60.png)

**Comment by Sarthakjain594** [comment]
heyyy , I am a LGMSOC'21 participant . Can I work on this issue ?

**Comment by deeqakkk** [comment]
You can work on it @Sarthakjain594 !
