### ISSUE TITLE
Expereince Page Dark Mode Card UI Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#803]
# Current UI

![Current_Expereince](https://user-images.githubusercontent.com/46641503/123431199-a1485a80-d5e6-11eb-9a71-8f05a6339135.png)

# Sample Reference for Expected UI

![Experience_Page](https://user-images.githubusercontent.com/46641503/123431080-81189b80-d5e6-11eb-946a-e420747e0d7f.png)

This should be done for all of the cards

**Comment by Sarthakjain594** [comment]
heyy , I would like to work o this issue ?

**Comment by smaranjitghose** [comment]
@Sarthakjain594  Assigned for 2 days

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGM-SOC

**Comment by aliya-rahmani** [comment]
@Amrutha1101 it's already assigned, look for other unassigned issues.

**Comment by Sarthakjain594** [comment]
Heyy I have resolved that issue but i wanna ask that . Is the dark color to be applied to all the cards in the page or only these first three cards .

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGM-SOC

**Comment by aliya-rahmani** [comment]
@Amrutha1101 you have 3 days to work on it.

**Comment by Amrutha1101** [comment]
![Screenshot (129)](https://user-images.githubusercontent.com/63070698/124284073-3d83db80-db6a-11eb-85ae-af18bb1044f2.png)
What about the (background) open source cards in the page?

**Comment by Amrutha1101** [comment]
![Screenshot (135)](https://user-images.githubusercontent.com/63070698/124510180-e5aad600-ddf0-11eb-8e51-35f2711110b3.png)
What colors do you want me to add for the highlighted ones?

**Comment by smaranjitghose** [comment]
Have a look at the issue description for #884 @Amrutha1101

**Comment by smaranjitghose** [comment]
@Amrutha1101 Please try to finish this asap

**Comment by Amrutha1101** [comment]
> @Amrutha1101 Please try to finish this asap

I'll make a PR by the end of the day :)

**Comment by smaranjitghose** [comment]
Resolved and would be improved in further issues
