### ISSUE TITLE
Footer Form Mircro animation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#804]
[Reference](https://codepen.io/MichaelArestad/details/ohLIa)

- The 4th one is the effect we prefer
- Modify the label and the helper texts in the form accordingly 
- The colors should be consistent with the rest of the website
- __Before Raising a PR, please inspect your changes and ensure that the footer is responsive for all screen sizes on all pages__

**Comment by shreyanshu07** [comment]
Please assign me this work under LGMSoC'21 . I am looking forward to work on this feature. I will ensure the responsiveness remains the same .

**Comment by deeqakkk** [comment]
@shreyanshu07 You can work on it.

**Comment by smaranjitghose** [comment]
Assigned for 2 days

**Comment by shreyanshu07** [comment]
![image_2021-06-28_130835](https://user-images.githubusercontent.com/72155853/123598269-f2886200-d811-11eb-807a-9b718fc7424c.png)
@smaranjitghose @deeqakkk  Is it okay ? Or any color change is needed ?
Please revert me back if any change is need .

**Comment by deeqakkk** [comment]
@shreyanshu07 change background color of the name and email label to #43D1AF and also when we click on the text field , label should move to extreme left of text field.

**Comment by shreyanshu07** [comment]
@deeqakkk sir I have done the changes . It is shown in the pull request section
![image](https://user-images.githubusercontent.com/72155853/123797415-c8af6800-d903-11eb-9cf2-094da0f6e59e.png)
The label is sliding to very left but I am not able to take the screenshot properly.
I am attaching the link of deployment.
https://awesome-portfolio-websites-9tjgsw0lw-smaranjitghose.vercel.app

**Comment by deeqakkk** [comment]
@shreyanshu07 I saw your deployment and everything is almost fine, you just need to remove bottom margin of the labels which is making a bottom line gap effect.

**Comment by shreyanshu07** [comment]
@deeqakkk https://awesome-portfolio-websites-ne7xucbfr-smaranjitghose.vercel.app
Pls review it . I have removed the greenish margin.
![image](https://user-images.githubusercontent.com/72155853/123818625-c571a780-d916-11eb-9c8b-bcc02a8d9f68.png)

**Comment by deeqakkk** [comment]
![image](https://user-images.githubusercontent.com/78724676/123820006-dcfd6000-d917-11eb-8a4b-01d6a98d5821.png)
@shreyanshu07 You just need to remove this and you are good to go.
Go through the reference once again it will help you.

**Comment by deeqakkk** [comment]
@smaranjitghose please check this issue .

**Comment by smaranjitghose** [comment]
@shreyanshu07 Any updates?
