### ISSUE TITLE
Parallax Photo Carosel for Event Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#805]
[Reference](https://codepen.io/creativeocean/pen/mdROBXx)

- The footer and the navbar should be used as it is present in the other pages
- Do not add a tab in the Nav Bar. The page would be accessed directly with ``./event.html``
- The CSS file should be `./assets/css/event.css` and the Js should be ``./assets/js/event.js``
- All the images should be placed inside  `./assets/images/event/`
- Name the images properly
- The images to be used for the purpose of the demo page are to be taken from [here](https://www.instagram.com/p/B71KSgEDw7I/)
- To add or remove cards and the details for the same, it should be done from a JSON variable inside event.js. Check out research.js for reference.
- **Do not make a light mode for this**

**Comment by Ayush7614** [comment]
@smaranjitghose sir i have to work on this plss assign me but not under LGM SOC

**Comment by aliya-rahmani** [comment]
@Ayush7614 what do you mean?

**Comment by Ayush7614** [comment]
Maam i am not Participant of LGM SOC but i was contributing to open source and project this thing i have to say

**Comment by aliya-rahmani** [comment]
Alright, you can fix the other issue first, then I'll assign you this one.

**Comment by Ayush7614** [comment]
ok

**Comment by Ayush7614** [comment]
@aliya-rahmani assign me please

**Comment by aliya-rahmani** [comment]
@Ayush7614 updates?

**Comment by Ananya-Misra** [comment]
@smaranjitghose Please assign this issue to me under LGMSOC.

**Comment by deeqakkk** [comment]
@Ananya-Misra Yes , Go ahead to solve this issue.
and try to solve all your assigend issues before commenting for next one. :)

**Comment by Ananya-Misra** [comment]
@deeqakkk Will do so.

**Comment by smaranjitghose** [comment]
@Ananya-Misra any updates?

**Comment by Ananya-Misra** [comment]
@smaranjitghose  Yes, I am working on it I will make the PR by tonight or by tomorrow morning at the most.
