### ISSUE TITLE
PreLoader UI Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#806]
[Reference](https://codepen.io/webcraftsman/pen/xxgvzwj)

- Change the background of the current pre-loader to the shade of the black shown above
- The atom animation should remain the same
- Add the Fade in Text Animation and change the text to a quote like "I could either watch it happen or be a part of it". The prepositions should not be made bold
- Make sure the preloader works for all the pages and all screen sizes (Use chrome dev tools).
- In the PR description, upload a clip of the the above testing

**Comment by rachejazz** [comment]
Please assign this to me
