### ISSUE TITLE
404 UI Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#807]
[Reference](https://codepen.io/uiswarup/pen/dyoyLOp)

- All the images/illustrations should be local and present inside `./assets/images/404/`
- Add the Go Back to Home Button
- Modify the color scheme according to the theme of the website

**Comment by jigar-sable** [comment]
![image](https://user-images.githubusercontent.com/64949957/123523151-87d70980-d6df-11eb-87c4-a7e43882dcb4.png)

- #### Should it be like that or any other design. It's animated and responsive too.

**Comment by RiyaGupta89** [comment]
Can i work on this issue?

**Comment by smaranjitghose** [comment]
- The size of the svg should be proportionate to the page
- Make sure the Back button redirects to the Home Page
- The overall animation should not change
- All assets should be local

Do raise a PR
