### ISSUE TITLE
add some badges to README

### ISSUE THREAD

**Issue by Umesh-01** [smaranjitghose/awesome-portfolio-websites#809]
### Description
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

### Solution
**I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.**
I can add them below the image or above the image wherever as u want @smaranjitghose 

![image](https://user-images.githubusercontent.com/83420185/123468072-e7191900-d60e-11eb-9d31-0e158f5081ec.png)

### Work under/as
- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@deeqakkk @anushbhatia @smaranjitghose should I work on this??

I will add badges like this, also if u want some specific only then I can do that

![image](https://user-images.githubusercontent.com/83420185/123469150-4e839880-d610-11eb-9340-7ff7564bb9c7.png)

**Comment by deeqakkk** [comment]
@Umesh-01 Yes, sure you can work on this.
