### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#81]
We intend to use Fast pages for this [ You will be submitting the patch files as Pull Requests to this repo and the corresponding changes as PRs to another repo]

Please checkout fastpages [repo](https://github.com/fastai/fastpages) to learn more about it.

# Suggested Tasks:

- [ ] Work on creating a custom.css file
- [ ] Improve the Navigation Bar ( Try to make it consistent with that of this project)
- [ ] Create Dark Mode
- [ ] Add a default landing page to the blog ( Make changes to the index.html)
- [ ] Custom Fonts
- [ ] Improve Footer

**Comment by ALOKARYAN51** [comment]
I would like to work on this issue.

**Comment by spiyush0212** [comment]
Sir, I would like to work on this issue;
1) Improve Nav Bar and
2) Improve Footer
Can you please assign this to me?

**Comment by avinashkranjan** [comment]
I'd have to learn Fast pages..Gimme some time..but I'd like to work on this issue..

**Comment by UshasriMavuri1999** [comment]
Sir, I would like to work on this issue (i) Adding default landing page to the blog (ii) Creating dark mode.
