### ISSUE TITLE
add skills page and skill attribute in navbar

### ISSUE THREAD

**Issue by anandalisha** [smaranjitghose/awesome-portfolio-websites#811]
## Description
want to add a page showing  professional skills of the person and as a new attribute in the navbar

## Solution
![Screenshot (74)](https://user-images.githubusercontent.com/55910525/123493854-7805e980-d63b-11eb-8e7b-98c3550df089.png)
want to create something like this

**Comment by anandalisha** [comment]
@smaranjitghose  @anushbhatia Please assign me under LGMSOC!!

**Comment by deeqakkk** [comment]
@anandalisha Yes, you can work on it.

**Comment by Ak-panchal** [comment]
p;z assign me under LGMSOC!!

**Comment by smaranjitghose** [comment]
Skill Page would be added in the end
