### ISSUE TITLE
Fix responsiveness in Home Page

### ISSUE THREAD

**Issue by Yunika-Bajracharya** [smaranjitghose/awesome-portfolio-websites#817]
<img width="954" alt="error" src="https://user-images.githubusercontent.com/60802409/123531229-9c88c100-d722-11eb-81cd-11d65a52b4cd.PNG">

The text **Hi, I am John Doe** is hidden when the screen size is 1355px * 542px and less.

Also, the social media icons can be made a bit smaller and fit into a single row.

**Comment by RiyaGupta89** [comment]
Can i work on this issue?

**Comment by smaranjitghose** [comment]
Assigned for 2 days

**Comment by smaranjitghose** [comment]
Check for other screen sizes especially on mobile screens as well!
