### ISSUE TITLE
Add Guidelines for Raising a New Isuue in README

### ISSUE THREAD

**Issue by Yunika-Bajracharya** [smaranjitghose/awesome-portfolio-websites#818]

**Comment by RiyaGupta89** [comment]
Can i work on this issue?

**Comment by smaranjitghose** [comment]
Actually, we are shifting everything to the Contributing.MD. Instead you can give a PR to Remove the Contribution related content from the ReadMe, put up a banner image for " Set up and Contribution guidelines" which redirects to Contributing.MD

**Comment by Yunika-Bajracharya** [comment]
> verything to the Contributing.MD. Instead you can give a PR to Remove the Contribution related content from the ReadMe, put up a banner image for " Set up and Contribution guidelines" which redirects to Contributing.MD

**Comment by smaranjitghose** [comment]
Assigned for 2 days
