### ISSUE TITLE
Research Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#82]
- [ ] The UI can be similar to a Google Scholar profile
- [ ] Try experimenting with latex.now.sh
-  Have a button to generate BibTex

**Comment by akshaykrishh** [comment]
Can I work on the Research Page?

**Comment by smaranjitghose** [comment]
2 more days for your 1st PR @akshaykrishh. Cool? If you have doubts regarding the UI get in touch with @anushbhatia  over slack

**Comment by mharshita** [comment]
@smaranjitghose Okay!

**Comment by anushbhatia** [comment]
@swapniltripathi123 pm me on slack
