### ISSUE TITLE
Change text color of work experience section to make it more readable in dark mode. 

### ISSUE THREAD

**Issue by deeqakkk** [smaranjitghose/awesome-portfolio-websites#829]
![image](https://user-images.githubusercontent.com/78724676/123586330-2d829980-d802-11eb-88a3-55aeed144e6c.png)

**Comment by Amrutha1101** [comment]
I can work on this issue under LGM-SOC.

**Comment by smaranjitghose** [comment]
Check #803 

Closed: Duplicate.

@Amrutha1101 do comment there. If the assigned participant is unable to complete it within the deadline, you can take over

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGM-SOC
