### ISSUE TITLE
Education Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#83]
** Do Improvements in the UI, Add Animations
# Suggested Features
- [ ] Formal Education Section [ Try to have it in a timeline or branches of a tree theme]
- [ ] Summer Schools and MOOCs Section
- [ ] Badges Section

**Comment by RiyaAgrawal17** [comment]
I want to contribute to some of these features.

**Comment by N00Bmaster2810** [comment]
I want to work on any one of these. Please consider me

**Comment by anushbhatia** [comment]
tell me which subtask u will be working on @RiyaAgrawal17 @N00Bmaster2810

**Comment by N00Bmaster2810** [comment]
@anushbhatia sir I can work on the badges one

**Comment by N00Bmaster2810** [comment]
@anushbhatia  sir we have to only change the animations, UI in this section or the content too?

**Comment by RiyaAgrawal17** [comment]
@anushbhatia sir I can work on formal education and badges section

**Comment by anushbhatia** [comment]
@N00Bmaster2810 -badges
@RiyaAgrawal17 -formal education

**Comment by raksha009** [comment]
Hi, plz guide a bit about what do we have to do in MOOC section and Summer schools section. I am unable to find the Summer School section on the page.

**Comment by Rishikakanojia** [comment]
Hi, i would like to work on MOOCs section , can you suggest me ways to get started?

**Comment by anushbhatia** [comment]
@Rishikakanojia this is assigned for @raksha009 for 2 dyas if she isn't able to do it then u can continue

**Comment by raksha009** [comment]
@anushbhatia plz guide a bit about what do we have to do in MOOC section and Summer schools section. I am unable to find the Summer School section on the page.
Also, am i assigned mooc section or sunmer school one !?

**Comment by smaranjitghose** [comment]
> @anushbhatia plz guide a bit about what do we have to do in MOOC section and Summer schools section. I am unable to find the Summer School section on the page.
> Also, am i assigned mooc section or sunmer school one !?

Basically the MOOC/Summer School section is to potray any short term course done online like Stanford Summer School,etc. You need improve the UI

**Comment by raksha009** [comment]
Ohkay ty

**Comment by raksha009** [comment]
@anushbhatia @smaranjitghose is the MOOCs section (Massive  Open Online Courses)!? Also, what content should I add in there?

**Comment by smaranjitghose** [comment]
> asically the MOOC/Summer School section is to potray any short term course done online like Stanford Summer School,etc. You need improve the UI

@raksha009 You are right! And this is what the section is about ^^^

**Comment by smaranjitghose** [comment]
> @anushbhatia @smaranjitghose is the MOOCs section (Massive Open Online Courses)!? Also, what content should I add in there?

Put random coursera specializations (check the popular ones), Google Adwords Certification and similar stuff.

**Comment by raksha009** [comment]
Okayy. Ty

**Comment by smaranjitghose** [comment]
@raksha009 @RiyaAgrawal17 @N00Bmaster2810.
Three more days for this. After that, I expect all of your first PR related to this issue.
 [ For discussing your designs, getting feedback, please make use of the common slack channel so that we can interact more and the mentors and admins can assist you in an efficient manner if required ]

**Comment by srishtij2000** [comment]
Okay I will do
