### ISSUE TITLE
Added Issue Templates in the Issue section

### ISSUE THREAD

**Issue by Ayush7614** [smaranjitghose/awesome-portfolio-websites#839]
Added Issue Templates like Featue request,Bug this type

**Comment by Ayush7614** [comment]
Plss assign me this issue @smaranjitghose sir

**Comment by Ayush7614** [comment]
@aliya-rahmani maam i am not the LGM SOC participant i am only contribute to project

**Comment by aliya-rahmani** [comment]
I've removed the tag so it'll be fine for you

**Comment by Ayush7614** [comment]
Yes maam

**Comment by Cartikx3** [comment]
I am a LGM SOC participant can i contribute to this project . If yes please assign this to me .
