### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#84]
Suggested Features:
- [ ] Logo
- [ ] Quote
- [ ] Contact Form - Name, Email, Message
- [ ] Social Media Links

**Comment by ymaheshwari1** [comment]
I want to work on this issue.

**Comment by debanshu08** [comment]
I can contribute to the footer.

**Comment by Rishikeshrajrxl** [comment]
i want to work on footer

**Comment by N00Bmaster2810** [comment]
Can I work on the contact form in the footer

**Comment by RiyaAgrawal17** [comment]
I want to contribute to this section.

**Comment by N00Bmaster2810** [comment]
I was trying to publish a new branch on the forked version of this repo but I was unable to do so. Kindly help how to move forward

**Comment by ymaheshwari1** [comment]
@N00Bmaster2810 Which command you are executing, because I am able to create a new branch.

**Comment by N00Bmaster2810** [comment]
I was using github desktop so as to create new branch and then publish it. But I was successful in creating the branch and making local commits but while publishing it gives an error

**Comment by salonilakhotia** [comment]
I want ot contribute in this

**Comment by imPGupta** [comment]
@smaranjitghose assign me this task, I want to contribute on this.

**Comment by Tejas1510** [comment]
Sir i would like to work on the issue

**Comment by sakshirajput02** [comment]
I would like to work on this.

**Comment by N00Bmaster2810** [comment]
@smaranjitghose sir can I work on form for footer

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir can I work on form for footer

@N00Bmaster2810 Can you please proceed with the other two tasks assigned to you, I want to distribute the work among more people so that everyone gets a chance. Once you are done with those, you can surely contribute to this

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir can I work on form for footer

@N00Bmaster2810 Can you please proceed with the other two tasks assigned to you, I want to distribute the work among more people so that everyone gets a chance. Once you are done with those, you can surely contribute to this

> I would like to work on this.

Can you please check out the other issues and let me know if you are interested in them

**Comment by smaranjitghose** [comment]
> I would like to work on this.

Can you please check out the other issues and let me know if you are interested in them

**Comment by smaranjitghose** [comment]
> @smaranjitghose assign me this task, I want to contribute on this.

Can you please check out the other issues and let me know if you are interested in them

**Comment by salonilakhotia** [comment]
Thank you sir @smaranjitghose ..I will do this.

**Comment by Rishi-121** [comment]
I want to contribute to the footer.

**Comment by pvalesha** [comment]
I want to contribute to this

**Comment by anushbhatia** [comment]
one of you can work on social media animations

**Comment by Anjali2001saxena** [comment]
I want to contribute.

**Comment by Tanya919** [comment]
Sir,assign me these tasks

**Comment by ankitapuri** [comment]
I want to work on this issue

**Comment by kashika3101** [comment]
I want to work on this issue. Please assign it to me.

**Comment by mharshita** [comment]
@smaranjitghose  I want to add social-media icons and set up the css for quote in the footer. Please assign this issue to me for Contributors Hack 2020.

**Comment by smaranjitghose** [comment]
> @smaranjitghose I want to add social-media icons and set up the css for quote in the footer. Please assign this issue to me for Contributors Hack 2020.

Cool, collaborate with @salonilakhotia for this to ensure there is no merge conflict

**Comment by smaranjitghose** [comment]
@Anjali2001saxena @Tanya919 @kashika3101 @ankitapuri This is a relatively small task, once @salonilakhotia and @mharshita are done with their work (within the next 4 days). If anyone of you wish to improve, please comment back on this issue on what you would like to improvise and you will be assigned it. Meanwhile please checkout the other issues. We have a Resume Issue. To be built in LaTex. It would require a lot of effort. You all can contribute to that if you wish

**Comment by siddhiisonii** [comment]
@smaranjitghose  sir i want to work in footer section please assign me this.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir i want to work in footer section please assign me this.

Please read this: https://github.com/smaranjitghose/awesome-portfolio-websites/issues/84#issuecomment-674506119

**Comment by smaranjitghose** [comment]
** The older comments are deleted purposefully to keep the more relevant discussion on the top
@salonilakhotia @mharshita you are assigned this for 2 more days

**Comment by mharshita** [comment]
@smaranjitghose  I have made the changes. Please review PR #98 .

**Comment by akshita2903** [comment]
I want to contribute to it

**Comment by akshita2903** [comment]
I want to work on footer section please assign to me

**Comment by amit-singh1** [comment]
Please assign me this task

**Comment by anushbhatia** [comment]
Any updates @akshita2903

**Comment by akshita2903** [comment]
@anushbhatia  sir  I have made a pull request.Please check it
I am a newbie to this If there is any suggestion or improvement needed please tell.
Thankyou

**Comment by akshita2903** [comment]
@anushbhatia Sir I have created a local   footer template in local repo .So I wanna ask whether can I make pull request for this template or I need to contribute to section of @smaranjitghose Sir 's repo in different (new branch) and then make pull request

**Comment by akshita2903** [comment]
Or can I contribute to original footer files of @smaranjitghose Sir 's  repo using another new branch

**Comment by shreyakapoor08** [comment]
> @anushbhatia Sir I have created a local footer template in local repo .So I wanna ask whether can I make pull request for this template or I need to contribute to section of @smaranjitghose Sir 's repo in different (new branch) and then make pull request

Make new branch and then work on it. Make sure to take pull from the original repo

**Comment by ankitapuri** [comment]
Can I work on reducing the width of footer

**Comment by smaranjitghose** [comment]
> Can I work on reducing the width of footer

Go ahead and give a PR
