### ISSUE TITLE
Label commenting bot

### ISSUE THREAD

**Issue by srisatya1197** [smaranjitghose/awesome-portfolio-websites#841]
I would like it to generate different messages for following labels:-

lgmsoc21
level0
level1
level2
level3
under review
changes requested

## screenshots
![New Tab - Google Chrome 30-06-2021 16_12_53](https://user-images.githubusercontent.com/78905067/123947824-71ba9900-d9be-11eb-8630-572e3887539d.png)

**Comment by smaranjitghose** [comment]
Participants are not supposed to set the levels. For the rest we already have PR Triage and another workflow
