### ISSUE TITLE
Would like to add active and hover effects to the navbar links 

### ISSUE THREAD

**Issue by siddhi-244** [smaranjitghose/awesome-portfolio-websites#846]

**Comment by siddhi-244** [comment]
Please assign me this under lgmsoc

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/124351628-159f8100-dc19-11eb-93b3-e6faf0c3c4b3.mp4

I have added active effects please have a look at it ! @smaranjitghose

**Comment by siddhi-244** [comment]
@aliya-rahmani

**Comment by urmi-256** [comment]
Can I work on this issue too if not closed?

**Comment by siddhi-244** [comment]
I am working on it

**Comment by aliya-rahmani** [comment]
@siddhi-244 make a PR and link this issue.

**Comment by siddhi-244** [comment]
Sure !

**Comment by urmi-256** [comment]
> I am working on it

Okk

**Comment by siddhi-244** [comment]
Done @aliya-rahmani
