### ISSUE TITLE
Miscellaneous and Optimizations

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#85]
- [ ] Search Engine Optimization
- [ ] Google Analytics
- [ ] Chatbot
- [ ] JSON data entry

**Comment by sakshirajput02** [comment]
I can work on creating the chatbot using react.js @smaranjitghose

**Comment by smaranjitghose** [comment]
> I can work on creating the chatbot using react.js @smaranjitghose

Can you please elaborate more on what framework you want to use for the chatbot? DialogFlow?

Also, since the current development is not in react, I can create a secondary branch for you so that once we have finalized the work for the basic HTML,css one we can shift to react in a week and meanwhile your chatbot will be ready

**Comment by sakshirajput02** [comment]
Can you tell me the language that is being used for current development?

**Comment by anushbhatia** [comment]
HTML,CSS,JS

**Comment by sakshirajput02** [comment]
Assign me this task. I'll try it using javascript and once I am done I'll report back to u

**Comment by sakshirajput02** [comment]
@smaranjitghose can i start making it or i need to do anything here in order to start?

**Comment by anushbhatia** [comment]
start making the bot

**Comment by smaranjitghose** [comment]
@sakshirajput02 Any updates?

**Comment by sakshirajput02** [comment]
working on it @smaranjitghose

**Comment by sakshirajput02** [comment]
i have the complete zipped folder the chatbot code made using python.Further , i don't know how to upload it here.. please guide. @smaranjitghose

**Comment by smaranjitghose** [comment]
> i have the complete zipped folder of the chatbot code made using python.Further , i don't know how to upload it here.. please guide. @smaranjitghose

Zipped it? As in?😅 Do you mean the export we get from DialogFlow?

**Comment by anushbhatia** [comment]
send me or @smaranjitghose on via slack will look into it.

**Comment by shreyakapoor08** [comment]
> Can you provide me with the email I'd.. any one of you.. I'll send it their .its not getting uploaded on slack.

Are you still working on this issue?
