### ISSUE TITLE
Font awesome icon not visible in footer

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#852]
![image](https://user-images.githubusercontent.com/78655439/124379603-a89df100-dcd5-11eb-85b7-47c607f969a4.png)
The left quote icon is a blank square on the **education** page.

**Comment by supzi-del** [comment]
I would like to fix this under LGMSOC

**Comment by smaranjitghose** [comment]
Replace it with a feather icon please

**Comment by thebhavana** [comment]
@smaranjitghose  I have cloned this project on pc. But unable to see any pop up on any pages. Can you help with it?

**Comment by smaranjitghose** [comment]
Could you please elaborate? I did not understand what you mean by pop up?

**Comment by thebhavana** [comment]
Yes! 
* The center pop cards are missing from all pages . 
* I have all files but still not able to see any cards at center.

 Can you describe what maybe an error here .

![Screenshot (2303)](https://user-images.githubusercontent.com/84395267/124383151-7ba70980-dce8-11eb-8d2d-adb4350c7f79.png)
![Screenshot (2304)](https://user-images.githubusercontent.com/84395267/124383153-7d70cd00-dce8-11eb-8ece-2a8f7c740dec.png)

**Comment by supzi-del** [comment]
> Replace it with a feather icon please

On all the pages?

**Comment by smaranjitghose** [comment]
> > Replace it with a feather icon please
> 
> On all the pages?

yep

**Comment by smaranjitghose** [comment]
> Yes!
> 
> * The center pop cards are missing from all pages .
> * I have all files but still not able to see any cards at center.
> 
> Can you describe what maybe an error here .
> 
> ![Screenshot (2303)](https://user-images.githubusercontent.com/84395267/124383151-7ba70980-dce8-11eb-8d2d-adb4350c7f79.png)
> ![Screenshot (2304)](https://user-images.githubusercontent.com/84395267/124383153-7d70cd00-dce8-11eb-8ece-2a8f7c740dec.png)

This is little complicated to identify unless I can go over the codebase at your end to check for any discrepencies

**Comment by deeqakkk** [comment]
> Yes!
> 
> * The center pop cards are missing from all pages .
> * I have all files but still not able to see any cards at center.
> 
> Can you describe what maybe an error here .
> 
> ![Screenshot (2303)](https://user-images.githubusercontent.com/84395267/124383151-7ba70980-dce8-11eb-8d2d-adb4350c7f79.png)
> ![Screenshot (2304)](https://user-images.githubusercontent.com/84395267/124383153-7d70cd00-dce8-11eb-8ece-2a8f7c740dec.png)

@thebhavana if you haven't made some major changes than you can clone a fresh copy of this repo again, then it should work fine for you.
