### ISSUE TITLE
Fix and Redesign To Top Button [React Version]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#857]
- The to top button's position should be dynamic w.r.t location of the page
- On click, it should take us to the topmost section of each page
- It should not appear on mobile screens
- It should not appear on the top of the page (or in fact midway)
- Try to change the UI as well.

For reference: Check out the hosted version

**Comment by AmanBisht01** [comment]
I can work on this issue please assign it to me.

**Comment by AmanBisht01** [comment]
under LGMSOC

**Comment by smaranjitghose** [comment]
Assigned for 2 days
