### ISSUE TITLE
Nav Bar Unresponsiveness Bug in Mobile Screens [React]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#859]
## Current Navbar/Sidebar in Mobile Screens

![Navbar_current](https://user-images.githubusercontent.com/46641503/124384136-93cd5780-dced-11eb-9c28-22cb9228be76.png)

![Navbar_current_1](https://user-images.githubusercontent.com/46641503/124384195-bbbcbb00-dced-11eb-9186-54a829084cb3.png)

## React Version
![Navbar_unresponsive](https://user-images.githubusercontent.com/46641503/124384091-713b3e80-dced-11eb-83e3-0e94966fb731.png)

- There is a micro animation on clicking the hamburger button [ [Reference](https://codepen.io/RRoberts/pen/ZBYaJr) 2nd row, 2nd column is a preference)
- A drop down effect spanning the entire page 
- An illustration at the bottom (Feel free to change this)

**Comment by jayeshpurohit12** [comment]
i wanna work on this issue

**Comment by urmi-256** [comment]
Can I work on this?

**Comment by deeqakkk** [comment]
@urmi-256 any updates?

**Comment by urmi-256** [comment]
https://user-images.githubusercontent.com/71149323/125199275-12dd0580-e283-11eb-9dcd-29317bdf6361.mp4

Is it ok ?

**Comment by smaranjitghose** [comment]
You can give a PR

**Comment by smaranjitghose** [comment]
Please note this is exclusively for the React version

**Comment by GiotisK** [comment]
Hello. 
I would like to help with this issue aswell. I will try to make it the same as the master branch. I will post screenshots whenever it is ready

**Comment by aliya-rahmani** [comment]
@GiotisK, go ahead!

**Comment by GiotisK** [comment]
I did the changes. Please take a look and let me know if I have to change anything.

https://user-images.githubusercontent.com/10963096/125960137-dbb2646e-989f-4d02-81b3-9287fa618a30.mp4
