### ISSUE TITLE
Replace Typewrite effect in Home Page with Animation on Change [React]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#862]
- [Reference](https://nearform.github.io/react-animation/)
- Try to implement something similar to the second example given in the above under Custom Animation
- Make sure the change is mobile responsive

**Comment by hitenSharm** [comment]
I would like to give this a try.

**Comment by hitenSharm** [comment]
@smaranjitghose  should I just make sure that my component is responsive? Also, is the ReactJS branch website responsive, I am asking because it doesn't seem to be much responsive on my screen but I am not sure whether it is because of code I changed or if it wasn't responsive in the first place?

**Comment by smaranjitghose** [comment]
Some recent changes have been pushed to improve the responsivness. Just make sure the home page is responsive

**Comment by amruta-11** [comment]
Can you assign me this issue?

**Comment by Anadee11** [comment]
Can I work on this under JWoC?
