### ISSUE TITLE
Particle Effect Component to be used in the background of all the pages[React]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#864]
- This has to be built using three.js
- [Reference video](https://www.youtube.com/watch?v=dLYMzNmILQA)
- We just need the dark background with the particles so that any card or other objects can be placed infront of it for the various pages
- The geometric shape is not required.

**Comment by Shivani13121007** [comment]
Hii, I'm Shivani Gupta 
please assign this issue to me.
thank you

**Comment by deeqakkk** [comment]
@Shivani13121007 Try to make a PR within 2-3days.

**Comment by Shivani13121007** [comment]
Okk...I'll do it by today
But can u plz tell me 
Do i need to create a dark  background only and u can embedd the code wherever you want by your own or i have to embedd it?

**Comment by Shivani13121007** [comment]
Please review this. If you find this as the one that you want then I make PR😅
and do tell me the code should be in react or basic html, css, js 
I done this in both the languages
![Screenshot (135)](https://user-images.githubusercontent.com/68291301/125476092-c32cbda5-4a28-4ff0-9c06-40f4a1b98cd7.png)

**Comment by Shivani13121007** [comment]
Cards used are for demo purpose
https://user-images.githubusercontent.com/68291301/125477057-72035952-d283-4325-9af8-8b494816a8a9.mp4

**Comment by Shivani13121007** [comment]
https://user-images.githubusercontent.com/68291301/125504562-713d5ed5-6074-4c51-8994-948ae3645e0e.mp4

**Comment by smaranjitghose** [comment]
Even after providing the exact video for this, if this is the result, I can't help further with this

**Comment by smaranjitghose** [comment]
A detailed walkthrough of the entire UI has been provided along with the colors scheme in the above reference video. Please follow that

**Comment by AmanBisht01** [comment]
Assign this issue to me .

**Comment by deeqakkk** [comment]
> @smaranjitghose
> Please Assign this issue to me .

try to make a PR soon.

**Comment by battuAshita** [comment]
Hi @anushbhatia
I have been trying to animate the particles but it shows an error: 
![error](https://user-images.githubusercontent.com/63910374/136706422-b83383e4-de15-439b-922c-d406ea176a4d.png)
The main component which I have exported contains this code as shown below:
![particles](https://user-images.githubusercontent.com/63910374/136706474-f095c83a-232e-43c7-bd85-44fa11b949e9.png)

**Comment by battuAshita** [comment]
Thank you. It works now. Will make a PR soon :)
