### ISSUE TITLE
3D Terrain Effect in the Footer to replace the current illustration

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#865]
- [Reference Video](https://www.youtube.com/watch?v=2AQLMZwQpDo&list=PL0lNJEnwfVVO4sNO2WDq_h73w-eHQStCB)
- Build it as a component

**Comment by shagun0915** [comment]
I want to work on this. Please assign it to me.

**Comment by deeqakkk** [comment]
any updates?

**Comment by Serjeel-Ranjan-911** [comment]
@smaranjitghose what you mean by component here?

**Comment by anushbhatia** [comment]
https://github.com/smaranjitghose/awesome-portfolio-websites/tree/reactjs/src/components create 3d wave here and import it directly to the footer in pages folder so that footer has less amount of code.

**Comment by Serjeel-Ranjan-911** [comment]
okay didn't notice there is reactjs branch as well

**Comment by Serjeel-Ranjan-911** [comment]
![image](https://user-images.githubusercontent.com/74287984/132094805-e8744bed-f403-4588-9bad-f27849dfa4c6.png)
is your goal to replace this graphic with terrain one?

**Comment by Serjeel-Ranjan-911** [comment]
@smaranjitghose 
demonstration from my side

https://user-images.githubusercontent.com/74287984/132100261-125fb5cd-8363-48eb-8dc0-f3efc0c3436a.mp4

I have created a terrain component.
For demonstration purpose I have imported it in a div inside footer. 
![image](https://user-images.githubusercontent.com/74287984/132100273-7c15692e-e4cc-477c-93b4-c107e7d016fc.png)

- The terrain component can be imported anywhere and will occupy 100% of parent container.
- background of terrain is transparent so it will blend with background.
- The bump is totally dependent on height map, different height maps will give different results.
- only one dependency added ie THREE

If everything fine then tell me. I will raise PR

**Comment by Nzamuyejoram** [comment]
@Serjeel-Ranjan-911  i would like to know more about terrain geometry, throw more light on this and have more ideas

**Comment by Serjeel-Ranjan-911** [comment]
@Nzamuyejoram 
The terrain is a 2d plane which is divided in a grid of 64 by 64. Now each point on this grid is given a vertical height based on a displacement map. Displacement map is just a black and white image which stores height information. The terrain is blue in colour due to the light projected on it.
