### ISSUE TITLE
Reference Page [ React Version]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#878]
## [Reference UI](https://teamway.io/)

- Updating the navbar is not required for now
- Make sure the routing is done properly ( i.e. our page should be available at `/references`
- The footer and navbar should be the same as the other pages
- Modify the color scheme as per the one used in the website
- Use free and open-source illustrations from [Undraw](https://undraw.co/) for placeholder images
- Images/illustrations should be placed inside assets/images/references/
- The relative horizontal position of the image and text should be alternate.
![reference_page](https://user-images.githubusercontent.com/46641503/124398963-1f6ad680-dd36-11eb-8ae7-c20aa39cd0c7.png)
![reference_page_2](https://user-images.githubusercontent.com/46641503/124398964-209c0380-dd36-11eb-95f0-04e234d51842.png)

**Comment by Shivani13121007** [comment]
do we need to create the same design?

**Comment by smaranjitghose** [comment]
Yes

**Comment by Shivani13121007** [comment]
Okkk assign this issue to me

**Comment by deeqakkk** [comment]
@Shivani13121007 Plz Make PR's for previously assigned issues first.

**Comment by AshuKV** [comment]
Hey @smaranjitghose, can you please assign this issue to me.

**Comment by deeqakkk** [comment]
@AshuKV do try to make a PR soon.

**Comment by vwang0101** [comment]
@smaranjitghose Hi, can I work on this issue please?
