### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#88]
# Development
- Build the resume from scratch using Pure LaTeX
- Use [Overleaf](https://www.overleaf.com/) for this.
- Do one section at a time to keep it simple.
- Whoever is working on this, ping me on Slack for the template
- Resources to get started with LaTeX: [Vincet Knight's Youtube Videos](https://www.youtube.com/watch?v=rLWT0z6yvrk&list=PLnC5h3PY-znyDQKn3knfXfekZLgWyL7QW) , [LaTeX Documentation](https://www.latex-project.org/help/documentation/), [Overleaf Guides](https://www.overleaf.com/learn),[Overleaf Tutorials](https://www.overleaf.com/learn/latex/Tutorials)
- Give the PRs to a branch called ```resume_latex```  ( Before you do it remind me or any of the mentors to create the branch for you)
- __Humble Suggestion__: Do not run LaTeX files locally
# Integration
- [ ] To be added to the Navbar once complete
- [ ] On clicking, the pdf should start downloading

**Comment by ALOKARYAN51** [comment]
Hi i would like to work this issue

**Comment by ALOKARYAN51** [comment]
I would like to work on this issue.

**Comment by ankitapuri** [comment]
I would like to contribute on this issue.

**Comment by smaranjitghose** [comment]
Both of you please learn LaTeX, take a week's time, and show me a basic resume you made from scratch and then I'll provide you the UI. The description of the issue is self-explanatory to get started. Please read it carefully

**Comment by ALOKARYAN51** [comment]
Okk sir

**Comment by ShristiJalan** [comment]
Sir I would like to contribute to this issue

**Comment by anushbhatia** [comment]
Any update guys ?

**Comment by ankitapuri** [comment]
Yeah I have watched most of the videos from youtube 
Have gained a basic knowledge about LaTeX

**Comment by smaranjitghose** [comment]
> Sir I would like to contribute to this issue

@ShristiJalan Let me know are you still interested to work on this?

**Comment by smaranjitghose** [comment]
@ALOKARYAN51 @ankitapuri Any updates?

**Comment by ALOKARYAN51** [comment]
Yes we are doing. We got the template and start working on it

**Comment by anushbhatia** [comment]
Great when can we expect a PR

**Comment by ALOKARYAN51** [comment]
Within 4-5 days

**Comment by anushbhatia** [comment]
okay so I can expect a PR by 9th

**Comment by ALOKARYAN51** [comment]
Yes

**Comment by N00Bmaster2810** [comment]
can I work on adding the resume to the navbar?

**Comment by smaranjitghose** [comment]
> can I work on adding the resume to the navbar?

Go ahead
