### ISSUE TITLE
Simplify NavBar on Hover Effect

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#881]
## [Reference](https://codepen.io/maheshambure21/pen/QwXaRw)

Use the Underline Stoke Effect

**Comment by geniusbharti** [comment]
@smaranjitghose  I would like to work on this as a part of LGMSoC.

**Comment by deeqakkk** [comment]
@geniusbharti yes , you can work on it.

**Comment by aliya-rahmani** [comment]
@geniusbharti updates?

**Comment by geniusbharti** [comment]
@aliya-rahmani working on it.

**Comment by aliya-rahmani** [comment]
@geniusbharti do make a PR soon
