### ISSUE TITLE
Scroll Bar Bug during Pre-Loader

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#882]
The Scroll bar appears during the pre-loader animation which is unexpected behavior
![Scroll_Bar_bug](https://user-images.githubusercontent.com/46641503/124399908-60fe8000-dd3c-11eb-9f91-ba8ad67e51fa.png)

**Comment by battuAshita** [comment]
Hi @smaranjitghose. Can I work on this issue as part of OSD'21?

**Comment by smaranjitghose** [comment]
Sure @battuAshita

**Comment by deeqakkk** [comment]
@battuAshita any updates?

**Comment by battuAshita** [comment]
Yes. Almost done. Will raise a PR :)
