### ISSUE TITLE
Modify Pre-Loader UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#883]
![pre_loader_yui](https://user-images.githubusercontent.com/46641503/124400036-2517ea80-dd3d-11eb-9159-30e2270fb797.png)

- Remove the text at the top(from all the pages)
- Increase the size of the illustration
- Make sure the preloader is mobile responsive

**Comment by pallavi-1812** [comment]
Hello! Can I work on this issue?

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by smaranjitghose** [comment]
@pallavi-1812 Any updates?
