### ISSUE TITLE
Education Page Cards Dark Mode UI Update

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#884]
![education_Page](https://user-images.githubusercontent.com/46641503/124400114-c7d06900-dd3d-11eb-8132-ed31a4247ac8.png)

## [Reference](https://passbase.com/)

- Change the background color
- Change card background-color
- Modify Headings UI 
- Replace the color of all the appropriate elements in purple/mauve colors with the shade of blue in the above reference [ Text Color/illustration/footer illustration/footer form/scroll bar]

**Comment by monishamandal02** [comment]
Please assign this issue to me?

**Comment by deeqakkk** [comment]
@monishamandal02 assigned for 3 days.

**Comment by aliya-rahmani** [comment]
@monishamandal02 updates?
