### ISSUE TITLE
Education Page To Top Button Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#885]
![to_top_education](https://user-images.githubusercontent.com/46641503/124400208-60ff7f80-dd3e-11eb-937b-0f6aba0ab23f.png)

**Comment by harishpansari** [comment]
I would like to work on this bug. Assign me. under LGMSOC21.

**Comment by deeqakkk** [comment]
@harishpansari Yes, go ahead and solve this issue.

**Comment by aliya-rahmani** [comment]
@harishpansari  updates?

**Comment by harishpansari** [comment]
@aliya-rahmani working on it.

**Comment by aliya-rahmani** [comment]
@harishpansari, do make a PR soon!
