### ISSUE TITLE
NAV bar Glitch in Experience Page

### ISSUE THREAD

**Issue by Sanju-github002** [smaranjitghose/awesome-portfolio-websites#893]
<img width="544" alt="Screenshot 2021-07-08 211300" src="https://user-images.githubusercontent.com/78341083/124952050-8ab3f180-e031-11eb-9fe3-e4db5dca006a.png">

I see this issue in Page now where I see nav bar is hide in page  you can check this once

**Comment by smaranjitghose** [comment]
Would you like to resolve it?

**Comment by Sanju-github002** [comment]
> Would you like to resolve it?

Yes I try to resolve this issue

**Comment by smaranjitghose** [comment]
Closed due to inactivity
