### ISSUE TITLE
Round corners and Hover of Send button

### ISSUE THREAD

**Issue by geniusbharti** [smaranjitghose/awesome-portfolio-websites#899]
I would like to add rounded corners to the send button present inside the form and its hover color.
Can I work on this issue?

**Before**
![Screenshot (107)](https://user-images.githubusercontent.com/75856835/125096983-47ba5280-e0f3-11eb-9576-519f8a7cff01.png)
**After**
![Screenshot (108)](https://user-images.githubusercontent.com/75856835/125097041-57d23200-e0f3-11eb-9a55-c5327c8f17a9.png)
**On Hover**
![Screenshot (109)](https://user-images.githubusercontent.com/75856835/125097142-6ddff280-e0f3-11eb-829c-8fa27ea65f40.png)

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by ahmadsohail404** [comment]
I can do it, please assign it to me

**Comment by smaranjitghose** [comment]
@geniusbharti You can give  two PRs, one for the master version and the second for the react version

**Comment by geniusbharti** [comment]
@smaranjitghose Okay.
