### ISSUE TITLE
Bug: Research Page Contents are not visible

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#900]
- Try to inspect and debug this issue
- I believe this is owing to the scrollbar commit and the body tag update

**Comment by Garima-7** [comment]
assign this to me.
As the pull request made by me for the issue #901 resolves this problem also.
This problem was due to scroll bar issue.

**Comment by Garima-7** [comment]
Bhaiya this issue is already resolved in my previous pull request.(which is not merged yet)
So Again I have to make PR?

**Comment by smaranjitghose** [comment]
No, it's fine.  I have merged that
