### ISSUE TITLE
Console Logs of Scrolling

### ISSUE THREAD

**Issue by AnirudhPanda** [smaranjitghose/awesome-portfolio-websites#906]
`console.log($(window).scrollTop()); ` is present in app.js which logs out numbers according to our position in the window during scrolling.
Was it supposed to be there?

**Comment by smaranjitghose** [comment]
I believe that was used for the purpose of debugging. Feel free to raise a PR and remove it

**Comment by AnirudhPanda** [comment]
> I believe that was used for the purpose of debugging. Feel free to raise a PR and remove it

#912 FIXED.
