### ISSUE TITLE
Add website visitor counter

### ISSUE THREAD

**Issue by Dhruv-194** [smaranjitghose/awesome-portfolio-websites#911]
Adding a website visitor counter which counts the number visits would definitely be a great added feature to this amazing portfolio website.

**Comment by smaranjitghose** [comment]
Where are you planning to display the count?

**Comment by Dhruv-194** [comment]
Hey @smaranjitghose I was thinking to show that on the header NavBar near the name. Or even at the very bottom of the page near the social icons. 

If you have any suggestions regarding the same then you can also please guide me.

**Comment by smaranjitghose** [comment]
We can create a separate page for that. Putting it up on the main pages would make it awkward since the purpose of the portfolio would be create an impression on the hiring managers and that metric would not be useful in that case

**Comment by Dhruv-194** [comment]
@smaranjitghose creating an entire new page for just this one additional feature won't be feasible I think.  

What we can do is create a pop-up widget or dialog box kind of a thing for this. I think that would be better. What are your thoughts?

**Comment by smaranjitghose** [comment]
Placing that would be an issue w.r.t. the UI. Let's see perhaps once we are done with the animations and all, we can reopen this
