### ISSUE TITLE
Cannot see where to find main.js 

### ISSUE THREAD

**Issue by cubthemagiclion** [smaranjitghose/awesome-portfolio-websites#915]
Hello! I am following the "Getting Started" guide but there is no where I can find the main.js to change things like signature on top left. Can you please provide some insights? Thank you.
<img width="724" alt="Screen Shot 2021-07-11 at 7 38 02 PM" src="https://user-images.githubusercontent.com/48465360/125222919-c0e6b080-e27f-11eb-8c46-1d98b824fd3c.png">

**Comment by smaranjitghose** [comment]
Hey @cubthemagiclion . We have shifted the code from main.js to app.js
