### ISSUE TITLE
Animate the Open Source Cards

### ISSUE THREAD

**Issue by Dhruv-194** [smaranjitghose/awesome-portfolio-websites#919]
We can animate the Open Source Cards in the Experience Section which animates upwards when we scroll past them similar to how the Work Experience Cards animates when we scroll through them. 

Kindly please assign this issue to me!

**Comment by smaranjitghose** [comment]
AOS? sure!

**Comment by anushbhatia** [comment]
Assigned for 4 days.

**Comment by Dhruv-194** [comment]
@smaranjitghose yes I was talking about AOS (Animate on scroll) only. Thanks for assigning me this issue! 

@anushbhatia alright I will try sending my PRs within 4 days :)
