### ISSUE TITLE
Create Professional Reference Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#921]
## [Reference UI](https://teamway.io/)

- Updating the navbar is not required for now
- The code should be placed inside reference.js, reference.css, reference.html
- Adding data should be done dynamically from a variable as done in research.js
- The footer and navbar should be the same as the other pages
- Modify the color scheme as per the one used on the website
- Use free and open-source illustrations from [Undraw](https://undraw.co/) for placeholder images
- Images/illustrations should be placed inside assets/images/references/
- The relative horizontal position of the image and text should be alternate.
![reference_page](https://user-images.githubusercontent.com/46641503/124398963-1f6ad680-dd36-11eb-8ae7-c20aa39cd0c7.png)
![reference_page_2](https://user-images.githubusercontent.com/46641503/124398964-209c0380-dd36-11eb-95f0-04e234d51842.png)

**Comment by Ayush2020012016** [comment]
It must be done with UI or with coding

**Comment by anushbhatia** [comment]
Better to do it with coding. If you are using design then dynamically import text and image to that

**Comment by shagun0915** [comment]
I want to work on this issue. Please assign it to me.

**Comment by deeqakkk** [comment]
any updates @shagun0915 .

**Comment by A-GHOSH-dev** [comment]
I think this issue is still open. Can I contribute please?

**Comment by A-GHOSH-dev** [comment]
Please assign me by today. I need to contribute by tomorrow.

**Comment by A-GHOSH-dev** [comment]
I have done the work and created a pull request. 

I did this work for a task given by Microsoft (submission today). And it would be very helpful if the PR review is done as soon as possible. 

Thank you.
