### ISSUE TITLE
New Graphic Design Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#922]
- Remove all code related to the gallery page (i.e. gallery.html, gallery.css, and gallery.js)
- [Reference](https://www.stevewolf.co/)
- All the code should be placed in design.html, design.css, and design.js. 
- Updating the navbar is not required for now
- The footer and navbar should be the same as the other pages
- Use free and open-source designs from dribble 
- Images/illustrations should be placed inside assets/images/designs/

**Comment by anushbhatia** [comment]
or you can take references from https://kundu.design/

**Comment by Ayush2020012016** [comment]
hello I want to contribute to this please assign this work to me.

**Comment by aliya-rahmani** [comment]
@Ayush2020012016 updates?

**Comment by pranjal345678** [comment]
Hello I want to contribute to this please assign this work to me.

**Comment by deeqakkk** [comment]
> Hello I want to contribute to this please assign this work to me.

Sure, @pranjal345678 you can work on it.
