### ISSUE TITLE
Build Hackathon Component for Expereince Page [React]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#924]
[Reference](https://codepen.io/JavaScriptJunkie/details/WgRBxw)

- The title of the section should be __Hackathon Participation__
- The UI should be more or less the same as in the master branch of the project (Feel free to modify the cards or anything else if you wish)
- Do not change the background color of the page ( in the reference it is a shade of orange)
- The Color of the scrollbar of the timeline should be the same as that of the headings of the page
- Do not put Lorem Ipsum and random Images. Use the data given for the same in the master branch
- The data should be dynamically inserted using a variable as done through expereince.js in the current version.
- The title should be the name of the Hackathon
- Add a subtitle for the role (Judge/Mentor/Speaker/Winner/Runnerup)
- Images/illustrations should be placed inside assets/images/hackathons/

**Comment by souravseal99** [comment]
I would like to work on this.

**Comment by deeqakkk** [comment]
@souravseal99 assigned for 3 days.

**Comment by aliya-rahmani** [comment]
@souravseal99 updates?

**Comment by souravseal99** [comment]
> @souravseal99 updates?

yes @aliya-rahmani, I have completed the card section, the only task left is styling the image of the card. I'm really sorry about the deadline, I was facing some health related issues from a couple of days. I'll try my best to make the PR by tonight.

![image](https://user-images.githubusercontent.com/69809086/126057514-895b399e-1ca2-47b7-9d66-d9f4b3e1ff82.png)

**Comment by aliya-rahmani** [comment]
@souravseal99 take your time but try to make it asap.

**Comment by souravseal99** [comment]
Thanks @aliya-rahmani.

Can you please help me with the Image, I tried different things but was unable to apply the desired styles as portrayed in the master branch.

**Comment by aliya-rahmani** [comment]
@souravseal99 No worries, make a PR first with whatever you've tried then we can request changes for the image styling.

**Comment by souravseal99** [comment]
> @souravseal99 No worries, make a PR first with whatever you've tried then we can request changes for the image styling.

Thanks a lot @aliya-rahmani , making the PR shortly.
