### ISSUE TITLE
Build Open Source Component for Expereince Page [React]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#928]
![open_source](https://user-images.githubusercontent.com/46641503/124398700-b6cf2a00-dd34-11eb-8e89-8f3bfb8ec4f1.png)

## [Reference UI](https://teamway.io/)

- The title of the section should be OpenSource Participation
- Please follow the above UI for the design exclusively
- The Color Scheme should be modified as per the requirements of the project (Check current version)
- All the cards should have a logo (i.e. image of the open-source program)
- Take the data from the current version
- The data should be dynamically loaded from a variable as done in the expereince.js
- All the images/logos should be placed at assets/images/opensource/

**Comment by ujju20** [comment]
Please Assign me this issue 
Actually, I have mistaken I thought that you people are just shifting from Vanilla Js to react so I thought that I have to use the old UI.
Now I am clear, I will work on it.

**Comment by aliya-rahmani** [comment]
@ujju20 updates?

**Comment by shagun0915** [comment]
I will work on this. Please assign me this issue.

**Comment by aliya-rahmani** [comment]
@shagun0915  updates?

**Comment by shagun0915** [comment]
> @shagun0915 updates?

Working on it. Will make a PR in a day.

**Comment by anushbhatia** [comment]
Any progress?

**Comment by sanchitjain336** [comment]
Hello, 
If this issue is open I am can work on it.
Please Assign me this issue.

**Comment by sanchitjain336** [comment]
Hello , 
If this issue is open I can work on it.
Please assign me this issue.

**Comment by anushbhatia** [comment]
Sure go ahead with it.

**Comment by sanchitjain336** [comment]
Hii, I have made the changes. Please have a look

This is the new look:
<img width="819" alt="Screenshot 2022-01-10 at 6 52 32 PM" src="https://user-images.githubusercontent.com/78586251/148773744-9a83c5c0-b0b3-4de3-b2e4-d0f4041f46e2.png">

The old look:
<img width="911" alt="Screenshot 2022-01-10 at 12 26 56 PM" src="https://user-images.githubusercontent.com/78586251/148773857-2fd2face-1d66-4351-8358-bf08bd9f420b.png">

**Comment by smaranjitghose** [comment]
@sanchitjain336 Please refer the image given in the issue description once and modify your update accordingly. The cards should be rectangular in shape. You can place the heading next to the logo and experiment.

I am closing this issue (since it is not related to the main branch) but feel free to continue working on it
