### ISSUE TITLE
Build Research Page [React]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#929]
- [Sample Reference](https://www.cs.utoronto.ca/~fidler/publications.html)
- Do refer to the current version on the main branch too (Except the way the pictures are placed)
- The color of the buttons needs to be changed to suit the theme
- The cards should be mobile responsive.
- Use Animation on Scroll
- We need Abstract, Paper, and Cite buttons
- Add an on hover effect for the buttons
- The data should be defined in a variable and dynamically inserted as done in the current research.js
-  Images/illustrations should be placed inside assets/images/research/

**Comment by sanchi-chugh** [comment]
pls assign this issue to me
i would love to work on this

**Comment by unnati914** [comment]
i can work on this if it is not completed

**Comment by anushbhatia** [comment]
Any updates @unnati914 ?
