### ISSUE TITLE
Remove Horizontal Scroll Bar

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#931]
![Vertical_Nav_Bar](https://user-images.githubusercontent.com/46641503/125512777-3855895b-3f12-4406-9257-3a1713e04ac0.png)

It appears when one hovers over the scroll bar track

**Comment by geniusbharti** [comment]
@smaranjitghose I would like to work on this as a part of LGMSOC'21

**Comment by purohitmansi** [comment]
Please do assign this to me.
I would like to work on this.

**Comment by geniusbharti** [comment]
Okay

**Comment by Ayush2020012016** [comment]
is it still opened I want to contribute to this

**Comment by vvijayalakshmi21** [comment]
Hi,
Is this available to work?
