### ISSUE TITLE
Fix Footer Responsiveness [React]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#932]
### Required [Master Branch Version]

![footer](https://user-images.githubusercontent.com/46641503/125513279-04683cde-d421-4f1f-95be-0a622d9d9368.png)

### React Version

![Responsiveness](https://user-images.githubusercontent.com/46641503/125513298-a07b52a4-9668-429a-912c-8851fd71a192.png)

**Comment by GiotisK** [comment]
I'd like to take over this issue. I have already tweaked the css file. 
Here is the picture. Is it fine?
![react-cont](https://user-images.githubusercontent.com/10963096/125539742-a8729e1a-f75c-41c3-b761-7b5731d06e24.PNG)

**Comment by smaranjitghose** [comment]
Sure. Do give a PR
