### ISSUE TITLE
Website Bugs in Mozilla Firefox

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#933]
![firefox](https://user-images.githubusercontent.com/46641503/125513962-3d2af951-f62b-410f-b15b-48f947a6ba18.png)

- Sidebar and Navbar should not overlap for laptop screens
- The custom scrollbar is absent

### Reference Articles for such issues:

- [Article 1](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/HTML_and_CSS)
- [Article 2](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance)

**Comment by Kirsten-Nancy** [comment]
Hi, can I work on this as part of open-source-day? Though I can't see an up for grab label

**Comment by smaranjitghose** [comment]
> Hi, can I work on this as part of open-source-day? Though I can't see an up for grab label

Sure. My bad. I missed that

**Comment by Ayush2020012016** [comment]
is it still opened

**Comment by Kirsten-Nancy** [comment]
You're using Mozilla?

**Comment by Kirsten-Nancy** [comment]
It's still open

**Comment by Kirsten-Nancy** [comment]
Fixed both bugs in mozilla, however it seems firefox doesn't have full customizable features for scroll bar such as the box-shadow, it has only two properties scrollbar-color scrollbar-width

![mozilla](https://user-images.githubusercontent.com/25672951/125827067-219a7abb-c7a0-407b-bce8-caffc63ab160.png)

**Comment by smaranjitghose** [comment]
Sure
