### ISSUE TITLE
[ UX ] The text on the Experience cards looks light and hard to read on Dark Mode

### ISSUE THREAD

**Issue by AnirudhPanda** [smaranjitghose/awesome-portfolio-websites#937]
![issue](https://user-images.githubusercontent.com/66218496/125661864-d9dd0511-3a4e-4257-bfef-e89cdbcafac6.PNG)

@smaranjitghose what do you say?

**Comment by smaranjitghose** [comment]
Yes. This is a bug we need to resolve

**Comment by su123qq** [comment]
can you assign me this issue?

**Comment by AnirudhPanda** [comment]
Assigned!

> can you assign me this issue?
