### ISSUE TITLE
Add Animate on Scroll to Project Section

### ISSUE THREAD

**Issue by Dhruv-194** [smaranjitghose/awesome-portfolio-websites#939]
Adding an animate on scroll to the 'My Project Section' similar to the 'Experience Section' where the Text and Project cards both get animated when scroll past through them. 

Kindly please assign me this issue!

**Comment by Dhruv-194** [comment]
@aliya-rahmani @anushbhatia @smaranjitghose can anyone of you please add the DCP label to this so that I can send my PR and link this issue with it

**Comment by anushbhatia** [comment]
Any update @Dhruv-194 ?

**Comment by Dhruv-194** [comment]
Oh sorry I forgot to work on this issue. I will do it right away and send the PR. 
Sorry for the delay @anushbhatia
