### ISSUE TITLE
Add box shadow below social icons

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#949]
On the homepage, you can see a box-shadow beneath the profile photo. However, there's no shadow below the social icons. 
Please refer this image below in order to add the code!

![Screenshot (362)_LI](https://user-images.githubusercontent.com/78655439/125840964-23c38b23-9f2c-4dcd-8b4c-7093360b1a53.jpg)

**Comment by anushbhatia** [comment]
Don't add the x component of box-shadow it might look weird.
https://getcssscan.com/css-box-shadow-examples
this has almost every framework's shadow you can refer to this and then add it.

**Comment by supzi-del** [comment]
Ref #790

**Comment by anushbhatia** [comment]
Yes you can work on this but keep the box shadow subtle for both keeping the references given above in mind.

**Comment by supzi-del** [comment]
> Yes you can work on this but keep the box shadow subtle for both keeping the references given above in mind.

Hey, actually I opened this issue as a mentor for OSD for participants...you can unassignme.

**Comment by anushbhatia** [comment]
Sorry😐 my bad

**Comment by himanshu007-creator** [comment]
Hi, i would like to solve this issue as an OSD participant
