### ISSUE TITLE
Search Field

### ISSUE THREAD

**Issue by kmlhsn** [smaranjitghose/awesome-portfolio-websites#95]
**Description of the enhancement**
A clear and concise description of what the problem you wish to solve or any enhancement you wish to do for the project

- search field

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

**Comment by smaranjitghose** [comment]
> **Description of the enhancement**
> A clear and concise description of what the problem you wish to solve or any enhancement you wish to do for the project
> 
> * search field
> 
> **Screenshots**
> Screenshots of the proposed changes compared with the current version of the project

Please give elaborate description of what you wish to do

**Comment by kmlhsn** [comment]
> 
> 
> > **Description of the enhancement**
> > A clear and concise description of what the problem you wish to solve or any enhancement you wish to do for the project
> > 
> > * search field
> > 
> > **Screenshots**
> > Screenshots of the proposed changes compared with the current version of the project
> 
> Please give elaborate description of what you wish to do

@smaranjitghose There should have a search box so that the visitor can search their information.
