### ISSUE TITLE
Suggested change: rename 'master' branch to 'main' branch

### ISSUE THREAD

**Issue by sarahstandish** [smaranjitghose/awesome-portfolio-websites#950]
Github has made 'main' the [default name for primary branches](https://github.com/github/renaming) now due to the term 'master' having a [connotation of slavery](https://github.com/dialpad/inclusive-language/blob/main/README.rst#master-slave-terminology).

**Comment by smaranjitghose** [comment]
@sarahstandish Thanks for pointing this out. We plan to perform this transition once we are done with the development till a particular point since it would cause issues for a lot of our collaborators and contributors w.r.t setting up the project who have been actively a part of the project

**Comment by sarahstandish** [comment]
Thanks for your reply! That makes sense.
