### ISSUE TITLE
Improving UI in homepage

### ISSUE THREAD

**Issue by Yunika-Bajracharya** [smaranjitghose/awesome-portfolio-websites#951]
Can alter the size of the text / social media icons in the Ipad, IPad pro size screens so as to improve the UI further. 

![1](https://user-images.githubusercontent.com/60802409/125844315-6626300e-7157-46ee-859c-bddd0e908b5b.jpg)
<img width="478" alt="2" src="https://user-images.githubusercontent.com/60802409/125844330-d4822824-cf44-4da4-a49c-4e5a9864b842.png">

**Comment by Trevy05** [comment]
Hi. Could you explain the issue more clearly, I would love to work on it.

**Comment by Yunika-Bajracharya** [comment]
For other screen sizes, the text and icons are big enough. For instance here,
<img width="410" alt="3" src="https://user-images.githubusercontent.com/60802409/125876229-86189b0b-122c-4cda-9518-ea9368eb148d.png">
But as for the iPad and iPad pro sizes, the text/icons appear smaller and there is plenty of space left so, you can increase their sizes and improve the UI further. Hope that makes it clear.

**Comment by Trevy05** [comment]
I understand now, could you assign this issue to me?
