### ISSUE TITLE
Fix bug in dark mode navbar hover

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#956]
When the navbar "a " elements are hovered, its hard to see the text in the dark mode. Hence removing the hover as shown below would be a suitable fix.
![Screenshot (366)_LI](https://user-images.githubusercontent.com/78655439/125853515-59933908-d526-4852-8e89-b4d3dd09c72d.jpg)

**Comment by ceruleanox** [comment]
Hi! I'd like to take this one for OSD w/AnitaB. 

For clarity, is it completely take out the link hover color? Or is it taking it out only when it is in dark mode?

**Comment by smaranjitghose** [comment]
Take it out for both light and dark modes

**Comment by supzi-del** [comment]
Assigned to @ceruleanox

**Comment by ceruleanox** [comment]
Hi! 

While adding the following fixes the issue, it does not remove the hover:

.dark-theme .nav-link:hover{
    color: rgba(255, 255, 255, 1) !important;
}

The black hover comes from the default template (Bootstrap probably) being used. That is, the color is not defined in any CSS file. Did you want me to create a PR with the addition? Or did you want to define another issue to make this edit?

**Comment by anushbhatia** [comment]
you can create a new issue for this

**Comment by ceruleanox** [comment]
Writing to follow up that I created separate issue and pull request:
#1010 - https://github.com/smaranjitghose/awesome-portfolio-websites/issues/1010
PR - https://github.com/smaranjitghose/awesome-portfolio-websites/pull/1011
