### ISSUE TITLE
Toggle Button on Hover Bug

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#959]
![Button_on_hover](https://user-images.githubusercontent.com/46641503/125866660-19e592a5-f546-434a-acae-0ea7cdd32042.png)

This should only appear for the text in the navbar and not the toggle button

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi,
I want to take this up as part of OSD21

**Comment by vijaya-lakshmi-venkatraman** [comment]
I see that under \assets\js\app.js we have code related to toggle button:
`<input type="checkbox" class="dark_toggler" aria-label="Toggle Light Mode" onclick="toggle_light_mode()">`

And there is also definition for toggle_light_mode()

Please can you give me some pointers on how to disable the hover color?

**Comment by vijaya-lakshmi-venkatraman** [comment]
//function to remove underline on hover

$(document).ready(function () {
  $("a.nav-link").hover(
    function () {
      $(this).removeClass("current-link");
    },
    function () {
      if ($(this).prop("href") == window.location.href) {
        $(this).addClass("current-link");
      }
    }
  );
});

Is this snippet relevant to this issue?

**Comment by vijaya-lakshmi-venkatraman** [comment]
I think the changes required is in the input tag to unset/reset the background-color attribute because nav-item has the below property:

```
.nav-item::after {
        content: "";
        display: block;
        margin-left: auto;
        margin-right: auto;
        height: 0.15em;
        bottom: 0;
        width: 0%;
        background-color: #6a00bb;
        transition: all ease-in-out 280ms;
    }
```

Is that right?

**Comment by vijaya-lakshmi-venkatraman** [comment]
I have made a PR with the changes based on my analysis.
Please can someone review and also help me on how to test the changes?

**Comment by Swatilekha-Roy** [comment]
@smaranjitghose @anushbhatia I'd love to work on this issue! As I can understand, nobody is assigned to it yet. So, could you kindly assign it to me as a part of Open Source Day 2021, if that is possible? Thanks.
