### ISSUE TITLE
Experience Page Responsiveness Bug in Mobile Screens

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#961]
![responsivenes_Issue](https://user-images.githubusercontent.com/46641503/125867104-507d9396-7ff9-4a20-b122-146c64bf6da7.png)

**Comment by Swatilekha-Roy** [comment]
Hi, could you please explain a little bit more on what aspects of the experience page responsiveness you to improve? Thanks a lot.
Also, I would live to work on this issue as a part of OSD 2021! :)

**Comment by smaranjitghose** [comment]
Basically the work experience and open source card sizes and positions

**Comment by Swatilekha-Roy** [comment]
![Screenshot (211)](https://user-images.githubusercontent.com/66589183/125915027-56d4e0d1-f430-471e-be0c-d3546df28e50.png)
![Screenshot (210)](https://user-images.githubusercontent.com/66589183/125915032-55491335-9662-4a95-956f-02065ff1a9e2.png)

Hey, I have been actually trying on my end, but the open source and experience cards seem to be aligned in the middle itself and therefore, the position looks untethered here. The screenshots are from Galaxy mobile device emulations and I also tried Pixel 2 like in your sc but I don't get zoomed in cards actually, there is ample margin in the right side. Could you kindly suggest me some media query breakpoints in which I could reproduce this? Thanks.

**Comment by anushbhatia** [comment]
enter values like 471 and 731 in the resolution box or select the pixel2 device

**Comment by Swatilekha-Roy** [comment]
Okay okay thanks.

**Comment by Swatilekha-Roy** [comment]
![Screenshot (215)](https://user-images.githubusercontent.com/66589183/126054090-750b0085-3ce7-4bae-a3e1-006453ad438c.png)
![Screenshot (216)](https://user-images.githubusercontent.com/66589183/126054092-e55d82c7-84a6-4276-8a64-0e00f6a4e198.png)

Sorry, but I am still unable to see it. @smaranjitghose @anushbhatia However, I will reduce the card sizes anyway and make the pr. Will that be okay?

**Comment by anushbhatia** [comment]
![image](https://user-images.githubusercontent.com/40017559/126063793-ee09568a-3615-4b13-b5cf-27d7ba890465.png)
Try pixel 2 411* 731 100% i can see this

**Comment by Swatilekha-Roy** [comment]
@anushbhatia please check my above screenshots, I tried the resolution and device that you mentioned only.
I am not seeing that.

**Comment by anushbhatia** [comment]
I think then this must be resolved look for other pages if you find something you can raise an issue.
