### ISSUE TITLE
Research Page Bug: Image Size Overflow

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#962]
![Reseearch_page_bug](https://user-images.githubusercontent.com/46641503/125867427-5876696c-b597-4e64-9441-a66623d2d6e1.png)

**Comment by Kriti-bit** [comment]
I would like to work on this issue

**Comment by battuAshita** [comment]
Hi @smaranjitghose. Can I work on this issue as part of OSD'21?
