### ISSUE TITLE
Experience Page Dark Mode UI Improvement

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#963]
## Current UI
![image](https://user-images.githubusercontent.com/46641503/125867581-363aa33e-f8d7-4133-8b66-4f29bd515270.png)

# Sample Reference for Expected UI

![Experience_Page](https://user-images.githubusercontent.com/46641503/123431080-81189b80-d5e6-11eb-946a-e420747e0d7f.png)

- Check out the social media buttons for dark mode on the home page as a reference for the same
- This should be done for all of the cards

**Comment by bukolastella** [comment]
I will like to take on this issue

**Comment by bukolastella** [comment]
The color of the h2 tag in dark theme mood might need to be changed, what do you think?

![dark-theme](https://user-images.githubusercontent.com/53631117/125956218-e18bd4bb-f029-452b-b0fd-9e9fbac7cb17.PNG)

**Comment by bukolastella** [comment]
The color of the h2 tag in dark theme mood might need to be changed, what do you think?

![dark-theme](https://user-images.githubusercontent.com/53631117/125956218-e18bd4bb-f029-452b-b0fd-9e9fbac7cb17.PNG)

**Comment by anushbhatia** [comment]
Yes it won't be visible change it 
https://uxdesign.cc/dark-mode-ui-design-the-definitive-guide-part-1-color-53dcfaea5129 if you need help

**Comment by smaranjitghose** [comment]
@bukolastella Yes. Have a look a the resource provided by @anushbhatia
