### ISSUE TITLE
No Response After Clicking Send

### ISSUE THREAD

**Issue by divyesh1099** [smaranjitghose/awesome-portfolio-websites#966]
# No Success/Fail response after Clicking Send

#### Explanatory Video [Here](https://youtu.be/cuKlN2DNw10)

**Comment by smaranjitghose** [comment]
We have a pop for this

**Comment by divyesh1099** [comment]
Okay So should I start working on it ?

**Comment by smaranjitghose** [comment]
Sure. Just choose the colors judiciously so that it is consistent with the rest of the theme

**Comment by divyesh1099** [comment]
Okay sir. I'll do it asap

**Comment by smaranjitghose** [comment]
Any updates @divyesh1099 ?

**Comment by divyesh1099** [comment]
Yes sir I'll do it before 6 pm today. Sorry for the delay sir. I was working on issue #977 (sorry for not working on this). I'll try to complete this asap. If I'm not able to do this task then I'll notify.

**Comment by divyesh1099** [comment]
Sorry sir I couldn't do it.
