### ISSUE TITLE
Cursor Bug: Invisible in the ScrollBar Area

### ISSUE THREAD

**Issue by mruga7** [smaranjitghose/awesome-portfolio-websites#968]
#### the video explanation is [here](https://youtu.be/f2nLGQfeNyQ)

**Comment by AnirudhPanda** [comment]
> #### cursor disappears from scrollbar
> #### the video explanation is [here](https://youtu.be/f2nLGQfeNyQ)

Hey Quick Suggestion, instead of uploading issues video on youtube which is a long process you can use something like [Lice Cap](https://licecap.en.softonic.com/)

**Comment by smaranjitghose** [comment]
Keep it simple😅🤣: Use windows game bar, drag and drop the clip in the issue description

**Comment by AnirudhPanda** [comment]
> > #### cursor disappears from scrollbar
> > #### the video explanation is [here](https://youtu.be/f2nLGQfeNyQ)
> 
> Hey Quick Suggestion, instead of uploading issues video on youtube which is a long process you can use something like [Lice Cap](https://licecap.en.softonic.com/)



> Keep it simple😅🤣: Use windows game bar, drag and drop the clip in the issue description

Man, I didn't know about it! Thanks. 😂🤦‍♂️

**Comment by smaranjitghose** [comment]
Any updates @mruga7 ?

**Comment by mruga7** [comment]
@smaranjitghose Sorry for the delay Sir, will get it done today iteself

**Comment by smaranjitghose** [comment]
Cool 😊
