### ISSUE TITLE
Github.io page needs a correction

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [smaranjitghose/awesome-portfolio-websites#969]
https://smaranjitghose.github.io/awesome-portfolio-websites/#open-source-programs-we-have-been-a-associated-with 

This link shows the title as "Open Source Programs we have been **a** associated with" instead of "Open Source Programs we have been associated with"

This needs changing.
Also, can we include OSD in to the list?

**Comment by vijaya-lakshmi-venkatraman** [comment]
Thanks for assigning this issue to me.
I checked the source code using VSCode for locating the text associated for the change.
But I have been unable to. Please can you provide some leads?

**Comment by AnirudhPanda** [comment]
> Thanks for assigning this issue to me.
> I checked the source code using VSCode for locating the text associated for the change.
> But I have been unable to. Please can you provide some leads?

You checked the `documentation` branch, right?

**Comment by vijaya-lakshmi-venkatraman** [comment]
I didn't earlier.
But can see everything in there. 
Thanks!
Btw It is marked as stale branch. Can I still go ahead and create a PR to fix this?
