### ISSUE TITLE
Dark mode is not working when we change to different pages 

### ISSUE THREAD

**Issue by alceil** [smaranjitghose/awesome-portfolio-websites#973]
Dark mode works only for one page when we change to other page it automatically changes to light mode.Its a bug that needs to be solved.

**Comment by shreyachalla** [comment]
I am going to try to work on this for OSD

**Comment by IwonaBaran** [comment]
Can I try to fix this?

**Comment by smaranjitghose** [comment]
Sure.

**Comment by anushbhatia** [comment]
updates @IwonaBaran ?

**Comment by bukolastella** [comment]
I will like to take on this issue
