### ISSUE TITLE
Research Page UI Improvement [Dark Mode]

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#988]
[Refer this](https://uxdesign.cc/dark-mode-ui-design-the-definitive-guide-part-1-color-53dcfaea5129)

**Comment by nik464** [comment]
i will do this .

**Comment by nik464** [comment]
actually what exact improvement has to be done in dark mode?

**Comment by anushbhatia** [comment]
Enhancing the box shadow according to reference
Having the colour scheme similar to that displayed as currently the page is too dark
Following the purple scheme present there.
Also modifying the buttons in the same page with the same colour codes of purple.

**Comment by deeqakkk** [comment]
@nik464 any updates?

**Comment by bukolastella** [comment]
I will like to take on this issue

**Comment by nik464** [comment]
I am extremely sorry sir. My laptop got damaged . So I had to get it repaired from shop. I got it back today. First I was working on header issue and now I will work on this issue.
