### ISSUE TITLE
Remove ScrollBar Track during Preloader animation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#989]
![Scroll_bar](https://user-images.githubusercontent.com/46641503/126129579-d52afd68-29c0-478e-a3da-4e82adbf25ca.png)

**Comment by aashimawadhwa** [comment]
Can I work on this issue. Please assign it to me.

**Comment by anushbhatia** [comment]
Any updates @aashimawadhwa ?

**Comment by aashimawadhwa** [comment]
Was having exams this week , started working on jt yesterday it will be done by tomorrow. @anushbhatia
