### ISSUE TITLE
Light mode is not working in Event page

### ISSUE THREAD

**Issue by stephenchinkenvun** [smaranjitghose/awesome-portfolio-websites#997]
Hi, I am Stephen. I just found that light mode is not working on the event.html page when we changed from dark mode to light mode. I would like to try to fix it. Besides that, the light mode and dark mode on the travel temp.html page have been swapped, where dark mode showing a white background.
![event_page_error](https://user-images.githubusercontent.com/55908964/126513074-8cbda174-27dc-4f74-bc99-f1dafd73a30d.png)
![image](https://user-images.githubusercontent.com/55908964/126592635-693ed29b-20be-4670-807e-f1cd3e6db7b0.png)
![image](https://user-images.githubusercontent.com/55908964/126592648-4c0e1d93-ca2d-44dc-8c9d-f40d139c54cd.png)

**Comment by anushbhatia** [comment]
please resolve these and try giving the pr as soon as possible
